--Purpose    : Changes Made to Claim
--Author     : Lavin Hawes
--Created On : 22-Feb-10

ALTER TABLE CLAIM ADD LABOR_ROUNDUP_WINDOW_FROM_DATE DATE
/

ALTER TABLE CLAIM ADD LABOR_ROUNDUP_WINDOW_TO_DATE DATE
/

COMMIT