--PURPOSE    : PATCH FOR ADDING NEW CONFIG PARAM FOR PART RETURN VISIBILITY FOR DEALERS
--AUTHOR     : Amritha Krishnamoorthy
--CREATED ON : 12-JAN-2010


UPDATE part_return SET bar_code = null WHERe bar_Code IS NOT null
/
commit
/
ALTER TABLE PART_RETURN
      ADD CONSTRAINT PART_RETURN_UQ UNIQUE(BAR_CODE) 
/
     