--Purpose    : Patch for Minimum Labour Round Up
--Author     : Mayank Vikram
--Created On : 16-FEB-10


CREATE TABLE  MINIMUM_LABOR_ROUND_UP
  (
    ID                 NUMBER(19,0)  NOT NULL ENABLE,
    BUSINESS_UNIT_INFO VARCHAR2(255 BYTE),
    DAYS_BETWEEN_REPAIR NUMBER(19,0) ,
    ROUND_UP_HOURS NUMBER(19,0),
    APPL_COMMERICAL_POLICY  NUMBER(1,0),
    APPL_CAMPAIGN_CLAIM  NUMBER(1,0),
    D_CREATED_ON DATE,
    D_INTERNAL_COMMENTS VARCHAR2(255 CHAR),
    D_UPDATED_ON DATE,
    D_LAST_UPDATED_BY NUMBER(19,0),
    D_CREATED_TIME TIMESTAMP (6),
    D_UPDATED_TIME TIMESTAMP (6),
    D_ACTIVE NUMBER(1,0) DEFAULT 1,
    CONSTRAINT MIN_LBR_ROUND_UP_PK  PRIMARY KEY (ID),
	  CONSTRAINT MIN_LBR_BU_FK  FOREIGN KEY ( BUSINESS_UNIT_INFO ) REFERENCES  BUSINESS_UNIT  ( NAME )
  )
/
CREATE TABLE MIN_LBR_ROUND_UP_APP_PRODUCTS
 (
     MINIMUM_LABOR_ROUND_UP        NUMBER(19,0),
     APPLICABLE_PRODUCTS             NUMBER(19,0),
   
    CONSTRAINT MIN_LBR_APP_PRODUCTS_PK  
           PRIMARY KEY( MINIMUM_LABOR_ROUND_UP ,  APPLICABLE_PRODUCTS ), 
   
    CONSTRAINT  MIN_LBR_ROUND_UP_FK  FOREIGN KEY ( MINIMUM_LABOR_ROUND_UP ) 
           REFERENCES  MINIMUM_LABOR_ROUND_UP  ( ID ) ,
    
    CONSTRAINT  APPLICABLE_PRODUCTS_FK  FOREIGN KEY ( APPLICABLE_PRODUCTS ) 
           REFERENCES  ITEM_GROUP  ( ID ) 
  )
/