--Purpose    : Patch for Adding BU column in model category
--Author     : saya.sudha	
--Created On : 08-jan-2010

ALTER TABLE MODEL_CATEGORY ADD (business_unit_info VARCHAR2(255 BYTE))
/
ALTER TABLE MODEL_CATEGORY ADD 
(CONSTRAINT MODEL_CATEGORY_BU_FK FOREIGN KEY (BUSINESS_UNIT_INFO) REFERENCES BUSINESS_UNIT (NAME))
/
UPDATE MODEL_CATEGORY SET BUSINESS_UNIT_INFO='Transport Solutions ESA' WHERE MODEL_CODE='A'
/
UPDATE MODEL_CATEGORY SET BUSINESS_UNIT_INFO='Transport Solutions ESA' WHERE MODEL_CODE='B'
/
UPDATE MODEL_CATEGORY SET BUSINESS_UNIT_INFO='Transport Solutions ESA' WHERE MODEL_CODE='C'
/
UPDATE MODEL_CATEGORY SET BUSINESS_UNIT_INFO='Transport Solutions ESA' WHERE MODEL_CODE='D'
/
UPDATE MODEL_CATEGORY SET BUSINESS_UNIT_INFO='Transport Solutions ESA' WHERE MODEL_CODE='E'
/
UPDATE MODEL_CATEGORY SET BUSINESS_UNIT_INFO='Transport Solutions ESA' WHERE MODEL_CODE='F'
/
UPDATE MODEL_CATEGORY SET BUSINESS_UNIT_INFO='Transport Solutions ESA' WHERE MODEL_CODE='G'
/
UPDATE MODEL_CATEGORY SET BUSINESS_UNIT_INFO='Transport Solutions ESA' WHERE MODEL_CODE='X'
/
INSERT INTO MODEL_CATEGORY(ID, model_code, version, business_unit_info) 
VALUES(MODEL_CATEGORY_SEQ.NEXTVAL,'Truck','0','Thermo King TSA')
/
INSERT INTO MODEL_CATEGORY(ID, model_code, version, business_unit_info) 
VALUES(MODEL_CATEGORY_SEQ.NEXTVAL,'Bus','0','Thermo King TSA')
/
COMMIT
/