ALTER TABLE LIMIT_OF_AUTHORITY_LEVEL MODIFY (LOA_SCHEME NUMBER(19,0))
/
ALTER TABLE LIMIT_OF_AUTHORITY_LEVEL MODIFY (LOA_USER NUMBER(19,0))
/
ALTER TABLE LOA_AMOUNT MODIFY (LOA_LEVEL NUMBER(19,0))
/
COMMIT
/