--PURPOSE    : PATCH FOR ADDING NEW CONFIG PARAM FOR PART RETURN VISIBILITY FOR DEALERS
--AUTHOR     : Amritha Krishnamoorthy
--CREATED ON : 21-DEC-09

alter table CLAIM
add PAYMENT_RECALCULATION_REQUIRED NUMBER(1, 0)
/
COMMIT
/


