--Purpose    : Add Columns to Claim, Service_INFORMATION,OEM_PART_REPLACED, INSTALLED_PART to mainatin failure reports corresponding to each of them
--Author     : Pradyot.rout
--Created On : 27-Mar-10

ALTER TABLE CLAIM ADD  FAILURE_REPORT_PENDING NUMBER(1,0)
/
ALTER TABLE INSTALLED_PARTS ADD  CUSTOM_REPORT_ANSWER NUMBER(19,0)
/
ALTER TABLE INSTALLED_PARTS ADD CONSTRAINT INST_PRT_CUST_RPT_ANS_FK FOREIGN KEY (CUSTOM_REPORT_ANSWER) REFERENCES CUSTOM_REPORT_ANSWER
/
ALTER TABLE OEM_PART_REPLACED ADD CUSTOM_REPORT_ANSWER NUMBER(19,0)
/
ALTER TABLE OEM_PART_REPLACED ADD CONSTRAINT OEM_PRT_CUST_RPT_ANS_FK FOREIGN KEY (CUSTOM_REPORT_ANSWER) REFERENCES CUSTOM_REPORT_ANSWER
/
ALTER TABLE SERVICE_INFORMATION ADD  CUSTOM_REPORT_ANSWER NUMBER(19,0)
/
ALTER TABLE SERVICE_INFORMATION ADD CONSTRAINT CSL_PRT_CUST_RPT_ANS_FK FOREIGN KEY (CUSTOM_REPORT_ANSWER) REFERENCES CUSTOM_REPORT_ANSWER
/
ALTER TABLE CUSTOM_REPORT_ANSWER ADD STATUS VARCHAR2(255)
/
COMMIT
/