--Purpose    : Inclusion of Purposes Warranty Coverage,Extended Coverage and Standard Coverage
--Author     : Lavin Hawes
--Created On : 07-Jan-10

INSERT INTO PURPOSE (ID, NAME, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_CREATED_TIME, D_UPDATED_TIME, BUSINESS_UNIT_INFO, D_ACTIVE) VALUES ('1101100000158', 'Warranty Coverage', '1', TO_DATE('21-DEC-09', 'DD-MON-RR'), 'IRI-Migration', TO_DATE('21-DEC-09', 'DD-MON-RR'), TO_TIMESTAMP('21-DEC-09 12.00.00.', 'DD-MON-RR HH.MI.SS.FF AM'), TO_TIMESTAMP('21-DEC-09 12.00.00.', 'DD-MON-RR HH.MI.SS.FF AM'), 'Thermo King TSA', '1')
/
INSERT INTO PURPOSE (ID, NAME, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_CREATED_TIME, D_UPDATED_TIME, BUSINESS_UNIT_INFO, D_ACTIVE) VALUES ('1101100000159', 'Standard Coverage', '1', TO_DATE('21-DEC-09', 'DD-MON-RR'), 'IRI-Migration', TO_DATE('21-DEC-09', 'DD-MON-RR'), TO_TIMESTAMP('21-DEC-09 12.00.00.', 'DD-MON-RR HH.MI.SS.FF AM'), TO_TIMESTAMP('21-DEC-09 12.00.00.', 'DD-MON-RR HH.MI.SS.FF AM'), 'Thermo King TSA', '1')
/
INSERT INTO PURPOSE (ID, NAME, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_CREATED_TIME, D_UPDATED_TIME, BUSINESS_UNIT_INFO, D_ACTIVE) VALUES ('1101100000160', 'Extended Coverage', '1', TO_DATE('21-DEC-09', 'DD-MON-RR'), 'IRI-Migration', TO_DATE('21-DEC-09', 'DD-MON-RR'), TO_TIMESTAMP('21-DEC-09 12.00.00.', 'DD-MON-RR HH.MI.SS.FF AM'), TO_TIMESTAMP('21-DEC-09 12.00.00.', 'DD-MON-RR HH.MI.SS.FF AM'), 'Thermo King TSA', '1')
/
COMMIT
/