--Purpose    : Patch for Cost Categories dependent on unit’s product
--Author     : Mayank Vikram
--Created On : 29-MAR-10


CREATE TABLE COSTCAT_APPL_PRODUCTS
	 (
	    COST_CATEGORY NUMBER(19,0) NOT NULL ENABLE,
	    ITEM_GROUP   NUMBER(19,0) NOT NULL ENABLE,    
	    CONSTRAINT COSTCAT_APPL_PRD_COSTCAR_FK FOREIGN KEY (COST_CATEGORY) REFERENCES COST_CATEGORY (ID) ENABLE,    
	    CONSTRAINT COSTCAT_APPL_PRD_GRP_FK FOREIGN KEY (ITEM_GROUP) REFERENCES ITEM_GROUP (ID) ENABLE
	)
/
