--Purpose    : Adding upload mgt entries for warranty registration
--Author     : Kuldeep Patil
--Created On : 14/07/2010

create table STG_REQUEST_EXTENSION(
	ID NUMBER(19,0) PRIMARY KEY,
	FILE_UPLOAD_MGT_ID NUMBER(19,0),
	DEALER_NUMBER VARCHAR2(255),
	SERIAL_NUMBER VARCHAR2(255),
	DELIVERY_DATE VARCHAR2(255),
	POLICY_CODE VARCHAR2(255),
	POLICY_END_DATE VARCHAR2(255),
	MONTHS_COVERED_BY_POLICY NUMBER,
	GOODWILL_POLICY_CODE VARCHAR2(255),
	GOODWILL_POLICY_END_DATE VARCHAR2(255),
	HOURS_COVERED NUMBER,
	COMMENTS VARCHAR2(4000),
	ERROR_STATUS	VARCHAR2(255),
	ERROR_CODE	VARCHAR2(255),
	UPLOAD_STATUS	VARCHAR2(255),
	UPLOAD_ERROR	VARCHAR2(255),
	UPLOAD_DATE	VARCHAR2(20),
	ITEM_NUMBER VARCHAR2(255),
	BUSINESS_UNIT_INFO VARCHAR2(255),
	ACTION_PERFORMED VARCHAR2(255)
)
/
COMMIT
/