--Purpose    : tables created for the supplier recovery flow
--Author     : Kaustubhshobhan Basu
--Created On : 12/15/09
--Sequence: 1

CREATE SEQUENCE RECOVERABLE_PART_SEQ
START WITH 200
INCREMENT BY 20
MINVALUE 0
MAXVALUE 999999999999999999999999999
CACHE 20
NOCYCLE 
NOORDER
/
COMMIT
/
CREATE TABLE RECOVERABLE_PART
(
  ID NUMBER(19),
  PART NUMBER(19),
  QUANTITY NUMBER(19),
  D_CREATED_ON DATE, 
  D_INTERNAL_COMMENTS VARCHAR2(255 CHAR), 
  D_UPDATED_ON DATE, 
  D_LAST_UPDATED_BY NUMBER(19,0), 
  D_CREATED_TIME TIMESTAMP (6), 
  D_UPDATED_TIME TIMESTAMP (6), 
  D_ACTIVE NUMBER(1,0) DEFAULT 1
)

/
COMMIT
/
ALTER TABLE RECOVERABLE_PART ADD (
  CONSTRAINT PK_RECOVERABLE_PART
 PRIMARY KEY (ID))
/
ALTER TABLE RECOVERABLE_PART ADD (
  CONSTRAINT FK_PART_RECOVERABLE_PART
 FOREIGN KEY (PART) 
 REFERENCES ITEM (ID))
/
COMMIT
/
CREATE TABLE RECOVERABLE_PART_BAR_CODES
(
	RECOVERABLE_PART NUMBER(19),
	BAR_CODES VARCHAR2(255)
)
/
COMMIT
/
ALTER TABLE RECOVERABLE_PART_BAR_CODES ADD (
	CONSTRAINT FK_P_R_PART_BAR_CODES
	FOREIGN KEY (RECOVERABLE_PART)
	REFERENCES RECOVERABLE_PART (ID)
)
/
COMMIT
/
CREATE SEQUENCE RECOVERY_CLAIM_INFO_SEQ
START WITH 200
INCREMENT BY 20
MINVALUE 0
MAXVALUE 999999999999999999999999999
CACHE 20
NOCYCLE 
NOORDER
/
COMMIT
/
CREATE TABLE RECOVERY_CLAIM_INFO
(
	ID NUMBER(19),
	CONTRACT NUMBER(19),
	ACTIVE NUMBER(1,0) DEFAULT 1,
	D_CREATED_ON DATE, 
	D_INTERNAL_COMMENTS VARCHAR2(255 CHAR), 
	D_UPDATED_ON DATE, 
	D_LAST_UPDATED_BY NUMBER(19,0), 
	D_CREATED_TIME TIMESTAMP (6), 
	D_UPDATED_TIME TIMESTAMP (6), 
	D_ACTIVE NUMBER(1,0) DEFAULT 1
)
/
COMMIT
/
ALTER TABLE RECOVERY_CLAIM_INFO ADD (
  CONSTRAINT PK_RECOVERY_CLAIM_INFO
  PRIMARY KEY (ID)
)
/
ALTER TABLE RECOVERY_CLAIM_INFO ADD (
  CONSTRAINT FK_C_RECOVERY_CLAIM_INFO
  FOREIGN KEY (CONTRACT) 
  REFERENCES CONTRACT (ID)
)
/
COMMIT
/
CREATE TABLE REC_CLAIM_INFO_REC_PARTS
(
	RECOVERY_CLAIM_INFO NUMBER(19),
	RECOVERABLE_PARTS NUMBER(19)
)
/
COMMIT
/
ALTER TABLE REC_CLAIM_INFO_REC_PARTS ADD (
	CONSTRAINT FK_R_C_RECOVERABLE_PARTS
	FOREIGN KEY (RECOVERY_CLAIM_INFO) 
	REFERENCES RECOVERY_CLAIM_INFO (ID)
)
/
ALTER TABLE REC_CLAIM_INFO_REC_PARTS ADD (
	CONSTRAINT FK_R_P_RECOVERABLE_PARTS
	FOREIGN KEY (RECOVERABLE_PARTS) 
	REFERENCES RECOVERABLE_PART (ID)
)
/
COMMIT
/
CREATE TABLE REC_CLAIM_INFO_REC_CLAIMS
(
	RECOVERY_CLAIM_INFO NUMBER(19),
	RECOVERY_CLAIMS NUMBER(19)
)
/
COMMIT
/
ALTER TABLE REC_CLAIM_INFO_REC_CLAIMS ADD (
	CONSTRAINT FK_R_RECOVERY_CLAIMS
	FOREIGN KEY (RECOVERY_CLAIM_INFO) 
	REFERENCES RECOVERY_CLAIM_INFO (ID)
)
/
ALTER TABLE REC_CLAIM_INFO_REC_CLAIMS ADD (
	CONSTRAINT FK_R_RECOVERABLE_PARTS
	FOREIGN KEY (RECOVERY_CLAIMS) 
	REFERENCES RECOVERY_CLAIM (ID)
)
/
COMMIT
/

CREATE SEQUENCE RECOVERY_INFO_SEQ
START WITH 200
INCREMENT BY 20
MINVALUE 0
MAXVALUE 999999999999999999999999999
CACHE 20
NOCYCLE 
NOORDER
/
COMMIT
/
CREATE TABLE RECOVERY_INFO(
  ID NUMBER(19),
  WARRANTY_CLAIM NUMBER(19),
  CAUSAL_PART_RECOVERY NUMBER(19),
  D_CREATED_ON DATE, 
  D_INTERNAL_COMMENTS VARCHAR2(255 CHAR), 
  D_UPDATED_ON DATE, 
  D_LAST_UPDATED_BY NUMBER(19,0), 
  D_CREATED_TIME TIMESTAMP (6), 
  D_UPDATED_TIME TIMESTAMP (6), 
  D_ACTIVE NUMBER(1,0) DEFAULT 1,
  BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
)
/
COMMIT
/
ALTER TABLE RECOVERY_INFO ADD (
  CONSTRAINT PK_RRECOVERY_INFO
  PRIMARY KEY (ID)
)
/
ALTER TABLE RECOVERY_INFO ADD (
  CONSTRAINT FK_W_CLAIM_RECOVERY_INFO
  FOREIGN KEY (WARRANTY_CLAIM) 
  REFERENCES CLAIM (ID)
)
/
ALTER TABLE RECOVERY_INFO ADD (
  CONSTRAINT FK_C_P_REC_INFO
  FOREIGN KEY (CAUSAL_PART_RECOVERY) 
  REFERENCES RECOVERY_CLAIM_INFO (ID)
)
/
COMMIT
/
CREATE TABLE REC_INFO_REP_PARTS_REC(
  RECOVERY_INFO NUMBER(19),
  REPLACED_PARTS_RECOVERY NUMBER(19)
)
/
COMMIT
/
ALTER TABLE REC_INFO_REP_PARTS_REC ADD (
	CONSTRAINT FK_R_REP_PARTS_REC
	FOREIGN KEY (RECOVERY_INFO) 
	REFERENCES RECOVERY_INFO (ID)
)
/
ALTER TABLE REC_INFO_REP_PARTS_REC ADD (
	CONSTRAINT FK_R_P_REP_PARTS_REC
	FOREIGN KEY (REPLACED_PARTS_RECOVERY) 
	REFERENCES RECOVERY_CLAIM_INFO (ID)
)
/
COMMIT
/
CREATE TABLE RECOVERY_INFO_COMMENTS(
  RECOVERY_INFO NUMBER(19),
  COMMENTS NUMBER(19)
)
/
COMMIT
/
ALTER TABLE RECOVERY_INFO_COMMENTS ADD (
	CONSTRAINT FK_R_INFO_COMMENTS
	FOREIGN KEY (RECOVERY_INFO) 
	REFERENCES RECOVERY_INFO (ID)
)
/
ALTER TABLE RECOVERY_INFO_COMMENTS ADD (
	CONSTRAINT FK_C_INFO_COMMENTS
	FOREIGN KEY (COMMENTS) 
	REFERENCES USER_COMMENT (ID)
)
/
COMMIT
/
ALTER TABLE CLAIM ADD(RECOVERY_INFO NUMBER(19))
/
ALTER TABLE CLAIM ADD (
	CONSTRAINT FK_CLAIM_REC_INFO
	FOREIGN KEY (RECOVERY_INFO) 
	REFERENCES RECOVERY_INFO (ID)
)
/
COMMIT
/