<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://www.tavant.com/globalsync/exchangeratesync/definition"
                  xmlns:impl="http://www.tavant.com/globalsync/exchangeratesync/definition"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:message name="syncRequest">
        <wsdl:part name="syncRequest" type="xsd:string"/>
    </wsdl:message>
    <wsdl:message name="syncResponse">
        <wsdl:part name="syncResponse" type="xsd:string"/>
    </wsdl:message>
    <wsdl:portType name="ProcessGlobalExchangeRate">
        <wsdl:operation name="sync" parameterOrder="syncRequest">
            <wsdl:input message="impl:syncRequest" name="syncRequest"/>
            <wsdl:output message="impl:syncResponse" name="syncResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="ProcessGlobalExchangeRate-WSSoapBinding" type="ProcessGlobalExchangeRate">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="sync">
            <soap:operation soapAction="http://www.tavant.com/globalsync/exchangeratesync"/>
            <wsdl:input name="syncRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="syncResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="ProcessGlobalExchangeRate-WS">
        <wsdl:port binding="impl:ProcessGlobalExchangeRate-WSSoapBinding" name="ProcessGlobalExchangeRate-WS">
            <soap:address location="http://10.5.106.201:9090/services/integration/ProcessGlobalExchangeRate-WS"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>