<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://external.server.integration.twms.tavant" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://external.server.integration.twms.tavant" xmlns:intf="http://external.server.integration.twms.tavant" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
  <wsdl:message name="syncResponse">
    <wsdl:part name="syncReturn" type="xsd:string"/>
  </wsdl:message>
  <wsdl:message name="syncRequest">
    <wsdl:part name="in0" type="xsd:string"/>
  </wsdl:message>
  <wsdl:portType name="$Proxy207">
    <wsdl:operation name="sync" parameterOrder="in0">
      <wsdl:input message="impl:syncRequest" name="syncRequest"/>
      <wsdl:output message="impl:syncResponse" name="syncResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ProcessCreditSubmit-WSSoapBinding" type="impl:$Proxy207">
    <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sync">
      <wsdlsoap:operation soapAction=""/>
      <wsdl:input name="syncRequest">
        <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://external.server.integration.twms.tavant" use="encoded"/>
      </wsdl:input>
      <wsdl:output name="syncResponse">
        <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://external.server.integration.twms.tavant" use="encoded"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ProcessCreditSubmit-WS">
    <wsdl:port binding="impl:ProcessCreditSubmit-WSSoapBinding" name="ProcessCreditSubmit-WS">
      <wsdlsoap:address location="http://blrirap01.in.corp.tavant.com:8086/services/ProcessCreditSubmit-WS"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>