CREATE TABLE LABOR_SPLIT
(
  ID                   NUMBER(19),
  SERVICE_DETAIL       NUMBER(19),
  LABOR_TYPE           NUMBER(19),
  HOURS_SPENT          NUMBER(19,2),
  REASON               VARCHAR2(255 BYTE),
  INCLUSIVE            NUMBER(1),
  VERSION              NUMBER(10),
  D_CREATED_ON         DATE,
  D_UPDATED_ON         DATE,
  D_INTERNAL_COMMENTS  VARCHAR2(255 BYTE),
  D_LAST_UPDATED_BY    NUMBER(19),
  D_CREATED_TIME       TIMESTAMP(6),
  D_UPDATED_TIME       TIMESTAMP(6),
  LIST_INDEX           NUMBER(10)
)
/
CREATE UNIQUE INDEX LABOR_SPLIT_PK ON LABOR_SPLIT(ID)
/
ALTER TABLE LABOR_SPLIT ADD (
  CONSTRAINT LABOR_SPLIT_PK
 PRIMARY KEY
 (ID))
/
CREATE SEQUENCE LABOR_SPLIT_SEQ
  START WITH 3800
  INCREMENT BY 20
  MAXVALUE 999999999999999999999999999
  MINVALUE 1000
  NOCYCLE
  CACHE 20
  NOORDER;
