CREATE TABLE LABOR_SPLIT_TYPE
(
  ID                    NUMBER(19),
  LABOR_TYPE            VARCHAR2(255 BYTE),
  MULTIPLICATION_VALUE  NUMBER(19,2),
  STATUS                VARCHAR2(255 BYTE),
  VERSION               NUMBER(10),
  D_CREATED_ON          DATE,
  D_UPDATED_ON          DATE,
  D_INTERNAL_COMMENTS   VARCHAR2(255 BYTE),
  D_LAST_UPDATED_BY     NUMBER(19),
  D_CREATED_TIME        TIMESTAMP(6),
  D_UPDATED_TIME        TIMESTAMP(6),
  BUSINESS_UNIT_INFO    VARCHAR2(255 BYTE)
)
/
CREATE UNIQUE INDEX LABOR_SPLIT_TYPE_PK ON LABOR_SPLIT_TYPE(ID)
/
ALTER TABLE LABOR_SPLIT_TYPE ADD (
  CONSTRAINT LABOR_SPLIT_TYPE_PK
 PRIMARY KEY (ID) )
/
CREATE SEQUENCE LABOR_SPLIT_TYPE_SEQ
  START WITH 2600
  INCREMENT BY 20
  MAXVALUE 999999999999999999999999999
  MINVALUE 1000
  NOCYCLE
  CACHE 20
  NOORDER;
/
ALTER TABLE LABOR_SPLIT ADD (
  CONSTRAINT LABOR_SPLIT_SERVICE_DTL_FK 
 FOREIGN KEY (SERVICE_DETAIL) 
 REFERENCES SERVICE (ID),
  CONSTRAINT LABOR_SPLIT_LABOR_TYPE_FK 
 FOREIGN KEY (LABOR_TYPE) 
 REFERENCES LABOR_SPLIT_TYPE (ID))
/
