CREATE SEQUENCE NOTIFICATION_EVENT_SEQ
START WITH 1000
INCREMENT BY 20
NOCYCLE
NOCACHE
/
CREATE SEQUENCE NOTIFICATION_MSG_SEQ
START WITH 1000
INCREMENT BY 20
NOCYCLE
NOCACHE
/
CREATE SEQUENCE NOTIFICATION_PARAM_SEQ
START WITH 1000
INCREMENT BY 20
NOCYCLE
NOCACHE
/
CREATE SEQUENCE NOTIFICATION_MSG_PARAM_SEQ
START WITH 1000
INCREMENT BY 20
NOCYCLE
NOCACHE
/
CREATE SEQUENCE EVENT_STATE_SEQ
START WITH 1000
INCREMENT BY 20
NOCYCLE
NOCACHE
/
CREATE TABLE NOTIFICATION_EVENT 
(
	ID NUMBER PRIMARY KEY,
	EVENT_NAME VARCHAR2(255),
	ENTITY_NAME VARCHAR2(255),
	NUMBER_OF_TRIALS NUMBER,
	PENDING NUMBER(1)
)
/
CREATE TABLE EVENT_STATE
(
	ID NUMBER PRIMARY KEY,
	VERSION NUMBER,
	NAME VARCHAR2(255),
	DISPLAY_NAME VARCHAR2(255),
	D_CREATED_ON DATE,
	D_INTERNAL_COMMENTS VARCHAR2(255),
	D_UPDATED_ON DATE,
	D_LAST_UPDATED_BY NUMBER,
	D_CREATED_TIME	TIMESTAMP,
	D_UPDATED_TIME	TIMESTAMP,
	D_ACTIVE	NUMBER
)
/
CREATE TABLE NOTIFICATION_PARAMETER
(
	ID NUMBER,
	NOTIFICATION_EVENT NUMBER,
	KEY VARCHAR2(255),
	VALUE VARCHAR2(255)
)
/
ALTER TABLE NOTIFICATION_PARAMETER ADD 
    CONSTRAINT FK_NOTIFICATION_EVENT
    FOREIGN    KEY (NOTIFICATION_EVENT)
    REFERENCES NOTIFICATION_EVENT(ID)
/
CREATE TABLE EVENT_ROLE_MAPPING
(
EVENT_TYPES NUMBER,
ROLES NUMBER
)
/
ALTER TABLE EVENT_ROLE_MAPPING ADD 
    CONSTRAINT FK_EVENT_STATE
    FOREIGN    KEY (EVENT_TYPES)
    REFERENCES EVENT_STATE(ID)
/
ALTER TABLE EVENT_ROLE_MAPPING ADD 
    CONSTRAINT FK_ROLES
    FOREIGN    KEY (ROLES)
    REFERENCES ROLE(ID)
/
CREATE TABLE USER_EVENT_STATES
(
  ORG_USER NUMBER,
  EVENT_STATES NUMBER
)
/
ALTER TABLE USER_EVENT_STATES ADD 
    CONSTRAINT FK_ORG_USER
    FOREIGN    KEY (ORG_USER)
    REFERENCES ORG_USER(ID)
/
ALTER TABLE USER_EVENT_STATES ADD 
    CONSTRAINT FK_EVENT_STATES
    FOREIGN    KEY (EVENT_STATES)
    REFERENCES EVENT_STATE(ID)
/
CREATE TABLE ABSTRACT_NOTIFICATION_MESSAGE
(
	ID NUMBER PRIMARY KEY,
	MESSAGE_TEMPLATE	VARCHAR2(255),
	number_of_trials	NUMBER,
	CREATION_DATE		DATE, 
	MESSAGE_STATE		VARCHAR2(255), 
	PARAM_MAP			CLOB, 
	RECIPIENT			VARCHAR2(255), 
	VERSION				NUMBER, 
	type				VARCHAR2(255)
)
/
CREATE TABLE NOTIFICATION_MESSAGE_PARAMETER
(
	ID NUMBER,
	NOTIFICATION_MESSAGE NUMBER,
	KEY VARCHAR2(255),
	VALUE VARCHAR2(255)
)
/
ALTER TABLE NOTIFICATION_MESSAGE_PARAMETER ADD 
    CONSTRAINT FK_NOTIFICATION_MESSAGE
    FOREIGN    KEY (NOTIFICATION_MESSAGE)
    REFERENCES ABSTRACT_NOTIFICATION_MESSAGE(ID)
/