Insert into EVENT_STATE (ID, VERSION, NAME, DISPLAY_NAME, D_ACTIVE) Values (Event_state_seq.nextval, 0, 'WAITING_FOR_LABOR', 'Waiting For Labor FOC Claims', 1)
/
Insert into EVENT_STATE (ID, VERSION, NAME, DISPLAY_NAME, D_ACTIVE) Values (Event_state_seq.nextval, 0, 'CP_REVIEW', 'Commercial Policy Advisor Review', 1)
/
Insert into EVENT_STATE (ID, VERSION, NAME, DISPLAY_NAME, D_ACTIVE) Values (Event_state_seq.nextval, 0, 'CP_TRANSFER', 'Commercial Policy Advisor Transfer', 1)
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'WAITING_FOR_LABOR'),(SELECT ID FROM ROLE WHERE NAME = 'processor'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'WAITING_FOR_LABOR'),(SELECT ID FROM ROLE WHERE NAME = 'dealer'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'CP_REVIEW'),(SELECT ID FROM ROLE WHERE NAME = 'cpAdvisor'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'CP_TRANSFER'),(SELECT ID FROM ROLE WHERE NAME = 'cpAdvisor'))
/
