DELETE EVENT_ROLE_MAPPING
WHERE EVENT_TYPES IN (SELECT ID FROM EVENT_STATE
WHERE NAME = 'PART_RETURN_SHIPPED')
/
COMMIT
/
DELETE FROM EVENT_STATE
WHERE NAME = 'PART_RETURN_SHIPPED'
/
COMMIT
/
INSERT INTO EVENT_STATE
(ID, VERSION, NAME, DISPLAY_NAME, D_ACTIVE)
VALUES
((SELECT MAX(ID)+1 FROM EVENT_STATE),0,'PARTS_REJECTED_ON_CLAIM','Parts Rejected On Claim',1)
/
INSERT INTO EVENT_STATE
(ID, VERSION, NAME, DISPLAY_NAME, D_ACTIVE)
VALUES
((SELECT MAX(ID)+1 FROM EVENT_STATE),0,'PART_MOVED_TO_OVERDUE','Part Moved To Overdue',1)
/
INSERT INTO EVENT_STATE
(ID, VERSION, NAME, DISPLAY_NAME, D_ACTIVE)
VALUES
((SELECT MAX(ID)+1 FROM EVENT_STATE),0,'CLAIM_DENIED_FOR_LACK_OF_PART_RETURNS','Claim Denied For Lack Of Parts',1)
/
COMMIT
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'PARTS_REJECTED_ON_CLAIM'),(SELECT ID FROM ROLE WHERE NAME = 'processor'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'PART_MOVED_TO_OVERDUE'),(SELECT ID FROM ROLE WHERE NAME = 'dealer'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'CLAIM_DENIED_FOR_LACK_OF_PART_RETURNS'),(SELECT ID FROM ROLE WHERE NAME = 'dealer'))
/
COMMIT
/