INSERT INTO EVENT_STATE (ID,VERSION,NAME,DISPLAY_NAME,D_CREATED_ON,D_INTERNAL_COMMENTS,D_UPDATED_ON,D_LAST_UPDATED_BY,D_CREATED_TIME,D_UPDATED_TIME,D_ACTIVE) VALUES (1,0,'CLAIM_PROCESSOR_REVIEW','Claim Processer Review',null,null,null,null,null,null,1)
/
INSERT INTO EVENT_STATE (ID,VERSION,NAME,DISPLAY_NAME,D_CREATED_ON,D_INTERNAL_COMMENTS,D_UPDATED_ON,D_LAST_UPDATED_BY,D_CREATED_TIME,D_UPDATED_TIME,D_ACTIVE) VALUES (2,0,'SERVICE_MANAGER_REVIEW','Service Manager Review',null,null,null,null,null,null,1)
/
INSERT INTO EVENT_STATE (ID,VERSION,NAME,DISPLAY_NAME,D_CREATED_ON,D_INTERNAL_COMMENTS,D_UPDATED_ON,D_LAST_UPDATED_BY,D_CREATED_TIME,D_UPDATED_TIME,D_ACTIVE) VALUES (3,0,'SERVICE_MANAGER_RESPONSE','Service Manager Response',null,null,null,null,null,null,1)
/
INSERT INTO EVENT_STATE (ID,VERSION,NAME,DISPLAY_NAME,D_CREATED_ON,D_INTERNAL_COMMENTS,D_UPDATED_ON,D_LAST_UPDATED_BY,D_CREATED_TIME,D_UPDATED_TIME,D_ACTIVE) VALUES (4,0,'CLAIM_FORWARDED','Claim Forwarded',null,null,null,null,null,null,1)
/
INSERT INTO EVENT_STATE (ID,VERSION,NAME,DISPLAY_NAME,D_CREATED_ON,D_INTERNAL_COMMENTS,D_UPDATED_ON,D_LAST_UPDATED_BY,D_CREATED_TIME,D_UPDATED_TIME,D_ACTIVE) VALUES (5,0,'CLAIM_TRANSFERED','Claim Transfered',null,null,null,null,null,null,1)
/
INSERT INTO EVENT_STATE (ID,VERSION,NAME,DISPLAY_NAME,D_CREATED_ON,D_INTERNAL_COMMENTS,D_UPDATED_ON,D_LAST_UPDATED_BY,D_CREATED_TIME,D_UPDATED_TIME,D_ACTIVE) VALUES (6,0,'ADVICE_REQUEST','Claim Sent For Advice Request',null,null,null,null,null,null,1)
/
INSERT INTO EVENT_STATE (ID,VERSION,NAME,DISPLAY_NAME,D_CREATED_ON,D_INTERNAL_COMMENTS,D_UPDATED_ON,D_LAST_UPDATED_BY,D_CREATED_TIME,D_UPDATED_TIME,D_ACTIVE) VALUES (7,0,'CLAIM_REPLIES','Claim Replied Back',null,null,null,null,null,null,1)
/
INSERT INTO EVENT_STATE (ID,VERSION,NAME,DISPLAY_NAME,D_CREATED_ON,D_INTERNAL_COMMENTS,D_UPDATED_ON,D_LAST_UPDATED_BY,D_CREATED_TIME,D_UPDATED_TIME,D_ACTIVE) VALUES (8,0,'WAITING_FOR_PART_RETURNS','Waiting For Part Return',null,null,null,null,null,null,1)
/
INSERT INTO EVENT_STATE (ID,VERSION,NAME,DISPLAY_NAME,D_CREATED_ON,D_INTERNAL_COMMENTS,D_UPDATED_ON,D_LAST_UPDATED_BY,D_CREATED_TIME,D_UPDATED_TIME,D_ACTIVE) VALUES (9,0,'REJECTED_PART_RETURN','Rejected Part Returns',null,null,null,null,null,null,1)
/
INSERT INTO EVENT_STATE (ID,VERSION,NAME,DISPLAY_NAME,D_CREATED_ON,D_INTERNAL_COMMENTS,D_UPDATED_ON,D_LAST_UPDATED_BY,D_CREATED_TIME,D_UPDATED_TIME,D_ACTIVE) VALUES (10,0,'CLAIM_REACCEPTED','Claim Reaccepted',null,null,null,null,null,null,1)
/
INSERT INTO EVENT_STATE (ID,VERSION,NAME,DISPLAY_NAME,D_CREATED_ON,D_INTERNAL_COMMENTS,D_UPDATED_ON,D_LAST_UPDATED_BY,D_CREATED_TIME,D_UPDATED_TIME,D_ACTIVE) VALUES (11,0,'CLAIM_ACCEPTED_AND_CLOSED','Claim Accepted And Closed',null,null,null,null,null,null,1)
/
INSERT INTO EVENT_STATE (ID,VERSION,NAME,DISPLAY_NAME,D_CREATED_ON,D_INTERNAL_COMMENTS,D_UPDATED_ON,D_LAST_UPDATED_BY,D_CREATED_TIME,D_UPDATED_TIME,D_ACTIVE) VALUES (12,0,'CLAIM_DENIED_AND_CLOSED','Claim Denied And Closed',null,null,null,null,null,null,1)
/
INSERT INTO EVENT_STATE (ID,VERSION,NAME,DISPLAY_NAME,D_CREATED_ON,D_INTERNAL_COMMENTS,D_UPDATED_ON,D_LAST_UPDATED_BY,D_CREATED_TIME,D_UPDATED_TIME,D_ACTIVE) VALUES (13,0,'CLAIM_APPEALED','Claim Appealed',null,null,null,null,null,null,1)
/
INSERT INTO EVENT_STATE (ID,VERSION,NAME,DISPLAY_NAME,D_CREATED_ON,D_INTERNAL_COMMENTS,D_UPDATED_ON,D_LAST_UPDATED_BY,D_CREATED_TIME,D_UPDATED_TIME,D_ACTIVE) VALUES (14,0,'PART_RETURN_SHIPPED','Parts Shipped',null,null,null,null,null,null,1)
/
INSERT INTO EVENT_STATE (ID,VERSION,NAME,DISPLAY_NAME,D_CREATED_ON,D_INTERNAL_COMMENTS,D_UPDATED_ON,D_LAST_UPDATED_BY,D_CREATED_TIME,D_UPDATED_TIME,D_ACTIVE) VALUES (15,0,'DUE_PART_RETURN_RECEIPT','Part Recieved',null,null,null,null,null,null,1)
/
INSERT INTO EVENT_STATE (ID,VERSION,NAME,DISPLAY_NAME,D_CREATED_ON,D_INTERNAL_COMMENTS,D_UPDATED_ON,D_LAST_UPDATED_BY,D_CREATED_TIME,D_UPDATED_TIME,D_ACTIVE) VALUES (16,0,'START_PART_RETURN','Part To Be Returned',null,null,null,null,null,null,1)
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'SERVICE_MANAGER_REVIEW'),(SELECT ID FROM ROLE WHERE NAME = 'dsm'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'SERVICE_MANAGER_RESPONSE'),(SELECT ID FROM ROLE WHERE NAME = 'dealer'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'CLAIM_FORWARDED'),(SELECT ID FROM ROLE WHERE NAME = 'dealer'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'CLAIM_TRANSFERED'),(SELECT ID FROM ROLE WHERE NAME = 'processor'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'ADVICE_REQUEST'),(SELECT ID FROM ROLE WHERE NAME = 'dsmAdvisor'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'CLAIM_REPLIES'),(SELECT ID FROM ROLE WHERE NAME = 'processor'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'WAITING_FOR_PART_RETURNS'),(SELECT ID FROM ROLE WHERE NAME = 'dealer'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'REJECTED_PART_RETURN'),(SELECT ID FROM ROLE WHERE NAME = 'processor'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'CLAIM_REACCEPTED'),(SELECT ID FROM ROLE WHERE NAME = 'dealer'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'CLAIM_PROCESSOR_REVIEW'),(SELECT ID FROM ROLE WHERE NAME = 'processor'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'CLAIM_ACCEPTED_AND_CLOSED'),(SELECT ID FROM ROLE WHERE NAME = 'dealer'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'CLAIM_DENIED_AND_CLOSED'),(SELECT ID FROM ROLE WHERE NAME = 'dealer'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'CLAIM_APPEALED'),(SELECT ID FROM ROLE WHERE NAME = 'processor'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'PART_RETURN_SHIPPED'),(SELECT ID FROM ROLE WHERE NAME = 'processor'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'PART_RETURN_SHIPPED'),(SELECT ID FROM ROLE WHERE NAME = 'receiver'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'DUE_PART_RETURN_RECEIPT'),(SELECT ID FROM ROLE WHERE NAME = 'dealer'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'DUE_PART_RETURN_RECEIPT'),(SELECT ID FROM ROLE WHERE NAME = 'processor'))
/
INSERT INTO EVENT_ROLE_MAPPING (EVENT_TYPES, ROLES) VALUES ((SELECT ID FROM EVENT_STATE WHERE NAME = 'START_PART_RETURN'),(SELECT ID FROM ROLE WHERE NAME = 'dealer'))
/
COMMIT
/