
ALTER TABLE CLAIM DROP CONSTRAINT CLAIM_FORDEALER_FK
/
ALTER TABLE CLAIM ADD (CONSTRAINT CLAIM_FORDEALER_FK FOREIGN KEY (FOR_DEALER) REFERENCES ORGANIZATION (ID))
/
CREATE TABLE THIRDPARTY ( ID NUMBER(19), THIRD_PARTY_NUMBER VARCHAR2(255 BYTE) ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/
CREATE UNIQUE INDEX THIRDPARTY_PK ON THIRDPARTY (ID) LOGGING NOPARALLEL
/
ALTER TABLE THIRDPARTY ADD ( CONSTRAINT THIRDPARTY_PK PRIMARY KEY (ID))
/
