--Purpose: Patch for modifying foreign key references to i18nitem_text table, adding data to the i18nitem_text table 
--and adding columns for the tables SERVICE_INFORMATION and FAILED_RULE
--Author: P Shraddha Nanda
--Created On: Date 12 Nov 2008

ALTER TABLE I18NITEM_TEXT ADD CONSTRAINT 
I18NITEM_TEXT_ITEM_FK FOREIGN KEY (ITEM)
REFERENCES ITEM (ID)
/
ALTER TABLE SERVICE_INFORMATION ADD  (
THIRD_PARTY_LABOR_RATE_AMT NUMBER(19,2)
)
/
ALTER TABLE SERVICE_INFORMATION ADD  (
THIRD_PARTY_LABOR_RATE_CURR VARCHAR2(255)
)
/
ALTER TABLE FAILED_RULE ADD (
DEFAULT_RULE_MSG_IN_US VARCHAR2(255)
)
/
INSERT INTO I18NITEM_TEXT (
SELECT I18N_ITEM_TEXT_SEQ.NEXTVAL, 'EN_US', DESCRIPTION, ID  FROM ITEM)