-- Patch for showing Replaced Installed Parts section
-- 24th February, 2009
-- Author: P Shraddha Nanda

INSERT INTO CONFIG_PARAM 
(ID, DESCRIPTION, DISPLAY_NAME, NAME, TYPE,PARAM_DISPLAY_TYPE,D_ACTIVE) VALUES (
CONFIG_PARAM_SEQ.NEXTVAL,'Display Parts Replaced Installed section','Display Parts Replaced Installed section',
'isPartsReplacedInstalledSectionVisible','boolean','radio',1)
/
INSERT INTO CONFIG_PARAM_OPTIONS_MAPPING 
VALUES ( CFG_PARAM_OPTNS_MAPPING_SEQ.NEXTVAL, (SELECT ID FROM  CONFIG_PARAM CP WHERE NAME='isPartsReplacedInstalledSectionVisible'),
(SELECT ID FROM  CONFIG_PARAM_OPTION CPO WHERE CPO.DISPLAY_VALUE ='Yes')) 
/
INSERT INTO CONFIG_PARAM_OPTIONS_MAPPING 
VALUES ( CFG_PARAM_OPTNS_MAPPING_SEQ.NEXTVAL, (SELECT ID FROM  CONFIG_PARAM CP WHERE NAME='isPartsReplacedInstalledSectionVisible'),
(SELECT ID FROM  CONFIG_PARAM_OPTION CPO WHERE CPO.DISPLAY_VALUE ='No'))
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, CONFIG_PARAM,BUSINESS_UNIT_INFO, CONFIG_PARAM_OPTION, D_ACTIVE) 
VALUES
((SELECT MAX(ID)+10 FROM CONFIG_VALUE),1,
(SELECT ID FROM CONFIG_PARAM WHERE NAME='isPartsReplacedInstalledSectionVisible'),'Hussmann',
(SELECT ID FROM CONFIG_PARAM_OPTION WHERE VALUE='true'),1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, CONFIG_PARAM,BUSINESS_UNIT_INFO, CONFIG_PARAM_OPTION, D_ACTIVE) 
VALUES
((SELECT MAX(ID)+10 FROM CONFIG_VALUE),1,
(SELECT ID FROM CONFIG_PARAM WHERE NAME='isPartsReplacedInstalledSectionVisible'),'AIR',
(SELECT ID FROM CONFIG_PARAM_OPTION WHERE VALUE='false'),1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, CONFIG_PARAM,BUSINESS_UNIT_INFO, CONFIG_PARAM_OPTION, D_ACTIVE) 
VALUES
((SELECT MAX(ID)+10 FROM CONFIG_VALUE),1,
(SELECT ID FROM CONFIG_PARAM WHERE NAME='isPartsReplacedInstalledSectionVisible'),'Club Car',
(SELECT ID FROM CONFIG_PARAM_OPTION WHERE VALUE='false'),1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, CONFIG_PARAM,BUSINESS_UNIT_INFO, CONFIG_PARAM_OPTION, D_ACTIVE) 
VALUES
((SELECT MAX(ID)+10 FROM CONFIG_VALUE),1,
(SELECT ID FROM CONFIG_PARAM WHERE NAME='isPartsReplacedInstalledSectionVisible'),'Transport Solutions ESA',
(SELECT ID FROM CONFIG_PARAM_OPTION WHERE VALUE='false'),1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, CONFIG_PARAM,BUSINESS_UNIT_INFO, CONFIG_PARAM_OPTION, D_ACTIVE) 
VALUES
((SELECT MAX(ID)+10 FROM CONFIG_VALUE),1,
(SELECT ID FROM CONFIG_PARAM WHERE NAME='isPartsReplacedInstalledSectionVisible'),'TFM',
(SELECT ID FROM CONFIG_PARAM_OPTION WHERE VALUE='false'),1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, CONFIG_PARAM,BUSINESS_UNIT_INFO, CONFIG_PARAM_OPTION, D_ACTIVE) 
VALUES
((SELECT MAX(ID)+10 FROM CONFIG_VALUE),1,
(SELECT ID FROM CONFIG_PARAM WHERE NAME='isPartsReplacedInstalledSectionVisible'),'Clubcar ESA',
(SELECT ID FROM CONFIG_PARAM_OPTION WHERE VALUE='false'),1)
/
COMMIT
/ 