--purpose : PATCH FOR JBPM CHANGES DONE
--Author: P Shraddha Nanda
--Created On: Date 10 Dec 2008

UPDATE JBPM_DECISIONCONDITIONS SET EXPRESSION_ = '#{partReturn.oemPartReplaced.partToBeReturned and claim.thirdPartyClaim == false}' WHERE TRANSITIONNAME_ = 'ShipmentToOEM'
/
INSERT INTO JBPM_DECISIONCONDITIONS (DECISION_,TRANSITIONNAME_,EXPRESSION_,INDEX_)
VALUES
(SELECT DECISION_ FROM JBPM_DECISIONCONDITIONS WHERE TRANSITIONNAME_ = 'ShipmentToOEM','ThirdPartyShipment','#{partReturn.oemPartReplaced.partToBeReturned and claim.thirdPartyClaim == true}',SELECT MAX(INDEX_)+1 FROM JBPM_DECISIONCONDITIONS WHERE DECISION_ IN (SELECT DECISION_ FROM JBPM_DECISIONCONDITIONS WHERE TRANSITIONNAME_ = 'ShipmentToOEM'))
/
INSERT INTO JBPM_NODE (ID_, CLASS_, NAME_, PROCESSDEFINITION_, ISASYNC_, ACTION_, SUPERSTATE_, SIGNAL_, CREATETASKS_, ENDTASKS_, TASK_NAMES_TO_END, DECISIONEXPRESSION_, DECISIONDELEGATION, SUBPROCESSDEFINITION_, END_TRANSITION, NORMAL_TRANSITION, NODECOLLECTIONINDEX_) 
VALUES 
(HIBERNATE_SEQUENCE.NEXTVAL, 'A','Due Parts for Third Party',
(SELECT ID_ FROM JBPM_PROCESSDEFINITION WHERE NAME_='PartsReturn'),0,NULL,NULL,4,1,0,NULL,NULL,NULL,NULL,NULL,NULL,3)
/
INSERT INTO JBPM_TASK (ID_, NAME_, PROCESSDEFINITION_, DESCRIPTION_, ISBLOCKING_, ISSIGNALLING_, DUEDATE_, ACTORIDEXPRESSION_, POOLEDACTORSEXPRESSION_, TASKMGMTDEFINITION_, TASKNODE_, STARTSTATE_, ASSIGNMENTDELEGATION_, SWIMLANE_, TASKCONTROLLER_) 
VALUES 
(HIBERNATE_SEQUENCE.NEXTVAL, 'Third Party Due Parts',
(SELECT ID_ FROM JBPM_PROCESSDEFINITION WHERE NAME_='PartsReturn'),NULL,0,1,NULL,NULL,NULL,
(SELECT ID_ FROM JBPM_MODULEDEFINITION WHERE NAME_='org.jbpm.taskmgmt.def.TaskMgmtDefinition' AND PROCESSDEFINITION_=(SELECT ID_ FROM JBPM_PROCESSDEFINITION WHERE NAME_='PartsReturn')),
(SELECT ID_ FROM JBPM_NODE WHERE NAME_='Due Parts for Third Party'),NULL,NULL,
(SELECT ID_ FROM JBPM_SWIMLANE WHERE NAME_='dealer' AND TASKMGMTDEFINITION_ = (SELECT ID_ FROM JBPM_MODULEDEFINITION 
WHERE NAME_='org.jbpm.taskmgmt.def.TaskMgmtDefinition' AND 
PROCESSDEFINITION_=(SELECT ID_ FROM JBPM_PROCESSDEFINITION WHERE NAME_='PartsReturn'))),NULL)
/
INSERT INTO JBPM_FORM_NODES (FORM_TASK_NODE_FORM_ID,FORM_VALUE,FORM_TYPE) 
VALUES 
(SELECT ID_ FROM JBPM_NODE WHERE NAME_ = 'Due Parts for Third Party','thirdPartyDueParts','actionUrl')
/
INSERT INTO JBPM_TRANSITION (ID_,NAME_,PROCESSDEFINITION_,FROM_,TO_,FROMINDEX_)
VALUES
(HIBERNATE_SEQUENCE.NEXTVAL,'toEnd',SELECT ID_ FROM JBPM_PROCESSDEFINITION WHERE NAME_='PartsReturn',SELECT ID_ FROM JBPM_NODE WHERE NAME_ = 'Due Parts for Third Party',SELECT * FROM JBPM_NODE WHERE NAME_ = 'End' and class_ = 'E' and processdefinition_ = (SELECT ID_ FROM JBPM_PROCESSDEFINITION WHERE NAME_='PartsReturn'),0)
/
INSERT INTO JBPM_TRANSITION (ID_,NAME_,PROCESSDEFINITION_,FROM_,TO_,FROMINDEX_)
VALUES
(HIBERNATE_SEQUENCE.NEXTVAL,'Generate Shipment',SELECT ID_ FROM JBPM_PROCESSDEFINITION WHERE NAME_='PartsReturn',SELECT ID_ FROM JBPM_NODE WHERE NAME_ = 'Due Parts for Third Party',SELECT * FROM JBPM_NODE WHERE NAME_ = 'Shipment Generated' and processdefinition_ = (SELECT ID_ FROM JBPM_PROCESSDEFINITION WHERE NAME_='PartsReturn'),1)
/
INSERT INTO JBPM_TRANSITION (ID_,NAME_,PROCESSDEFINITION_,FROM_,TO_,FROMINDEX_)
VALUES
(HIBERNATE_SEQUENCE.NEXTVAL,'ThirdPartyShipment',(SELECT ID_ FROM JBPM_PROCESSDEFINITION WHERE NAME_='PartsReturn'),(SELECT ID_ FROM JBPM_NODE WHERE NAME_ = 'IsPartToBeReturned'),(SELECT ID_ FROM JBPM_NODE WHERE NAME_ = 'Due Parts for Third Party' and class_ = 'A' and processdefinition_ = (SELECT ID_ FROM JBPM_PROCESSDEFINITION WHERE NAME_='PartsReturn')),
(SELECT MAX(FROMINDEX_)+1 FROM JBPM_TRANSITION WHERE FROM_ = (SELECT ID_ FROM JBPM_NODE WHERE NAME_ = 'IsPartToBeReturned' )))
/
INSERT INTO JBPM_EVENT (ID_,EVENTTYPE_,TYPE_,GRAPHELEMENT_,TRANSITION_,TASK_,NODE_,PROCESSDEFINITION_) 
VALUES
(HIBERNATE_SEQUENCE.NEXTVAL,'transition','T',(SELECT ID_ FROM JBPM_TRANSITION WHERE NAME_ = 'Generate Shipment'),(SELECT ID_ FROM JBPM_TRANSITION WHERE NAME_ = 'Generate Shipment'),NULL,NULL,NULL)
/
INSERT INTO JBPM_ACTION (ID_, CLASS, NAME_, ISPROPAGATIONALLOWED_, ACTIONEXPRESSION_, ISASYNC_, REFERENCEDACTION_, ACTIONDELEGATION_, EVENT_, PROCESSDEFINITION_, TIMERNAME_, EXPRESSION_, DUEDATE_, REPEAT_, TRANSITIONNAME_, TIMERACTION_, EVENTINDEX_, EXCEPTIONHANDLER_, EXCEPTIONHANDLERINDEX_)
VALUES
(HIBERNATE_SEQUENCE.NEXTVAL,'S',NULL,1,null,0,null,null,(SELECT ID_ FROM JBPM_EVENT WHERE TRANSITION_ = (SELECT ID_ FROM JBPM_TRANSITION WHERE NAME_ = 'Generate Shipment')),null,null,'partReturn.setStatus(tavant.twms.domain.partreturn.PartReturnStatus.SHIPMENT_GENERATED)',null,null,null,null,0,null,null)
/
INSERT INTO JBPM_DELEGATION (ID_, CLASSNAME_, CONFIGURATION_, CONFIGTYPE_, PROCESSDEFINITION_) 
VALUES 
(HIBERNATE_SEQUENCE.NEXTVAL,'tavant.twms.jbpm.assignment.ExpressionAssignmentHandler','<expression>actor=ognl{claim.filedBy.name}</expression>',NULL,(SELECT ID_ FROM JBPM_PROCESSDEFINITION WHERE NAME_='ClaimSubmission'))
/
INSERT INTO  JBPM_SWIMLANE (ID_, NAME_, ACTORIDEXPRESSION_, POOLEDACTORSEXPRESSION_, ASSIGNMENTDELEGATION_, TASKMGMTDEFINITION_) VALUES (HIBERNATE_SEQUENCE.NEXTVAL,'baserole',NULL,NULL,
(SELECT ID_ FROM JBPM_DELEGATION WHERE PROCESSDEFINITION_=(SELECT ID_ FROM JBPM_PROCESSDEFINITION WHERE NAME_='ClaimSubmission') AND CLASSNAME_='tavant.twms.jbpm.assignment.ExpressionAssignmentHandler'
AND CONFIGURATION_ LIKE '%<expression>actor=ognl{claim.filedBy.name}</expression>%' AND 
ID_ NOT IN (SELECT DISTINCT ASSIGNMENTDELEGATION_ FROM JBPM_SWIMLANE)
),
(SELECT ID_ FROM JBPM_MODULEDEFINITION WHERE PROCESSDEFINITION_=(SELECT ID_ FROM JBPM_PROCESSDEFINITION WHERE NAME_='ClaimSubmission') 
AND NAME_='org.jbpm.taskmgmt.def.TaskMgmtDefinition')
)
/
UPDATE JBPM_TASK SET SWIMLANE_ = (SELECT ID FROM JBPM_SWIMLANE WHERE NAME_ = 'baserole') WHERE NAME_ = 'Draft Claim'
/
commit
/
