--Purpose: Patch for modifying OEM_PART_REPLACED AND INSTALLED_PARTS
--Author: Shraddha Nanda P 
--Created On: Date  09 JAN 2009

CREATE TABLE HUSS_PARTS_REPLACED_INSTALLED
(
 ID NUMBER(19),
 SERVICE_DETAIL NUMBER(19)
)
/
ALTER TABLE HUSS_PARTS_REPLACED_INSTALLED ADD (
  CONSTRAINT HUSSPARTS_REPINSTALL_PK
 PRIMARY KEY
 (ID)
)
/
ALTER TABLE HUSS_PARTS_REPLACED_INSTALLED ADD (
CONSTRAINT HUSSPARTSREPINS_SERVICE_FK 
FOREIGN KEY (SERVICE_DETAIL) 
REFERENCES SERVICE (ID))
/
ALTER TABLE OEM_PART_REPLACED ADD 
OEM_REPLACED_PARTS NUMBER(19)
/
ALTER TABLE OEM_PART_REPLACED ADD (
  CONSTRAINT OEMPRTREP_HUSSREPINS_FK 
 FOREIGN KEY (OEM_REPLACED_PARTS) 
 REFERENCES HUSS_PARTS_REPLACED_INSTALLED (ID))
/
CREATE TABLE INSTALLED_PARTS
(
  ID                         NUMBER(19),
  PART_NUMBER                VARCHAR2(255 BYTE),
  COST_PRICE_PER_UNIT_AMT    NUMBER(19,2),
  COST_PRICE_PER_UNIT_CURR   VARCHAR2(255 CHAR),
  NUMBER_OF_UNITS            NUMBER(10),
  PRICE_PER_UNIT_AMT         NUMBER(19,2),
  PRICE_PER_UNIT_CURR        VARCHAR2(255 CHAR),
  INVENTORY_LEVEL            NUMBER(1),
  MATERIAL_COST_AMT          NUMBER(19,2),
  MATERIAL_COST_CURR         VARCHAR2(255 CHAR),
  DESCRIPTION                VARCHAR2(255 BYTE),
  PRICE                      NUMBER(19),
  IS_HUSSMAN_PART            VARCHAR2(10 BYTE),
  OEM_PARTS_INSTALLED        NUMBER(19),
  NON_OEM_PARTS_INSTALLED    NUMBER(19),
  ITEM						           NUMBER(19),
  D_CREATED_ON               DATE,
  D_INTERNAL_COMMENTS        VARCHAR2(255 CHAR),
  D_UPDATED_ON               DATE,
  D_LAST_UPDATED_BY          NUMBER(19),
  STATUS                     VARCHAR2(255 CHAR),
  D_CREATED_TIME             TIMESTAMP(6),
  D_ACTIVE 		               NUMBER(1,0),
  D_UPDATED_TIME             TIMESTAMP(6)
)
/
CREATE UNIQUE INDEX INSTALLED_PARTS_PK ON INSTALLED_PARTS
(ID)
/
ALTER TABLE INSTALLED_PARTS ADD (
  CONSTRAINT INSTALLED_PARTS_PK
 PRIMARY KEY
 (ID))
/
ALTER TABLE INSTALLED_PARTS ADD (
  CONSTRAINT INST_HUSSREPINS_HUSS_FK 
 FOREIGN KEY (OEM_PARTS_INSTALLED) 
 REFERENCES HUSS_PARTS_REPLACED_INSTALLED (ID))
/
ALTER TABLE INSTALLED_PARTS ADD (
  CONSTRAINT INST_HUSSREPINS_NONHUSS_FK 
 FOREIGN KEY (NON_OEM_PARTS_INSTALLED) 
 REFERENCES HUSS_PARTS_REPLACED_INSTALLED (ID))
/
ALTER TABLE INSTALLED_PARTS ADD (
  CONSTRAINT INST_PARTS_ITEM_FK 
 FOREIGN KEY (ITEM) 
 REFERENCES ITEM (ID))
/
ALTER TABLE HUSS_PARTS_REPLACED_INSTALLED
 ADD (INVOICE  NUMBER(19))
/
CREATE SEQUENCE GROUP_ID_SEQ
  START WITH 1000
  INCREMENT BY 20
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
/
CREATE SEQUENCE HUSSPARTS_REPINSTALLED_SEQ
  START WITH 1000
  INCREMENT BY 20
  MAXVALUE 999999999999999999999999999
  MINVALUE 1000
  NOCYCLE
  CACHE 20
  NOORDER
