--purpose : PATCH FOR SUPPLIER PART RECOVERY FLOW OF THE HUSSMANN PARTS REPLACED INSTALLED MAPPING CR
--Author: P Shraddha Nanda
--Created On: Date 18 FEB,2009

ALTER TABLE INSTALLED_PARTS ADD 
OEM_DEALER_PART_REPLACED    NUMBER(19)
/
ALTER TABLE INSTALLED_PARTS ADD (
  CONSTRAINT INSTPARTS_OEMDEALERPARTREPL_FK 
 FOREIGN KEY (OEM_DEALER_PART_REPLACED) 
 REFERENCES ITEM (ID))
/
ALTER TABLE INSTALLED_PARTS ADD 
SUPPLIER_ITEM               NUMBER(19)
/
ALTER TABLE INSTALLED_PARTS ADD (
  CONSTRAINT INSTPARTS_SUPPLIERITEM_FK 
 FOREIGN KEY (SUPPLIER_ITEM) 
 REFERENCES ITEM (ID))
/