<%@taglib prefix="s" uri="/struts-tags"%>
<%@taglib prefix="t" uri="twms"%><%@taglib prefix="u" uri="/ui-ext"%>
<%@taglib prefix="authz" uri="authz"%>
<s:iterator value="recoveryClaim.recoveryClaimInfo.recoverableParts" status="partReplacedStatus">
   <s:if test="partRecoveryAudits!=null && partRecoveryAudits.size>0">
        <div class="mainTitle" style="margin-top:5px;">
            <table class="grid" width="100%" cellspacing="0" cellpadding="0" style="margin-top:-10px;">
                <tr> <td class="labelStyle" nowrap="nowrap" width="10%"> <s:text name="label.contractAdmin.oemPartNumber"/> </td>
                     <td class="non_editable" > (<s:property value="oemPart.itemReference.unserializedItem.number"/> ) </td>
                </tr><tr>
                     <td class="labelStyle" nowrap="nowrap" width="10%"> <s:text name="columnTitle.duePartsInspection.supplier_part_no"/>  </td>
                     <td class="non_editable"> (<s:property value="supplierItem.number"/> ) </td> </tr>
            </table>
        </div>
        <div class="borderTable" >&nbsp;</div>

        	<table class="grid" width="100%" cellspacing="0" cellpadding="0" style="margin-top:-10px;">
            	 <tr>
            		<td class="labelStyle" nowrap="nowrap" width="10%"><s:text name="columnTitle.shipmentGenerated.qty"/>:</td>
                    <td class="non_editable">
                        <s:property value="quantity"/>
                    </td>
                 </tr>
                 <tr>
            		<td class="labelStyle" nowrap="nowrap" width="20%"><s:text name="columnTitle.shipmentGenerated.return_location"/>:</td>
            		<td class="non_editable" width="30%" >
                        <s:property value="supplierPartReturns[0].returnLocation.code"/>
                    </td>
               	 </tr>
               	 <tr>
                <td class="labelStyle" nowrap="nowrap" width="20%"><s:text name="columnTitle.partShipperPartsShipped.RGA_number"/>:</td>
                <td class="non_editable" width="30%" >
                 <s:if test="supplierPartReturns[0]!=null && supplierPartReturns[0].rgaNumber!=null">
						 <s:property value="supplierPartReturns[0].rgaNumber" /></s:if>
                     	<s:else>
						<s:property value="oemPart.partReturns[0].rmaNumber"/></s:else>
                 </td>
                 </tr>
            </table>
   </s:if>
   <s:if test="partRecoveryAudits!=null && partRecoveryAudits.size>0">
   <table  class="grid borderForTable" style="width:97%" cellspacing="0" cellpadding="0">
   	<thead>
   		<tr class="row_head">
            <th><s:text name="label.common.date" /></th>
   			<th><s:text name="label.policyAudit.status"/></th>
   			<th><s:text name="label.common.user"/></th>
   			<th><s:text name="label.common.comments"/></th>
        </tr>
   	</thead>
   	<tbody>
    <s:iterator value="partRecoveryAudits" status="auditStatus">
          <%--<s:if test="isLoggedInUserAnInternalUser()">--%>
              <tr>
               <td ><s:property value="d.updatedOn"/></td>
               <td >
                   <s:if test="(prStatus=='Shipment Generated' || prStatus=='Partially Shipment Generated')">
                        <s:text name="part.recovery.shipment.generated.status"/>
                   </s:if>
                   <s:else>
                       <s:property value="prStatus"/>
                   </s:else>
                   <s:if test="(prStatus=='Partially Shipped' || prStatus=='Part Shipped' || prStatus=='Parts shipped to NMHG by Supplier')">
                       &nbsp;(<s:text name="columnTitle.supplierDueParts.tracking_number" /> : <s:property value="%{trackingNo}" />)
                   </s:if>
                   <s:if test="(prStatus=='Shipment Generated' || prStatus=='Partially Shipment Generated' || prStatus=='Shipment Generated By Supplier for parts to be shipped back to NMHG')">
                       &nbsp;(<s:text name="columnTitle.partShipperPartsShipped.vpraNumber" /> : <s:property value="%{shipmentNumber}" />)
                   </s:if>
               </td>
               <td ><s:property value="d.lastUpdatedBy.CompleteNameAndLogin"/></td>
               <td><s:property value="comments"/><br/>
               <s:if test="partReturnAction1!=null">
                  <s:property value="partReturnAction1.actionTaken"/>:<s:property value="partReturnAction1.value"/><br/>
               </s:if>
               <s:if test="partReturnAction2!=null">
                  <s:property value="partReturnAction2.actionTaken"/>:<s:property value="partReturnAction2.value"/><br/>
               </s:if>
               <s:if test="partReturnAction3!=null">
                  <s:property value="partReturnAction3.actionTaken"/>:<s:property value="partReturnAction3.value"/><br/>
               </s:if>
               </td>
               </tr>
          <%--</s:if>--%>
   </s:iterator>
   	</tbody>
    </table>
   </s:if>

</s:iterator>