--Purpose    : Claim Competitor model Added to Claim, changes made as a part of 4.3 upgrade 
--Author     : lavin.hawes
--Created On : 05/02/10
--Impact     : None

ALTER TABLE CLAIM ADD ( CLAIM_COMPETITOR_MODEL number(19,0))
/
ALTER TABLE CLAIM ADD (
	CONSTRAINT CLAIM_COMPETITORMODEL_FK
	FOREIGN KEY (CLAIM_COMPETITOR_MODEL) 
	REFERENCES LIST_OF_VALUES(ID)
)
/
ALTER TABLE CLAIM ADD LABOR_ROUNDUP_WINDOW_FROM_DATE DATE
/
ALTER TABLE CLAIM ADD LABOR_ROUNDUP_WINDOW_TO_DATE DATE
/
ALTER TABLE claim ADD BOM_UPDATION_NEEDED NUMBER(1,0)
/
UPDATE claim SET BOM_UPDATION_NEEDED=0 WHERE BOM_UPDATION_NEEDED IS NULL
/
ALTER TABLE CLAIM ADD  SOURCE VARCHAR2(255)
/
COMMIT
/


