--Purpose    : Patch for Additional Labor Eligibility for Dealers, changed as a part of 4.3 upgrade.
--Author     : Kuldeep Patil
--Created On : 11-Oct-10


CREATE TABLE ADDITIONAL_LABOR_ELIGIBILITY
  (
    ID                 NUMBER(19,0)  NOT NULL ENABLE,
    BUSINESS_UNIT_INFO VARCHAR2(255 BYTE),
    D_CREATED_ON DATE,
    D_INTERNAL_COMMENTS VARCHAR2(255 CHAR),
    D_UPDATED_ON DATE,
    D_LAST_UPDATED_BY NUMBER(19,0),
    D_CREATED_TIME TIMESTAMP (6),
    D_UPDATED_TIME TIMESTAMP (6),
    D_ACTIVE NUMBER(1,0) DEFAULT 1,
    CONSTRAINT ADDITIONAL_LABOR_ELIG_PK  PRIMARY KEY (ID),
	CONSTRAINT  ADDN_LABOR_ELIG_BU_FK  FOREIGN KEY ( BUSINESS_UNIT_INFO ) 
           REFERENCES  BUSINESS_UNIT  ( NAME )
  )
/
CREATE TABLE ADD_LBR_EGL_SERVICE_PROVIDERS
  (
     ADDITIONAL_LABOR_ELIGIBILITY  NUMBER(19,0),
     SERVICE_PROVIDERS             NUMBER(19,0),
     D_CREATED_ON  DATE,
     D_INTERNAL_COMMENTS  VARCHAR2(255 CHAR),
     D_UPDATED_ON  DATE,
     D_LAST_UPDATED_BY  NUMBER(19,0),
     D_CREATED_TIME  TIMESTAMP (6),
     D_UPDATED_TIME  TIMESTAMP (6),
     D_ACTIVE  NUMBER(1,0) DEFAULT 1,
    CONSTRAINT  ADD_LBR_EGL_SRC_PROVIDERS_PK  
           PRIMARY KEY( ADDITIONAL_LABOR_ELIGIBILITY ,  SERVICE_PROVIDERS ), 
   
    CONSTRAINT  ADD_LABOR_EGL_FK  FOREIGN KEY ( ADDITIONAL_LABOR_ELIGIBILITY ) 
           REFERENCES  ADDITIONAL_LABOR_ELIGIBILITY  ( ID ) ,
    
    CONSTRAINT  SERVICE_PROVIDERS_FK  FOREIGN KEY ( SERVICE_PROVIDERS ) 
           REFERENCES  SERVICE_PROVIDER  ( ID ) 
  )
/