--Purpose    : Scripts for dropping supplier columns, changes made as a part of 4.3 upgrade 
--Created On : 11-Oct-2010
--Created By : Kuldeep Patil
--Impact     : None

CREATE TABLE OEM_PART_REPLACED_BACKUP
AS
(
	SELECT 
	ID,
	SUPPLIER_PART_RETURN,
	SUPPLIER_SHIPMENT,
	SUPPLIER_ITEM,
	SUPPLIER_RETURN_NEEDED
	FROM OEM_PART_REPLACED
)
/
ALTER TABLE OEM_PART_REPLACED DROP COLUMN SUPPLIER_PART_RETURN
/
ALTER TABLE OEM_PART_REPLACED DROP COLUMN SUPPLIER_SHIPMENT
/
ALTER TABLE OEM_PART_REPLACED DROP COLUMN SUPPLIER_ITEM
/
ALTER TABLE OEM_PART_REPLACED DROP COLUMN SUPPLIER_RETURN_NEEDED
/
COMMIT
/