--Purpose    : Modifying the recovery claim to hold the recovery Claim number, changes made as a part of 4.3 upgrade 
--Created On : 11-Oct-2010
--Created By : Kuldeep Patil
--Impact     : None

ALTER TABLE RECOVERY_CLAIM ADD(RECOVERY_CLAIM_NUMBER VARCHAR2(255))
/
DECLARE 

	CURSOR ALL_REC
	IS 
	SELECT RCL.ID, CLAIM, CL.CLAIM_NUMBER 
	FROM RECOVERY_CLAIM RCL, CLAIM CL 
	WHERE RCL.CLAIM = CL.ID AND CLAIM IN ( SELECT CLAIM FROM (SELECT CLAIM, COUNT(*) FROM RECOVERY_CLAIM GROUP BY  CLAIM HAVING COUNT(*) > 1)) ORDER BY CLAIM;
	
	V_REC_CLAIM_NUMBER VARCHAR2(255);
	V_CLAIM_NUMBER NUMBER(19,0) := 0;

BEGIN
	
	UPDATE RECOVERY_CLAIM REC_CLAIM 
	SET RECOVERY_CLAIM_NUMBER = (SELECT CLAIM_NUMBER||'_1' FROM CLAIM WHERE CLAIM.ID = REC_CLAIM.CLAIM)
	WHERE CLAIM NOT IN ( SELECT CLAIM FROM (SELECT CLAIM, COUNT(*) FROM RECOVERY_CLAIM GROUP BY CLAIM HAVING COUNT(*) > 1));
		
	FOR EACH_REC IN ALL_REC
	LOOP
		BEGIN
			V_REC_CLAIM_NUMBER := NULL;

			IF V_CLAIM_NUMBER = EACH_REC.CLAIM THEN
				V_REC_CLAIM_NUMBER := EACH_REC.CLAIM_NUMBER ||'_2';
			ELSE
				V_REC_CLAIM_NUMBER := EACH_REC.CLAIM_NUMBER ||'_1';
			END IF;

			UPDATE RECOVERY_CLAIM REC_CLAIM 
			SET RECOVERY_CLAIM_NUMBER = V_REC_CLAIM_NUMBER WHERE ID = EACH_REC.ID;

			V_CLAIM_NUMBER := EACH_REC.CLAIM;
		END;
	END LOOP;
	
	COMMIT;
	
	EXCEPTION WHEN OTHERS THEN
	ROLLBACK;
END;
/
COMMIT
/