--Purpose    : Add columns to Warranty for changes in WR as well as introduction of additional marketing information, changed as a part of 4.3 upgrade
--Author     : Kuldeep Patil
--Created On : 11-Oct-10


CREATE TABLE ADDTL_MARKETING_INFO
( ID NUMBER(19) PRIMARY KEY,
  VERSION NUMBER(19),
  APPL_ITEM_GROUP NUMBER(19),
  FIELD_NAME VARCHAR2(255),
  INFO_TYPE	VARCHAR2(255),
  BUSINESS_UNIT_INFO  VARCHAR2(255),
  D_CREATED_ON DATE, 
  D_INTERNAL_COMMENTS VARCHAR2(255), 
  D_UPDATED_ON DATE, 
  D_LAST_UPDATED_BY NUMBER(19,0), 
  D_CREATED_TIME TIMESTAMP (6), 
  D_UPDATED_TIME TIMESTAMP (6), 
  D_ACTIVE NUMBER(1,0) DEFAULT 1
)
/
ALTER TABLE ADDTL_MARKETING_INFO ADD (
  CONSTRAINT ADDTL_MKT_INFO_LST_UPDT_BY_FK 
 FOREIGN KEY (D_LAST_UPDATED_BY) 
 REFERENCES ORG_USER (ID))
/
ALTER TABLE ADDTL_MARKETING_INFO ADD (
  CONSTRAINT ADD_MKT_INFO_APPL_ITEM_GRP_FK 
 FOREIGN KEY (APPL_ITEM_GROUP) 
 REFERENCES ITEM_GROUP (ID))
/
CREATE SEQUENCE  ADDTL_MKTING_INFO_SEQ
MINVALUE 1000
MAXVALUE 99999999999999999999999 
INCREMENT BY 20 
START WITH 1000
CACHE 20 
NOORDER  
NOCYCLE
/
COMMIT
/
CREATE TABLE ADDTL_MKTING_INFO_OPTIONS
( 
  ID NUMBER(19) PRIMARY KEY,
  VERSION NUMBER(19),
  OPTION_VALUE VARCHAR2(4000),
  BUSINESS_UNIT_INFO  VARCHAR2(255),
  D_CREATED_ON DATE, 
  D_INTERNAL_COMMENTS VARCHAR2(255), 
  D_UPDATED_ON DATE, 
  D_LAST_UPDATED_BY NUMBER(19,0), 
  D_CREATED_TIME TIMESTAMP (6), 
  D_UPDATED_TIME TIMESTAMP (6), 
  D_ACTIVE NUMBER(1,0) DEFAULT 1
)
/
ALTER TABLE ADDTL_MKTING_INFO_OPTIONS ADD (
  CONSTRAINT ADDMKTINFOOPTNS_LST_UPDT_BY_FK 
 FOREIGN KEY (D_LAST_UPDATED_BY) 
 REFERENCES ORG_USER (ID))
/
CREATE SEQUENCE  ADDTL_MKTING_INFO_OPTIONS_SEQ
MINVALUE 1000
MAXVALUE 99999999999999999999999 
INCREMENT BY 20 
START WITH 1000
CACHE 20 
NOORDER  
NOCYCLE
/
COMMIT
/
CREATE TABLE ADD_MKTING_INFO_OPTNS_MAPPING
(
FOR_ADDTL_MKTING_INFO number(19),
OPTION_ID	number(19)
)
/
ALTER TABLE ADD_MKTING_INFO_OPTNS_MAPPING ADD (
 CONSTRAINT ADDTL_MKT_INFO_OPTIONS_MAP_FK 
 FOREIGN KEY (FOR_ADDTL_MKTING_INFO) 
 REFERENCES ADDTL_MARKETING_INFO (ID))
/
ALTER TABLE ADD_MKTING_INFO_OPTNS_MAPPING ADD (
 CONSTRAINT ADDMKTINFO_OPTNS_MAP_OPTION_FK 
 FOREIGN KEY (OPTION_ID) 
 REFERENCES ADDTL_MKTING_INFO_OPTIONS (ID))
/
CREATE TABLE SEL_ADDTL_MKTING_INFO
(
  ID NUMBER(19) PRIMARY KEY,
  VERSION NUMBER(19),
  ADDTL_MARKETING_INFO NUMBER(19),
  FOR_WARRANTY NUMBER(19),
  VALUE	VARCHAR2(255),
  D_CREATED_ON DATE, 
  D_INTERNAL_COMMENTS VARCHAR2(255 CHAR), 
  D_UPDATED_ON DATE, 
  D_LAST_UPDATED_BY NUMBER(19,0), 
  D_CREATED_TIME TIMESTAMP (6), 
  D_UPDATED_TIME TIMESTAMP (6), 
  D_ACTIVE NUMBER(1,0) DEFAULT 1
)
/
ALTER TABLE SEL_ADDTL_MKTING_INFO ADD (
  CONSTRAINT SEL_ADDMKTINFO_LST_UPDT_BY_FK 
 FOREIGN KEY (D_LAST_UPDATED_BY) 
 REFERENCES ORG_USER (ID))
/
ALTER TABLE SEL_ADDTL_MKTING_INFO ADD (
  CONSTRAINT SEL_ADD_MKT_INFO_FK 
 FOREIGN KEY (ADDTL_MARKETING_INFO) 
 REFERENCES ADDTL_MARKETING_INFO (ID))
/
ALTER TABLE SEL_ADDTL_MKTING_INFO ADD (
  CONSTRAINT SEL_ADD_MKT_INFO_WNTY_FK 
 FOREIGN KEY (FOR_WARRANTY) 
 REFERENCES WARRANTY (ID))
/
CREATE SEQUENCE  SEL_ADDTL_MARKETING_INFO_SEQ
MINVALUE 1000 
MAXVALUE 999999999999999999999999 
INCREMENT BY 20 
START WITH 1000 
CACHE 20 
NOORDER  
NOCYCLE
/
COMMIT
/
ALTER TABLE WARRANTY
ADD (
    OPERATOR NUMBER(19),
	INSTALLING_DEALER NUMBER(19),
    OEM NUMBER(19),
	FLEET_NUMBER VARCHAR2(255),
	EQUIPMENT_VIN  VARCHAR2(255),
	INSTALLATION_DATE DATE
	)
/
ALTER TABLE WARRANTY ADD (
  CONSTRAINT WNTY_OPERATOR_FK 
 FOREIGN KEY (OPERATOR) 
 REFERENCES CUSTOMER (ID))
/
ALTER TABLE WARRANTY ADD (
  CONSTRAINT WNTY_INSTALL_DLR_FK 
 FOREIGN KEY (INSTALLING_DEALER) 
 REFERENCES PARTY (ID))
/
COMMIT
/