--Purpose    : Scripts for creating campaign tables, changes made as a part of 4.3 upgrade 
--Created On : 11-Oct-2010
--Created By : Kuldeep Patil
--Impact     : None

CREATE SEQUENCE  RELATE_CAMPAIGN_SEQ
MINVALUE 1000
MAXVALUE 99999999999999999999999 
INCREMENT BY 20 
START WITH 1000
CACHE 20 
NOORDER  
NOCYCLE
/
CREATE TABLE RELATE_CAMPAIGN
( ID NUMBER(19) PRIMARY KEY,
  VERSION NUMBER(19),
  BUSINESS_UNIT_INFO  VARCHAR2(255),
  CODE VARCHAR2(255),
  DESCRIPTION	VARCHAR2(4000 BYTE), 
  D_CREATED_ON DATE, 
  D_INTERNAL_COMMENTS VARCHAR2(255), 
  D_UPDATED_ON DATE, 
  D_LAST_UPDATED_BY NUMBER(19,0), 
  D_CREATED_TIME TIMESTAMP (6), 
  D_UPDATED_TIME TIMESTAMP (6), 
  D_ACTIVE NUMBER(1,0) DEFAULT 1,
  CONSTRAINT RELATE_CAMPAIGN_BU_FK FOREIGN KEY (BUSINESS_UNIT_INFO) REFERENCES BUSINESS_UNIT (NAME) ENABLE,
  CONSTRAINT RELATE_CAMPAIGN_ORG_USER_FK FOREIGN KEY (D_LAST_UPDATED_BY) REFERENCES ORG_USER (ID) ENABLE
)
/
create table CAMPAIGNS_IN_RELATED_CAMPAIGN 
(CAMPAIGN  NUMBER not null, 
RELATED_CAMPAIGNS  NUMBER not null,
CONSTRAINT CAMPAIGNS_IN_RC_CAMPAIGN_FK FOREIGN KEY (CAMPAIGN) REFERENCES CAMPAIGN (ID) ENABLE,
CONSTRAINT C_IN_RC_RLTD_CAMPAIGNS_FK FOREIGN KEY (RELATED_CAMPAIGNS) REFERENCES RELATE_CAMPAIGN (ID) ENABLE
)
/
COMMIT
/