--Purpose    : Patch for Adding certifiedInstaller and nonCertifiedInstaller columns in warranty, changes made as a part of 4.3 upgrade 
--Author     : saya.sudha	
--Created On : 03-mar-2010

ALTER TABLE WARRANTY ADD (CERTIFIED_INSTALLER NUMBER(19))
/
ALTER TABLE WARRANTY ADD (
	CONSTRAINT WARRANTY_CI_FK
	FOREIGN KEY (CERTIFIED_INSTALLER)
	REFERENCES SERVICE_PROVIDER(ID)
)
/
ALTER TABLE WARRANTY ADD (NON_CERTIFIED_INSTALLER NUMBER(19))
/
ALTER TABLE WARRANTY ADD (
	CONSTRAINT WARRANTY_NCI_FK
	FOREIGN KEY (NON_CERTIFIED_INSTALLER)
	REFERENCES CUSTOMER(ID)
)
/
COMMIT
/