--Purpose    : New fields added in supplier_part_return for FD14 UC09.
--Created On : 07-APR-2010
--Created By : Sudaksh Chohan

--ALTER TABLE SUPPLIER_PART_RETURN ADD (SUPPLIER_SHIPMENT NUMBER(19,0))
--/
--ALTER TABLE SUPPLIER_PART_RETURN ADD (
--	CONSTRAINT FK_SUP_PART_RETURN_SHIPMENT
--	FOREIGN KEY (SUPPLIER_SHIPMENT) 
--	REFERENCES SHIPMENT(ID)
--)
--/
--ALTER TABLE SUPPLIER_PART_RETURN ADD (BAR_CODE VARCHAR2(255))
--/
--ALTER TABLE SUPPLIER_PART_RETURN ADD (RECOVERABLE_PART NUMBER(19,0))
--/
--ALTER TABLE SUPPLIER_PART_RETURN ADD (
--	CONSTRAINT FK_SUP_PART_RETURN_REC_PART
--	FOREIGN KEY (RECOVERABLE_PART) 
--	REFERENCES RECOVERABLE_PART(ID)
--)
--/
COMMIT
/