--Purpose    : Domain changes for staging extended warranty purchase notifications, changes made as a part of 4.3 upgrade 
--Created On : 11-Oct-2010
--Created By : Kuldeep Patil
--Impact     : None


CREATE TABLE EXTENDED_WARRANTY_NOTIFICATION 
(
  ID NUMBER(19) NOT NULL, 
  PURCHASING_DEALER NUMBER(19) NOT NULL, 
  FOR_UNIT NUMBER(19) NOT NULL, 
  POLICY NUMBER(19) NOT NULL, 
  NOTIFICATION_TYPE VARCHAR2(255) NOT NULL, 
  SALES_ORDER_NUMBER VARCHAR2(255), 
  SALES_ORDER_LINE_NUMBER VARCHAR2(255), 
  INVOICE_NUMBER VARCHAR2(255), 
  INVOICE_DATE DATE, 
  BUSINESS_UNIT_INFO VARCHAR2(255), 
  VERSION NUMBER, 
  D_CREATED_ON DATE, 
  D_UPDATED_ON DATE, 
  D_INTERNAL_COMMENTS VARCHAR2(255),
  D_LAST_UPDATED_BY NUMBER(19), 
  D_CREATED_TIME TIMESTAMP(6), 
  D_UPDATED_TIME TIMESTAMP(6), 
  D_ACTIVE NUMBER(1,0) DEFAULT 1 
)
/
ALTER TABLE EXTENDED_WARRANTY_NOTIFICATION ADD (
  CONSTRAINT PK_EXTENDED_WNTY_NOTIFICATION
 PRIMARY KEY (ID))
/
ALTER TABLE EXTENDED_WARRANTY_NOTIFICATION ADD (
  CONSTRAINT FK_PURCHASING_DEALER_EXTN_WNTY
 FOREIGN KEY (PURCHASING_DEALER) 
 REFERENCES ORGANIZATION (ID))
/
ALTER TABLE EXTENDED_WARRANTY_NOTIFICATION ADD (
  CONSTRAINT FK_FOR_UNIT_EXTN_WNTY
 FOREIGN KEY (FOR_UNIT) 
 REFERENCES INVENTORY_ITEM (ID))
/
ALTER TABLE EXTENDED_WARRANTY_NOTIFICATION ADD (
  CONSTRAINT FK_POLICY_EXTN_WNTY
 FOREIGN KEY (POLICY) 
 REFERENCES POLICY_DEFINITION (ID))
/
ALTER TABLE EXTENDED_WARRANTY_NOTIFICATION ADD (
  CONSTRAINT FK_BU_EXTN_WNTY
 FOREIGN KEY (BUSINESS_UNIT_INFO) 
 REFERENCES BUSINESS_UNIT (NAME))
/
ALTER TABLE EXTENDED_WARRANTY_NOTIFICATION ADD (
  CONSTRAINT FK_LST_UPDT_BY_EXTN_WNTY
 FOREIGN KEY (D_LAST_UPDATED_BY) 
 REFERENCES ORG_USER (ID))
/
CREATE SEQUENCE EXTENDED_WNTY_NOTIFICATION_SEQ
MINVALUE 1000
MAXVALUE 99999999999999999999999 
INCREMENT BY 20 
START WITH 1000
CACHE 20 
NOORDER  
NOCYCLE
/
CREATE INDEX EXT_WNTY_NOTIFY_FORUNIT_IDX ON extended_warranty_notification(FOR_UNIT)
/
COMMIT
/