--Purpose    : Inclusion of Purposes Warranty Coverage,Extended Coverage and Standard Coverage, changes made as a part of 4.3 upgrade 
--Author     : Lavin Hawes
--Created On : 07-Jan-10

INSERT INTO PURPOSE 
(ID, NAME, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_CREATED_TIME, D_UPDATED_TIME, BUSINESS_UNIT_INFO, D_ACTIVE) 
VALUES (PURPOSE_SEQ.nextval, 'Warranty Coverage', '1', SYSDATE, '4.3 Upgrade', SYSDATE, SYSDATE, SYSDATE, 'Transport Solutions ESA', '1')
/
INSERT INTO PURPOSE 
(ID, NAME, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_CREATED_TIME, D_UPDATED_TIME, BUSINESS_UNIT_INFO, D_ACTIVE) 
VALUES (PURPOSE_SEQ.nextval, 'Warranty Coverage', '1', SYSDATE, '4.3 Upgrade', SYSDATE, SYSDATE, SYSDATE, 'Hussmann', '1')
/
INSERT INTO PURPOSE 
(ID, NAME, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_CREATED_TIME, D_UPDATED_TIME, BUSINESS_UNIT_INFO, D_ACTIVE) 
VALUES (PURPOSE_SEQ.nextval, 'Warranty Coverage', '1', SYSDATE, '4.3 Upgrade', SYSDATE, SYSDATE, SYSDATE, 'TFM', '1')
/
INSERT INTO PURPOSE 
(ID, NAME, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_CREATED_TIME, D_UPDATED_TIME, BUSINESS_UNIT_INFO, D_ACTIVE) 
VALUES (PURPOSE_SEQ.nextval, 'Warranty Coverage', '1', SYSDATE, '4.3 Upgrade', SYSDATE, SYSDATE, SYSDATE, 'AIR', '1')
/
INSERT INTO PURPOSE 
(ID, NAME, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_CREATED_TIME, D_UPDATED_TIME, BUSINESS_UNIT_INFO, D_ACTIVE) 
VALUES (PURPOSE_SEQ.nextval, 'Warranty Coverage', '1', SYSDATE, '4.3 Upgrade', SYSDATE, SYSDATE, SYSDATE, 'Clubcar ESA', '1')
/
INSERT INTO PURPOSE 
(ID, NAME, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_CREATED_TIME, D_UPDATED_TIME, BUSINESS_UNIT_INFO, D_ACTIVE) 
VALUES (PURPOSE_SEQ.nextval, 'Standard Coverage', '1', SYSDATE, '4.3 Upgrade', SYSDATE, SYSDATE, SYSDATE, 'Transport Solutions ESA', '1')
/
INSERT INTO PURPOSE 
(ID, NAME, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_CREATED_TIME, D_UPDATED_TIME, BUSINESS_UNIT_INFO, D_ACTIVE) 
VALUES (PURPOSE_SEQ.nextval, 'Standard Coverage', '1', SYSDATE, '4.3 Upgrade', SYSDATE, SYSDATE, SYSDATE, 'Hussmann', '1')
/
INSERT INTO PURPOSE 
(ID, NAME, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_CREATED_TIME, D_UPDATED_TIME, BUSINESS_UNIT_INFO, D_ACTIVE) 
VALUES (PURPOSE_SEQ.nextval, 'Standard Coverage', '1', SYSDATE, '4.3 Upgrade', SYSDATE, SYSDATE, SYSDATE, 'TFM', '1')
/
INSERT INTO PURPOSE 
(ID, NAME, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_CREATED_TIME, D_UPDATED_TIME, BUSINESS_UNIT_INFO, D_ACTIVE) 
VALUES (PURPOSE_SEQ.nextval, 'Standard Coverage', '1', SYSDATE, '4.3 Upgrade', SYSDATE, SYSDATE, SYSDATE, 'AIR', '1')
/
INSERT INTO PURPOSE 
(ID, NAME, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_CREATED_TIME, D_UPDATED_TIME, BUSINESS_UNIT_INFO, D_ACTIVE) 
VALUES (PURPOSE_SEQ.nextval, 'Standard Coverage', '1', SYSDATE, '4.3 Upgrade', SYSDATE, SYSDATE, SYSDATE, 'Clubcar ESA', '1')
/
INSERT INTO PURPOSE 
(ID, NAME, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_CREATED_TIME, D_UPDATED_TIME, BUSINESS_UNIT_INFO, D_ACTIVE) 
VALUES (PURPOSE_SEQ.nextval, 'Extended Coverage', '1', SYSDATE, '4.3 Upgrade', SYSDATE, SYSDATE, SYSDATE, 'Transport Solutions ESA', '1')
/
INSERT INTO PURPOSE 
(ID, NAME, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_CREATED_TIME, D_UPDATED_TIME, BUSINESS_UNIT_INFO, D_ACTIVE) 
VALUES (PURPOSE_SEQ.nextval, 'Extended Coverage', '1', SYSDATE, '4.3 Upgrade', SYSDATE, SYSDATE, SYSDATE, 'Hussmann', '1')
/
INSERT INTO PURPOSE 
(ID, NAME, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_CREATED_TIME, D_UPDATED_TIME, BUSINESS_UNIT_INFO, D_ACTIVE) 
VALUES (PURPOSE_SEQ.nextval, 'Extended Coverage', '1', SYSDATE, '4.3 Upgrade', SYSDATE, SYSDATE, SYSDATE, 'TFM', '1')
/
INSERT INTO PURPOSE 
(ID, NAME, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_CREATED_TIME, D_UPDATED_TIME, BUSINESS_UNIT_INFO, D_ACTIVE) 
VALUES (PURPOSE_SEQ.nextval, 'Extended Coverage', '1', SYSDATE, '4.3 Upgrade', SYSDATE, SYSDATE, SYSDATE, 'AIR', '1')
/
INSERT INTO PURPOSE 
(ID, NAME, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_CREATED_TIME, D_UPDATED_TIME, BUSINESS_UNIT_INFO, D_ACTIVE) 
VALUES (PURPOSE_SEQ.nextval, 'Extended Coverage', '1', SYSDATE, '4.3 Upgrade', SYSDATE, SYSDATE, SYSDATE, 'Clubcar ESA', '1')
/
COMMIT
/