--Purpose    : New fields added in RecoverablePart.java for FD14 UC09, changes made as a part of 4.3 upgrade 
--Created On : 11-Oct-2010
--Created By : Kuldeep Patil
--Impact     : None

--ALTER TABLE RECOVERABLE_PART ADD (SUPPLIER_RETURN_NEEDED NUMBER(1,0))
--/
--UPDATE RECOVERABLE_PART A SET A.SUPPLIER_RETURN_NEEDED = (SELECT B.SUPPLIER_RETURN_NEEDED FROM OEM_PART_REPLACED B WHERE B.ID = A.OEM_PART)
--/
--UPDATE RECOVERABLE_PART A SET A.SUPPLIER_RETURN_NEEDED = 0 WHERE A.SUPPLIER_RETURN_NEEDED IS NULL
--/
--ALTER TABLE RECOVERABLE_PART ADD(SUPPLIER_ITEM NUMBER(19,0))
--/
ALTER TABLE RECOVERABLE_PART ADD (
	CONSTRAINT FK_RECOVERABLE_PART_ITEM
	FOREIGN KEY (SUPPLIER_ITEM) 
	REFERENCES ITEM(ID)
)
/
--CREATE TABLE REC_PARTS_SUP_PART_RETURNS
--(
--RECOVERABLE_PART NUMBER(19,0),
--SUPPLIER_PART_RETURN NUMBER(19,0)
--)
--/
--ALTER TABLE REC_PARTS_SUP_PART_RETURNS ADD (
--	CONSTRAINT FK_R_P_SUP_PART_RETURNS
--	FOREIGN KEY (RECOVERABLE_PART) 
--	REFERENCES RECOVERABLE_PART(ID)
--)
--/
--ALTER TABLE REC_PARTS_SUP_PART_RETURNS ADD (
--	CONSTRAINT FK_S_P_SUP_PART_RETURNS
--	FOREIGN KEY (SUPPLIER_PART_RETURN) 
--	REFERENCES SUPPLIER_PART_RETURN(ID)
--)
--
--/
COMMIT
/