--Purpose    : Changes Made for Inventory Item Composition , Inventory item and Serialized Item Replacement for Inventory Item Composition Registration as a part of 4.3 upgrade 
--Created On : 11-Oct-2010
--Created By : Kuldeep Patil
--Impact     : None

CREATE TABLE INVENTORY_ITEM_COMP_BACKUP
AS
(
	SELECT ID, BASED_ON
	FROM INVENTORY_ITEM_COMPOSITION
)
/
CREATE TABLE SZED_ITEM_REPLACEMENT_BACKUP
AS
(
	SELECT ID, FOR_COMPOSITION,	NEW_PART
	FROM SERIALIZED_ITEM_REPLACEMENT
)
/
ALTER TABLE INVENTORY_ITEM_COMPOSITION DROP COLUMN BASED_ON
/
ALTER TABLE INVENTORY_ITEM_COMPOSITION ADD SOURCE_OF_PART VARCHAR2(255)
/
ALTER TABLE INVENTORY_ITEM ADD INSTALLATION_DATE DATE
/
ALTER TABLE INVENTORY_ITEM ADD SERIALIZED_PART NUMBER(1,0) DEFAULT 0
/
ALTER TABLE SERIALIZED_ITEM_REPLACEMENT ADD OLD_SERIAL_NUMBER VARCHAR2(255)
/
ALTER TABLE SERIALIZED_ITEM_REPLACEMENT DROP COLUMN FOR_COMPOSITION
/
ALTER TABLE SERIALIZED_ITEM_REPLACEMENT DROP COLUMN NEW_PART
/
COMMIT
/

