--Purpose    : Script for creating Requests for extension staging table changes made as a part of 4.3 upgrade 
--Created On : 11-Oct-2010
--Created By : Kuldeep Patil
--Impact     : None

create table STG_REQUESTS_FOR_EXTENSION(
	ID NUMBER(19,0) PRIMARY KEY,
	FILE_UPLOAD_MGT_ID NUMBER(19,0),
	DEALER_NUMBER VARCHAR2(255),
	SERIAL_NUMBER VARCHAR2(255),
	DELIVERY_DATE VARCHAR2(255),
	POLICY_CODE VARCHAR2(255),
	POLICY_END_DATE VARCHAR2(255),
	MONTHS_COVERED_BY_POLICY NUMBER,
	GOODWILL_POLICY_CODE VARCHAR2(255),
	GOODWILL_POLICY_END_DATE VARCHAR2(255),
	HOURS_COVERED NUMBER,
	COMMENTS VARCHAR2(4000),
	ERROR_STATUS	VARCHAR2(255),
	ERROR_CODE	VARCHAR2(255),
	UPLOAD_STATUS	VARCHAR2(255),
	UPLOAD_ERROR	VARCHAR2(255),
	UPLOAD_DATE	VARCHAR2(20),
	ITEM_NUMBER VARCHAR2(255),
	BUSINESS_UNIT_INFO VARCHAR2(255),
	ACTION_PERFORMED VARCHAR2(255)
)
/
COMMIT
/