--Purpose    : FK added for OEM, changes done as per 4.3 upgrade
--AUTHOR     : Kuldeep Patil
--CREATED ON : 11-Oct-2010

UPDATE WARRANTY SET OEM = null
/
ALTER TABLE INVENTORY_ITEM ADD (
 CONSTRAINT INVENTORY_ITEM_OEM_FK 
 FOREIGN KEY (OEM)
 REFERENCES LIST_OF_VALUES(ID)
)
/
ALTER TABLE WARRANTY ADD (
 CONSTRAINT WARRANTY_OEM_FK
 FOREIGN KEY (OEM)
 REFERENCES LIST_OF_VALUES(ID)
)
/
COMMIT
/