--Purpose    : Creating table for dealer group and user group for service allowance,changes made as a part of 4.3 upgrade
--Author     : Saya Sudha
--Created On : 13-Jan-10

CREATE TABLE DCAP_DLRGRP_RDUSERGRP
(
 DEALER_GROUP NUMBER(19), 
 USER_CLUSTER NUMBER(19)
)
/
COMMIT
/
ALTER TABLE DCAP_DLRGRP_RDUSERGRP ADD (
	CONSTRAINT DLRGRPRDUSERGRP_DEALERGROUP_FK
	FOREIGN KEY (DEALER_GROUP)
	REFERENCES DEALER_GROUP(ID)
)
/
ALTER TABLE DCAP_DLRGRP_RDUSERGRP ADD (
	CONSTRAINT DLRGRPRDUSERGRP_USERCLUSTER_FK
	FOREIGN KEY (USER_CLUSTER)
	REFERENCES USER_CLUSTER(ID)
)
/
COMMIT
/
