ALTER TABLE MODIFIERS RENAME COLUMN "LINE_ITEM_GROUP_AUDIT" TO "LINE_ITEM_GROUP"
/
ALTER TABLE MODIFIERS DROP CONSTRAINT "MODIFIERS_LINE_ITEM_AUDIT_FK"
/

ALTER TABLE MODIFIERS ADD CONSTRAINT MODIFIERS_LINE_ITEM_GROUP_FK FOREIGN KEY 
("LINE_ITEM_GROUP") REFERENCES LINE_ITEM_GROUP ("ID") 
/

CREATE TABLE ADDITIONAL_PAYMENT_INFO
(
  ID NUMBER(19, 0) NOT NULL,
  TYPE VARCHAR2(255 CHAR),
  ADDITIONAL_AMT NUMBER(19, 2),
  ADDITIONAL_CURR VARCHAR2(255 CHAR),
  PERCENTAGE_ACCEPTANCE NUMBER(19, 2)
, CONSTRAINT ADDITIONAL_PAYMENT_INFO_PK PRIMARY KEY
  (
    ID
  )
)
/

CREATE SEQUENCE ADDITIONAL_PAYMENT_INFO_SEQ INCREMENT BY 20 START WITH 1000
/

CREATE TABLE ADD_PAYMENT_INFO
(
  ADDITIONAL_PAYMENT_INFO NUMBER(19, 0),
  LINE_ITEM_GROUP NUMBER(19, 0)
)
/

ALTER TABLE ADD_PAYMENT_INFO ADD CONSTRAINT ADD_PYM_INFO_LINE_ITEM_GRP_FK FOREIGN KEY 
(
"LINE_ITEM_GROUP"
) REFERENCES LINE_ITEM_GROUP 
(
"ID"
) 
/
ALTER TABLE ADD_PAYMENT_INFO 
ADD CONSTRAINT ADDITIONAL_PAYMENT_INFO_FK FOREIGN KEY 
(
"ADDITIONAL_PAYMENT_INFO"
) REFERENCES ADDITIONAL_PAYMENT_INFO 
(
"ID"
) 
/

ALTER TABLE LINE_ITEM_GROUP 
ADD ("BASE_AMT" NUMBER(19, 2))
/

ALTER TABLE LINE_ITEM_GROUP 
ADD ("BASE_CURR" VARCHAR2(255 CHAR))
/

ALTER TABLE LINE_ITEM_GROUP 
ADD ("GROUPTOTAL_AMT" NUMBER(19, 2))
/

ALTER TABLE LINE_ITEM_GROUP 
ADD ("GROUPTOTAL_CURR" VARCHAR2(255 CHAR))
/

ALTER TABLE LINE_ITEM_GROUP 
ADD ("TOTAL_CREDIT_AMT" NUMBER(19, 2))
/

ALTER TABLE LINE_ITEM_GROUP 
ADD ("TOTAL_CREDIT_CURR" VARCHAR2(255 CHAR))
/

ALTER TABLE LINE_ITEM_GROUP 
ADD ("RATE" NUMBER(19, 2))
/

ALTER TABLE LINE_ITEM_GROUP 
ADD ("RATE_CURR" VARCHAR2(255 CHAR))
/

ALTER TABLE LINE_ITM_GRP_AUDIT_SLT_DTL 
RENAME COLUMN "LINE_ITM_GRP_AUDIT" TO "LINE_ITEM_GROUP"
/

ALTER TABLE LINE_ITM_GRP_AUDIT_SLT_DTL 
RENAME COLUMN "SPLIT_DTL_AUDIT" TO "LABOR_SPLIT_DETAIL_AUDIT"
/

ALTER TABLE LINE_ITM_GRP_AUDIT_SLT_DTL 
DROP CONSTRAINT "GRP_AUDIT_SLT_DTL_FK"
/

Create Table Temp_Labor_Split_Details as (
Select * From LINE_ITM_GRP_AUDIT_SLT_DTL
)
/

COMMIT
/

UPDATE LINE_ITM_GRP_AUDIT_SLT_DTL
SET LINE_ITEM_GROUP = null
/
ALTER TABLE LINE_ITM_GRP_AUDIT_SLT_DTL 
ADD CONSTRAINT LABOR_SPLIT_LINE_ITEM_GROUP_FK FOREIGN KEY 
(
"LINE_ITEM_GROUP"
) REFERENCES LINE_ITEM_GROUP 
(
"ID"
) 
/

ALTER TABLE LINE_ITM_GRP_AUDIT_SLT_DTL RENAME TO LABOR_SPLIT_DETAILS
/

Declare
Cursor C Is
Select B.For_Line_Item_Grp, A.LABOR_SPLIT_DETAIL_AUDIT 
From Temp_Labor_Split_Details A, Line_Item_Group_Audit B
where a.line_item_group = b.id;
v_error varchar2(4000) :='';
Begin
For Rec In C Loop
begin
Update Labor_Split_Details
Set Line_Item_Group = Rec.for_line_item_grp
Where Labor_Split_Detail_Audit = Rec.LABOR_SPLIT_DETAIL_AUDIT;
Exception when Others Then
V_Error := V_Error || '|' || Rec.LABOR_SPLIT_DETAIL_AUDIT;
end;
End Loop;
commit;
dbms_output.put_line(v_error);
end;
/

ALTER TABLE CLAIM_AUDIT 
ADD ("PAYMENT" NUMBER(19, 0))
/

ALTER TABLE CLAIM_AUDIT 
ADD CONSTRAINT CLAIM_AUDIT_PAYMENT_FK1 FOREIGN KEY 
(
"PAYMENT"
) REFERENCES PAYMENT 
(
"ID"
)
/