ALTER TABLE INVENTORY_ITEM_COMPOSITION DROP COLUMN BASED_ON
/
ALTER TABLE INVENTORY_ITEM_COMPOSITION ADD SOURCE_OF_PART VARCHAR2(255)
/
ALTER TABLE INVENTORY_ITEM ADD INSTALLATION_DATE DATE
/
ALTER TABLE INVENTORY_ITEM ADD SERIALIZED_PART NUMBER(1,0) DEFAULT 0
/
ALTER TABLE SERIALIZED_ITEM_REPLACEMENT ADD OLD_SERIAL_NUMBER VARCHAR2(255)
/
ALTER TABLE SERIALIZED_ITEM_REPLACEMENT DROP COLUMN FOR_COMPOSITION
/
ALTER TABLE SERIALIZED_ITEM_REPLACEMENT DROP COLUMN NEW_PART
/
