ALTER TABLE INVENTORY_ITEM ADD (
 CONSTRAINT INVENTORY_ITEM_OEM_FK 
 FOREIGN KEY (OEM)
 REFERENCES LIST_OF_VALUES(ID)
)
/
ALTER TABLE WARRANTY ADD (
 CONSTRAINT WARRANTY_OEM_FK
 FOREIGN KEY (OEM)
 REFERENCES LIST_OF_VALUES(ID)
)
/
