--Purpose    : Changes Made to include Dealer and Dealer Groups  to a Policy
--Author     : Lavin Hawes
--Created On : 18-Dec-09


CREATE TABLE POLICY_FOR_PROVIDERS
(
POLICY_DEFN NUMBER(19), 
FOR_SERVICE_PROVIDER NUMBER(19)
)
/
COMMIT
/
ALTER TABLE POLICY_FOR_PROVIDERS ADD (
	CONSTRAINT FK_POLICY_DEFNIT
	FOREIGN KEY (POLICY_DEFN)
	REFERENCES POLICY_DEFINITION (ID)
)
/
COMMIT
/
ALTER TABLE POLICY_FOR_PROVIDERS ADD (
	CONSTRAINT FK_SERVICE_PROVIDER
	FOREIGN KEY (FOR_SERVICE_PROVIDER)
	REFERENCES SERVICE_PROVIDER (ID)
)
/
COMMIT
/
CREATE TABLE POLICY_FOR_DEALER_GROUPS
(
POLICY_DEFN NUMBER(19), 
FOR_DEALER_GROUPS NUMBER(19)
)
/
COMMIT
/
ALTER TABLE POLICY_FOR_DEALER_GROUPS ADD (
	CONSTRAINT FK_POLICY_DEFN_DEALER_GROUP
	FOREIGN KEY (POLICY_DEFN)
	REFERENCES POLICY_DEFINITION (ID)
)
/
COMMIT
/
ALTER TABLE POLICY_FOR_DEALER_GROUPS ADD (
	CONSTRAINT FK_DEALER_GROUP
	FOREIGN KEY (FOR_DEALER_GROUPS)
	REFERENCES DEALER_GROUP (ID)
)
/
COMMIT
/