--Purpose    : Create tables for fault code - part class association, and for inclusive job codes
--Author     : Rashmi Malik
--Created On : 25-Jan-10

CREATE TABLE FAULT_CODE_PART_CLASS_ASSOC 
	(FAULT_CODE_DEFINITION NUMBER(19,0) NOT NULL, 
	ITM_CR_ITEM NUMBER(19,0), 
	ITM_CR_ITEM_GRP NUMBER(19,0), 
	ITM_CR_ITEM_IDNTFR VARCHAR2(255 CHAR), 
	ITEM_CRITERION_INDEX NUMBER(10,0) NOT NULL, 
	PRIMARY KEY (FAULT_CODE_DEFINITION, ITEM_CRITERION_INDEX)
	)
/
ALTER TABLE FAULT_CODE_PART_CLASS_ASSOC 
	ADD CONSTRAINT FAULT_CODE_PRT_CLS_ITEM_GRP_FK 
	FOREIGN KEY (ITM_CR_ITEM_GRP) 
	REFERENCES ITEM_GROUP
/
ALTER TABLE FAULT_CODE_PART_CLASS_ASSOC 
	ADD CONSTRAINT FAULT_CODE_PRT_CLS_DEF_FK 
	FOREIGN KEY (FAULT_CODE_DEFINITION) 
	REFERENCES FAULT_CODE_DEFINITION
/
ALTER TABLE FAULT_CODE_PART_CLASS_ASSOC 
	ADD CONSTRAINT FAULT_CODE_PRT_CLS_ITEM_FK  
	FOREIGN KEY (ITM_CR_ITEM) 
	REFERENCES ITEM
/
CREATE TABLE INCLUSIVE_JOB_CODES 
	(PARENT_JOB NUMBER(19,0) NOT NULL, 
	CHILD_JOB NUMBER(19,0) NOT NULL)
/
ALTER TABLE INCLUSIVE_JOB_CODES 
	ADD CONSTRAINT INCL_JOB_CODES_CHILD_FK 
	FOREIGN KEY (CHILD_JOB) 
	REFERENCES SERVICE_PROCEDURE_DEFINITION
/
ALTER TABLE INCLUSIVE_JOB_CODES 
	ADD CONSTRAINT INCL_JOB_CODES_PARENT_FK
	FOREIGN KEY (PARENT_JOB) 
	REFERENCES SERVICE_PROCEDURE_DEFINITION
/
COMMIT
/

