--Purpose    : Need list_index on domain rule audit to get audits in correct order
--Created On : 24-June-2010
--Created By : Ramalakshmi P
--Impact     : Rules throughout the application


ALTER TABLE DOMAIN_RULE_AUDIT ADD (LIST_INDEX NUMBER(10))
/
DECLARE
CURSOR ALL_RULE_ID IS
SELECT ID FROM DOMAIN_RULE;

V_DRA_LIST_INDEX NUMBER(10);

CURSOR DOMAIN_RULE_AUDIT_FOR_RULE(RULE_ID NUMBER) IS
    SELECT DRA.ID
    FROM DOMAIN_RULE_AUDIT DRA
    WHERE DRA.DOMAIN_RULE = RULE_ID
    ORDER BY DRA.ID;

BEGIN
 FOR EACH_REC IN ALL_RULE_ID LOOP
      V_DRA_LIST_INDEX := 0;
	    FOR EACH_RULE_AUDIT_ID IN DOMAIN_RULE_AUDIT_FOR_RULE(EACH_REC.ID) LOOP
		  UPDATE DOMAIN_RULE_AUDIT SET LIST_INDEX = V_DRA_LIST_INDEX
		  WHERE ID = EACH_RULE_AUDIT_ID.ID;
		  V_DRA_LIST_INDEX := V_DRA_LIST_INDEX + 1;
	    END LOOP; 	 
 END LOOP;	 
END;   
/
COMMIT
/
ALTER TABLE DOMAIN_RULE_AUDIT MODIFY (LIST_INDEX NOT NULL)
/
