CREATE TABLE LOA_AMOUNT
	(LOA_LEVEL NUMBER(10,0) NOT NULL, 
	AMOUNT	NUMBER(19,2),
  CURRENCY	VARCHAR2(255 CHAR))
/
ALTER TABLE LOA_AMOUNT 
	ADD CONSTRAINT LOA_AMOUNT_LEVEL_FK 
	FOREIGN KEY (LOA_LEVEL) 
	REFERENCES "LIMIT_OF_AUTHORITY_LEVEL" ("ID")
/
COMMIT
/
  
  
