--Purpose    : Perf fix for claim search
--Created On : 31-May-2010
--Created By : Rahul Katariya
--Impact     : Claim Search


CREATE INDEX OEM_PART_REPLACED_ORP_I1 ON OEM_PART_REPLACED (OEM_REPLACED_PARTS)
/
CREATE INDEX HUSS_PRI_SERVICE_DET_I1 ON HUSS_PARTS_REPLACED_INSTALLED (SERVICE_DETAIL)
/
CREATE INDEX INST_PRT_OEM_PRT_INST_I1 ON INSTALLED_PARTS (OEM_PARTS_INSTALLED)
/
COMMIT
/