--Author     : Amritha 
--Created On : 21-4-2010

CREATE TABLE STG_SUPPLIER_DECISION
  (
     ID   NUMBER NOT NULL PRIMARY KEY,
     FILE_UPLOAD_MGT_ID NUMBER,
     RECOVERY_CLAIM_NUMBER  VARCHAR2(255 BYTE),
     DECISION     VARCHAR2(255 BYTE),
     DECISION_REASON     VARCHAR2(255 BYTE),
     DECISION_COMMENTS    VARCHAR2(255 BYTE),
     ERROR_CODE VARCHAR2(255  BYTE),
     ERROR_STATUS VARCHAR2(255  BYTE),
     UPLOAD_STATUS VARCHAR2(255  BYTE),
     UPLOAD_ERROR VARCHAR2(255  BYTE)
     )
/


