--PURPOSE    : Patch to add a new column  Latest_Warranty in inventory_item table.
ALTER TABLE INVENTORY_ITEM ADD  LATEST_WARRANTY number(19,0) NULL
/
ALTER TABLE INVENTORY_ITEM ADD CONSTRAINT LATEST_WARRANTY_II FOREIGN KEY (LATEST_WARRANTY) REFERENCES WARRANTY (ID) ENABLE
/