--PURPOSE    : PATCH FOR ADDING COLUMN IN CAMPAIGN_NOTIFICATION TABLE FOR ENTRY VALIDATION RULES OF CAMPAIGNS
--AUTHOR     : RAVIKUMAR.Y
--CREATED ON : 01-AUG-12

ALTER TABLE CAMPAIGN_NOTIFICATION ADD (FIELD_MOD_INV_STATUS NUMBER(19,0))
/
ALTER TABLE CAMPAIGN_NOTIFICATION ADD CONSTRAINT CAMP_FieldMODINVSTATUS_FK FOREIGN KEY (FIELD_MOD_INV_STATUS) REFERENCES LIST_OF_VALUES (ID) ENABLE
/