-- Patch for Claim and Claim audit clean up
-- Author Tanveer Chowdary
-- Date August 13, 2012

ALTER TABLE CLAIM_AUDIT ADD (
"WORK_ORDER_NUMBER"           VARCHAR2(255 CHAR),
"FAILURE_DATE" DATE,
"REPAIR_DATE" DATE,
"INSTALLATION_DATE" DATE,
"PURCHASE_DATE" DATE,
"STATE"                          VARCHAR2(255 CHAR),
"SERVICE_INFORMATION"            NUMBER(19,0),
"PROBABLE_CAUSE"            VARCHAR2(4000 CHAR),
"WORK_PERFORMED"            VARCHAR2(4000 CHAR),
"OTHER_COMMENTS"            VARCHAR2(4000 CHAR),
"CONDITION_FOUND"           VARCHAR2(4000 CHAR),
"INTERNAL_COMMENT"          VARCHAR2(4000 BYTE),
"EXTERNAL_COMMENT"          VARCHAR2(4000 BYTE),
"SERVICE_MANAGER_ACCEPTED"       NUMBER(1,0),
"ACCEPTANCE_REASON"              NUMBER(19,0),    
"ACCEPTANCE_REASON_FOR_CP"       NUMBER(19,0),
"REJECTION_REASON"               NUMBER(19,0),
"ACCOUNTABILITY_CODE"            NUMBER(19,0),
"TRAVEL_HRS_CONFIG"              NUMBER(1,0),
"TRAVEL_TRIP_CONFIG"             NUMBER(1,0),
"TRAVEL_DIS_CONFIG"              NUMBER(1,0),
"OEM_CONFIG"                     NUMBER(1,0),
"NON_OEM_CONFIG"                 NUMBER(1,0),
"MISC_PARTS_CONFIG"              NUMBER(1,0),
"MEALS_CONFIG"                   NUMBER(1,0),
"PARKING_CONFIG"                 NUMBER(1,0),
"ITEM_DUTY_CONFIG"               NUMBER(1,0),
"LABOR_CONFIG"                   NUMBER(1,0),
"CP_REVIEWED"                    NUMBER(1,0),
"PER_DIEM_CONFIG"                NUMBER(1,0),
"RENTAL_CHARGES_CONFIG"          NUMBER(1,0),
"ADDITIONAL_TRAVEL_HOURS_CONFIG" NUMBER(1,0),
"LOCAL_PURCHASE_CONFIG"          NUMBER(1,0),
"TOLLS_CONFIG"                   NUMBER(1,0),
"OTHER_FREIGHT_DUTY_CONFIG"      NUMBER(1,0),
 "OTHERS_CONFIG"                 NUMBER(1,0),
 "INVOICE_NUMBER"                VARCHAR2(50 BYTE),
 "SELLING_ENTITY"                NUMBER(19,0),
 "OWNER_INFORMATION"             NUMBER,
 "CLAIM_PROCESSED_AS"            VARCHAR2(255 BYTE),
 "ASSIGN_TO_USER"                NUMBER(19,0),

CONSTRAINT "CLAIMAUD_SERVICEINFO_FK" FOREIGN KEY ("SERVICE_INFORMATION") REFERENCES "SERVICE_INFORMATION" ("ID"),
CONSTRAINT "CLAIMAUD_ACCEPTANCEREASON_FK" FOREIGN KEY ("ACCEPTANCE_REASON") REFERENCES "LIST_OF_VALUES" ("ID") ,
CONSTRAINT "CLAIMAUD_ACCREASONFORCP_FK" FOREIGN KEY ("ACCEPTANCE_REASON_FOR_CP") REFERENCES "LIST_OF_VALUES" ("ID") ,
CONSTRAINT "CLAIMAUD_REJECTIONREASON_FK" FOREIGN KEY ("REJECTION_REASON") REFERENCES "LIST_OF_VALUES" ("ID") ,
CONSTRAINT "CLAIMAUD_ACCOUNTCODE_FK" FOREIGN KEY ("ACCOUNTABILITY_CODE") REFERENCES "LIST_OF_VALUES" ("ID") ,
CONSTRAINT "CLAIMAUD_SELL_ENTITY_FK" FOREIGN KEY ("SELLING_ENTITY") REFERENCES "LIST_OF_VALUES" ("ID") ,
CONSTRAINT "CLAIMAUD_OWNER_INFO_FK" FOREIGN KEY ("OWNER_INFORMATION") REFERENCES "ADDRESS" ("ID") ,
CONSTRAINT "CLAIMAUD_ASSIGNTOUSER_FK" FOREIGN KEY ("ASSIGN_TO_USER") REFERENCES "ORG_USER" ("ID") )
/
CREATE TABLE CLAIM_AUDIT_RULE_FAILURES
  (
    "CLAIM_AUDIT"         NUMBER(19,0) NOT NULL ENABLE,
    "RULE_FAILURES" NUMBER(19,0) NOT NULL ENABLE,
    CONSTRAINT "CLAIM_AUD_RULE_FAIL_PK" PRIMARY KEY ("CLAIM_AUDIT", "RULE_FAILURES") ,
    CONSTRAINT "CLMAUDRULEFAIL_RULEFAIL_FK" FOREIGN KEY ("RULE_FAILURES") REFERENCES "RULE_FAILURE" ("ID") ,
    CONSTRAINT "CLAIMAUDRULEFAIL_CLAIMAUD_FK" FOREIGN KEY ("CLAIM_AUDIT") REFERENCES "CLAIM_AUDIT" ("ID") 
  )
/
CREATE TABLE "CLAIM_AUDIT_ATTACHMENTS"
  (
    "CLAIM_AUDIT"       NUMBER(19,0) NOT NULL ENABLE,
    "ATTACHMENTS" NUMBER(19,0) NOT NULL ENABLE,
    CONSTRAINT "CLAIMAUDATTACH_CLAIMAUD_FK" FOREIGN KEY ("CLAIM_AUDIT") REFERENCES "CLAIM_AUDIT" ("ID") ,
    CONSTRAINT "CLMAUDATTACH_ATTACHMENTS_FK" FOREIGN KEY ("ATTACHMENTS") REFERENCES "DOCUMENT" ("ID")
  )
/
CREATE TABLE "CLAIM_AUDIT_USER_PRO_COMMENTS"
  (
    "CLAIM_AUDIT"                 NUMBER(19,0) NOT NULL ENABLE,
    "USER_PROCESS_COMMENTS" NUMBER(19,0) NOT NULL ENABLE,
    CONSTRAINT "CLMAUD_USRPROCMTS_PK" PRIMARY KEY ("CLAIM_AUDIT", "USER_PROCESS_COMMENTS"),
    CONSTRAINT "CLMAUD_USRPROCMTS_CLM_FK" FOREIGN KEY ("CLAIM_AUDIT") REFERENCES "CLAIM_AUDIT" ("ID") ENABLE,
    CONSTRAINT "CLMAUD_USRPROCMTS_USRPCMTS_FK" FOREIGN KEY ("USER_PROCESS_COMMENTS") REFERENCES "USER_COMMENT" ("ID") ENABLE
  )
/
ALTER TABLE CLAIM ADD(
"ACTIVE_CLAIM_AUDIT"            NUMBER(19,0),
CONSTRAINT "ACTCLMAUD_CLMAUD_FK" FOREIGN KEY ("ACTIVE_CLAIM_AUDIT") REFERENCES "CLAIM_AUDIT" ("ID") ENABLE)
/
CREATE TABLE "CLAIM_AUDIT_ALARM_CODES"
  (
    "CLAIM_AUDIT"       NUMBER(19,0) NOT NULL ENABLE,
    "ALARM_CODES" NUMBER(19,0) NOT NULL ENABLE,
    CONSTRAINT "ALARMAUD_CODES_CLAIM_FK" FOREIGN KEY ("CLAIM_AUDIT") REFERENCES "CLAIM_AUDIT" ("ID") ENABLE NOVALIDATE,
    CONSTRAINT "ALARMAUD_CODES_ALARM_CODES_FK" FOREIGN KEY ("ALARM_CODES") REFERENCES "ALARM_CODE" ("ID") ENABLE NOVALIDATE
  )
/
BEGIN
FOR I IN 
(
SELECT a.CONSTRAINT_NAME,
  A.SEARCH_CONDITION
FROM USER_CONSTRAINTS a ,
  USER_CONS_COLUMNS b
WHERE A.TABLE_NAME    = 'CLAIM_AUDIT'
AND B.COLUMN_NAME = 'LIST_INDEX'
AND A.CONSTRAINT_NAME = B.CONSTRAINT_NAME
and a.CONSTRAINT_TYPE = 'C'
)
loop
IF UPPER(i.SEARCH_CONDITION) LIKE '%IS NOT NULL%' THEN
execute immediate 'alter table CLAIM_AUDIT drop constraint ' || i.CONSTRAINT_NAME;
END IF;
END LOOP;
end;
/
alter table claim modify(SERVICE_MANAGER_ACCEPTED null)
/
delete from default_folder_view
/
delete from inbox_view
/
commit
/