--PURPOSE    : Patch for capturing action history for part return configuration, as part of Doosan Heavy TWMS implementation
--AUTHOR     : Kuldeep Patil
--CREATED ON : 03-July-2012

ALTER TABLE PART_RETURN_DEFINITION ADD COMMENTS VARCHAR2(4000)
/
CREATE SEQUENCE PART_RETURN_DEFN_AUDIT_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 START WITH 1 INCREMENT BY 20 NOCACHE NOORDER NOCYCLE
/
CREATE TABLE PART_RETURN_DEFINITION_AUDIT
  (
	ID NUMBER(19) NOT NULL,
	STATUS VARCHAR2(30),
	COMMENTS VARCHAR2(4000),
	FOR_DEFINITION NUMBER(19),
	D_CREATED_ON DATE,
	D_INTERNAL_COMMENTS VARCHAR2(255 CHAR),
	D_UPDATED_ON DATE,
	D_LAST_UPDATED_BY NUMBER(19),
	D_CREATED_TIME TIMESTAMP(6),
	D_UPDATED_TIME TIMESTAMP(6),
	LIST_INDEX NUMBER(10),
	D_ACTIVE NUMBER(1,0) DEFAULT 1
  )
/
ALTER TABLE PART_RETURN_DEFINITION_AUDIT ADD CONSTRAINT PART_RETURN_DEFNITION_AUDIT_PK PRIMARY KEY (ID)
/
ALTER TABLE PART_RETURN_DEFINITION_AUDIT ADD CONSTRAINT PART_RET_DEF_audit_for_defn_FK FOREIGN KEY (FOR_DEFINITION) REFERENCES PART_RETURN_DEFINITION(ID)
/