--PURPOSE    : Patch for capturing dealer or dealer groups to be excluded from part returns, as part of Doosan Heavy TWMS implementation
--AUTHOR     : Kuldeep Patil
--CREATED ON : 11-July-2012

CREATE TABLE PART_RET_DEALER_EXCLUSIONS
  (
    PART_RETURN_DEFINITION NUMBER(19),
    DEALER                 NUMBER(19)
  )
/
ALTER TABLE PART_RET_DEALER_EXCLUSIONS ADD CONSTRAINT PART_RET_DEFN_DLR_EXCLSN_FK FOREIGN KEY (PART_RETURN_DEFINITION) REFERENCES PART_RETURN_DEFINITION(ID)
/
ALTER TABLE PART_RET_DEALER_EXCLUSIONS ADD CONSTRAINT DEALER_FK FOREIGN KEY (DEALER) REFERENCES SERVICE_PROVIDER(ID)
/
CREATE TABLE PART_RET_DEALER_GRP_EXCLUSIONS
  (
    PART_RETURN_DEFINITION NUMBER(19),
    DEALER_GROUP           NUMBER(19)
  )
/
ALTER TABLE PART_RET_DEALER_GRP_EXCLUSIONS ADD CONSTRAINT PART_RET_DEFN_DLR_GRP_FK FOREIGN KEY (PART_RETURN_DEFINITION) REFERENCES PART_RETURN_DEFINITION(ID)
/
ALTER TABLE PART_RET_DEALER_GRP_EXCLUSIONS ADD CONSTRAINT DEALER_GROUP_FK FOREIGN KEY (DEALER_GROUP) REFERENCES DEALER_GROUP(ID)
/