-- Purpose    : Deleting DCAP related tables
-- Author     : RaviKumar.Y
-- Created On : 05-Apr-2012

ALTER TABLE CREDIT_MEMO DROP CONSTRAINT CREDIT_MEMO_DCAP_CLM_FK
/
ALTER TABLE DCAP_CLAIM DROP CONSTRAINT DCAP_CLM_INV_DCAP_FK
/
DROP TABLE DCAP_CLAIM
/
DROP TABLE DCAP_CLAIM_AUDIT
/
DROP TABLE DCAP_DETAIL_HISTORY
/
DROP TABLE INVENTORY_DCAP_DETAIL
/
DROP TABLE MODEL_CATEGORY_SPLIT
/
DROP TABLE PRICE_MATRIX
/
DROP TABLE MODEL_CATEGORY
/
DROP TABLE SPLIT_TYPE
/
DROP TABLE DCAP_DLRGRP_RDUSERGRP
/
ALTER TABLE CREDIT_MEMO DROP COLUMN DCAP_CLAIM
/