--PURPOSE    : PATCH TO UPDATE PART_ID 
--AUTHOR     : GHANASHYAM DAS
--CREATED ON : 27-APR-12

DECLARE
	v_count integer := 0;

  CURSOR VPARTS_REC
  IS
    SELECT J.ID_  AS TASK_INSTANCE_ID,
           V.LONGVALUE_ AS PART_RETURN_ID
    FROM JBPM_TASKINSTANCE J,
         JBPM_MODULEINSTANCE M,
         JBPM_VARIABLEINSTANCE V
    WHERE J.TASKMGMTINSTANCE_ = M.ID_
    AND M.PROCESSINSTANCE_    = V.PROCESSINSTANCE_
    AND V.NAME_    IN  ('partReturn','supplierPartReturn')         
    AND V.LONGVALUE_         IS NOT NULL ;
BEGIN
  FOR EACH_VPARTS_REC IN VPARTS_REC
  LOOP
    BEGIN
      UPDATE JBPM_TASKINSTANCE
      SET PART_RETURN_ID = EACH_VPARTS_REC.PART_RETURN_ID
      WHERE ID_   = EACH_VPARTS_REC.TASK_INSTANCE_ID;
	  IF V_COUNT = 100 THEN
		COMMIT;
		V_COUNT := 0;
	  ELSE
	   V_COUNT :=  V_COUNT + 1;
	  END IF;
	EXCEPTION
	when others then
	NULL;
	--TODO : track erros into separate table.
    END;
	 
  END LOOP;
  COMMIT;
END ;
/