--PURPOSE    : Patch to add a new constraint in WARRANTY Table
--AUTHOR     : Amrita Rout
--CREATED ON : 9-August-2012

ALTER TABLE warranty
DROP CONSTRAINT WARRANTY_CUSTOMER_FK
/
ALTER TABLE warranty ADD(CONSTRAINT "WNTY_CUSTOMER_FK" FOREIGN KEY ("CUSTOMER") REFERENCES PARTY("ID"))
/