--purpose : PATCH FOR deleting  battery test sheet tables.

--Created On: Date 05-04-2012

DROP TABLE BATTERY_VOLTAGE_INFO
/
DROP TABLE CELL_SPECIFIC_GRAVITY
/
DROP TABLE SPECIFIC_GRAVITY_INFO
/
DROP TABLE OEM_PART_REPLACED_BATTERY_INFO
/
DROP TABLE BATTERY_INFO
/
DROP TABLE BATTERY_TEST_SHEET
/
DROP TABLE on_charge_voltage_test
/
DROP TABLE hydrometer_test
/
DROP TABLE FULL_CHARGE_BATTERY_TEST
/
DROP TABLE DISCHARGE_TEST_TEMP_RANGE
/
DROP TABLE DISCHARGE_TEST
/
DROP TABLE DISCHARGE
/