-- Patch for implementing permission based admin authorization framework
-- Author Tanveer Chowdary
-- Date August 7, 2012

Insert into MST_ADMIN_ACTION (ACTION,DESCRIPTION,ID) values ('view','View',1)
/
Insert into MST_ADMIN_ACTION (ACTION,DESCRIPTION,ID) values ('create','Create',2)
/
Insert into MST_ADMIN_ACTION (ACTION,DESCRIPTION,ID) values ('delete','Delete',3)
/
Insert into MST_ADMIN_ACTION (ACTION,DESCRIPTION,ID) values ('update','Update',4)
/
Insert into MST_ADMIN_ACTION (ACTION,DESCRIPTION,ID) values ('search','search',5)
/
INSERT INTO MST_ADMIN_SUBJECT_AREA VALUES (MST_ADMIN_SUBJECT_AREA_SEQ.nextval,'buConfigurations','BU Configurations')
/
INSERT INTO MST_ADMIN_FNC_AREA VALUES (MST_ADMIN_FNC_AREA_SEQ.nextval,'buConfigurationsSetup','BU Configurations Setup')
/
INSERT INTO SUBJECT_FUNC_AREA_MAPPING (FUNCTIONAL_AREA,SUBJECT_AREA) VALUES ((SELECT ID FROM MST_ADMIN_FNC_AREA WHERE NAME='buConfigurationsSetup'),
(SELECT ID FROM MST_ADMIN_SUBJECT_AREA WHERE NAME='buConfigurations'))
/
INSERT INTO ROLE_PERMISSION_MAPPING(ROLE_DEF_ID, ACTION ,FUNCTIONAL_AREA, ID , SUBJECT_AREA) 
VALUES ( (SELECT ID FROM ROLE WHERE NAME ='admin'),(SELECT ID FROM MST_ADMIN_ACTION WHERE action = 'update'), 
(SELECT ID FROM MST_ADMIN_FNC_AREA WHERE NAME='buConfigurationsSetup'), ROLE_PERMISSION_MAPPING_SEQ.NEXTVAL ,
(SELECT ID FROM MST_ADMIN_SUBJECT_AREA WHERE NAME='buConfigurations'))
/
UPDATE ROLE_PERMISSION_MAPPING A
SET A.PERMISSION_STRING =
  (
  SELECT
  (SELECT NAME FROM MST_ADMIN_SUBJECT_AREA WHERE ID = A.SUBJECT_AREA
  )
  || ':'
  ||
  (SELECT NAME FROM mst_admin_fnc_area WHERE ID = A.FUNCTIONAL_AREA
  )
  || ':'
  ||
  (SELECT T.ACTION FROM MST_ADMIN_ACTION T WHERE ID = A.ACTION
  )
  FROM DUAL
  )
/
COMMIT
/