--PURPOSE    : Patch to add a new column in Warranty and inventory_item table.

ALTER TABLE WARRANTY ADD  CUSTOMER_ADDRESS number(19,0) NULL
/
ALTER TABLE WARRANTY ADD CONSTRAINT WARRANTY_ADDRESS FOREIGN KEY (CUSTOMER_ADDRESS) REFERENCES ADDRESS (ID) ENABLE
/
ALTER TABLE inventory_item add ("BILL_TO"  number(19,0))
/
ALTER TABLE inventory_item add (CONSTRAINT "BILL_TO_FK" FOREIGN KEY ("BILL_TO") REFERENCES ORGANIZATION ("ID"))
/