-------------------------------------------------------------------

CREATE TABLE PARTY_ARRAY_TABLE(ID NUMBER, OLD_43_ID NUMBER);

CREATE TABLE ORG_USER_ARRAY_TABLE(ID NUMBER, OLD_43_ID NUMBER);

CREATE TABLE COST_CATEGORY_ARRAY_TABLE(ID NUMBER, OLD_43_ID NUMBER);


INSERT INTO party_array_table@DLKTKPRD31(ID,OLD_43_ID)
SELECT id,old_43_id FROM TG_PARTY;

INSERT INTO org_user_array_table@DLKTKPRD31(ID,OLD_43_ID)
SELECT ID,OLD_43_ID FROM TG_ORG_USER;

INSERT INTO cost_category_array_table@DLKTKPRD31(ID,OLD_43_ID)
SELECT ID,OLD_43_ID FROM TG_COST_CATEGORY;

---indexes

CREATE INDEX PARTY_ARRAY_TABLE_ID ON PARTY_ARRAY_TABLE(ID);
CREATE INDEX PARTY_ARRAY_TABLE_43_ID ON PARTY_ARRAY_TABLE(OLD_43_ID);

CREATE INDEX ORG_USER_ARRAY_TABLE_ID ON ORG_USER_ARRAY_TABLE(ID);
CREATE INDEX ORG_USER_ARRAY_TABLE_43_ID ON ORG_USER_ARRAY_TABLE(OLD_43_ID);

CREATE INDEX COST_CATEGORY_ARRAY_TABLE_ID ON COST_CATEGORY_ARRAY_TABLE(ID);
CREATE INDEX COST_CAT_ARRAY_TABLE_43_ID ON COST_CATEGORY_ARRAY_TABLE(OLD_43_ID);


COMMIT;


------------------------------------------------------------------
--------------Do not use the below queries-----------------------------



-- Create Claim Audit Temperory table

DROP TABLE CLAIM_AUDIT_TEMP;

CREATE TABLE claim_audit_temp as
SELECT a.id,a.prev_claim_snapshot_string as xml_src_data, b.filed_on_date
  	FROM claim_audit a,claim b
	  WHERE b.id = a.for_claim	  	  
    AND b.filed_on_date > TO_DATE('06AUG2009')    
	ORDER BY b.filed_on_date DESC;
	
ALTER TABLE claim_audit_temp ADD (xml_data CLOB , comments VARCHAR2(4000));	

-- Create Array Tables to avoid lookup

CREATE TABLE PARTY_ARRAY_TABLE
AS SELECT ID, OLD_43_ID FROM TG_PARTY;

CREATE INDEX PARTY_ARRAY_TABLE_ID ON PARTY_ARRAY_TABLE(ID);
CREATE INDEX PARTY_ARRAY_TABLE_43_ID ON PARTY_ARRAY_TABLE(OLD_43_ID);

CREATE TABLE ORG_USER_ARRAY_TABLE
AS SELECT ID,OLD_43_ID FROM TG_ORG_USER;

CREATE INDEX ORG_USER_ARRAY_TABLE_ID ON ORG_USER_ARRAY_TABLE(ID);
CREATE INDEX ORG_USER_ARRAY_TABLE_43_ID ON ORG_USER_ARRAY_TABLE(OLD_43_ID);

CREATE TABLE COST_CATEGORY_ARRAY_TABLE
AS SELECT ID,OLD_43_ID FROM TG_COST_CATEGORY;

CREATE INDEX COST_CATEGORY_ARRAY_TABLE_ID ON COST_CATEGORY_ARRAY_TABLE(ID);
CREATE INDEX COST_CAT_ARRAY_TABLE_43_ID ON COST_CATEGORY_ARRAY_TABLE(OLD_43_ID);




---- Table script to be created in 6.0 database------------------------------------

CREATE TABLE claim_audit_temp(ID NUMBER, xml_src_data CLOB, xml_data CLOB, filed_on_date DATE, comments VARCHAR2(4000));

CREATE TABLE PARTY_ARRAY_TABLE(ID NUMBER, OLD_43_ID NUMBER);

CREATE TABLE ORG_USER_ARRAY_TABLE(ID NUMBER, OLD_43_ID NUMBER);

CREATE TABLE COST_CATEGORY_ARRAY_TABLE(ID NUMBER, OLD_43_ID NUMBER);


-- inserts over db links

INSERT INTO claim_audit_temp@DLKTKPRD31(id,xml_src_data,filed_on_date) 
SELECT a.id,a.prev_claim_snapshot_string as xml_src_data, b.filed_on_date
  	FROM claim_audit a,claim b
	  WHERE b.id = a.for_claim	  	  
    AND b.filed_on_date > TO_DATE('06AUG2009')
    AND ROWNUM <= 25000;