--Purpose    :    Parts Upload Email table is credted to  capture the details of the email status of Part Inventory Upload
--Author     :     Anand Vijay Kamalnath. M
--Created On : 17-Nov-08
--Created By : Anand Vijay Kamalnath. M

CREATE SEQUENCE PARTS_UPLOAD_EMAIL_SEQ
START WITH 20
INCREMENT BY 20
MINVALUE 0
MAXVALUE 999999999999999999999999999
CACHE 20
NOCYCLE 
NOORDER
/
COMMIT
/
CREATE TABLE PARTS_UPLOAD_EMAIL
(
  ID                       NUMBER(19),
  USER_FIRST_NAME  VARCHAR2(255 CHAR),
  PARTS_UPLOAD             NUMBER(19),
  ERROR_FILE               BLOB,
  XML_SENT_BY              NUMBER(19),
  USER_EMAIL               VARCHAR2(255 CHAR),
  EMAIL_SENT               NUMBER(1),
  EMAIL_SENT_ON            DATE,
  ERRORS_IN_EMAIL_PROCESS  VARCHAR2(4000 CHAR)
)
/
COMMIT
/
ALTER TABLE PARTS_UPLOAD_EMAIL ADD (
  CONSTRAINT PK_PARTS_UPLOAD_EMAIL
 PRIMARY KEY (ID))
/
ALTER TABLE PARTS_UPLOAD_EMAIL ADD (
  CONSTRAINT FK_P_UPLOAD_EMAIL_PARTS_UPLOAD 
 FOREIGN KEY (PARTS_UPLOAD) 
 REFERENCES PARTS_UPLOAD (ID))
/
COMMIT
/