DECLARE

CURSOR cur_det_table
IS
select distinct B.INDEX_NAME
FROM TAV_GIM_VALID_TABLES A,
  USER_INDEXES B,
  USER_IND_COLUMNS C
WHERE A.TABLE_NAME = B.TABLE_NAME
and B.INDEX_NAME  = C.INDEX_NAME
and a.EXEC_ORDER > 0
and b.status <> 'VALID'
and a.table_name in 
(
'USER_ROLES',
'ROLE',
'PAYMENT',
'CLAIM',
'RECOVERY_INFO',
'ORG_USER_BELONGS_TO_ORGS ',
'ORGANIZATION',
'PARTY ',
'SERVICE_PROVIDER ',
'NATIONAL_ACCOUNT',
'ORIGINAL_EQUIP_MANUFACTURER',
'SUPPLIER ',
'INTER_COMPANY',
'THIRD_PARTY',
'DIRECT_CUSTOMER',
'DEALERSHIP',
'BUSINESS_UNIT',
'BU_USER_MAPPING',
'TECHNICIAN',
'ORG_USER',
'COST_CATEGORY',
'COUNTRY',
'MSA',
'PART_RETURN ',
'BASE_PART_RETURN ',
'LOCATION',
'RECOVERY_CLAIM',
'RECOVERY_CLAIM_INFO',
'REC_CLAIM_INFO_REC_PARTS',
'RECOVERABLE_PART');




BEGIN 



  
	FOR cur_det_table_rec IN cur_det_table	LOOP
		BEGIN		
		EXECUTE IMMEDIATE 'ALTER INDEX ' || CUR_DET_TABLE_REC.INDEX_NAME || ' REBUILD';
		EXCEPTION
		when OTHERS then
		raise;
		end;
	END LOOP;


	
EXCEPTION
when OTHERS then
DBMS_OUTPUT.PUT_LINE('0' || SQLERRM);
END;
/