DECLARE
  P_IN_SCHEMA_NAME VARCHAR2(200);
  P_IN_DBLINK_NAME VARCHAR2(200);
  P_OUT_ERROR_CODE NUMBER;
  P_OUT_ERROR_MESSAGE VARCHAR2(200);
BEGIN
	
  P_IN_SCHEMA_NAME := '&&P_IN_SCHEMA_NAME';
  P_IN_DBLINK_NAME := '&&P_IN_DBLINK_NAME';

  TAV_GIM_INITIAL_SETUP.TAV_GIM_CREATE_SYNONYM(
    P_IN_SCHEMA_NAME => P_IN_SCHEMA_NAME,
    P_IN_DBLINK_NAME => P_IN_DBLINK_NAME,
	P_OUT_ERROR_CODE => P_OUT_ERROR_CODE,
    P_OUT_ERROR_MESSAGE => P_OUT_ERROR_MESSAGE   
  );

END;
/
