/*-----------------------------------------------------------------------------
 * File Name	:	TAV_GIM_INSERT_CYCLIC_REFERENCES.sql
 *
 * Purpose	:	This will populate all cyclic/self referencing table details in the given source database
 *                           
 * Revision History:
 *
 *  Date           Programmer              Description
 *  ------------   ---------------------   ------------------------------------
 *  Jan 15, 2011   Joseph                  Initial Write-Up
 *  Mar 28,2011	   Prabhu R		   Code Organization
 *-----------------------------------------------------------------------------
*/

Prompt Message: Inserting Self/Cyclic References table...

Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('ADDRESS','D_LAST_UPDATED_BY','N');
Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('ADDRESS','BELONGS_TO','N');
Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('PARTY','IS_PART_OF_ORGANIZATION','N');
Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('CLAIM','RECOVERY_INFO','N');
Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('RECOVERY_CLAIM_INFO','RECOVERY_CLAIM','N');
Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('CREDIT_MEMO','DCAP_CLAIM','N');
Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('RECOVERY_PAYMENT','FOR_RECOVERY_CLAIM','N');
Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('PARTY','D_LAST_UPDATED_BY','N');
Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('MARKET','PARENT_ID','S');
Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('USER_CLUSTER','IS_PART_OF','S');
Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('ROLE_GROUP','IS_PART_OF','S');
Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('ORG_USER','SUPERVISOR','S');
Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('ORG_USER','D_LAST_UPDATED_BY','S');
Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('ITEM_GROUP','IS_PART_OF','S');
Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('DEALER_GROUP','IS_PART_OF','S');
Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('ASSEMBLY','IS_PART_OF_ASSEMBLY','S');
--Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('UPLOAD_HISTORY','INPUT_FILE','B');
--Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('UPLOAD_HISTORY','ERROR_FILE','B');
Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('DOCUMENT','CONTENT','B');
--Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('PARTS_UPLOAD','ERROR_FILE','B');
--Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('PARTS_UPLOAD','CONTENT','B');
--Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('PARTS_UPLOAD_EMAIL','ERROR_FILE','B');
--Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('FILE_UPLOAD_MGT','ERROR_FILE_CONTENT','B');
--Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('FILE_UPLOAD_MGT','FILE_CONTENT','B');
--Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('DOCUMENT_DELETED_RECS','CONTENT','B');
Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('CLAIM_AUDIT','PREV_CLAIM_SNAPSHOT_STRING','B');
Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('SYNC_TRACKER','BODXML','B');
Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('SYNC_TRACKER','RECORD','B');
Insert into TAV_GIM_CYCLIC_REF (CYC_REF_TABLE,CYC_REF_COLUMN,IGNORE) values ('SYNC_TRACKER','ERROR_MESSAGE','B');

COMMIT;
/