DECLARE
  P_OUT_ERROR_CODE NUMBER;
  P_OUT_ERROR_MESSAGE VARCHAR2(200);
BEGIN

  TAV_GIM_PROCESS_MIGRATION.TAV_GIM_PROCESS_MASTER(
    P_OUT_ERROR_CODE => P_OUT_ERROR_CODE,
    P_OUT_ERROR_MESSAGE => P_OUT_ERROR_MESSAGE
  );
  DBMS_OUTPUT.PUT_LINE('P_OUT_ERROR_CODE = ' || P_OUT_ERROR_CODE);
  DBMS_OUTPUT.PUT_LINE('P_OUT_ERROR_MESSAGE = ' || P_OUT_ERROR_MESSAGE);
END;
/
