begin

EXECUTE IMMEDIATE 'ALTER TABLE LABOR_SPLIT_DETAILS enable CONSTRAINT SLT_DTL_GRP_AUDIT_FK';
EXECUTE IMMEDIATE 'alter table LABOR_SPLIT_DETAILS enable constraint LABOR_SPLIT_LINE_ITEM_GROUP_FK';

EXECUTE IMMEDIATE 'ALTER TABLE INV_ITEM_ATTR_VALS enable CONSTRAINT INVITEMATTRVALS_INVITEMID_FK';
EXECUTE IMMEDIATE 'alter table INV_ITEM_ATTR_VALS enable constraint INVATTRVAL_INVITEMATTRVALID_FK';

EXECUTE IMMEDIATE 'ALTER TABLE ADD_PAYMENT_INFO enable CONSTRAINT  ADD_PYM_INFO_LINE_ITEM_GRP_FK';
EXECUTE IMMEDIATE 'ALTER TABLE ADD_PAYMENT_INFO enable CONSTRAINT  ADDITIONAL_PAYMENT_INFO_FK';

EXECUTE IMMEDIATE 'ALTER TABLE MODIFIERS enable CONSTRAINT   MODIFIERS_LINE_ITE_FK';
EXECUTE IMMEDIATE 'ALTER TABLE MODIFIERS enable CONSTRAINT   MODIFIERS_LINE_ITEM_GROUP_FK';

EXECUTE IMMEDIATE 'alter table I18NITEM_TEXT enable constraint I18NITEM_TEXT_ITEM_FK';

execute immediate 'alter table LINE_ITEM_GROUPS enable constraint LINEITEMGROUPS_LINEITEMGRPS_FK';
EXECUTE IMMEDIATE 'alter table LINE_ITEM_GROUPS enable constraint LINEITEMGROUPS_FORPAYMENT_FK';



end;
/
select status,table_name
FROM user_constraints
where constraint_name in ('LINEITEMGROUPS_LINEITEMGRPS_FK'
,'LINEITEMGROUPS_FORPAYMENT_FK'
,'SLT_DTL_GRP_AUDIT_FK'
,'LABOR_SPLIT_LINE_ITEM_GROUP_FK'
,'INVITEMATTRVALS_INVITEMID_FK'
,'INVATTRVAL_INVITEMATTRVALID_FK'
,'ADD_PYM_INFO_LINE_ITEM_GRP_FK'
,'ADDITIONAL_PAYMENT_INFO_FK'
,'MODIFIERS_LINE_ITE_FK'
,'MODIFIERS_LINE_ITEM_GROUP_FK'
,'I18NITEM_TEXT_ITEM_FK'
);
/
select 'alter table ' || table_name || ' enable constraint ' || constraint_name from user_constraints where status <> 'ENABLED' and table_name in ('MODIFIERS','ADD_PAYMENT_INFO','INVENTORY_ITEM','INV_ITEM_ATTR_VALS','LABOR_SPLIT_DETAILS','LINE_ITEM_GROUPS');
/

