CREATE TABLE CLAIM_AUDIT_HIST_LABOR
  (
    ID                           NUMBER PRIMARY KEY,
    SERVICE_PROCEDURE_DEFINITION NUMBER,
    LABOR_HRS_ON_JOB             NUMBER(19,2),
    ADDITIONAL_LABOR_HRS         NUMBER(19,2),
    AUDIT_ID                     NUMBER
  )
/
CREATE TABLE CLAIM_AUDIT_HIST_PARTS
  (
    ID                   NUMBER PRIMARY KEY,
    REPLACED_PART_ID     NUMBER,
    NUMBER_OF_UNITS      NUMBER,
    UNIT_PRICE           NUMBER(19,2),
    UNIT_PRICE_CURR      VARCHAR2(10),
    UNIT_COST_PRICE      NUMBER(19,2),
    UNIT_COST_PRICE_CURR VARCHAR2(10),
    IS_PART_RETURNED     VARCHAR2(1),
    AUDIT_ID             NUMBER
  )
/
CREATE TABLE CLAIM_AUDIT_HISTORICAL
  (
    ID                		NUMBER PRIMARY KEY,
    CLAIM_NUMBER      		VARCHAR2(255),
    WORK_ORDER_NUMBER 		VARCHAR2(255),
    LAST_UPDATED_ON_DATE 	DATE,
    FAILURE_DATE 			DATE,
    REPAIR_DATE 			DATE,
    CAUSAL_PART_ITEM        NUMBER,
    FAULT_CODE_DEFINITION   NUMBER,
    FAILURE_TYPE_DEFINITION NUMBER,
    TECHNICIAN              NUMBER,
	IS_SMR 					VARCHAR2(1),
	WORK_PERFORMED          VARCHAR2(4000 CHAR),
	CONDITION_FOUND         VARCHAR2(4000 CHAR), 
	OTHER_COMMENTS          VARCHAR2(4000 CHAR),
	ACCEPTANCE_REASON       NUMBER(19) ,         
ACCOUNTABILITY_CODE         NUMBER(19)      ,    
REJECTION_REASON            NUMBER(19)  ,
    AUDIT_ID                NUMBER
  )
/
CREATE TABLE CLAIM_AUDIT_HIST_TRAVEL
  (
	ID                   NUMBER PRIMARY KEY,
	DISTANCE			 NUMBER(19,2),
	HOURS                NUMBER(19,2),
	LOCATION             VARCHAR2(255),
	TRIPS                NUMBER(10,0),
	UOM                  VARCHAR2(255),
	ADDITIONAL_HOURS 	 NUMBER(19,2),
	AUDIT_ID             NUMBER
  )
/
CREATE TABLE CLAIM_AUDIT_HIST_INCIDENTALS
  (
    ID                            NUMBER PRIMARY KEY,
    FREIGHT_DUTY_AMT              NUMBER(19,2) ,
    FREIGHT_DUTY_CURR             VARCHAR2(255 ) ,
    MEALS_AMT                     NUMBER(19,2) ,
    MEALS_CURR                    VARCHAR2(255 ),
    OTHER_FREIGHT_DUTY_AMT        NUMBER(19,2) ,
    OTHER_FREIGHT_DUTY_CURR       VARCHAR2(255) ,
    OTHERS_AMT                    NUMBER(19,2) ,
    OTHERS_CURR                   VARCHAR2(255) ,
    AUDIT_ID                      NUMBER(19)
  )
/
CREATE TABLE CLAIM_AUDIT_HIST_NONOEM_PARTS
  (
    ID               NUMBER(19) primary key,
    NUMBER_OF_UNITS          NUMBER(10) ,
    PRICE_PER_UNIT_AMT       NUMBER(19,2) ,
    PRICE_PER_UNIT_CURR      VARCHAR2(255 ) ,
    DESCRIPTION              VARCHAR2(255) ,
    INVOICE_id               NUMBER(19) ,
    AUDIT_ID                 NUMBER
  )
/