--create index ITEM_SCHEME_PURPOSES_IDX on ITEM_SCHEME_PURPOSES("PURPOSES")
--/
--create index ITEM_GRP_BU_ACT_IDX on ITEM_GROUP("BUSINESS_UNIT_INFO","D_ACTIVE")
--/
--create index RECOVERY_INFO_BU_ACT_IDX on RECOVERY_INFO("BUSINESS_UNIT_INFO","D_ACTIVE")
--/
--create index CLAIM_BU_IDX on CLAIM(BUSINESS_UNIT_INFO)
--/
create index CLAIM_FILED_ON_DATE_IDX on CLAIM("FILED_ON_DATE")
/
create index CLAIM_AUDIT_UPDATED_TIME_IDX on CLAIM_AUDIT("UPDATED_TIME")
/
create index CLAIM_LST_UPDT_DATE_IDX on CLAIM("LAST_UPDATED_ON_DATE")
/
create index INV_ITEM_LOWSERIAL_NUMBER_IDX on inventory_item(LOWER("SERIAL_NUMBER"))
/