--To improve pref defined searches in R6
create index II_TYPE_BU_SERPART_ACT_IDX on INVENTORY_ITEM(TYPE,BUSINESS_UNIT_INFO,SERIALIZED_PART,D_ACTIVE)
/
CREATE INDEX INV_TRNSN_SALES_ORDER_NUM_IDX ON INVENTORY_TRANSACTION(SALES_ORDER_NUMBER)
/