--PURPOSE    : Indexes for claim submission work flow encountered during  part return workflow
--AUTHOR     : Ramalakshmi P
--CREATED ON : 19-MAY-11

CREATE INDEX CLM_IDX_WORKORDER ON CLAIM(LOWER(WORK_ORDER_NUMBER))
/
CREATE INDEX CLMALARMCODE_IDX_CLAM ON CLAIM_ALARM_CODES(CLAIM)
/
CREATE INDEX ADDPMTINFO_IDX_LINTITMGRP ON ADD_PAYMENT_INFO(LINE_ITEM_GROUP)
/
CREATE INDEX LABORSPLITDET_IDX_LINEITMGRP ON LABOR_SPLIT_DETAILS(LINE_ITEM_GROUP)
/
CREATE INDEX MODIFIERS_IDX_LINEITEMGRP ON MODIFIERS(LINE_ITEM_GROUP)
/