--PURPOSE    : Created indexes home page work flow
--AUTHOR     : Ramalakshmi P
--CREATED ON : 28-APR-11

CREATE INDEX WARRANTY_IDX_FORDEALER ON WARRANTY(FOR_DEALER)
/
CREATE INDEX REQWNTYCVGAUTID_IDX_ASSIGNEDTO ON REQUEST_WNTY_CVG_AUDIT(ASSIGNED_TO)
/
CREATE BITMAP INDEX REQWNTYCVGAUTID_IDX_STATUS ON REQUEST_WNTY_CVG_AUDIT(STATUS)
/
CREATE INDEX JBPM_VARINSTANCE_IDX_CLSNAME ON JBPM_VARIABLEINSTANCE(NAME_,CLASS_)
/
CREATE INDEX JBPM_MODULEINSTANCE_I3 ON JBPM_MODULEINSTANCE(PROCESSINSTANCE_, ID_)
/
CREATE INDEX ORGUSRBELONGSTO_IDX_ORGUSER ON ORG_USER_BELONGS_TO_ORGS(ORG_USER)
/
CREATE BITMAP INDEX WARRANTY_IDX_TRNXTYPE ON WARRANTY(TRANSACTION_TYPE)
/
DROP INDEX WARRANTY_TASK_INSTANCE_I1
/
CREATE BITMAP INDEX WARRANTY_TASK_INSTANCE_I1 ON WARRANTY_TASK_INSTANCE(STATUS)
/
CREATE BITMAP INDEX WARRANTY_TASK_INSTANCE_I3 ON WARRANTY_TASK_INSTANCE(BUSINESS_UNIT_INFO)
/
CREATE BITMAP INDEX WARRANTY_TASK_INSTANCE_I5 ON WARRANTY_TASK_INSTANCE(ACTIVE, STATUS)
/