/* Patch for removing the repeated ID in I18NDOMAIN_RULE_TEXT table */
create table I18NDOMAIN_RULE_TEXT_BACKUP
as (select * from I18NDOMAIN_RULE_TEXT)
/
delete from I18NDOMAIN_RULE_TEXT
/
commit
/
INSERT INTO I18NDOMAIN_RULE_TEXT(ID,LOCALE,FAILURE_DESCRIPTION,DOMAIN_RULE)
SELECT I18NDOMAINRULETEXT_SEQ.NEXTVAL,LOCALE,FAILURE_DESCRIPTION,DOMAIN_RULE
FROM I18NDOMAIN_RULE_TEXT_BACKUP
/
commit
/
drop table I18NDOMAIN_RULE_TEXT_BACKUP
/
commit
/