--PURPOSE    : Indexes for claim submission work flow encountered during  BTS analysis
--AUTHOR     : Ramalakshmi P
--CREATED ON : 19-MAY-11

CREATE INDEX CUSTREPANS_IDX_FORINVITEM ON CUSTOM_REPORT_ANSWER(FOR_INVENTORY)
/
CREATE INDEX DLRGRP_IDX_BUDACTIVE ON DEALER_GROUP(BUSINESS_UNIT_INFO,D_ACTIVE)
/
CREATE INDEX PRTDEF_IDX_BUDACTIVE ON PART_RETURN_DEFINITION(D_ACTIVE,BUSINESS_UNIT_INFO)
/
CREATE INDEX PRTRETAUDIT_IDX_FORPRTREP ON PART_RETURN_AUDIT(FOR_PART_REPLACED)
/
CREATE INDEX JBPM_SWMLANE_IDX_TASKMGNTINST ON JBPM_SWIMLANEINSTANCE(TASKMGMTINSTANCE_)
/
CREATE INDEX CUSTREP_IDX_BUDACTIVE ON CUSTOM_REPORT(BUSINESS_UNIT_INFO,D_ACTIVE)
/
CREATE INDEX ITEMGRPREPORT_IDX_CUSTREP ON ITEM_GROUPS_IN_REPORTS(CUSTOM_REPORT)
/
CREATE INDEX INVTYPREPORT_IDX_CUSTREPORT ON INVENTORY_TYPES_IN_REPORTS(CUSTOM_REPORT)
/
CREATE INDEX USER_IDX_LOGIN ON ORG_USER(LOWER(LOGIN))
/
CREATE INDEX JBPMRUNTIME_IDX_PROCESSINST ON JBPM_RUNTIMEACTION(PROCESSINSTANCE_)
/
