--PURPOSE    : PATCH FOR UPDATING HOURS_IN_SERVICE
--AUTHOR     : GHANASHYAM DAS
--CREATED ON : 21-NOV-11

ALTER TABLE CLAIMED_ITEM ADD (HOURS_IN_SERVICE_NEW NUMBER(19,0))
/
UPDATE CLAIMED_ITEM SET HOURS_IN_SERVICE_NEW = HOURS_IN_SERVICE
/
ALTER TABLE CLAIMED_ITEM DROP COLUMN HOURS_IN_SERVICE
/
ALTER TABLE CLAIMED_ITEM RENAME COLUMN HOURS_IN_SERVICE_NEW TO HOURS_IN_SERVICE
/
COMMIT
/