create index CLAIM_BU_IDX on CLAIM(BUSINESS_UNIT_INFO)
/
create index SMPR_MISC_PARTS_REPLACED_IDX on SERVICE_MISC_PARTS_REPLACED(MISC_PARTS_REPLACED)
/
create index CRF_RULE_FAILURES_IDX on CLAIM_RULE_FAILURES(RULE_FAILURES)
/