--PURPOSE    : Indexes for claim submission work flow
--AUTHOR     : Ramalakshmi P
--CREATED ON : 12-MAY-11

CREATE INDEX DLRGRP_IDX_NAME ON DEALER_GROUP(NAME)
/
CREATE INDEX JBPMTRANS_IDX_FROM_ ON JBPM_TRANSITION(FROM_)
/
CREATE INDEX JBPMEVN_IDX_NODE ON JBPM_EVENT(NODE_)
/
CREATE INDEX CLMITEM_IDX_CLAIMEDITEM ON CLAIM_CLAIMED_ITEMS (CLAIMED_ITEMS )
/

 
