-- Purpose    : Droping Incidental Cost Categories in the Campaign service detail
-- Author     : Jitesh Jain
-- Created On : 12-Jul-09

ALTER TABLE CAMPAIGN_SERVICE_DETAIL DROP COLUMN "FREIGHT_DUTY_AMT"
/
ALTER TABLE CAMPAIGN_SERVICE_DETAIL DROP COLUMN "FREIGHT_DUTY_CURR"
/
ALTER TABLE CAMPAIGN_SERVICE_DETAIL DROP COLUMN "MEALS_AMT"
/
ALTER TABLE CAMPAIGN_SERVICE_DETAIL DROP COLUMN "MEALS_CURR"
/
ALTER TABLE CAMPAIGN_SERVICE_DETAIL DROP COLUMN "PARKING_AND_TOLL_EXPENSE_AMT"
/
ALTER TABLE CAMPAIGN_SERVICE_DETAIL DROP COLUMN "PARKING_AND_TOLL_EXPENSE_CURR"
/
ALTER TABLE CAMPAIGN_SERVICE_DETAIL DROP COLUMN "PER_DIEM_AMT"
/
ALTER TABLE CAMPAIGN_SERVICE_DETAIL DROP COLUMN "PER_DIEM_CURR"
/
ALTER TABLE CAMPAIGN_SERVICE_DETAIL DROP COLUMN "RENTAL_CHARGES_AMT"
/
ALTER TABLE CAMPAIGN_SERVICE_DETAIL DROP COLUMN "RENTAL_CHARGES_CURR"
/
COMMIT
/