--Purpose : replaced parts for vendor recovery extract
--Author  : raguram.d
--Date    : 28/Dec/09

create or replace FUNCTION GET_MODEL_DESC (P_CLAIMID NUMBER) RETURN VARCHAR2 IS

V_RETURN_STR	VARCHAR2(255);

BEGIN

    V_RETURN_STR := null;
    BEGIN
	 SELECT NAME INTO V_RETURN_STR FROM ITEM_GROUP WHERE ID IN (
	 SELECT MODEL FROM ITEM WHERE ID IN (SELECT OF_TYPE FROM INVENTORY_ITEM WHERE ID 
	 IN (SELECT ITEM_REF_INV_ITEM FROM CLAIMED_ITEM WHERE CLAIM IN (P_CLAIMID) AND ROWNUM = 1)));
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
        BEGIN
	 	    SELECT NAME INTO V_RETURN_STR FROM ITEM_GROUP WHERE ID IN 
		    (SELECT MODEL_REF_FOR_UNSZED FROM CLAIMED_ITEM WHERE CLAIM IN (P_CLAIMID) AND ROWNUM = 1);
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                null;
        END;
    END;

RETURN V_RETURN_STR;

END;

