CREATE TABLE BU_ORG_MAPPING
(
  ORG  NUMBER(19)                               NOT NULL,
  BU   VARCHAR2(255 CHAR)                       NOT NULL
)
/
ALTER TABLE BU_ORG_MAPPING ADD CONSTRAINT BU_ORG_MAPPING_PK PRIMARY KEY (ORG, BU)
/