--PURPOSE    : ALTERED WARRANTY_TASK_INSTANCE TABLE FOR MULTIDR MANUAL APPROVAL FLOW
--AUTHOR     : PRADYOT.ROUT
--CREATED ON : 09-SEP-08

CREATE SEQUENCE WARRANTY_MULTIDRETR_NUMBER_SEQ
  START WITH 1000
  INCREMENT BY 20
  MAXVALUE 999999999999999999999999999
  MINVALUE 1000
  NOCYCLE
  CACHE 20
  NOORDER
/
ALTER TABLE WARRANTY ADD MULTIDRETRNUMBER VARCHAR2(255 CHAR)
/
ALTER TABLE WARRANTY_TASK_INSTANCE ADD MULTIDRETRNUMBER VARCHAR2(255 CHAR)
/
CREATE TABLE WARRANTY_TASK_INCLUDED_ITEMS (WARRANTY_TASK NUMBER(19,0) NOT NULL, INV_ITEM NUMBER(19,0) NOT NULL)
/
ALTER TABLE WARRANTY_TASK_INCLUDED_ITEMS ADD CONSTRAINT WNTY_TASK_INST_FK FOREIGN KEY (WARRANTY_TASK) REFERENCES WARRANTY_TASK_INSTANCE
/
ALTER TABLE WARRANTY_TASK_INCLUDED_ITEMS ADD CONSTRAINT WNTY_TASK_INV_ITEM_FK FOREIGN KEY (INV_ITEM) REFERENCES INVENTORY_ITEM
/
INSERT INTO CONFIG_PARAM (ID,DESCRIPTION,DISPLAY_NAME,NAME,TYPE)VALUES
((CONFIG_PARAM_SEQ.NEXTVAL),
'manualApprovalFlowForDR','manualApprovalFlowForDR','manualApprovalFlowForDR','boolean')
/
INSERT INTO CONFIG_VALUE (ID,ACTIVE,VALUE,CONFIG_PARAM,BUSINESS_UNIT_INFO) VALUES
(CONFIG_VALUE_SEQ.NEXTVAL,1,'true',(SELECT ID FROM CONFIG_PARAM WHERE NAME='manualApprovalFlowForDR'),
'Club Car')
/
DECLARE
CURSOR GET_WARRANTY_TASK  IS
SELECT FOR_ITEM,ID FROM WARRANTY_TASK_INSTANCE;
BEGIN
	FOR GET_REC IN GET_WARRANTY_TASK LOOP
	 	INSERT INTO WARRANTY_TASK_INCLUDED_ITEMS VALUES(GET_REC.ID,GET_REC.FOR_ITEM);			
	END LOOP;
END;
/
ALTER TABLE WARRANTY_TASK_INSTANCE DROP COLUMN FOR_ITEM
/
COMMIT
/