--Purpose    : PATCH FOR MAKING THE LABOR RATES DEACTIVATION
--Author     : Hari Krishna Y D
--Created On : 30-APRIL-09

alter table labor_Rates add(
D_CREATED_BY NUMBER, D_LAST_UPDATED_BY NUMBER,D_CREATED_ON DATE,
D_UPDATED_ON DATE,D_INTERNAL_COMMENTS VARCHAR2(20),D_CREATED_TIME TIMESTAMP, 
D_UPDATED_TIME TIMESTAMP,D_ACTIVE NUMBER(1) DEFAULT 1)
/
ALTER TABLE labor_Rates ADD CONSTRAINT labor_Rates_LAST_UPTD_BY_FK
FOREIGN KEY (D_LAST_UPDATED_BY)  REFERENCES ORG_USER (ID) ENABLE  VALIDATE
/
UPDATE LABOR_RATES SET D_ACTIVE=1
/
alter table travel_Rates add(
D_CREATED_BY NUMBER, D_LAST_UPDATED_BY NUMBER,D_CREATED_ON DATE,
D_UPDATED_ON DATE,D_INTERNAL_COMMENTS VARCHAR2(20),D_CREATED_TIME TIMESTAMP, 
D_UPDATED_TIME TIMESTAMP,D_ACTIVE NUMBER(1) DEFAULT 1)
/
ALTER TABLE travel_Rates ADD CONSTRAINT travel_Rates_LAST_UPTD_BY_FK
FOREIGN KEY (D_LAST_UPDATED_BY)  REFERENCES ORG_USER (ID) ENABLE  VALIDATE
/
UPDATE TRAVEL_RATES SET D_ACTIVE=1
/
COMMIT
/