--PURPOSE    : PATCH FOR IMPLEMENTING CUSTOM REPORTS
--AUTHOR     : PRADYOT ROUT
--CREATED ON : 10-DEC-08
CREATE SEQUENCE CUSTOM_REPORT_SEQ START WITH 1000 INCREMENT BY 20
/
CREATE SEQUENCE REPORT_FORM_ANSWER_OPTION_SEQ START WITH 1000 INCREMENT BY 20
/
CREATE SEQUENCE REPORT_FORM_QUESTION_SEQ START WITH 1000 INCREMENT BY 20
/
CREATE SEQUENCE REPORT_SECTION_SEQ START WITH 1000 INCREMENT BY 20
/
CREATE TABLE REPORT_FORM_ANSWER_OPTION
(
  ID                   NUMBER(19)               NOT NULL,
  ANSWER_OPTION        VARCHAR2(255 CHAR),
  D_CREATED_ON         DATE,
  D_CREATED_TIME       TIMESTAMP(6),
  D_INTERNAL_COMMENTS  VARCHAR2(255 CHAR),
  D_UPDATED_ON         DATE,
  D_UPDATED_TIME       TIMESTAMP(6),
  ANS_ORDER            NUMBER(10)               NOT NULL,
  D_LAST_UPDATED_BY    NUMBER(19),
  D_ACTIVE             NUMBER(1),
  CONSTRAINT REPORT_FORM_ANSWER_OPTION_PK PRIMARY KEY (ID)
)
/
ALTER TABLE REPORT_FORM_ANSWER_OPTION ADD (CONSTRAINT REPORT_FORM_ANS_OPT_UPDATED_FK FOREIGN KEY (D_LAST_UPDATED_BY) 
 REFERENCES ORG_USER (ID))
/
CREATE TABLE REPORT_FORM_QUESTION
(
  ID                   NUMBER(19)               NOT NULL,
  ANSWER_TYPE          VARCHAR2(255 CHAR),
  NAME                 VARCHAR2(255 CHAR),
  D_CREATED_ON         DATE,
  D_CREATED_TIME       TIMESTAMP(6),
  D_INTERNAL_COMMENTS  VARCHAR2(255 CHAR),
  D_UPDATED_ON         DATE,
  D_UPDATED_TIME       TIMESTAMP(6),
  QUESTION_ORDER       NUMBER(10)               NOT NULL,
  D_LAST_UPDATED_BY    NUMBER(19),
  MANDATORY            NUMBER(1),
  DEFAULT_ANSWER       NUMBER(19),
  D_ACTIVE             NUMBER(1),
  CONSTRAINT REPORT_SECTION_FORM_PK PRIMARY KEY (ID)
)
/
ALTER TABLE REPORT_FORM_QUESTION ADD CONSTRAINT REPORT_FORM_QUE_UPDATED_FK FOREIGN KEY (D_LAST_UPDATED_BY) REFERENCES ORG_USER
/
ALTER TABLE REPORT_FORM_QUESTION ADD CONSTRAINT REPORT_FORM_QUE_DEF_ANS_FK FOREIGN KEY (DEFAULT_ANSWER) REFERENCES REPORT_FORM_ANSWER_OPTION
/
CREATE TABLE SECTION_QUESTION_ANSWERS (FOR_QUESTION NUMBER(19,0) NOT NULL, ANSWER_OPTIONS NUMBER(19,0) NOT NULL, UNIQUE (ANSWER_OPTIONS))
/
ALTER TABLE SECTION_QUESTION_ANSWERS ADD CONSTRAINT SEC_QUE_ANS_FORM_ANS_OPT_FK FOREIGN KEY (ANSWER_OPTIONS) REFERENCES REPORT_FORM_ANSWER_OPTION
/
ALTER TABLE SECTION_QUESTION_ANSWERS ADD CONSTRAINT SECTION_QUE_ANS_FORM_QUE_FK FOREIGN KEY (FOR_QUESTION) REFERENCES REPORT_FORM_QUESTION
/
CREATE TABLE REPORT_SECTION
(
  ID                   NUMBER(19)               NOT NULL,
  D_CREATED_ON         DATE,
  D_CREATED_TIME       TIMESTAMP(6),
  D_INTERNAL_COMMENTS  VARCHAR2(255 CHAR),
  D_UPDATED_ON         DATE,
  D_UPDATED_TIME       TIMESTAMP(6),
  NAME                 VARCHAR2(255 CHAR),
  SECTION_ORDER        NUMBER(10)               NOT NULL,
  D_LAST_UPDATED_BY    NUMBER(19),
  D_ACTIVE             NUMBER(1),
  CONSTRAINT REPORT_SECTION_PK PRIMARY KEY (ID)
)
/
ALTER TABLE REPORT_SECTION ADD CONSTRAINT REPORT_SECTION_UPDATED_FK FOREIGN KEY (D_LAST_UPDATED_BY) REFERENCES ORG_USER
/
CREATE TABLE QUESTIONNAIRE (FOR_SECTION NUMBER(19,0) NOT NULL, QUESTIONNAIRE NUMBER(19,0) NOT NULL, UNIQUE (QUESTIONNAIRE))
/
ALTER TABLE QUESTIONNAIRE ADD CONSTRAINT QUESTIONNAIRE__SECTION_FORM_FK FOREIGN KEY (QUESTIONNAIRE) REFERENCES REPORT_FORM_QUESTION
/
ALTER TABLE QUESTIONNAIRE ADD CONSTRAINT QUESTIONNAIRE_SECTION_FK FOREIGN KEY (FOR_SECTION) REFERENCES REPORT_SECTION
/
CREATE TABLE CUSTOM_REPORT
(
  ID                   NUMBER(19)               NOT NULL,
  NAME                 VARCHAR2(255 CHAR),
  PUBLISHED            NUMBER(1),
  BUSINESS_UNIT_INFO   VARCHAR2(255 CHAR),
  D_CREATED_ON         DATE,
  D_CREATED_TIME       TIMESTAMP(6),
  D_INTERNAL_COMMENTS  VARCHAR2(255 CHAR),
  D_UPDATED_ON         DATE,
  D_UPDATED_TIME       TIMESTAMP(6),
  D_LAST_UPDATED_BY    NUMBER(19),
  D_ACTIVE             NUMBER(1),
  CONSTRAINT CUSTOM_REPORT_PK PRIMARY KEY (ID)
)
/
ALTER TABLE CUSTOM_REPORT ADD CONSTRAINT CUSTOM_REPORT_UPDATED_FK FOREIGN KEY (D_LAST_UPDATED_BY) REFERENCES ORG_USER
/
CREATE TABLE ITEM_GROUPS_IN_REPORTS (CUSTOM_REPORT NUMBER(19,0) NOT NULL, ITEM_GROUP NUMBER(19,0) NOT NULL)
/
ALTER TABLE ITEM_GROUPS_IN_REPORTS ADD CONSTRAINT ITEMS_IN_RPT_CUSTOM_RPT_FK FOREIGN KEY (CUSTOM_REPORT) REFERENCES CUSTOM_REPORT
/
ALTER TABLE ITEM_GROUPS_IN_REPORTS ADD CONSTRAINT ITEMS_IN_RPT_ITEM_GRP_FK FOREIGN KEY (ITEM_GROUP) REFERENCES ITEM_GROUP
/
CREATE TABLE REPORT_SECTIONS (FOR_REPORT NUMBER(19,0) NOT NULL, SECTIONS NUMBER(19,0) NOT NULL, UNIQUE (SECTIONS))
/
ALTER TABLE REPORT_SECTIONS ADD CONSTRAINT REPORT_SECTIONS_REPORT_SEC_FK FOREIGN KEY (SECTIONS) REFERENCES REPORT_SECTION
/
ALTER TABLE REPORT_SECTIONS ADD CONSTRAINT REPORT_SECTIONS_CUST_RPT_FK FOREIGN KEY (FOR_REPORT) REFERENCES CUSTOM_REPORT
/
COMMIT
/
CREATE SEQUENCE REPORT_FORM_ANSWER_SEQ START WITH 1000 INCREMENT BY 20
/
CREATE SEQUENCE CUSTOM_REPORT_ANSWER_SEQ START WITH 1000 INCREMENT BY 20
/
CREATE TABLE REPORT_FORM_ANSWER
(
  ID                   NUMBER(19)               NOT NULL,
  ANSWER_OPTION 	   NUMBER(19),
  QUESTION             NUMBER(19),
  SECTION              NUMBER(19),
  ANSWER_VALUE         VARCHAR2(255 CHAR),
  D_CREATED_ON         DATE,
  D_CREATED_TIME       TIMESTAMP(6),
  D_INTERNAL_COMMENTS  VARCHAR2(255 CHAR),
  D_UPDATED_ON         DATE,
  D_UPDATED_TIME       TIMESTAMP(6),
  D_LAST_UPDATED_BY    NUMBER(19),
  ANSWER_ORDER         NUMBER(19),
  D_ACTIVE             NUMBER(1),
  CONSTRAINT REPORT_FORM_ANSWER_PK PRIMARY KEY (ID)
)
/
ALTER TABLE REPORT_FORM_ANSWER ADD CONSTRAINT FORM_ANSWER_UPDATED_FK FOREIGN KEY (D_LAST_UPDATED_BY) REFERENCES ORG_USER
/
ALTER TABLE REPORT_FORM_ANSWER ADD CONSTRAINT FORM_ANSWER_OPTION_FK FOREIGN KEY (ANSWER_OPTION) REFERENCES Report_Form_Answer_Option
/
ALTER TABLE REPORT_FORM_ANSWER ADD CONSTRAINT FORM_ANSWER_QUESTION_FK FOREIGN KEY (QUESTION) REFERENCES REPORT_FORM_QUESTION
/
ALTER TABLE REPORT_FORM_ANSWER ADD CONSTRAINT FORM_ANSWER_SECTION_FK FOREIGN KEY (SECTION) REFERENCES REPORT_SECTION
/
CREATE TABLE CUSTOM_REPORT_ANSWER
(
  ID                   NUMBER(19)               NOT NULL,
  D_CREATED_ON         DATE,
  D_CREATED_TIME       TIMESTAMP(6),
  D_INTERNAL_COMMENTS  VARCHAR2(255 CHAR),
  D_UPDATED_ON         DATE,
  D_UPDATED_TIME       TIMESTAMP(6),
  D_LAST_UPDATED_BY    NUMBER(19),
  FOR_INVENTORY        NUMBER(19),
  CUSTOM_REPORT        NUMBER(19),
  D_ACTIVE             NUMBER(1)                DEFAULT 1,
  CONSTRAINT CUSTOM_REPORT_ANSWER_PK PRIMARY KEY (ID)
)
/
ALTER TABLE CUSTOM_REPORT_ANSWER 
ADD CONSTRAINT CUST_RPT_ANS_CUST_RPT_FK FOREIGN KEY (CUSTOM_REPORT) REFERENCES CUSTOM_REPORT
/
ALTER TABLE CUSTOM_REPORT_ANSWER ADD CONSTRAINT CUSTOM_REPORT_ANS_UPDATED_FK FOREIGN KEY (D_LAST_UPDATED_BY) REFERENCES ORG_USER
/
ALTER TABLE CUSTOM_REPORT_ANSWER ADD (
  CONSTRAINT CUST_RPT_ANS_FOR_INV_FK 
 FOREIGN KEY (FOR_INVENTORY) 
 REFERENCES INVENTORY_ITEM (ID))
/
CREATE TABLE CUSTOM_REPORT_ANSWERS
(
  FOR_REPORT_ANSWER   NUMBER(19)                NOT NULL,
  REPORT_FORM_ANSWER  NUMBER(19)                NOT NULL
)
/
ALTER TABLE CUSTOM_REPORT_ANSWERS ADD CONSTRAINT CUST_REPORT_ANS_FK FOREIGN KEY (FOR_REPORT_ANSWER) REFERENCES CUSTOM_REPORT_ANSWER
/
ALTER TABLE CUSTOM_REPORT_ANSWERS ADD CONSTRAINT CUST_RPT_ANS_FORM_ANS_FK FOREIGN KEY (REPORT_FORM_ANSWER) REFERENCES REPORT_FORM_ANSWER
/
CREATE TABLE form_answer_options (for_form_answer NUMBER(19,0) NOT NULL, answer_option NUMBER(19,0) NOT NULL)
/
ALTER TABLE FORM_ANSWER_OPTIONS ADD (
  CONSTRAINT FRM_ANS_OPT_FRM_ANS_OPT_FK 
 FOREIGN KEY (ANSWER_OPTION) 
 REFERENCES REPORT_FORM_ANSWER_OPTION (ID))
/
ALTER TABLE FORM_ANSWER_OPTIONS ADD (
  CONSTRAINT FRM_ANS_OPT_FRM_ANS_FK 
 FOREIGN KEY (FOR_FORM_ANSWER) 
 REFERENCES REPORT_FORM_ANSWER (ID))
/
COMMIT
/




