--Purpose    : Patch to create tables for new customer type in the application
--Author     : pratima.rajak
--Created On : 2-Sep-08

CREATE TABLE DIRECT_CUSTOMER (ID NUMBER(19,0) NOT NULL, DIRECT_CUSTOMER_NUMBER VARCHAR2(255 CHAR))
/
ALTER TABLE DIRECT_CUSTOMER ADD CONSTRAINT DIRECT_CUSTOMER_PK	PRIMARY KEY( 	ID	)
/
CREATE TABLE INTER_COMPANY (ID NUMBER(19,0) NOT NULL, INTER_COMPANY_NUMBER VARCHAR2(255 CHAR))
/
ALTER TABLE INTER_COMPANY ADD CONSTRAINT INTER_COMPANY_PK	PRIMARY KEY( 	ID	)
/
CREATE TABLE NATIONAL_ACCOUNT (ID NUMBER(19,0) NOT NULL, NATIONAL_ACCOUNT_NUMBER VARCHAR2(255 CHAR))
/
ALTER TABLE NATIONAL_ACCOUNT ADD CONSTRAINT NATIONAL_ACCOUNT_PK	PRIMARY KEY( 	ID	)
/
CREATE TABLE ORIGINAL_EQUIP_MANUFACTURER (ID NUMBER(19,0) NOT NULL, ORG_EQUIP_MANUF_NUMBER VARCHAR2(255 CHAR))
/
ALTER TABLE ORIGINAL_EQUIP_MANUFACTURER ADD CONSTRAINT ORIGINAL_EQUIP_MANUFACTURER_PK	PRIMARY KEY( 	ID	)
/
ALTER TABLE ORGANIZATION ADD PREFERRED_CURRENCY VARCHAR2(255 CHAR)
/