--Purpose: For Data Migration of Warranty Upload
--Author: Jhulfikar Ali A
--Created On: 14-Apr-2009
-- Read me: Need to see whether to drop Index or not : DROP INDEX COMPETITION_TYPE_PK

INSERT INTO competition_type (TYPE, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE, ID, BUSINESS_UNIT_INFO)
VALUES ('UNKNOWN/NOT PROVIDED', 0, sysdate, 'IRI-Migration', TRUNC(sysdate), NULL, TRUNC(SYSDATE), SYSDATE, 1, competition_type_seq.nextval, 'AIR')
/
INSERT INTO competition_type (TYPE, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE, ID, BUSINESS_UNIT_INFO)
VALUES ('UNKNOWN/NOT PROVIDED', 0, sysdate, 'IRI-Migration', sysdate, NULL, '', '', 1, competition_type_seq.nextval, 'TFM')
/
INSERT INTO competition_type (TYPE, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE, ID, BUSINESS_UNIT_INFO)
VALUES ('UNKNOWN/NOT PROVIDED', 0, sysdate, 'IRI-Migration', sysdate, NULL, '', '', 1, competition_type_seq.nextval, 'Transport Solutions ESA')
/
INSERT INTO competition_type (TYPE, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE, ID, BUSINESS_UNIT_INFO)
VALUES ('UNKNOWN/NOT PROVIDED', 0, sysdate, 'IRI-Migration', sysdate, NULL, '', '', 1, competition_type_seq.nextval, 'Clubcar ESA')
/
INSERT INTO market_type (ID, CODE, TITLE, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE, BUSINESS_UNIT_INFO)
VALUES (market_type_seq.nextval, '000', 'UNKNOWN/NOT PROVIDED', 0, sysdate, 'IRI-Migration', sysdate, NULL, '', '', 1, 'AIR')
/
INSERT INTO market_type (ID, CODE, TITLE, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE, BUSINESS_UNIT_INFO)
VALUES (market_type_seq.nextval, '000', 'UNKNOWN/NOT PROVIDED', 0, sysdate, 'IRI-Migration', sysdate, NULL, '', '', 1, 'TFM')
/
INSERT INTO market_type (ID, CODE, TITLE, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE, BUSINESS_UNIT_INFO)
VALUES (market_type_seq.nextval, '000', 'UNKNOWN/NOT PROVIDED', 0, sysdate, 'IRI-Migration', sysdate, NULL, '', '', 1, 'Transport Solutions ESA')
/
INSERT INTO market_type (ID, CODE, TITLE, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE, BUSINESS_UNIT_INFO)
VALUES (market_type_seq.nextval, '000', 'UNKNOWN/NOT PROVIDED', 0, sysdate, 'IRI-Migration', sysdate, NULL, '', '', 1, 'Clubcar ESA')
/
INSERT INTO COMPETITOR_MODEL (MODEL, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE, ID, BUSINESS_UNIT_INFO)
values ('UNKNOWN/NOT PROVIDED', 0, sysdate, 'IRI-Migration', sysdate, NULL, '', '', 1,COMPETITOR_MODEL_SEQ.nextval, 'AIR')
/
INSERT INTO COMPETITOR_MODEL (MODEL, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE, ID, BUSINESS_UNIT_INFO)
values ('UNKNOWN/NOT PROVIDED', 0, sysdate, 'IRI-Migration', sysdate, NULL, '', '', 1,COMPETITOR_MODEL_SEQ.nextval, 'TFM')
/
INSERT INTO COMPETITOR_MODEL (MODEL, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE, ID, BUSINESS_UNIT_INFO)
values ('UNKNOWN/NOT PROVIDED', 0, sysdate, 'IRI-Migration', sysdate, NULL, '', '', 1,COMPETITOR_MODEL_SEQ.nextval, 'Transport Solutions ESA')
/
INSERT INTO COMPETITOR_MODEL (MODEL, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE, ID, BUSINESS_UNIT_INFO)
values ('UNKNOWN/NOT PROVIDED', 0, sysdate, 'IRI-Migration', sysdate, NULL, '', '', 1,COMPETITOR_MODEL_SEQ.nextval, 'Clubcar ESA')
/
INSERT INTO COMPETITOR_MAKE (MAKE, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE, ID, BUSINESS_UNIT_INFO)
VALUES ('UNKNOWN/NOT PROVIDED', 0, sysdate, 'IRI-Migration', sysdate, NULL, '', '', 1, COMPETITOR_SEQ.nextval, 'AIR')
/
INSERT INTO COMPETITOR_MAKE (MAKE, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE, ID, BUSINESS_UNIT_INFO)
VALUES ('UNKNOWN/NOT PROVIDED', 0, sysdate, 'IRI-Migration', sysdate, NULL, '', '', 1, COMPETITOR_SEQ.nextval, 'TFM')
/
INSERT INTO COMPETITOR_MAKE (MAKE, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE, ID, BUSINESS_UNIT_INFO)
VALUES ('UNKNOWN/NOT PROVIDED', 0, sysdate, 'IRI-Migration', sysdate, NULL, '', '', 1, COMPETITOR_SEQ.nextval, 'Transport Solutions ESA')
/
INSERT INTO COMPETITOR_MAKE (MAKE, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE, ID, BUSINESS_UNIT_INFO)
VALUES ('UNKNOWN/NOT PROVIDED', 0, sysdate, 'IRI-Migration', sysdate, NULL, '', '', 1, COMPETITOR_SEQ.nextval, 'Clubcar ESA')
/
COMMIT
/