--Purpose    : Patch for DIVISION CODE BU MAPPING
--Author     : Hari Krishna Y D	
--Created On : 14 Feb 2009

CREATE SEQUENCE DIVISION_BU_MAPPING_SEQ START WITH 1000 INCREMENT BY 20
/
CREATE TABLE DIVISION_BU_MAPPING (
ID NUMBER(19,0) NOT NULL,
DIVISION_CODE VARCHAR2(100),
DESCRIPTION   VARCHAR2(2000),
USAGE VARCHAR2(255),
business_unit_info VARCHAR2(255),
INTERNAL_STATUS VARCHAR2(100)    DEFAULT 'ACTIVE',
D_CREATED_ON DATE,
D_CREATED_TIME TIMESTAMP, 
D_INTERNAL_COMMENTS VARCHAR2(255), 
D_UPDATED_ON DATE, 
D_UPDATED_TIME TIMESTAMP, 
D_LAST_UPDATED_BY NUMBER(19,0),
D_ACTIVE NUMBER(1,0),
CONSTRAINT DIVISION_BU_MAPPING_PK PRIMARY KEY (ID))
/
COMMIT
/


