-- Altering Travel Detail table to make the columns nullable
-- Author: Ramalakshmi P
-- May 9 2009

ALTER TABLE  TRAVEL_DETAIL MODIFY(DISTANCE NULL)
/
ALTER TABLE  TRAVEL_DETAIL MODIFY(HOURS NULL)
/
ALTER TABLE  TRAVEL_DETAIL MODIFY(TRIPS NULL)
/
ALTER TABLE CAMPAIGN_TRAVEL_DETAIL MODIFY(DISTANCE NULL)
/
ALTER TABLE CAMPAIGN_TRAVEL_DETAIL MODIFY(HOURS NULL)
/
ALTER TABLE CAMPAIGN_TRAVEL_DETAIL MODIFY(TRIPS NULL)
/