--Purpose    :INSERT TRANSITION FOR NODES WHERE PART SHIPPED NOT RECEIVED IS INTRODUCED
--Author     : pradyot.rout
--Created On : 26-Aug-08


CREATE OR REPLACE PROCEDURE PROC_PRTSHPNTRCVAFTRANS AS

	V_PROCESSDEFINITIONID NUMBER :=0;
	V_JBPMNODEID NUMBER:=0;
	V_JBPMTASKID NUMBER:=0;
	
-- THE TRANSITION IDS OF THE EXISTING NODES AFFECTED
	V_CLOSENODE NUMBER :=0;
	V_HOLDPARTNODE NUMBER :=0;
	V_REPLIESNODE NUMBER :=0;
	V_APPEALNODE NUMBER :=0;
	V_REJECTNODE NUMBER:=0;
	V_PROREVNODE NUMBER:=0;
	V_WAITNODE NUMBER:=0;
	V_DENYNODE NUMBER:=0;
	V_REPROCESSNODE NUMBER:=0;
	V_HOLDNODE NUMBER:=0;
	V_FORWARDNODE NUMBER:=0;
	V_TRANSFERNODE NUMBER:=0;
	V_ADVICENODE NUMBER:=0;
	
-- THE NEW TRANSITION IDS
	V_OTHERTRANS1 NUMBER:=0;
	V_OTHERTRANS2 NUMBER:=0;
	V_OTHERTRANS3 NUMBER:=0;
	V_OTHERTRANS4 NUMBER:=0;
	V_OTHERTRANS5 NUMBER:=0;
	V_OTHERTRANS6 NUMBER:=0;
	V_OTHERTRANS7 NUMBER:=0;
	V_OTHERTRANS8 NUMBER:=0;
	V_OTHERTRANS9 NUMBER:=0;
	V_DENYTRANS NUMBER:=0;
	
      
      BEGIN 
      
        SELECT ID_
	       INTO   V_PROCESSDEFINITIONID
	       FROM JBPM_PROCESSDEFINITION
               WHERE NAME_ = 'ClaimSubmission';
        
        SELECT ID_
        INTO V_JBPMNODEID FROM JBPM_NODE WHERE NAME_='MoveClaimToPartsShippedNotreceivedInbox';
        
         SELECT ID_
        INTO V_DENYNODE FROM JBPM_NODE WHERE NAME_='DebitPaymentOnDenial';
        
        SELECT ID_ INTO V_JBPMTASKID
         FROM JBPM_TASK WHERE NAME_='Part Shipped Not Received';
         
         
         
         -- FOR TRANSITIONS RELATED TO NEW :
         
         SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO V_OTHERTRANS1 FROM DUAL ;
         SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO V_OTHERTRANS2 FROM DUAL ;
         SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO V_OTHERTRANS3 FROM DUAL ;
         SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO V_OTHERTRANS4 FROM DUAL ;
         SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO V_OTHERTRANS5 FROM DUAL ;
         SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO V_OTHERTRANS6 FROM DUAL ;
         SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO V_OTHERTRANS7 FROM DUAL ;
         SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO V_OTHERTRANS8 FROM DUAL ;
         SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO V_OTHERTRANS9 FROM DUAL ;
         SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO V_DENYTRANS FROM DUAL ;
         
	SELECT ID_ INTO V_PROREVNODE
	FROM JBPM_NODE WHERE NAME_='ProcessorReview' AND PROCESSDEFINITION_=V_PROCESSDEFINITIONID;

	SELECT ID_ INTO V_REJECTNODE
	FROM JBPM_NODE WHERE NAME_='RejectedPartReturn' AND PROCESSDEFINITION_=V_PROCESSDEFINITIONID;

	SELECT ID_ INTO V_APPEALNODE
	FROM JBPM_NODE WHERE NAME_='ProcessAppeal' AND PROCESSDEFINITION_=V_PROCESSDEFINITIONID;

	SELECT ID_ INTO V_HOLDPARTNODE
	FROM JBPM_NODE WHERE NAME_='OnHoldForPartReturn' AND PROCESSDEFINITION_=V_PROCESSDEFINITIONID;

	SELECT ID_ INTO V_HOLDNODE
	FROM JBPM_NODE WHERE NAME_='OnHold' AND PROCESSDEFINITION_=V_PROCESSDEFINITIONID;

	SELECT ID_ INTO V_WAITNODE
	FROM JBPM_NODE WHERE NAME_='WaitForPartReturnsCompletion' AND PROCESSDEFINITION_=V_PROCESSDEFINITIONID;

	SELECT ID_ INTO V_TRANSFERNODE
	FROM JBPM_NODE WHERE NAME_='Transferred' AND PROCESSDEFINITION_=V_PROCESSDEFINITIONID;

	SELECT ID_ INTO V_REPLIESNODE
	FROM JBPM_NODE WHERE NAME_='Replies' AND PROCESSDEFINITION_=V_PROCESSDEFINITIONID;

	SELECT ID_ INTO V_CLOSENODE
	FROM JBPM_NODE WHERE NAME_='Close' AND PROCESSDEFINITION_=V_PROCESSDEFINITIONID;
         
         
         -- ADDING NEW TRANSITION(MOVE TO NEW INBOX)
	INSERT INTO JBPM_TRANSITION (ID_,NAME_,PROCESSDEFINITION_,FROM_,TO_,FROMINDEX_)
	VALUES (V_OTHERTRANS1,'MoveToShippedNotReceivedInbox',V_PROCESSDEFINITIONID,V_PROREVNODE,V_JBPMNODEID,
	(SELECT MAX(FROMINDEX_)+1 FROM JBPM_TRANSITION WHERE FROM_=V_PROREVNODE));	

	INSERT INTO JBPM_TRANSITION  (ID_,NAME_,PROCESSDEFINITION_,FROM_,TO_,FROMINDEX_)
	VALUES (V_OTHERTRANS2,'MoveToShippedNotReceivedInbox',V_PROCESSDEFINITIONID,V_REJECTNODE,V_JBPMNODEID,
	(SELECT MAX(FROMINDEX_)+1 FROM JBPM_TRANSITION WHERE FROM_=V_REJECTNODE));

	INSERT INTO JBPM_TRANSITION  (ID_,NAME_,PROCESSDEFINITION_,FROM_,TO_,FROMINDEX_)
	VALUES (V_OTHERTRANS3,'MoveToShippedNotReceivedInbox',V_PROCESSDEFINITIONID,V_APPEALNODE,V_JBPMNODEID,
	(SELECT MAX(FROMINDEX_)+1 FROM JBPM_TRANSITION WHERE FROM_=V_APPEALNODE));

	INSERT INTO JBPM_TRANSITION  (ID_,NAME_,PROCESSDEFINITION_,FROM_,TO_,FROMINDEX_)
	VALUES (V_OTHERTRANS4,'MoveToShippedNotReceivedInbox',V_PROCESSDEFINITIONID,V_HOLDNODE,V_JBPMNODEID,
	(SELECT MAX(FROMINDEX_)+1 FROM JBPM_TRANSITION WHERE FROM_=V_HOLDNODE));

	INSERT INTO JBPM_TRANSITION (ID_,NAME_,PROCESSDEFINITION_,FROM_,TO_,FROMINDEX_)
	VALUES (V_OTHERTRANS5,'MoveToShippedNotReceivedInbox',V_PROCESSDEFINITIONID,V_HOLDPARTNODE,V_JBPMNODEID,
	(SELECT MAX(FROMINDEX_)+1 FROM JBPM_TRANSITION WHERE FROM_=V_HOLDPARTNODE));

	INSERT INTO JBPM_TRANSITION  (ID_,NAME_,PROCESSDEFINITION_,FROM_,TO_,FROMINDEX_)
	VALUES (V_OTHERTRANS6,'MoveToShippedNotReceivedInbox',V_PROCESSDEFINITIONID,V_REPLIESNODE,V_JBPMNODEID,
	(SELECT MAX(FROMINDEX_)+1 FROM JBPM_TRANSITION WHERE FROM_=V_REPLIESNODE));

	INSERT INTO JBPM_TRANSITION (ID_,NAME_,PROCESSDEFINITION_,FROM_,TO_,FROMINDEX_)
	VALUES (V_OTHERTRANS7,'MoveToShippedNotReceivedInbox',V_PROCESSDEFINITIONID,V_TRANSFERNODE,V_JBPMNODEID,
	(SELECT MAX(FROMINDEX_)+1 FROM JBPM_TRANSITION WHERE FROM_=V_TRANSFERNODE));

	INSERT INTO JBPM_TRANSITION (ID_,NAME_,PROCESSDEFINITION_,FROM_,TO_,FROMINDEX_)
	VALUES (V_OTHERTRANS8,'MoveToShippedNotReceivedInbox',V_PROCESSDEFINITIONID,V_CLOSENODE,V_JBPMNODEID,
	(SELECT MAX(FROMINDEX_)+1 FROM JBPM_TRANSITION WHERE FROM_=V_CLOSENODE));

	INSERT INTO JBPM_TRANSITION (ID_,NAME_,PROCESSDEFINITION_,FROM_,TO_,FROMINDEX_)
	VALUES (V_OTHERTRANS9,'MoveToShippedNotReceivedInbox',V_PROCESSDEFINITIONID,V_WAITNODE,V_JBPMNODEID,
	(SELECT MAX(FROMINDEX_)+1 FROM JBPM_TRANSITION WHERE FROM_=V_WAITNODE));
	
	  -- ADDING NEW TRANSITION(DENY FLOW)
		INSERT INTO JBPM_TRANSITION (ID_,NAME_,PROCESSDEFINITION_,FROM_,TO_,FROMINDEX_)
		VALUES (V_DENYTRANS,'Deny',V_PROCESSDEFINITIONID,V_WAITNODE,V_DENYNODE,
		(SELECT MAX(FROMINDEX_)+1 FROM JBPM_TRANSITION WHERE FROM_=V_WAITNODE));
		
		INSERT INTO JBPM_EVENT (ID_,EVENTTYPE_,TYPE_,GRAPHELEMENT_,TRANSITION_) VALUES 
		             	(HIBERNATE_SEQUENCE.NEXTVAL,
             	'transition','T',V_DENYTRANS,V_DENYTRANS);
		
		
		INSERT INTO JBPM_ACTION (ID_,CLASS,ISPROPAGATIONALLOWED_,ISASYNC_,EVENT_,EVENTINDEX_,EXPRESSION_)
		             	VALUES (HIBERNATE_SEQUENCE.NEXTVAL,
		             	'S',1,0,(SELECT ID_ FROM JBPM_EVENT WHERE TRANSITION_ =V_DENYTRANS),0,
          	'isClaimDenied = true; claim.setState(tavant.twms.domain.claim.ClaimState.DENIED);');
          	
		
END;
/
BEGIN
PROC_PRTSHPNTRCVAFTRANS();
END;
/
COMMIT
/