-- Creating huss part replaced installed configurations for campaigns
-- Author Prashanth konda
-- April 8 2009

CREATE TABLE HUSS_PARTS_TO_REPLACE ( ID NUMBER(19),FOR_CAMPAIGN NUMBER(19),CONSTRAINT  HUSS_PARTS_TO_REPLACE_PK  PRIMARY KEY(ID))
/
CREATE SEQUENCE  "HUSS_PARTS_TO_REPLACE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 100 NOCACHE  NOORDER  NOCYCLE
/
ALTER TABLE OEM_PART_TO_REPLACE ADD FOR_HUSS_PARTS_TO_REPLACE NUMBER(19)
/
ALTER TABLE OEM_PART_TO_REPLACE ADD FOR_HUSS_PARTS_TO_INSTALL NUMBER(19)
/
ALTER TABLE NON_OEM_PART_TO_REPLACE ADD FOR_HUSS_PARTS_TO_REPLACE NUMBER(19)
/
ALTER TABLE OEM_PART_TO_REPLACE ADD CONSTRAINT OEM_PRT_RPLC_HUSS_PRT_RPLC_FK
FOREIGN KEY (FOR_HUSS_PARTS_TO_REPLACE)  REFERENCES HUSS_PARTS_TO_REPLACE (ID) ENABLE  VALIDATE
/
ALTER TABLE OEM_PART_TO_REPLACE ADD CONSTRAINT OEM_PRT_RPLC_HUSS_PRT_INST_FK
FOREIGN KEY (FOR_HUSS_PARTS_TO_INSTALL)  REFERENCES HUSS_PARTS_TO_REPLACE (ID) ENABLE  VALIDATE
/
ALTER TABLE NON_OEM_PART_TO_REPLACE ADD CONSTRAINT NOEM_PRT_RPlC_HUSS_PRT_RPLC_FK
FOREIGN KEY (FOR_HUSS_PARTS_TO_REPLACE)  REFERENCES HUSS_PARTS_TO_REPLACE (ID) ENABLE  VALIDATE
/
ALTER TABLE HUSS_PARTS_TO_REPLACE ADD CONSTRAINT HUSS_PRT_RPLC_CAMPAIGN_FK
FOREIGN KEY (FOR_CAMPAIGN)  REFERENCES CAMPAIGN (ID) ENABLE  VALIDATE
/
ALTER TABLE INSTALLED_PARTS ADD (  SHIPPED_BY_OEM NUMBER(1)  DEFAULT 0)
/
ALTER TABLE OEM_PART_TO_REPLACE ADD (IS_HUSS_PART_INSTALLED NUMBER(1))
/
UPDATE OEM_PART_TO_REPLACE SET IS_HUSS_PART_INSTALLED = 0
/
COMMIT
/