--PURPOSE    : PATCH FOR ADDING NEW COLUMNS IN LINE ITEM GROUP AUDIT
--AUTHOR     : PRADYOT ROUT
--CREATED ON : 28-FEB-09

ALTER TABLE LINE_ITEM_GROUP_AUDIT ADD PERCENTAGE_ACCEPTANCE_FOR_WNTY NUMBER(19,2)
/
ALTER TABLE LINE_ITEM_GROUP_AUDIT ADD ACCEPTED_AMT_FOR_WNTY NUMBER(19,2)
/
ALTER TABLE LINE_ITEM_GROUP_AUDIT ADD ACCEPTED_CURR_FOR_WNTY VARCHAR2(255 CHAR)
/
ALTER TABLE  LINE_ITEM_GROUP_AUDIT DROP COLUMN GROUPTOTAL_AMT_CP
/
ALTER TABLE  LINE_ITEM_GROUP_AUDIT DROP COLUMN GROUPTOTAL_CURR_CP
/
ALTER TABLE  LINE_ITEM_GROUP_AUDIT DROP COLUMN BASE_AMT_CP
/
ALTER TABLE  LINE_ITEM_GROUP_AUDIT DROP COLUMN BASE_CURR_CP
/
COMMIT
/