--Purpose    : Creation of a new table MISC_ITEM_RATE to store amount and currency in a Misc item configuration
--Author     : Jitesh Jain
--Created On : 28-Mar-09

CREATE TABLE MISC_ITEM_RATE
(
  ID NUMBER(19, 0) NOT NULL,
  AMOUNT NUMBER(19, 0),
  CURRENCY VARCHAR2(255),
  MISC_ITEM_CONFIG NUMBER(19, 0) NOT NULL
, CONSTRAINT MISC_ITEM_RATE_PK PRIMARY KEY( ID)
)
/
ALTER TABLE MISC_ITEM_RATE
ADD CONSTRAINT MISC_ITEM_RATE_MISC_ITEM__FK1 FOREIGN KEY
(MISC_ITEM_CONFIG)
REFERENCES MISC_ITEM_CONFIG(ID) 
/
CREATE SEQUENCE MISC_ITEM_RATE_SEQ INCREMENT BY 1 START WITH 1000 
/
alter table "MISC_ITEM_CONFIG" drop column "COST_PRICE_CURR"
/
alter table "MISC_ITEM_CONFIG" drop column "COST_PRICE_AMT"
/
COMMIT
/