--Purpose    : Modification of Marketing_Information(Change of FK) and Competitor_Model(Change of PK) tables for static i18n purpose
--Author     : shraddha.nanda
--Created On : 22-Aug-08

CREATE SEQUENCE COMPETITOR_MODEL_SEQ
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
/
ALTER TABLE marketing_information
DROP CONSTRAINT  MARKETINGINFO_MODEL_FK
/
ALTER TABLE COMPETITOR_MODEL
drop primary key
/
ALTER TABLE COMPETITOR_MODEL ADD(ID Number(19))
/
update COMPETITOR_MODEL set ID= COMPETITOR_MODEL_SEQ.nextval
/
ALTER TABLE COMPETITOR_MODEL ADD( CONSTRAINT COMPETITOR_MODEL_ID_PK PRIMARY KEY(ID))
/
declare
CURSOR GET_compModel  IS
select * from MARKETING_INFORMATION WHERE COMPETITOR_MODEL IS NOT NULL;

v_compModel number:=0;
v_compModelPrev varchar(255) ;

BEGIN
FOR GET_REC IN GET_compModel LOOP
	select id into 	v_compModel from COMPETITOR_MODEL where MODEL=GET_REC.COMPETITOR_MODEL;
	update MARKETING_INFORMATION set COMPETITOR_MODEL=v_compModel where id=GET_REC.id;
END LOOP;
END;

/
CREATE TABLE DUMMY_MARKETING_INFORMATION (ID NUMBER(19), COMPETITOR_MODEL VARCHAR2(255))
/
declare
CURSOR GET_transType  IS
select * from MARKETING_INFORMATION ;
BEGIN
FOR GET_REC IN GET_transType LOOP
	INSERT INTO DUMMY_MARKETING_INFORMATION (ID,COMPETITOR_MODEL) 
values (GET_REC.ID ,GET_REC.COMPETITOR_MODEL );
	END LOOP;
END;
/
Update MARKETING_INFORMATION set COMPETITOR_MODEL=null
/
ALTER TABLE MARKETING_INFORMATION DROP COLUMN COMPETITOR_MODEL 
/
ALTER TABLE MARKETING_INFORMATION ADD COMPETITOR_MODEL NUMBER(19)
/
ALTER TABLE MARKETING_INFORMATION ADD CONSTRAINT MARKETINGINFO_MODEL_FK 
FOREIGN KEY(COMPETITOR_MODEL) REFERENCES COMPETITOR_MODEL(ID)
/
declare
CURSOR GET_compModel  IS
select * from DUMMY_MARKETING_INFORMATION WHERE COMPETITOR_MODEL IS NOT NULL;

BEGIN
FOR GET_REC IN GET_compModel LOOP
	update MARKETING_INFORMATION set COMPETITOR_MODEL=GET_REC.COMPETITOR_MODEL where id=GET_REC.id;
	END LOOP;
END;
/
drop table DUMMY_MARKETING_INFORMATION
/
COMMIT
/