CREATE TABLE LINE_ITEM_GROUP_AUDIT (
ID NUMBER(19,0) NOT NULL, 
ACCEPTED_CP_AMT NUMBER(19,2), 
ACCEPTED_CP_CURR VARCHAR2(255 CHAR), 
ACCEPTED_AMT NUMBER(19,2) NOT NULL, 
ACCEPTED_CURR VARCHAR2(255 CHAR) NOT NULL, 
BASE_AMT NUMBER(19,2), 
BASE_CURR VARCHAR2(255 CHAR), 
D_CREATED_ON DATE, 
D_CREATED_TIME TIMESTAMP, 
D_INTERNAL_COMMENTS VARCHAR2(255 CHAR), 
D_UPDATED_ON DATE, 
D_UPDATED_TIME TIMESTAMP, 
DISBURSED_AMT NUMBER(19,2), 
DISBURSED_CURR VARCHAR2(255 CHAR), 
GROUPTOTAL_AMT NUMBER(19,2), 
GROUPTOTAL_CURR VARCHAR2(255 CHAR), 
MODIFIER_AMT NUMBER(19,2), 
MODIFIER_CURR VARCHAR2(255 CHAR), 
PERCENTAGE_ACCEPTANCE NUMBER(19,2),
PRORATED_AMT NUMBER(19,2), 
PRORATED_CURR VARCHAR2(255 CHAR), 
VERSION NUMBER(10,0) NOT NULL, 
D_LAST_UPDATED_BY NUMBER(19,0), 
FOR_LINE_ITEM_GRP NUMBER(19,0) NOT NULL, 
LIST_INDEX NUMBER(10,0) NOT NULL, 
CONSTRAINT LINE_ITEM_GROUP_AUDIT_PK  PRIMARY KEY (ID))
/
CREATE TABLE MODIFIERS (
LINE_ITEM_GROUP_AUDIT NUMBER(19,0) NOT NULL, 
MODIFIERS NUMBER(19,0) NOT NULL, UNIQUE (MODIFIERS))
/
ALTER TABLE LINE_ITEM_GROUP_AUDIT ADD CONSTRAINT LINE_AUDIT_ITEM_GROUP_FK FOREIGN KEY (FOR_LINE_ITEM_GRP) REFERENCES LINE_ITEM_GROUP
/
ALTER TABLE LINE_ITEM_GROUP_AUDIT ADD CONSTRAINT LINE_AUDIT_UPDATED_BY_FK FOREIGN KEY (D_LAST_UPDATED_BY) REFERENCES ORG_USER
/
ALTER TABLE MODIFIERS ADD CONSTRAINT MODIFIERS_LINE_ITE_FK FOREIGN KEY (MODIFIERS) REFERENCES LINE_ITEM
/
ALTER TABLE MODIFIERS ADD CONSTRAINT MODIFIERS_LINE_ITEM_AUDIT_FK FOREIGN KEY (LINE_ITEM_GROUP_AUDIT) REFERENCES LINE_ITEM_GROUP_AUDIT
/
CREATE SEQUENCE LINE_ITEM_GROUP_AUDIT_SEQ
  START WITH 1000
  INCREMENT BY 20
  MAXVALUE 999999999999999999999999999
  MINVALUE 1000
  NOCYCLE
  CACHE 20
  NOORDER
/
ALTER TABLE LINE_ITEM_GROUP_AUDIT ADD FOR_CLAIM_AUDIT NUMBER(19,0)
/
ALTER TABLE LINE_ITEM_GROUP_AUDIT ADD CONSTRAINT LINE_AUDIT_CLAIM_AUDIT_FK FOREIGN KEY (FOR_CLAIM_AUDIT) REFERENCES CLAIM_AUDIT
/
UPDATE JBPM_TRANSITION SET NAME_='goToEnd', FROM_= (SELECT ID_ FROM JBPM_NODE  WHERE NAME_='ComputePolicy') WHERE ID_= (SELECT ID_ FROM JBPM_TRANSITION WHERE FROM_=(SELECT ID_ FROM JBPM_NODE WHERE NAME_='ComputePayment'))
/
COMMIT
/
