--PURPOSE    : PATCH FOR MAKING CONTRACTS BU SPECIFIC
--AUTHOR     : Ramalakshmi P
--CREATED ON : 21-FEB-09

ALTER TABLE CONTRACT ADD BUSINESS_UNIT_INFO   VARCHAR2(255 CHAR)
/ 
ALTER TABLE CONTRACT ADD (CONSTRAINT WNTY_TASK_INST_BU_FK FOREIGN KEY (BUSINESS_UNIT_INFO) REFERENCES BUSINESS_UNIT (NAME))
/
COMMIT
/
