--Purpose    : PATCH FOR CHANGING HOURS_IN_SERVICE COLUMN TYPE IN CLAIMED_ITEM TABLE
--Author     : NEELAM
--Created On : 1-APRIL-09

ALTER TABLE CLAIMED_ITEM MODIFY HOURS_IN_SERVICE NUMBER
/
COMMIT
/
