--Purpose    : Modification of Marketing_Information(Change of FK) and Competition_Type(Change of PK) tables for static i18n purpose
--Author     : shraddha.nanda
--Created On : 22-Aug-08

--Purpose    : Modification of Marketing_Information(Change of FK) and Competition_Type(Change of PK) tables for static i18n purpose
--Author     : shraddha.nanda
--Created On : 22-Aug-08

ALTER TABLE marketing_information
DROP CONSTRAINT MKTINGINFO_COMPETITIONTYPE_FK 
/
ALTER TABLE COMPETITION_TYPE
DROP PRIMARY KEY
/
ALTER TABLE COMPETITION_TYPE ADD(ID NUMBER(19))
/
CREATE SEQUENCE COMPETITION_TYPE_SEQ
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
/
UPDATE COMPETITION_TYPE SET ID= COMPETITION_TYPE_SEQ.NEXTVAL
/
ALTER TABLE COMPETITION_TYPE ADD(CONSTRAINT COMPETITION_TYPE_ID_PK PRIMARY KEY(ID))
/
DECLARE
CURSOR GET_compType  IS
SELECT * FROM MARKETING_INFORMATION WHERE COMPETITION_TYPE IS NOT NULL;

v_compType NUMBER:=0;

BEGIN
FOR GET_REC IN GET_compType LOOP
	SELECT id INTO 	v_compType FROM COMPETITION_TYPE WHERE TYPE=GET_REC.COMPETITION_TYPE;
	UPDATE MARKETING_INFORMATION SET COMPETITION_TYPE=v_compType WHERE id=GET_REC.id;
END LOOP;
END;
/
CREATE TABLE DUMMY_MARKETING_INFORMATION (ID NUMBER(19), COMPETITION_TYPE VARCHAR2(255))
/
DECLARE
CURSOR GET_transType  IS
SELECT * FROM MARKETING_INFORMATION ;
BEGIN
FOR GET_REC IN GET_transType LOOP
	INSERT INTO DUMMY_MARKETING_INFORMATION (ID,COMPETITION_TYPE) 
VALUES (GET_REC.ID ,GET_REC.COMPETITION_TYPE );
	END LOOP;
END;
/
UPDATE MARKETING_INFORMATION SET COMPETITION_TYPE=NULL
/
ALTER TABLE MARKETING_INFORMATION DROP COLUMN COMPETITION_TYPE 
/
ALTER TABLE MARKETING_INFORMATION ADD COMPETITION_TYPE NUMBER(19)
/

ALTER TABLE MARKETING_INFORMATION ADD CONSTRAINT MKTINGINFO_COMPETITIONTYPE_FK 
FOREIGN KEY(COMPETITION_TYPE) REFERENCES COMPETITION_TYPE(ID)
/
DECLARE

CURSOR GET_COMPETITIONTYPE  IS
SELECT * FROM DUMMY_MARKETING_INFORMATION WHERE COMPETITION_TYPE IS NOT NULL;

BEGIN
FOR GET_REC IN GET_COMPETITIONTYPE LOOP
	UPDATE MARKETING_INFORMATION SET COMPETITION_TYPE=GET_REC.COMPETITION_TYPE WHERE id=GET_REC.id;
	END LOOP;
END;
/
DROP TABLE DUMMY_MARKETING_INFORMATION
/ 
COMMIT
/