--Purpose: For creating a Foreign Key BU_ORG_MAPPING table and BUSINESS_UNIT,ORGANIZATION
--Author: Shraddha Nanda P 
--Created On: Date 12 Sept 2008

ALTER TABLE BU_ORG_MAPPING ADD (
CONSTRAINT BU_ORG_MAPPING_BU_FK 
FOREIGN KEY (BU) 
REFERENCES BUSINESS_UNIT (NAME))
/
ALTER TABLE BU_ORG_MAPPING ADD (
CONSTRAINT BU_ORG_MAPPING_ORGANIZATION_FK
FOREIGN KEY (ORG)
REFERENCES ORGANIZATION(ID))
/