--PURPOSE    : PATCH TO UPDATE TOTAL CREDIT AMOUNT IN LINE ITEM GROUP AUDIT TABLE
--AUTHOR     : HARIKRISHNA.YD
--CREATED ON : 18-MAR-09

ALTER TABLE line_item_group_audit ADD(total_credit_amount NUMBER(19,2),total_credit_curr VARCHAR2(255))
/
COMMIT
/