--Purpose    : Updated and created new table for User Availability
--Author     : Jhulfikar Ali. A
--Created On : 02-Feb-09

CREATE TABLE USER_BU_AVAILABLITY (
  ID NUMBER NOT NULL,
  ORG_USER NUMBER,
  BUSINESS_UNIT_INFO VARCHAR2(255),
  AVAILABLE NUMBER(1), 
  CONSTRAINT USER_BU_AVAILABLITY_PK PRIMARY KEY(ID)
)
/
ALTER TABLE USER_BU_AVAILABLITY
ADD CONSTRAINT USER_BU_AVAILABLITY_USER_FK FOREIGN KEY(ORG_USER)
REFERENCES ORG_USER(ID)
/
CREATE TABLE USER_DEFAULT_ROLES (
  USER_BU_AVAILABLITY NUMBER,
  DEFAULT_ROLE NUMBER
)
/
ALTER TABLE USER_DEFAULT_ROLES
ADD CONSTRAINT USER_DEFAULT_ROLES_ROLE_FK FOREIGN KEY(DEFAULT_ROLE)
REFERENCES ROLE(ID)
/
CREATE SEQUENCE USER_BU_AVAILABILITY_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 
INCREMENT BY 20 START WITH 5800 
CACHE 20 NOORDER  NOCYCLE
/
ALTER TABLE ORG_USER DROP COLUMN AVAILABLE
/
ALTER TABLE ORG_USER DROP COLUMN DEFAULT_USER
/
COMMIT
/