-- FOC claim data to be stored in tavant system
-- Author Prashanth Konda
-- Date 16th Jan 2009

CREATE TABLE FOC_ORDER_DETAILS (ID NUMBER(19) NOT NULL,ORDER_NO VARCHAR2(255),ORDER_INFO CLOB,CLAIM_INFO CLOB,STATUS VARCHAR2(50),D_CREATED_BY NUMBER, D_LAST_UPDATED_BY NUMBER,D_CREATED_ON DATE,D_UPDATED_ON DATE,D_INTERNAL_COMMENTS VARCHAR2(255),D_CREATED_TIME TIMESTAMP, D_UPDATED_TIME TIMESTAMP,D_ACTIVE NUMBER(1),CONSTRAINT  FOC_ORDER_DETAILS_PK  PRIMARY KEY(ID))
/
ALTER TABLE  FOC_ORDER_DETAILS ADD UNIQUE(ORDER_NO)
/
CREATE SEQUENCE  "FOC_ORDER_DETAILS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 100 NOCACHE  NOORDER  NOCYCLE 
/
INSERT  INTO org_user(ID,EMAIL,LOCALE,PASSWORD,VERSION,BELONGS_TO_ORGANIZATION,FIRST_NAME,LAST_NAME,LOGIN,D_CREATED_ON,D_INTERNAL_COMMENTS,ORG_LOCALE,D_ACTIVE)
values (66,'FocUser@Hussmann.com','en_us','tavant123',1,(select id from party where name = 'OEM'),'focuser','focuser','focuser',sysdate,'For FOC Requirement','en_us',1)
/
insert into user_roles values ((select id from org_user where login = 'focuser'), (select id from role where name ='system') )
/
insert into bu_user_mapping values ((select id from org_user where login = 'focuser'),'Hussmann')
/
ALTER TABLE CLAIM ADD  (FOC NUMBER(1) DEFAULT 0)
/
ALTER TABLE CLAIM ADD (FOC_ORDER_NO VARCHAR2(255) )
/
ALTER TABLE INSTALLED_PARTS ADD  (READ_ONLY NUMBER(1) DEFAULT 0)
/
ALTER TABLE NON_OEM_PART_REPLACED ADD  (READ_ONLY NUMBER(1) DEFAULT 0)
/
ALTER TABLE OEM_PART_REPLACED ADD  (READ_ONLY NUMBER(1) DEFAULT 0)
/
ALTER TABLE ORG_USER ADD  (VIEW_FOC_CLAIMS NUMBER(1) DEFAULT 0)
/
COMMIT
/