--Purpose: For including customer type in  evaluating relevance  score for payment modifiers
--Author: Prashanth 
--Created On: Date 11 Sep 2008

ALTER TABLE PAYMENT_MODIFIER ADD (CUSTOMER_TYPE VARCHAR2(50))
/
UPDATE PAYMENT_MODIFIER SET CUSTOMER_TYPE = 'ALL'
/
INSERT INTO CRITERIA_EVALUATION_PRECEDENCE(ID, FOR_DATA, VERSION) VALUES ( (SELECT MAX(ID) + 1 FROM CRITERIA_EVALUATION_PRECEDENCE),'PAYMENT MODIFIER WEIGHTS',0)
/
INSERT INTO EVAL_PRECEDENCE_PROPERTIES  VALUES ((SELECT MAX(ID) FROM CRITERIA_EVALUATION_PRECEDENCE),NULL,'forCriteria.dealerCriterion.dealer',0)
/
INSERT INTO EVAL_PRECEDENCE_PROPERTIES  VALUES ((SELECT MAX(ID) FROM CRITERIA_EVALUATION_PRECEDENCE),NULL,'forCriteria.dealerCriterion.dealerGroup',1)
/
INSERT INTO EVAL_PRECEDENCE_PROPERTIES  VALUES ((SELECT MAX(ID) FROM CRITERIA_EVALUATION_PRECEDENCE),NULL,'forCriteria.claimType',2)
/
INSERT INTO EVAL_PRECEDENCE_PROPERTIES  VALUES ((SELECT MAX(ID) FROM CRITERIA_EVALUATION_PRECEDENCE),NULL,'forCriteria.warrantyType',3)
/
INSERT INTO EVAL_PRECEDENCE_PROPERTIES  VALUES ((SELECT MAX(ID) FROM CRITERIA_EVALUATION_PRECEDENCE),NULL,'forCriteria.productType',4)
/
INSERT INTO EVAL_PRECEDENCE_PROPERTIES  VALUES ((SELECT MAX(ID) FROM CRITERIA_EVALUATION_PRECEDENCE),NULL,'customerType',5)
/
COMMIT
/