-- Renaming active as status in Domain Rule
-- Author :Prashanth
-- Date : November 19 th 2008

ALTER TABLE DOMAIN_RULE ADD (STATUS VARCHAR2(30))
/
ALTER TABLE DOMAIN_RULE_AUDIT ADD (STATUS VARCHAR2(30))
/
UPDATE DOMAIN_RULE SET STATUS='ACTIVE' 
/
UPDATE DOMAIN_RULE_AUDIT SET STATUS='ACTIVE' 
/
COMMIT
/
