--Patch for UOM mappings
--Monday nov 24th 2008
--author : Prashanth Konda
CREATE TABLE UOM_MAPPINGS ( ID NUMBER, BASE_UOM VARCHAR2(50 BYTE), MAPPED_UOM VARCHAR2(50 BYTE), MAPPING_FRACTION NUMBER NOT NULL, VERSION NUMBER ,BUSINESS_UNIT_INFO VARCHAR2(255),D_CREATED_BY NUMBER, D_LAST_UPDATED_BY NUMBER,
D_CREATED_ON DATE,D_UPDATED_ON DATE,D_INTERNAL_COMMENTS VARCHAR2(20),D_CREATED_TIME TIMESTAMP, D_UPDATED_TIME TIMESTAMP,
CONSTRAINT UOM_MAPPINGS_PK PRIMARY KEY (ID)) LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/
ALTER TABLE UOM_MAPPINGS ADD CONSTRAINT UOM_MAP_LAST_UPTD_BY_USER_FK
FOREIGN KEY (D_LAST_UPDATED_BY)  REFERENCES ORG_USER (ID) ENABLE  VALIDATE
/
CREATE SEQUENCE UOM_MAPPINGS_SEQ START WITH 1000 INCREMENT BY 20  MINVALUE 0 MAXVALUE 999999999999999999999999999 NOCACHE NOCYCLE NOORDER 
/
CREATE TABLE I18N_UOM_MAPPING_VALUES ( ID NUMBER, UOM_MAPPING_ID NUMBER, LOCALE VARCHAR2(50), MAPPED_UOM VARCHAR2(50), CONSTRAINT I18N_UOM_MAPPING_VALUES_PK  PRIMARY KEY(ID)) LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/
CREATE SEQUENCE I18N_UOM_MAPPING_VALUES_SEQ START WITH 1000 INCREMENT BY 20  MINVALUE 0 MAXVALUE 999999999999999999999999999 NOCACHE NOCYCLE NOORDER 
/
ALTER TABLE I18N_UOM_MAPPING_VALUES ADD CONSTRAINT I18N_UOM_MAPPING_VALUES_UOM_FK FOREIGN KEY (UOM_MAPPING_ID) REFERENCES UOM_MAPPINGS(ID) ENABLE VALIDATE
/
ALTER TABLE UOM_MAPPINGS ADD(D_ACTIVE NUMBER(1))
/
COMMIT
/