--Purpose    : PATCH FOR MAKING THE ACCEPTED AMOUNT AND TOTAL AMOUNT FIELD NULLABLE
--Author     : pradyot.rout
--Created On : 10-FEB-08

ALTER TABLE LINE_ITEM_GROUP MODIFY (ACCEPTED_AMT NULL)
/
ALTER TABLE LINE_ITEM_GROUP MODIFY (ACCEPTED_CURR NULL)
/
ALTER TABLE LINE_ITEM_GROUP MODIFY (TOTAL_AMT NULL)
/
ALTER TABLE LINE_ITEM_GROUP MODIFY (TOTAL_CURR NULL)
/
COMMIT
/

 
