-- Patch for address book functionality for Non Serialized Claims
-- Author: Ramalakshmi P
-- Jun 4 2009

ALTER TABLE CLAIM ADD(OWNER_INFORMATION NUMBER)
/
ALTER TABLE CLAIM ADD CONSTRAINT CLAIM_OWNER_INFO_FK 
FOREIGN KEY (OWNER_INFORMATION) REFERENCES ADDRESS(ID) ENABLE VALIDATE
/