-- Patch for PurchaseExtendedWarranty pricecheck BU configured
-- 25th March 2009
-- Author: Manoj.Katare
INSERT INTO CONFIG_PARAM (ID, DESCRIPTION, DISPLAY_NAME, NAME, TYPE, PARAM_DISPLAY_TYPE,D_ACTIVE) VALUES ((SELECT MAX(ID)+1 FROM CONFIG_PARAM), 'Allowed Extended Warranty Price Check Enabled or Disable', 'Extended Warranty Price Check Enabled','extWarrantyPriceCheckEnabled','boolean','radio',1)
/
INSERT INTO CONFIG_PARAM_OPTIONS_MAPPING (ID, PARAM_ID, OPTION_ID)  VALUES ((select max(id)+1 from config_param_options_mapping),(SELECT ID FROM CONFIG_PARAM WHERE NAME = 'extWarrantyPriceCheckEnabled'),(SELECT ID FROM CONFIG_PARAM_OPTION WHERE VALUE = 'true'))
/
INSERT INTO CONFIG_PARAM_OPTIONS_MAPPING  (ID, PARAM_ID, OPTION_ID) VALUES ((select max(id)+1 from config_param_options_mapping),(SELECT ID FROM CONFIG_PARAM WHERE NAME = 'extWarrantyPriceCheckEnabled'),(SELECT ID FROM CONFIG_PARAM_OPTION WHERE VALUE = 'false'))
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, 
D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, NULL, (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'extWarrantyPriceCheckEnabled'),
TO_DATE('03/28/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, TO_DATE('03/28/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'Transport Solutions ESA', NULL, NULL,(select id from config_param_option where value='false'),1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, 
D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, NULL, (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'extWarrantyPriceCheckEnabled'),
TO_DATE('03/28/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, TO_DATE('03/28/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'AIR', NULL, NULL,(select id from config_param_option where value='false'),1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, 
D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, NULL, (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'extWarrantyPriceCheckEnabled'),
TO_DATE('03/28/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, TO_DATE('03/28/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'TFM', NULL, NULL,(select id from config_param_option where value='false'),1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, 
D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, NULL, (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'extWarrantyPriceCheckEnabled'),
TO_DATE('03/28/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, TO_DATE('03/28/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'Hussmann', NULL, NULL,(select id from config_param_option where value='false'),1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, 
D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, NULL, (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'extWarrantyPriceCheckEnabled'),
TO_DATE('03/28/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, TO_DATE('03/28/2009 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'Clubcar ESA', NULL, NULL,(select id from config_param_option where value='false'),1)
/
COMMIT
/