--Purpose: UI for updating BU Parameters
--Author: Prashanth 
--Created On: Date 18 Sep 2008



CREATE TABLE CONFIG_PARAM_OPTION ( 	ID 	NUMBER(20) 	NOT NULL,   	DISPLAY_VALUE VARCHAR2(50),   	VALUE 	VARCHAR2(50) , 	CONFIG_PARAM_ID NUMBER(20) NOT NULL,   	CONSTRAINT CONFIG_PARAM_OPTIONS_PK PRIMARY KEY (ID) )
/
ALTER TABLE CONFIG_PARAM ADD PARAM_DISPLAY_TYPE VARCHAR2(50)
/
ALTER TABLE CONFIG_PARAM ADD INTERNAL_COMMENTS VARCHAR2(50)
/
ALTER TABLE CONFIG_PARAM ADD INTERNAL_STATUS NUMBER(1)
/
ALTER TABLE CONFIG_PARAM ADD LOGICAL_GROUP VARCHAR2(20)
/
ALTER TABLE CONFIG_PARAM ADD LOGICAL_GROUP_ORDER NUMBER(20)
/
ALTER TABLE CONFIG_PARAM ADD SECTIONS VARCHAR2(50)
/
ALTER TABLE CONFIG_PARAM ADD SECTIONS_ORDER NUMBER(20)
/
ALTER TABLE CONFIG_PARAM ADD PARAM_ORDER NUMBER(20)
/
ALTER TABLE CONFIG_PARAM_OPTION ADD CONSTRAINT CFG_PRM_OPTN_CFG_PRM_ID_FK  FOREIGN KEY (CONFIG_PARAM_ID)  REFERENCES CONFIG_PARAM (ID) ENABLE VALIDATE
/
ALTER TABLE CONFIG_VALUE ADD (CONFIG_PARAM_OPTION NUMBER(20))
/
ALTER TABLE CONFIG_VALUE ADD CONSTRAINT CFG_VAL_CFG_PRM_OPT_ID_FK FOREIGN KEY (CONFIG_PARAM_OPTION)  REFERENCES CONFIG_PARAM_OPTION (ID) ENABLE  VALIDATE 
/
CREATE TABLE LOGICAL_GROUP
(
  ID           NUMBER(19)                       NOT NULL,
  DESCRIPTION  VARCHAR2(255 CHAR),
  NAME         VARCHAR2(255 CHAR),
  CONSTRAINT LOGICAL_GROUP_PK PRIMARY KEY (ID)
)
/
CREATE SEQUENCE  "Logical_Group_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 100 NOCACHE  NOORDER  NOCYCLE 
/
COMMIT
/
 