--PURPOSE    : PATCH TO INTRODUCE BUSINESS UNIT INFO
--AUTHOR     : HARIKRISHNA.YD
--CREATED ON : 10-JUL-08

ALTER TABLE DOMAIN_RULE ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE DOMAIN_PREDICATE ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE SERVICE_PROCEDURE_DEFINITION ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE FAULT_CODE_DEFINITION ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE CONFIG_VALUE ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE TRAVEL_RATES ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE LABOR_RATES ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE ITEM_PRICE_MODIFIER ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE ITEM_PRICE_CRITERIA ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE CLAIM ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE ITEM_SCHEME ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE ITEM_BASE_PRICE ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE ITEM_GROUP ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE ITEM ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE INVENTORY_ITEM ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE CAMPAIGN_CLASS ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE CAMPAIGN ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE BATTERY_TEST_SHEET ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE SMR_REASON ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE REJECTION_REASON ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE REC_CLM_REJECT_REASON ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE REC_CLM_ACCPT_REASON ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE PART_ACCEPTANCE_REASON ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE FAILURE_REASON ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE ACCOUNTABILITY_CODE ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE ACCEPTANCE_REASON ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE ADDITIONAL_ATTRIBUTES ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE ATTRIBUTE ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE CLAIM_NUMBER_PATTERN ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE LOCALIZED_MESSAGES ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE PART_RETURN_DEFINITION ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE PAYMENT_DEFINITION ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE PAYMENT_VARIABLE ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE POLICY_DEFINITION ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE POLICY_RATES ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE SUPPLIER ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE UPLOAD_HISTORY ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE USER_SCHEME ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
ALTER TABLE WAREHOUSE ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
CREATE SEQUENCE ACCEPTANCE_REASON_SEQ START WITH 1000 INCREMENT BY 20
/
CREATE SEQUENCE ACCOUNTABILITY_CODE_SEQ START WITH 1000 INCREMENT BY 20
/
CREATE SEQUENCE FAILURE_REASON_SEQ START WITH 1000 INCREMENT BY 20
/
CREATE SEQUENCE I18N_ITEM_TEXT_SEQ START WITH 1000 INCREMENT BY 20
/
CREATE SEQUENCE I18N_LOV_TEXT_SEQ START WITH 1000 INCREMENT BY 20
/
CREATE SEQUENCE MODEL_PROCESS_SEQ START WITH 1000 INCREMENT BY 20
/
CREATE SEQUENCE PART_ACCEPT_REASON_SEQ START WITH 1000 INCREMENT BY 20
/
CREATE SEQUENCE RECOVERY_CLM_ACCEPT_RSN_SEQ START WITH 1000 INCREMENT BY 20
/
CREATE SEQUENCE RECOVERY_CLM_REJECT_RSN_SEQ START WITH 1000 INCREMENT BY 20
/
CREATE SEQUENCE REJECTION_REASON_SEQ START WITH 1000 INCREMENT BY 20
/
CREATE SEQUENCE SECTION_SEQ START WITH 1000 INCREMENT BY 20
/
CREATE SEQUENCE SMR_REASON_SEQ START WITH 1000 INCREMENT BY 20
/
CREATE SEQUENCE LOGICAL_GROUP_SEQ START WITH 1000 INCREMENT BY 20
/
CREATE TABLE I18NITEM_TEXT (ID NUMBER(19,0) NOT NULL, LOCALE VARCHAR2(255 CHAR), DESCRIPTION VARCHAR2(255 CHAR), ITEM NUMBER(19,0) NOT NULL)
/
ALTER TABLE I18NITEM_TEXT ADD CONSTRAINT I18NITEM_TEXT_PK	PRIMARY KEY( 	ID	)
/
ALTER TABLE carrier ADD BUSINESS_UNIT_INFO VARCHAR2(255 CHAR)
/
COMMIT
/