--Purpose: UI for updating BU Parameters
--Author: Prashanth 
--Created On: Date 29 Sep 2008

CREATE TABLE CONFIG_PARAM_OPTIONS_MAPPING ( ID NUMBER(20) NOT NULL, PARAM_ID NUMBER(20) NOT NULL,OPTION_ID NUMBER(20) NOT NULL,	CONSTRAINT CONFIG_PARAM_OPTNS_MAPPING_PK PRIMARY KEY (ID) )
/
ALTER TABLE CONFIG_PARAM_OPTIONS_MAPPING ADD CONSTRAINT CFG_PARAM_MAP_CFG_PARAM_ID_FK  FOREIGN KEY (PARAM_ID)  REFERENCES CONFIG_PARAM (ID) ENABLE  VALIDATE
/
ALTER TABLE CONFIG_PARAM_OPTIONS_MAPPING ADD CONSTRAINT CFG_PARAM_MAP_CFG_OPTN_ID_FK  FOREIGN KEY (OPTION_ID)  REFERENCES CONFIG_PARAM_OPTION (ID) ENABLE VALIDATE
/
COMMIT
/