--PURPOSE    : PATCH FOR ADDING CONFIG PARAM FOR SPECIFYING NUMBER OF RESUBMITS ALLOWED ON A CLAIM
--AUTHOR     : JITESH JAIN
--CREATED ON : 1-APR-09

INSERT INTO CONFIG_PARAM
(ID, DESCRIPTION, DISPLAY_NAME, NAME, TYPE, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, D_CREATED_TIME, D_UPDATED_TIME, LOGICAL_GROUP, PARAM_DISPLAY_TYPE, LOGICAL_GROUP_ORDER, SECTIONS, SECTIONS_ORDER, PARAM_ORDER,d_active)
VALUES
(config_param_seq.NEXTVAL, 'Number of Claim Resubmits allowed to a Dealer', 'Number of Claim Resubmits allowed to a Dealer',
    'numberOfClaimResubmitAllowed','number', 
    TO_DATE('03/14/2008 15:38:14', 'MM/DD/YYYY HH24:MI:SS'), 'Configuration', TO_DATE('03/14/2008 15:38:14', 'MM/DD/YYYY HH24:MI:SS'), NULL, NULL, 
    NULL, NULL, 'textbox', NULL, NULL, 
    NULL, NULL,1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, 3, (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'numberOfClaimResubmitAllowed'),
TO_DATE('03/14/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, TO_DATE('03/14/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'Transport Solutions ESA', NULL, NULL,NULL,1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, 3, (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'numberOfClaimResubmitAllowed'),
TO_DATE('11/12/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, TO_DATE('11/12/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'Clubcar ESA', NULL, NULL,NULL,1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, 3, (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'numberOfClaimResubmitAllowed'),
TO_DATE('11/12/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, TO_DATE('11/12/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'Hussmann', NULL, NULL,NULL,1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, 3, (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'numberOfClaimResubmitAllowed'),
TO_DATE('11/12/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, TO_DATE('11/12/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'TFM', NULL, NULL,NULL,1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, 3, (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'numberOfClaimResubmitAllowed'),
TO_DATE('11/12/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, TO_DATE('11/12/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'AIR', NULL, NULL,NULL,1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, 3, (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'numberOfClaimResubmitAllowed'),
TO_DATE('11/12/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, TO_DATE('11/12/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'Club Car', NULL, NULL,NULL,1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, 3, (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'numberOfClaimResubmitAllowed'),
TO_DATE('11/12/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, TO_DATE('11/12/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 'TK', NULL, NULL,NULL,1)
/
COMMIT
/