--Purpose    : Patch to implement business unit info and label type
--Author     : Pradyot Rout
--Created On : 14-Nov-08

ALTER TABLE LABEL ADD TYPE VARCHAR(255)
/
ALTER TABLE LABEL ADD BUSINESS_UNIT_INFO VARCHAR(255)
/
ALTER TABLE label ADD CONSTRAINT LABEL_BUSINESS_UNIT_FK FOREIGN KEY (business_unit_info) REFERENCES BUSINESS_UNIT
/
COMMIT
/
DECLARE
CURSOR GET_INVENTORYITEM  IS
SELECT INVENTORY_ITEM,LABELS FROM INVENTORY_ITEM_LABELS;
BUSINESS_UNIT VARCHAR(255) ;
BEGIN
FOR GET_REC IN GET_INVENTORYITEM LOOP
SELECT BUSINESS_UNIT_INFO INTO BUSINESS_UNIT FROM INVENTORY_ITEM WHERE ID = GET_REC.INVENTORY_ITEM;
UPDATE LABEL SET BUSINESS_UNIT_INFO=BUSINESS_UNIT , TYPE='INVENTORY' WHERE NAME =GET_REC.LABELS;
END LOOP;
END;
/
COMMIT
/
DECLARE
CURSOR GET_POLICY  IS
SELECT POLICY_DEFINITION,LABELS FROM POLICY_DEFINITION_LABELS;
BUSINESS_UNIT VARCHAR(255) ;
BEGIN
FOR GET_REC IN GET_POLICY LOOP
SELECT BUSINESS_UNIT_INFO INTO BUSINESS_UNIT FROM POLICY_DEFINITION WHERE ID = GET_REC.POLICY_DEFINITION;
UPDATE LABEL SET BUSINESS_UNIT_INFO=BUSINESS_UNIT , TYPE='POLICY' WHERE NAME =GET_REC.LABELS;
END LOOP;
END;
/
COMMIT
/
DECLARE
CURSOR GET_FAULT_CODE  IS
SELECT FAULT_CODE_DEFINITION,LABELS FROM FAULT_CODE_DEFINITION_LABELS;
BUSINESS_UNIT VARCHAR(255) ;
BEGIN
FOR GET_REC IN GET_FAULT_CODE LOOP
SELECT BUSINESS_UNIT_INFO INTO BUSINESS_UNIT FROM FAULT_CODE_DEFINITION WHERE ID = GET_REC.FAULT_CODE_DEFINITION;
UPDATE LABEL SET BUSINESS_UNIT_INFO=BUSINESS_UNIT , TYPE='FAULTCODEDEFINITION' WHERE NAME =GET_REC.LABELS;
END LOOP;
END;
/
COMMIT
/
DECLARE
CURSOR GET_JOB_CODE  IS
SELECT SERVICE_PROCEDURE_DEFINITION,LABELS FROM SERVICE_PROCEDURE_DEF_LABELS;
BUSINESS_UNIT VARCHAR(255) ;
BEGIN
FOR GET_REC IN GET_JOB_CODE LOOP
SELECT BUSINESS_UNIT_INFO INTO BUSINESS_UNIT FROM SERVICE_PROCEDURE_DEFINITION WHERE ID = GET_REC.SERVICE_PROCEDURE_DEFINITION;
UPDATE LABEL SET BUSINESS_UNIT_INFO=BUSINESS_UNIT , TYPE='SERVICEPROCEDUREDEFINITION' WHERE NAME =GET_REC.LABELS;
END LOOP;
END;
/
COMMIT
/
DECLARE
CURSOR GET_SUPPLIER  IS
SELECT SUPPLIER,LABELS FROM SUPPLIER_LABELS;
BUSINESS_UNIT VARCHAR(255) ;
BEGIN
FOR GET_REC IN GET_SUPPLIER LOOP
SELECT BUSINESS_UNIT_INFO INTO BUSINESS_UNIT FROM SUPPLIER WHERE ID = GET_REC.SUPPLIER;
UPDATE LABEL SET BUSINESS_UNIT_INFO=BUSINESS_UNIT , TYPE='SUPPLIER' WHERE NAME =GET_REC.LABELS;
END LOOP;
END;
/
COMMIT
/