--Purpose    : Patch for creating Market table
--Author     : Pradyot Rout
--Created On : 20-Jun-09

CREATE TABLE MARKET
(
  ID                   NUMBER(19)               NOT NULL,
  VERSION              NUMBER(19),
  PARENT_ID            NUMBER(19),
  TYPE                 VARCHAR2(4000 BYTE),
  CODE                 VARCHAR2(4000 BYTE),
  D_CREATED_ON         DATE,
  D_CREATED_TIME       TIMESTAMP(6),
  D_INTERNAL_COMMENTS  VARCHAR2(255 CHAR),
  D_UPDATED_ON         DATE,
  D_UPDATED_TIME       TIMESTAMP(6),
  D_LAST_UPDATED_BY    NUMBER(19),
  D_ACTIVE             NUMBER(1),
  BUSINESS_UNIT_INFO   VARCHAR2(255 BYTE)
)
/
ALTER TABLE MARKET ADD (CONSTRAINT MARKET_PK PRIMARY KEY (ID))
/
ALTER TABLE MARKET ADD (CONSTRAINT MARKET_PARENT_FK  FOREIGN KEY (PARENT_ID)  REFERENCES MARKET (ID))
/
ALTER TABLE MARKET ADD (CONSTRAINT MARKET_UPDATED_FK FOREIGN KEY (D_LAST_UPDATED_BY) REFERENCES ORG_USER (ID))
/
ALTER TABLE MARKET ADD (CONSTRAINT BUSINESS_UNIT_INFO_FK FOREIGN KEY (BUSINESS_UNIT_INFO) REFERENCES BUSINESS_UNIT (NAME))
/
alter table marketing_information add (MARKET  NUMBER(19))
/
alter table marketing_information add (APPLICATION  NUMBER(19))
/
alter table  marketing_information add (ADDITIONAL_INFO VARCHAR2(255 BYTE))
/
ALTER TABLE MARKETING_INFORMATION ADD (
  CONSTRAINT MARKET_INFO_MARKET_FK 
 FOREIGN KEY (MARKET) 
 REFERENCES MARKET (ID))
/
ALTER TABLE MARKETING_INFORMATION ADD (
  CONSTRAINT MARKET_INFO_APPLICATION_FK 
 FOREIGN KEY (APPLICATION) 
 REFERENCES MARKET (ID))
/