-- Patch for changing from dealer to service provider
-- Author Prashanth konda
-- Date 19th january 2009

ALTER TABLE MISC_ITEM_CRITERIA ADD (SERVICE_PROVIDER NUMBER(19))
/
ALTER TABLE MISC_ITEM_CRITERIA ADD CONSTRAINT MISC_CRIT_SER_PROVIDER_FK FOREIGN KEY (SERVICE_PROVIDER) REFERENCES SERVICE_PROVIDER(ID) ENABLE VALIDATE 
/
ALTER TABLE MISC_ITEM_CRITERIA DROP CONSTRAINT MISC_ITEM_CRIT_DLR_ID_FK
/
ALTER TABLE MISC_ITEM_CRITERIA DROP COLUMN DEALER
/
ALTER TABLE MISC_ITEM_CONFIG DROP COLUMN MISC_ITEM
/
ALTER TABLE MISC_ITEM_CONFIG ADD (MISCELLANEOUS_ITEM NUMBER(19))
/
ALTER TABLE MISC_ITEM_CONFIG ADD CONSTRAINT MISC_ITEM_CFG_MISC_ITEM_ID_FK FOREIGN KEY (MISCELLANEOUS_ITEM) REFERENCES MISC_ITEM(ID) ENABLE VALIDATE
/
COMMIT
/
