--Purpose    : Index on i18n item table for performance fix
--Author     : Ramalakshmi P
--Created On : 30-JUL-09

CREATE INDEX  I18NITEM_TEXT_DESCLOC_IDX ON I18NITEM_TEXT (LOWER(DESCRIPTION), LOCALE, ITEM)
/
CREATE INDEX  ITEM_BUINFODACTIVEOWNEDBY_IDX ON ITEM (BUSINESS_UNIT_INFO, D_ACTIVE, OWNED_BY)
/
