--Purpose    : Introduce DCAP related tables and sequences
--Author     : rashmi.malik
--Created On : 13-Aug-08

--Split Type


CREATE TABLE SPLIT_TYPE
(
  ID       NUMBER(19)                           NOT NULL,
  NAME     VARCHAR2(250 BYTE),
  VERSION  NUMBER(10)                           NOT NULL
)
/



ALTER TABLE SPLIT_TYPE ADD (
  CONSTRAINT SPLIT_TYPE_PK
 PRIMARY KEY
 (ID)
)
/


CREATE SEQUENCE SPLIT_TYPE_SEQ
  START WITH 1000
  INCREMENT BY 20
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
/


--Model Category


CREATE TABLE MODEL_CATEGORY
(
  ID          NUMBER(19)          NOT NULL,
  MODEL_CODE  VARCHAR2(255 CHAR),
  version number(10)

)
/


ALTER TABLE MODEL_CATEGORY ADD (
  CONSTRAINT MODEL_CATEGORY_PK
 PRIMARY KEY
 (ID)
)
/


CREATE SEQUENCE MODEL_CATEGORY_SEQ
  START WITH 1000
  INCREMENT BY 20
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
/

--Inventory Dcap Detail


CREATE TABLE INVENTORY_DCAP_DETAIL
(
  ID                 NUMBER(19)                 NOT NULL,
  DCAP_ACCRUAL_CODE  VARCHAR2(255 CHAR),
  MODEL_CATEGORY     NUMBER(19),
  SCA_AMOUNT         NUMBER(19,2),
  SCA_CURR           VARCHAR2(255 CHAR),
  SCA_PAID_FLAG      NUMBER(1),
  SCA_PURGE_DATE     DATE,
  SCA_PURGE_FLAG     NUMBER(1),
  SEA_AMOUNT         NUMBER(19,2),
  SEA_CURR           VARCHAR2(255 CHAR),
  SEA_PAID_FLAG      NUMBER(1),
  SEA_PURGE_DATE     DATE,
  SEA_PURGE_FLAG     NUMBER(1),
  INVENTORY_ITEM     NUMBER(19),
  ACCRUAL_FLAG       NUMBER(1)
)
/


ALTER TABLE INVENTORY_DCAP_DETAIL ADD (
  CONSTRAINT INV_DCAP_DETAIL_PK
 PRIMARY KEY
 (ID)
)
/


ALTER TABLE INVENTORY_DCAP_DETAIL ADD (
  CONSTRAINT INV_DCAP_DETAIL_INV_ITEM_FK 
 FOREIGN KEY (INVENTORY_ITEM) 
 REFERENCES INVENTORY_ITEM (ID))
/

ALTER TABLE INVENTORY_DCAP_DETAIL ADD (
  CONSTRAINT INV_DCAP_DETAIL_MODEL_CAT_FK 
 FOREIGN KEY (MODEL_CATEGORY) 
 REFERENCES MODEL_CATEGORY (ID))
/


CREATE SEQUENCE INV_DCAP_DETAIL_SEQ
  START WITH 1000
  INCREMENT BY 20
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
/


--Dcap Detail History


CREATE TABLE DCAP_DETAIL_HISTORY
(
  ID                   NUMBER(19)               NOT NULL,
  VERSION              NUMBER(10)               NOT NULL,
  INV_DCAP_DETAIL      NUMBER(19),
  D_LAST_UPDATED_BY    NUMBER(19),
  D_CREATED_ON         DATE,
  D_UPDATED_ON         DATE,
  D_INTERNAL_COMMENTS  VARCHAR2(255 BYTE),
  LIST_INDEX           NUMBER(10)
)
/



ALTER TABLE DCAP_DETAIL_HISTORY ADD (
  CONSTRAINT DCAP_DETAIL_HIST_PK
 PRIMARY KEY
 (ID)
)
/


ALTER TABLE DCAP_DETAIL_HISTORY ADD (
  CONSTRAINT DCAP_DETAIL_HIST_INV_DCAP_FK 
 FOREIGN KEY (INV_DCAP_DETAIL) 
 REFERENCES INVENTORY_DCAP_DETAIL (ID))
/

ALTER TABLE DCAP_DETAIL_HISTORY ADD (
  CONSTRAINT DCAP_DETAIL_HIST_USER_FK 
 FOREIGN KEY (D_LAST_UPDATED_BY) 
 REFERENCES ORG_USER (ID))
/

CREATE SEQUENCE DCAP_DETAIL_HIST_SEQ
  START WITH 1
  INCREMENT BY 20
  MAXVALUE 99999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
/

--Price Matrix

CREATE TABLE PRICE_MATRIX
(
  ID                NUMBER(19)                  NOT NULL,
  FROM_DATE         DATE,
  TO_DATE           DATE,
  VERSION           NUMBER(10)                  NOT NULL,
  DEALER_GROUP      NUMBER(19),
  MODEL_CATEGORY    NUMBER(19),
  GRID_AMOUNT_CURR  VARCHAR2(255 BYTE),
  GRID_AMOUNT       NUMBER(19,2)
)
/


ALTER TABLE PRICE_MATRIX ADD (
  CONSTRAINT PRICE_MATRIX_PK
 PRIMARY KEY
 (ID)
)
/


ALTER TABLE PRICE_MATRIX ADD (
  CONSTRAINT PRICE_MATRIX_DLR_GROUP_FK 
 FOREIGN KEY (DEALER_GROUP) 
 REFERENCES DEALER_GROUP (ID))
/

ALTER TABLE PRICE_MATRIX ADD (
  CONSTRAINT PRICE_MATRIX_MODEL_CAT_FK 
 FOREIGN KEY (MODEL_CATEGORY) 
 REFERENCES MODEL_CATEGORY (ID))
/

CREATE SEQUENCE PRICE_MATRIX_SEQ
  START WITH 1000
  INCREMENT BY 20
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
/

--Model Category Split

CREATE TABLE MODEL_CATEGORY_SPLIT
(
  ID                NUMBER(19)                  NOT NULL,
  SPLIT_TYPE        NUMBER(19,2),
  VERSION           NUMBER(10)                  NOT NULL,
  PRICE_MATRIX      NUMBER(19)                  NOT NULL,
  SPLIT_PERCENTAGE  NUMBER(19,2)
)
/

ALTER TABLE MODEL_CATEGORY_SPLIT ADD (
  CONSTRAINT MODEL_CAT_SPLIT_PK
 PRIMARY KEY
 (ID)
)
/

ALTER TABLE MODEL_CATEGORY_SPLIT ADD (
  CONSTRAINT MODEL_CAT_SPLIT_PRC_MAT_FK 
 FOREIGN KEY (PRICE_MATRIX) 
 REFERENCES PRICE_MATRIX (ID))
/

ALTER TABLE MODEL_CATEGORY_SPLIT ADD (
  CONSTRAINT MODEL_CAT_SPLIT_TYPE_FK 
 FOREIGN KEY (SPLIT_TYPE) 
 REFERENCES SPLIT_TYPE (ID))
/

CREATE SEQUENCE MODEL_CAT_SPLIT_SEQ
  START WITH 1000
  INCREMENT BY 20
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
/



--Dcap Claim

CREATE TABLE DCAP_CLAIM
(
  ID                     NUMBER(19)             NOT NULL,
  BUSINESS_UNIT_INFO     VARCHAR2(255 CHAR),
  CLAIM_NUMBER           VARCHAR2(255 CHAR),
  CLAIM_TYPE             VARCHAR2(255 CHAR),
  STATE                  VARCHAR2(255 CHAR),
  UPDATED                NUMBER(1),
  VERSION                NUMBER(10)             NOT NULL,
  ACTIVE_CREDIT_MEMO     NUMBER(19),
  INVENTORY_DCAP_DETAIL  NUMBER(19),
  FOR_DEALER             NUMBER(19),
  INVENTORY_ITEM         NUMBER(19),
  FILED_ON               DATE,
  DEALER_GROUP           NUMBER(21),
  DEBIT_FLAG		 NUMBER(1)
)
/



ALTER TABLE DCAP_CLAIM ADD (
  CONSTRAINT DCAP_CLAIM_PK
 PRIMARY KEY
 (ID)
)
/


ALTER TABLE DCAP_CLAIM ADD (
  CONSTRAINT DCAP_CLAIM_DEALER_GRP_FK 
 FOREIGN KEY (DEALER_GROUP) 
 REFERENCES DEALER_GROUP (ID))
/

ALTER TABLE DCAP_CLAIM ADD (
  CONSTRAINT DCAP_CLM_CR_MEMO_FK 
 FOREIGN KEY (ACTIVE_CREDIT_MEMO) 
 REFERENCES CREDIT_MEMO (ID))
/

ALTER TABLE DCAP_CLAIM ADD (
  CONSTRAINT DCAP_CLM_DEALERSHIP_FK 
 FOREIGN KEY (FOR_DEALER) 
 REFERENCES DEALERSHIP (ID))
/

ALTER TABLE DCAP_CLAIM ADD (
  CONSTRAINT DCAP_CLM_INV_DCAP_FK 
 FOREIGN KEY (INVENTORY_DCAP_DETAIL) 
 REFERENCES INVENTORY_DCAP_DETAIL (ID))
/

ALTER TABLE DCAP_CLAIM ADD (
  CONSTRAINT DCAP_CLM_INV_ITEM_FK 
 FOREIGN KEY (INVENTORY_ITEM) 
 REFERENCES INVENTORY_ITEM (ID))
/


CREATE SEQUENCE DCAP_CLAIM_SEQ
  START WITH 1000
  INCREMENT BY 20
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
/


CREATE SEQUENCE DCAP_CLAIM_NUMBER_SEQ
  START WITH 1000000
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/



--Dcap Claim Audit

CREATE TABLE DCAP_CLAIM_AUDIT
(
  ID                     NUMBER(19)             NOT NULL,
  CLAIM_NUMBER           VARCHAR2(255 CHAR),
  CLAIM_TYPE             VARCHAR2(255 CHAR),
  CLAIMED_AMOUNT         NUMBER(19,2),
  CLAIMED_AMOUNT_CURR    VARCHAR2(255 CHAR),
  CURRENT_STATE          VARCHAR2(255 CHAR),
  D_CREATED_ON           DATE,
  D_INTERNAL_COMMENTS    VARCHAR2(255 CHAR),
  D_UPDATED_ON           DATE,
  VERSION                NUMBER(10)             NOT NULL,
  INVENTORY_DCAP_DETAIL  NUMBER(19),
  INVENTORY_ITEM         NUMBER(19),
  D_LAST_UPDATED_BY      NUMBER(19),
  FOR_CLAIM              NUMBER(19)             NOT NULL,
  ACTIVE_CREDIT_MEMO     NUMBER(19),
  LIST_INDEX             NUMBER(10)             NOT NULL,
  COMMENTS               VARCHAR2(500 BYTE)
)
/


ALTER TABLE DCAP_CLAIM_AUDIT ADD (
  CONSTRAINT DCAP_CLAIM_AUDIT_PK
 PRIMARY KEY
 (ID)
)
/


ALTER TABLE DCAP_CLAIM_AUDIT ADD (
  CONSTRAINT DCAP_CLM_AUDIT_CR_MEMO_FK 
 FOREIGN KEY (ACTIVE_CREDIT_MEMO) 
 REFERENCES CREDIT_MEMO (ID))
/

ALTER TABLE DCAP_CLAIM_AUDIT ADD (
  CONSTRAINT DCAP_CLM_AUDIT_DCAP_CLM_FK 
 FOREIGN KEY (FOR_CLAIM) 
 REFERENCES DCAP_CLAIM (ID))
/

ALTER TABLE DCAP_CLAIM_AUDIT ADD (
  CONSTRAINT DCAP_CLM_AUDIT_INV_DCAP_FK 
 FOREIGN KEY (INVENTORY_DCAP_DETAIL) 
 REFERENCES INVENTORY_DCAP_DETAIL (ID))
/

ALTER TABLE DCAP_CLAIM_AUDIT ADD (
  CONSTRAINT DCAP_CLM_AUDIT_INV_ITEM_FK 
 FOREIGN KEY (INVENTORY_ITEM) 
 REFERENCES INVENTORY_ITEM (ID))
/

ALTER TABLE DCAP_CLAIM_AUDIT ADD (
  CONSTRAINT DCAP_CLM_AUDIT_ORG_USER_FK 
 FOREIGN KEY (D_LAST_UPDATED_BY) 
 REFERENCES ORG_USER (ID))
/


CREATE SEQUENCE DCAP_CLAIM_AUDIT_SEQ
  START WITH 1000
  INCREMENT BY 20
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
/

--Credit Memo

ALTER TABLE CREDIT_MEMO ADD DCAP_CLAIM NUMBER
/
ALTER TABLE CREDIT_MEMO ADD (
  CONSTRAINT CREDIT_MEMO_DCAP_CLM_FK 
 FOREIGN KEY (DCAP_CLAIM) 
 REFERENCES DCAP_CLAIM (ID))
/


--Claim number pattern

alter table claim_number_pattern
add pattern_type varchar2(20)
/