ALTER TABLE TRANSACTION_TYPE ADD (BUSINESS_UNIT_INFO VARCHAR2(255 BYTE))
/
ALTER TABLE MARKET_TYPE ADD (BUSINESS_UNIT_INFO VARCHAR2(255 BYTE))
/
ALTER TABLE COMPETITION_TYPE ADD (BUSINESS_UNIT_INFO VARCHAR2(255 BYTE))
/
ALTER TABLE COMPETITOR_MODEL ADD (BUSINESS_UNIT_INFO VARCHAR2(255 BYTE))
/
ALTER TABLE COMPETITOR_MAKE ADD (BUSINESS_UNIT_INFO VARCHAR2(255 BYTE))
/
ALTER TABLE COMPETITOR_MODEL
 ADD CONSTRAINT COMPETITOR_MODEL_BU_FK
 FOREIGN KEY (BUSINESS_UNIT_INFO) 
 REFERENCES BUSINESS_UNIT (NAME) 
/
ALTER TABLE COMPETITOR_MAKE
ADD CONSTRAINT COMPETITOR_MAKE_BU_FK
FOREIGN KEY (BUSINESS_UNIT_INFO) 
REFERENCES BUSINESS_UNIT (NAME)
/
ALTER TABLE COMPETITION_TYPE
ADD CONSTRAINT COMPETITION_TYPE_BU_FK
FOREIGN KEY (BUSINESS_UNIT_INFO) 
REFERENCES BUSINESS_UNIT (NAME)
/
ALTER TABLE MARKET_TYPE
ADD CONSTRAINT MARKET_TYPE_BU_FK
FOREIGN KEY (BUSINESS_UNIT_INFO) 
REFERENCES BUSINESS_UNIT (NAME)
/
ALTER TABLE TRANSACTION_TYPE
ADD CONSTRAINT TRANSACTION_TYPE_BU_FK
FOREIGN KEY (BUSINESS_UNIT_INFO) 
REFERENCES BUSINESS_UNIT (NAME)
/