--Purpose    : Indexes added by Manjunath in club car production
--Author     : Nandakumar Devi
--Created On : 30-JUL-09

CREATE INDEX JBPM_TASKINSTANCE_I9 ON JBPM_TASKINSTANCE (TASK_)
/
CREATE INDEX JBPM_VARIABLEINSTANCE_I9 ON JBPM_VARIABLEINSTANCE (PROCESSINSTANCE_)
/
CREATE INDEX ITEM_GROUP_I2 ON ITEM_GROUP (NAME, ITEM_GROUP_TYPE, TREE_ID, LFT, RGT, ID)
/
CREATE INDEX JBPM_TOKEN_I2 ON JBPM_TOKEN (PARENT_)
/
CREATE INDEX PURPOSE_IDX ON PURPOSE (NAME)
/
CREATE INDEX ITEMS_IN_GROUP_IDX ON ITEMS_IN_GROUP (ITEM)
/
CREATE INDEX CUSTOMER_I2 ON CUSTOMER (ID, UPPER(COMPANY_NAME))
/
CREATE INDEX SHIPMENT_I2 ON SHIPMENT (UPPER(TRANSIENT_ID))
/
CREATE INDEX JBPM_TIMER_I3 ON JBPM_TIMER (ISSUSPENDED_, DUEDATE_)
/
CREATE INDEX SYNC_TRACKER_I2 ON SYNC_TRACKER (UNIQUE_ID_VALUE, SYNC_TYPE)
/
CREATE INDEX CLAIM_AUDIT_I2 ON CLAIM_AUDIT (FOR_CLAIM, PREVIOUS_STATE)
/
CREATE INDEX CLAIM_I3 ON CLAIM (STATE)
/
CREATE INDEX INVENTORY_TRANSACTION_I2 ON INVENTORY_TRANSACTION (TRANSACTED_ITEM, TRANSACTION_DATE, BUYER, ID)
/