--PURPOSE    : PATCH FOR CREATING ITEM_TYPE_MAPPING TABLE AND INSERTING MAPPING DATA
--AUTHOR     : GYANENDRA BISWANATH MISHRA
--CREATED ON : 20-FEB-09

CREATE TABLE item_type_mapping(ID NUMBER(19,0) NOT NULL, external_item_type VARCHAR2(255) UNIQUE, item_type VARCHAR2(255))
/
ALTER TABLE item_type_mapping ADD CONSTRAINT item_type_mapping_pk PRIMARY KEY(ID)
/
CREATE SEQUENCE ITEM_TYPE_MAPPING_SEQ START WITH 1000 INCREMENT BY 20
/
COMMIT
/
