--Purpose    : Used to keep all the upload data
--Author     : Jhulfikar Ali. A
--Created On : 24-Dec-08

CREATE TABLE FILE_UPLOAD_MGT
(
  ID                  INTEGER,
  FILE_NAME           VARCHAR2(100 BYTE)        NOT NULL,
  TEMPLATE_NAME       VARCHAR2(100 BYTE)        NOT NULL,
  RECEIVED_ON         DATE                      NOT NULL,
  UPLOAD_STATUS       INTEGER                   NOT NULL,
  FILE_CONTENT        BLOB,
  ERROR_FILE_CONTENT  BLOB,
  TOTAL_RECORDS       INTEGER,
  SUCCESS_RECORDS     INTEGER,
  ERROR_RECORDS       INTEGER,
  RETRY_COUNT         INTEGER                   DEFAULT 0                     NOT NULL,
  ERROR_MESSAGE       VARCHAR2(4000 BYTE)
)
/
ALTER TABLE FILE_UPLOAD_MGT
add CONSTRAINT PK_FILE_UPLOAD_MGT PRIMARY KEY (id)
/
CREATE SEQUENCE FILE_UPLOAD_MGT_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 0
CACHE 20
/
CREATE TABLE Upload_Mgt
(
  id                NUMBER,
  name_of_template  VARCHAR2(255),
  name_to_display   VARCHAR2(255),
  description       VARCHAR2(512),
  template_path     VARCHAR2(1000),
  staging_table     VARCHAR2(100),
  staging_procedure     VARCHAR2(100),
  validation_procedure  VARCHAR2(100),
  upload_procedure      VARCHAR2(100)
)
/
ALTER TABLE Upload_Mgt ADD (
  CONSTRAINT PK_Upload_Mgt
 PRIMARY KEY
 (id))
/
CREATE SEQUENCE Upload_Mgt_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 0
CACHE 20
/
CREATE TABLE STG_INSTALL_BASE
(
  ID                    NUMBER,
  FILE_UPLOAD_MGT_ID    NUMBER,
  SERIAL_NUMBER         VARCHAR2(255 BYTE),
  ITEM_NUMBER           VARCHAR2(255 BYTE),
  BUSINESS_UNIT_NAME    VARCHAR2(255 BYTE),
  LIFECYCLE_STATUS      NUMBER,
  STOCK_OR_RETAIL       VARCHAR2(40 BYTE),
  ENGINE_SERIAL_NUMBER  VARCHAR2(255 BYTE),
  ACR_DATE              DATE,
  MACHINE_BUILD_DATE    DATE,
  HOURS_IN_SERVICE      NUMBER,
  INTERNAL_COMMENTS     VARCHAR2(255 BYTE),
  INSTALLATION_DATE     DATE,
  SHIPMENT_DATE         DATE,
  DELIVERY_DATE         DATE,
  WARRANTY_START_DATE   DATE,
  INVOICE_NUMBER        VARCHAR2(255 BYTE),
  SALES_ORDER_NUMBER    VARCHAR2(255 BYTE),
  INVOICE_DATE          DATE,
  SHIP_FROM_WAREHOUSE   VARCHAR2(255 BYTE),
  DEALER_NUMBER         VARCHAR2(255 BYTE),
  DEALER_SITE_NUMBER    VARCHAR2(255 BYTE),
  END_CUSTOMER_NAME     VARCHAR2(255 BYTE),
  ADDRESS_LINE1		VARCHAR2(255 BYTE),
  ADDRESS_LINE2		VARCHAR2(255 BYTE),
  ADDRESS_LINE3		VARCHAR2(255 BYTE),
  CITY			VARCHAR2(255 BYTE),
  STATE			VARCHAR2(255 BYTE),
  COUNTRY		VARCHAR2(255 BYTE),
  ZIPCODE		NUMBER,
  PREFERED_LANGUAGE	VARCHAR2(255 BYTE),
  PHONE_NUMBER		VARCHAR2(255 BYTE),
  FAX_NUMBER		VARCHAR2(255 BYTE),
  E_MAIL		VARCHAR2(255 BYTE),
  CONTACT_FIRST_NAME	VARCHAR2(255 BYTE),
  CONTACT_MIDDLE_NAME	VARCHAR2(255 BYTE),
  CONTACT_LAST_NAME	VARCHAR2(255 BYTE),
  WMS_DEPLOYMENT_STACK	VARCHAR2(255 BYTE),
  APPLY_COVERAGE	VARCHAR2(255 BYTE),
  INVENTORY_ITEM_TYPE	VARCHAR2(255 BYTE),
  ERROR_STATUS	        VARCHAR2(20 BYTE),
  ERROR_CODE	        VARCHAR2(4000 BYTE),
  UPLOAD_STATUS	        VARCHAR2(20 BYTE),
  UPLOAD_ERROR	        VARCHAR2(4000 BYTE),
  UPLOAD_DATE	        VARCHAR2(20 BYTE)
)
/
CREATE TABLE STG_JOB_CODE
(
  ID                    NUMBER,
  FILE_UPLOAD_MGT_ID    NUMBER,
  BUSINESS_UNIT_NAME    VARCHAR2(255 BYTE),
  PRODUCT_CODE    VARCHAR2(255 BYTE),
  FIELD_MODEL VARCHAR2(255 BYTE),
  JOB_CODE      VARCHAR2(255 BYTE),
  ACTION    VARCHAR2(255 BYTE),
  LABOR_STANDARD_HOURS    VARCHAR2(255 BYTE),
  LABOR_STANDARD_MINUTES    VARCHAR2(255 BYTE),
  REPEATABLE    VARCHAR2(1 BYTE),
  FIELD_MODIFICATION_ONLY    VARCHAR2(1 BYTE),
  PART_AMOUNT_IN_USD    VARCHAR2(255 BYTE),
  PART_AMOUNT_IN_GBP    VARCHAR2(255 BYTE),
  PART_AMOUNT_IN_CAD    VARCHAR2(255 BYTE),
  PART_AMOUNT_IN_EURO    VARCHAR2(255 BYTE),
  ERROR_STATUS	        VARCHAR2(20 BYTE),
  ERROR_CODE	        VARCHAR2(4000 BYTE),
  UPLOAD_STATUS	        VARCHAR2(20 BYTE),
  UPLOAD_ERROR	        VARCHAR2(4000 BYTE),
  UPLOAD_DATE	        VARCHAR2(20 BYTE)
)
/
CREATE TABLE STG_STD_EXT_WNTY_CVG
(
  ID                    NUMBER,
  FILE_UPLOAD_MGT_ID    NUMBER,
  BUSINESS_UNIT_NAME    VARCHAR2(255 BYTE),
  Serial_Number    VARCHAR2(255 BYTE),
  Item_Number VARCHAR2(255 BYTE),
  Plan_Code      VARCHAR2(255 BYTE),
  Warranty_Start_Date    DATE,
  Warranty_End_Date    VARCHAR2(255 BYTE),
  Order_Date    VARCHAR2(255 BYTE),
  Order_NO    VARCHAR2(1 BYTE),
  FORCE_COVERAGE    VARCHAR2(1 BYTE),
  ERROR_STATUS	        VARCHAR2(20 BYTE),
  ERROR_CODE	        VARCHAR2(4000 BYTE),
  UPLOAD_STATUS	        VARCHAR2(20 BYTE),
  UPLOAD_ERROR	        VARCHAR2(4000 BYTE),
  UPLOAD_DATE	        VARCHAR2(20 BYTE)
)
/
COMMIT
/