--Purpose: Storing request and thier audits for policies with reduced coverage
--Author: Prashanth 
--Created On: Date 06 Nov 2008

CREATE TABLE REQUEST_WNTY_CVG (ID NUMBER(20) NOT NULL, INVENTORY_ITEM NUMBER(20) NOT NULL,STATUS VARCHAR2(50),CONSTRAINT REQUEST_WNTY_CVG_PK PRIMARY KEY (ID))
/
CREATE TABLE REQUEST_WNTY_CVG_AUDIT (ID NUMBER(20) NOT NULL, REQUEST_WNTY_CVG NUMBER(20) NOT NULL, COMMENTS VARCHAR2(250), STATUS VARCHAR2(50) NOT NULL, ASSIGNED_TO NUMBER(20), ASSIGNED_BY NUMBER(20),D_CREATED_ON DATE,D_UPDATED_ON DATE,
D_CREATED_TIME TIMESTAMP,D_UPDATED_TIME TIMESTAMP,D_INTERNAL_COMMENTS VARCHAR2(50),D_LAST_UPDATED_BY NUMBER,CONSTRAINT REQUEST_WNTY_CVG_AUDIT_PK PRIMARY KEY (ID))
/
ALTER TABLE REQUEST_WNTY_CVG ADD CONSTRAINT REQ_WNTY_CVG_INVENTORY_ITEM_FK  FOREIGN KEY (INVENTORY_ITEM) REFERENCES INVENTORY_ITEM (ID) ENABLE  VALIDATE
/
ALTER TABLE REQUEST_WNTY_CVG_AUDIT ADD CONSTRAINT REQ_WNTY_CVG_AUDIT_CVG_REQ_FK
FOREIGN KEY (REQUEST_WNTY_CVG)  REFERENCES REQUEST_WNTY_CVG (ID) ENABLE  VALIDATE
/
ALTER TABLE REQUEST_WNTY_CVG_AUDIT ADD CONSTRAINT REQ_WNTYCVGAUDIT_UPDBYUSER_FK
FOREIGN KEY (D_LAST_UPDATED_BY)  REFERENCES ORG_USER (ID) ENABLE  VALIDATE
/
ALTER TABLE REQUEST_WNTY_CVG_AUDIT ADD CONSTRAINT REQWNTYCVG_AUDIT_ASSIGNTO_FK
FOREIGN KEY (ASSIGNED_TO)  REFERENCES ORG_USER (ID) ENABLE  VALIDATE
/
ALTER TABLE REQUEST_WNTY_CVG_AUDIT ADD CONSTRAINT REQ_WNTYCVGAUDIT_ASSIGNBY_FK
FOREIGN KEY (ASSIGNED_BY)  REFERENCES ORG_USER (ID) ENABLE  VALIDATE
/
CREATE SEQUENCE REQUEST_WNTY_CVG_SEQ START WITH 10 INCREMENT BY 20 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCACHE  NOCYCLE NOORDER 
/
CREATE SEQUENCE REQUEST_WNTY_CVG_AUDIT_SEQ START WITH 10 INCREMENT BY 20 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCACHE  NOCYCLE NOORDER 
/
COMMIT
/