--PURPOSE    : PATCH FOR IVENTORY_ITEM CURRENT FK
--AUTHOR     : BHASKARA K
--CREATED ON : 20-APR-09

ALTER TABLE INVENTORY_ITEM DROP CONSTRAINT INVITEM_SERVPROVDR_FK
/
COMMIT
/
ALTER TABLE INVENTORY_ITEM ADD (CONSTRAINT INV_ITEM_ORGANIZATION_FK  FOREIGN KEY (CURRENT_OWNER)  REFERENCES ORGANIZATION (ID))
/
COMMIT
/
