-- Author: Ramalakshmi P
-- Date : 28 Nov 2008
-- Reason: Folder View in IRI TWMS

CREATE SEQUENCE  INBOX_VIEW_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 1000 
NOCACHE  NOORDER  NOCYCLE
/
CREATE SEQUENCE  DEFAULT_FOLDER_VIEW_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 1000 
NOCACHE  NOORDER  NOCYCLE
/
CREATE TABLE INBOX_VIEW
(
  ID                    NUMBER(19)              NOT NULL,
  FIELD_NAMES           CLOB,
  NAME                  VARCHAR2(255 BYTE)      NOT NULL,
  SORT_BY_FIELD         VARCHAR2(255 BYTE),
  SORT_ORDER_ASCENDING  NUMBER(1)               NOT NULL,
  TYPE                  VARCHAR2(255 BYTE),
  VERSION               NUMBER(10)              NOT NULL,
  CREATED_BY            NUMBER(19)
)
/
ALTER TABLE 	INBOX_VIEW	 ADD CONSTRAINT  	INBOX_VIEW_PK	PRIMARY KEY( 	ID	)
/
ALTER TABLE INBOX_VIEW ADD (CONSTRAINT INBOX_VIEW_USER_FK FOREIGN KEY (CREATED_BY) REFERENCES ORG_USER (ID))
/
CREATE TABLE DEFAULT_FOLDER_VIEW
(
  ID                  NUMBER(19)                NOT NULL,
  FOLDER_NAME         VARCHAR2(255 BYTE)        NOT NULL,
  DEFAULT_INBOX_VIEW  NUMBER(19)                NOT NULL,
  CREATED_BY          NUMBER(19)                NOT NULL
)
/
CREATE INDEX DEFAULTFOLDERVIEW_CREATEDBY_IX ON DEFAULT_FOLDER_VIEW
(CREATED_BY)
/
CREATE INDEX DEFAULTFOLDERVIEW_INBOXVIEW_IX ON DEFAULT_FOLDER_VIEW
(DEFAULT_INBOX_VIEW)
/
ALTER TABLE 	DEFAULT_FOLDER_VIEW	 ADD CONSTRAINT  	DEFAULT_FOLDER_VIEW_PK	PRIMARY KEY( 	ID	)
/
ALTER TABLE DEFAULT_FOLDER_VIEW ADD (
CONSTRAINT DEFAULT_FOLDER_VIEW_USER_FK 
FOREIGN KEY (CREATED_BY) 
REFERENCES ORG_USER (ID))
/
ALTER TABLE DEFAULT_FOLDER_VIEW ADD (
CONSTRAINT DEFAULT_FOLDER_VIEW_INBXVW_FK 
FOREIGN KEY (DEFAULT_INBOX_VIEW) 
REFERENCES INBOX_VIEW (ID))
/
COMMIT
/