--Purpose    : Create Join table to store Inventory Type appliable on report
--Author     : Jitesh Jain
--Created On : 31-Mar-09

CREATE TABLE INVENTORY_TYPES_IN_REPORTS
(CUSTOM_REPORT NUMBER(19) NOT NULL,INVENTORY_TYPE VARCHAR2(255) NOT NULL)
/
ALTER TABLE INVENTORY_TYPES_IN_REPORTS
ADD CONSTRAINT INV_TYPES_CUSTOM_REPORT FOREIGN KEY(CUSTOM_REPORT)
REFERENCES CUSTOM_REPORT(ID) 
/
ALTER TABLE INVENTORY_TYPES_IN_REPORTS
ADD CONSTRAINT INV_TYPES_INVENTORY_TYPE FOREIGN KEY(INVENTORY_TYPE)
REFERENCES INVENTORY_TYPE(TYPE) 
/
alter table "CUSTOM_REPORT" add(REPORT_TYPE NUMBER(19,0))
/
alter table "CUSTOM_REPORT" add constraint CUSTOM_REPORT_LOV_FK foreign key("REPORT_TYPE") references "LIST_OF_VALUES"("ID")
/
alter table "CUSTOM_REPORT_ANSWER" add(INSTALLATION_DATE DATE)
/
commit
/