--Purpose    : Modification of Marketing_Information(Change of FK) and Competitor_Make(Change of PK) tables for static i18n purpose
--Author     : shraddha.nanda
--Created On : 22-Aug-08

ALTER TABLE marketing_information
DROP CONSTRAINT MARKETINGINFO_MAKE_FK
/
ALTER TABLE COMPETITOR_MAKE
DROP PRIMARY KEY
/
ALTER TABLE COMPETITOR_MAKE ADD(ID NUMBER(19))
/
CREATE SEQUENCE COMPETITOR_MAKE_SEQ
  START WITH 61
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
/  
UPDATE COMPETITOR_MAKE SET ID= COMPETITOR_MAKE_SEQ.NEXTVAL
/
ALTER TABLE COMPETITOR_MAKE ADD(CONSTRAINT COMPETITOR_MAKE_PK PRIMARY KEY(ID))
/
DECLARE
CURSOR GET_compMake  IS
SELECT * FROM MARKETING_INFORMATION WHERE COMPETITOR_MAKE IS NOT NULL;

v_compMake NUMBER:=0;

BEGIN
FOR GET_REC IN GET_compMake LOOP
SELECT id INTO 	v_compMake FROM COMPETITOR_MAKE WHERE MAKE=GET_REC.COMPETITOR_MAKE;
UPDATE MARKETING_INFORMATION SET COMPETITOR_MAKE=v_compMake WHERE id=GET_REC.id;
END LOOP;
END;
/
CREATE TABLE DUMMY_MARKETING_INFORMATION (ID NUMBER(19), COMPETITOR_MAKE VARCHAR2(255))
/
DECLARE
CURSOR GET_transType  IS
SELECT * FROM MARKETING_INFORMATION ;
BEGIN
FOR GET_REC IN GET_transType LOOP
	INSERT INTO DUMMY_MARKETING_INFORMATION (ID,COMPETITOR_MAKE) 
VALUES (GET_REC.ID ,GET_REC.COMPETITOR_MAKE );
	END LOOP;
END;
/
UPDATE MARKETING_INFORMATION SET COMPETITOR_MAKE=NULL
/
ALTER TABLE MARKETING_INFORMATION DROP COLUMN COMPETITOR_MAKE
/
ALTER TABLE MARKETING_INFORMATION ADD COMPETITOR_MAKE NUMBER(19)
/
ALTER TABLE MARKETING_INFORMATION ADD CONSTRAINT MARKETINGINFO_MAKE_FK
FOREIGN KEY(COMPETITOR_MAKE) REFERENCES COMPETITOR_MAKE(ID)
/
DECLARE
CURSOR GET_COMPETITORMAKE  IS
SELECT * FROM DUMMY_MARKETING_INFORMATION WHERE COMPETITOR_MAKE IS NOT NULL;
BEGIN
FOR GET_REC IN GET_COMPETITORMAKE LOOP
	UPDATE MARKETING_INFORMATION SET COMPETITOR_MAKE=GET_REC.COMPETITOR_MAKE WHERE id=GET_REC.id;
	END LOOP;
END;
/
DROP TABLE DUMMY_MARKETING_INFORMATION
/