--PURPOSE    :ALTER LABOR_DETAIL TABLE TO HOLD ENTERED LABOR HRS BY DEALER AND SERVICE TO WAT WAS BU CONFIG DURING FILING CLAIM
--AUTHOR     : PRADYOT.ROUT
--CREATED ON : 25-APR-09


ALTER TABLE LABOR_DETAIL ADD LABOR_HRS_ENTERED NUMBER(19,2)
/
ALTER TABLE SERVICE ADD STD_LABOR_ENABLED NUMBER(1)
/
UPDATE SERVICE SET STD_LABOR_ENABLED=1
/
COMMIT
/
