--PURPOSE    : PATCH FOR ADD INVENTORY ITEM_TYPE RMA
--AUTHOR     : BHASKARA K
--CREATED ON : 20-APR-2009
INSERT INTO INVENTORY_TYPE ( TYPE, VERSION, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE ) VALUES ('RMA', 1, NULL, NULL, NULL, NULL, NULL, NULL, 1)
/
COMMIT
/