--PURPOSE    : PATCH FOR CAPTURING SERVICE PROVIDER NUMBER FOR ANONYMOUS THIRD PARTY
--AUTHOR     : PRASHANTH KONDA
--CREATED ON : 15-MAR-09

INSERT INTO CONFIG_PARAM
(ID, DESCRIPTION, DISPLAY_NAME, NAME, TYPE, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, D_CREATED_TIME, D_UPDATED_TIME, LOGICAL_GROUP, PARAM_DISPLAY_TYPE, LOGICAL_GROUP_ORDER, SECTIONS, SECTIONS_ORDER, PARAM_ORDER,d_active)
VALUES
(config_param_seq.NEXTVAL, 'This is not for ui display', 'Service provider no for anonymous third party',
    'anonymousThirdPartyNumber','java.lang.String', 
    TO_DATE('03/14/2008 15:38:14', 'MM/DD/YYYY HH24:MI:SS'), 'Configuration', TO_DATE('03/14/2008 15:38:14', 'MM/DD/YYYY HH24:MI:SS'), 56, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL,1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, '999999', (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'anonymousThirdPartyNumber'),
TO_DATE('03/14/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, TO_DATE('03/14/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 56, 'Hussmann', NULL, NULL,NULL,1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, '999999', (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'anonymousThirdPartyNumber'),
TO_DATE('03/14/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, TO_DATE('03/14/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 56, 'Transport Solutions ESA', NULL, NULL,NULL,1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, '999999', (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'anonymousThirdPartyNumber'),
TO_DATE('03/14/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, TO_DATE('03/14/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 56, 'Clubcar ESA', NULL, NULL,NULL,1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, '999999', (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'anonymousThirdPartyNumber'),
TO_DATE('03/14/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, TO_DATE('03/14/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 56, 'TFM', NULL, NULL,NULL,1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, '999999', (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'anonymousThirdPartyNumber'),
TO_DATE('03/14/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, TO_DATE('03/14/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 56, 'AIR', NULL, NULL,NULL,1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, '999999', (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'anonymousThirdPartyNumber'),
TO_DATE('03/14/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, TO_DATE('03/14/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 56, 'Club Car', NULL, NULL,NULL,1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, '999999', (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'anonymousThirdPartyNumber'),
TO_DATE('03/14/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, TO_DATE('03/14/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 56, 'TK', NULL, NULL,NULL,1)
/
COMMIT
/
