--Purpose    : Used to validate copy job code upload data
--Author     : Jhulfikar Ali. A
--Created On : 15-Jan-08

CREATE TABLE STG_COPY_JOB_CODE_FF
(
  ID                    NUMBER,
  FILE_UPLOAD_MGT_ID    NUMBER,
  BUSINESS_UNIT_NAME    VARCHAR2(255 BYTE),
  From_Product_Code    VARCHAR2(255 BYTE),
  From_Model_Number VARCHAR2(255 BYTE),
  To_Product_Code      VARCHAR2(255 BYTE),
  To_Model_Number    VARCHAR2(255 BYTE),
  Copy    VARCHAR2(255 BYTE),
  ERROR_STATUS	        VARCHAR2(20 BYTE),
  ERROR_CODE	        VARCHAR2(4000 BYTE),
  UPLOAD_STATUS	        VARCHAR2(20 BYTE),
  UPLOAD_ERROR	        VARCHAR2(4000 BYTE),
  UPLOAD_DATE	        VARCHAR2(20 BYTE)
)
/
CREATE TABLE STG_PART_SRC_HIST_UPLD
(
  ID                    NUMBER,
  FILE_UPLOAD_MGT_ID    NUMBER,
  ACTION    NUMBER,
  BUSINESS_UNIT_NAME    VARCHAR2(255 BYTE),
  Catalog_Name    VARCHAR2(255 BYTE),
  Item_Number VARCHAR2(255 BYTE),
  Supplier_Name      VARCHAR2(255 BYTE),
  From_Date    VARCHAR2(255 BYTE),
  To_Date    VARCHAR2(255 BYTE),
  Supplier_Number VARCHAR2(255 BYTE),
  supplier_item_number VARCHAR2(255 BYTE),
  Recoverable_Causal_Flag varchar2(10), 
  Recoverable_All_Flag varchar2(10), 
  Need_Additional_Info_Flag varchar2(10),
  Coverage_Period NUMBER,
  ERROR_STATUS	        VARCHAR2(20 BYTE),
  ERROR_CODE	        VARCHAR2(4000 BYTE),
  UPLOAD_STATUS	        VARCHAR2(20 BYTE),
  UPLOAD_ERROR	        VARCHAR2(4000 BYTE),
  UPLOAD_DATE	        VARCHAR2(20 BYTE)
)
/
CREATE TABLE STG_DRAFT_CLAIM 
(
  ID                    		NUMBER,
  FILE_UPLOAD_MGT_ID    		NUMBER,
  CLAIM_NUMBER          		VARCHAR2(255 BYTE),
  DRAFTING_USER_LOGIN   		VARCHAR2(255 BYTE),
  FILING_DEALER_NUMBER  		VARCHAR2(255 BYTE),
  REMOTE_SYSTEM         		VARCHAR2(255 BYTE),
  CLAIM_TYPE            		VARCHAR2(10 BYTE),
  SERIAL_NUMBER				VARCHAR2(255 BYTE),
  EQUIPMENT_ITEM_NUMBER 		VARCHAR2(255 BYTE),
  BUSINESS_UNIT_NAME    		VARCHAR2(255 BYTE),
  WORK_ORDER_NUMBER     		VARCHAR2(255 BYTE),
  DATE_OF_FAILURE			VARCHAR2(255 BYTE),
  DATE_OF_REPAIR			VARCHAR2(255 BYTE),
  REQUEST_FOR_SWC			VARCHAR2(10 BYTE),
  SWC_REASON				VARCHAR2(255 BYTE),
  PART_NUMBER				VARCHAR2(255 BYTE),
  IS_PART_INSTALLED_WITH_MACHINE 	VARCHAR2(10 BYTE),
  DATE_OF_INSTALLATION			VARCHAR2(255 BYTE),
  DATE_OF_PURCHASE			VARCHAR2(255 BYTE),
  CAUSAL_PART				VARCHAR2(255 BYTE),
  FAULT_CODE				VARCHAR2(255 BYTE),
  FAULT_FOUND				VARCHAR2(255 BYTE),
  CAUSED_BY				VARCHAR2(255 BYTE),
  ROOT_CAUSE				VARCHAR2(255 BYTE),
  JOB_CODE				VARCHAR2(255 BYTE),
  TOTAL_LABOR_HOURS			VARCHAR2(255 BYTE),
  TOTAL_TRAVEL_HOURS			VARCHAR2(255 BYTE),
  TECHNICIAN_LOGIN			VARCHAR2(255 BYTE),
  TRAVEL_LOCATION			VARCHAR2(255 BYTE),
  TRAVEL_DISTANCE			VARCHAR2(255 BYTE),
  TRAVEL_UNITS				VARCHAR2(255 BYTE),
  CONDITIONS_FOUND			VARCHAR2(255 BYTE),
  PROBABLE_CAUSE			VARCHAR2(255 BYTE),
  WORK_PERFORMED			VARCHAR2(255 BYTE),
  ADDITIONAL_COMMENTS			VARCHAR2(255 BYTE),
  HOURS_IN_SERVICE			VARCHAR2(255 BYTE),
  ERROR_STATUS	        		VARCHAR2(20 BYTE),
  ERROR_CODE	        		VARCHAR2(4000 BYTE),
  UPLOAD_STATUS	        		VARCHAR2(20 BYTE),
  UPLOAD_ERROR	        		VARCHAR2(4000 BYTE),
  UPLOAD_DATE	        		VARCHAR2(20 BYTE)
)
/
alter table stg_install_base modify (ACR_DATE VARCHAR2(10), MACHINE_BUILD_DATE VARCHAR2(10), 
INSTALLATION_DATE VARCHAR2(10), SHIPMENT_DATE VARCHAR2(10), DELIVERY_DATE VARCHAR2(10), 
WARRANTY_START_DATE VARCHAR2(10), INVOICE_DATE VARCHAR2(10), ZIPCODE VARCHAR2(20))
/
alter table stg_job_code modify (REPEATABLE VARCHAR2(10),FIELD_MODIFICATION_ONLY VARCHAR2(10))
/
COMMIT
/