--Purpose     Added tables CUSTOMER_TYPE to capture customer types for which policy is applicable
--Author      Jitesh Jain
--Created On  19-SEP-08

CREATE TABLE APPLICABLE_CUSTOMER_TYPES (id NUMBER(19,0) NOT NULL, type VARCHAR2(255 CHAR), policy_definition NUMBER(19,0) NOT NULL)
/
ALTER TABLE APPLICABLE_CUSTOMER_TYPES ADD CONSTRAINT APPLICABLE_CUSTOMER_TYPES_PK PRIMARY KEY(ID)
/
ALTER TABLE APPLICABLE_CUSTOMER_TYPES ADD CONSTRAINT APP_CUST_POLICY_DEF_FK FOREIGN KEY (policy_definition) REFERENCES policy_definition(ID)
/
CREATE SEQUENCE APPLICABLE_CUSTOMER_TYPES_SEQ START WITH 1000 INCREMENT BY 20
/
