--PURPOSE    : PATCH FOR ADDING SOURCE WAREHOUSE
--AUTHOR     : PRADYOT ROUT
--CREATED ON : 19-JAN-09

CREATE SEQUENCE SOURCE_WAREHOUSE_SEQ START WITH 1000 INCREMENT BY 20
/
CREATE TABLE SOURCE_WAREHOUSE (
ID NUMBER(19,0) NOT NULL,
NAME VARCHAR2(255),
BUSINESS_UNIT_INFO VARCHAR2(255),
D_CREATED_ON DATE, 
D_CREATED_TIME TIMESTAMP, 
D_INTERNAL_COMMENTS VARCHAR2(255 CHAR), 
D_UPDATED_ON DATE, 
D_UPDATED_TIME TIMESTAMP, 
D_LAST_UPDATED_BY NUMBER(19,0),
D_ACTIVE NUMBER(1,0),
CONSTRAINT SOURCE_WAREHOUSE_PK PRIMARY KEY (ID))
/
ALTER TABLE SOURCE_WAREHOUSE  ADD CONSTRAINT SRC_WAREHOUSE_UPDATED_FK FOREIGN KEY (D_LAST_UPDATED_BY) REFERENCES ORG_USER
/
ALTER TABLE SOURCE_WAREHOUSE ADD (
  CONSTRAINT SRC_WAREHOUSE_BUSINESS_UNIT_FK 
 FOREIGN KEY (BUSINESS_UNIT_INFO) 
 REFERENCES BUSINESS_UNIT (NAME))
/
--commented below 2 insert statements, as this is dummy data and real data will be inserted in IRI-Migration process.
--INSERT INTO SOURCE_WAREHOUSE VALUES (SOURCE_WAREHOUSE_SEQ.NEXTVAL,'WREHOUSE 1','Club Car',SYSDATE,SYSDATE,'DUMMY',SYSDATE,
--SYSDATE,117247,1)
--/
--INSERT INTO SOURCE_WAREHOUSE VALUES (SOURCE_WAREHOUSE_SEQ.NEXTVAL,'WREHOUSE 1','AIR',SYSDATE,SYSDATE,'DUMMY',SYSDATE,
--SYSDATE,117247,1)
--/
ALTER TABLE CLAIM ADD SOURCE_WAREHOUSE NUMBER(19,0)
/
ALTER TABLE CLAIM  ADD CONSTRAINT CLAIM_SRC_WAREHOUSE_FK FOREIGN KEY (SOURCE_WAREHOUSE) REFERENCES SOURCE_WAREHOUSE
/
INSERT INTO CONFIG_PARAM
(ID, DESCRIPTION, DISPLAY_NAME, NAME, TYPE, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, D_CREATED_TIME, D_UPDATED_TIME, LOGICAL_GROUP, PARAM_DISPLAY_TYPE, LOGICAL_GROUP_ORDER, SECTIONS, SECTIONS_ORDER, PARAM_ORDER,d_active)
VALUES
(config_param_seq.NEXTVAL, 'CaptureSourceWarehouse', 'CaptureSourceWarehouse',
    'CaptureSourceWarehouse','boolean', 
    TO_DATE('11/01/2008 15:38:14', 'MM/DD/YYYY HH24:MI:SS'), 'Configuration', TO_DATE('12/24/2008 15:38:14', 'MM/DD/YYYY HH24:MI:SS'), 117247, NULL, 
    NULL, NULL, 'radio', NULL, NULL, 
    NULL, NULL,1)
/
INSERT INTO CONFIG_PARAM_OPTIONS_MAPPING (ID, PARAM_ID, OPTION_ID) 
values
(CFG_PARAM_OPTNS_MAPPING_SEQ.NEXTVAL,
(select id from config_param where name='CaptureSourceWarehouse'),
(select id from config_param_option where value='true'))
/
INSERT INTO CONFIG_PARAM_OPTIONS_MAPPING (ID, PARAM_ID, OPTION_ID) 
values
(CFG_PARAM_OPTNS_MAPPING_SEQ.NEXTVAL,
(select id from config_param where name='CaptureSourceWarehouse'),
(select id from config_param_option where value='false'))
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, NULL, (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'CaptureSourceWarehouse'),
TO_DATE('11/12/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, TO_DATE('11/12/2008 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 117247, 'Club Car', NULL, NULL,(select id from config_param_option where value='true'),1)
/
COMMIT
/