--PURPOSE    : PATCH FOR ADDING CONFIG PARAM FOR SPECIFYING COST PRICE CONFIGURATION
--AUTHOR     : JITESH JAIN
--CREATED ON : 9-JUN-09

INSERT INTO CONFIG_PARAM
(ID, DESCRIPTION, DISPLAY_NAME, NAME, TYPE, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, D_CREATED_TIME, D_UPDATED_TIME, LOGICAL_GROUP, PARAM_DISPLAY_TYPE, LOGICAL_GROUP_ORDER, SECTIONS, SECTIONS_ORDER, PARAM_ORDER,d_active)
VALUES
(config_param_seq.NEXTVAL, 'Cost Price Type Configuration', 'Cost Price Type Configuration',
    'costPriceConfiguration','string', 
    sysdate, 'Configuration', sysdate, NULL, NULL, 
    NULL, 'SUPPLIER_RECOVERY', 'select', 1, NULL, 
    1, 1,1)
/
insert into config_param_option values (config_param_option_seq.nextval, 'MaterialCost','MaterialCost')
/
insert into config_param_option values (config_param_option_seq.nextval, 'StandardCost','StandardCost')
/
insert into config_param_options_mapping values (
CFG_PARAM_OPTNS_MAPPING_SEQ.nextval,
(SELECT ID FROM CONFIG_PARAM WHERE NAME = 'costPriceConfiguration'),
(SELECT ID FROM CONFIG_PARAM_OPTION WHERE value = 'MaterialCost')
)
/
insert into config_param_options_mapping values (
CFG_PARAM_OPTNS_MAPPING_SEQ.nextval,
(SELECT ID FROM CONFIG_PARAM WHERE NAME = 'costPriceConfiguration'),
(SELECT ID FROM CONFIG_PARAM_OPTION WHERE value = 'StandardCost')
)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, null, (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'costPriceConfiguration'),
sysdate, NULL, sysdate, NULL, 'Transport Solutions ESA', NULL, NULL,
(SELECT ID FROM CONFIG_PARAM_OPTION WHERE value = 'StandardCost'),1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, null, (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'costPriceConfiguration'),
sysdate, NULL, sysdate, NULL, 'Clubcar ESA', NULL, NULL,
(SELECT ID FROM CONFIG_PARAM_OPTION WHERE value = 'StandardCost'),1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, null, (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'costPriceConfiguration'),
sysdate, NULL, sysdate, NULL, 'Hussmann', NULL, NULL,
(SELECT ID FROM CONFIG_PARAM_OPTION WHERE value = 'StandardCost'),1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, null, (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'costPriceConfiguration'),
sysdate, NULL, sysdate, NULL, 'TFM', NULL, NULL,
(SELECT ID FROM CONFIG_PARAM_OPTION WHERE value = 'StandardCost'),1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, null, (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'costPriceConfiguration'),
sysdate, NULL, sysdate, NULL, 'AIR', NULL, NULL,
(SELECT ID FROM CONFIG_PARAM_OPTION WHERE value = 'StandardCost'),1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, null, (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'costPriceConfiguration'),
sysdate, NULL, sysdate, NULL, 'Club Car', NULL, NULL,
(SELECT ID FROM CONFIG_PARAM_OPTION WHERE value = 'StandardCost'),1)
/
INSERT INTO CONFIG_VALUE 
(ID, ACTIVE, VALUE, CONFIG_PARAM, D_CREATED_ON, D_INTERNAL_COMMENTS, D_UPDATED_ON, D_LAST_UPDATED_BY, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, CONFIG_PARAM_OPTION,d_active) 
VALUES 
(config_value_seq.NEXTVAL, 1, null, (SELECT ID FROM CONFIG_PARAM WHERE NAME = 'costPriceConfiguration'),
sysdate, NULL, sysdate, NULL, 'TK', NULL, NULL,
(SELECT ID FROM CONFIG_PARAM_OPTION WHERE value = 'StandardCost'),1)
/
COMMIT
/