--Add business unit info to recovery claim
--Author prashanth konda
--13th march 2009

ALTER TABLE RECOVERY_CLAIM ADD ( BUSINESS_UNIT_INFO VARCHAR2(255))
/
UPDATE RECOVERY_CLAIM RC SET RC.BUSINESS_UNIT_INFO = (SELECT BUSINESS_UNIT_INFO
 FROM CLAIM C WHERE C.ID = RC.CLAIM )
/
COMMIT
/
 

