--Purpose    : Modification of Marketing_Information(Change of FK) and TRANSACTION_TYPE(Change of PK) tables for static i18n purpose
--Author     : shraddha.nanda
--Created On : 22-Aug-08
ALTER TABLE marketing_information
DROP CONSTRAINT MKTINGINFO_TRANSACTIONTYPE_FK
/
ALTER TABLE TRANSACTION_TYPE
drop primary key
/
alter table TRANSACTION_TYPE add ID Number(19,0)
/
CREATE SEQUENCE TRANSACTION_TYPE_SEQ
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
/
update TRANSACTION_TYPE set ID = TRANSACTION_TYPE_SEQ.nextval
/
COMMIT
/
ALTER TABLE TRANSACTION_TYPE ADD(CONSTRAINT TRANSACTION_TYPE_ID_PK PRIMARY KEY(ID))
/
declare
CURSOR GET_transType  IS
select * from MARKETING_INFORMATION WHERE TRANSACTION_TYPE IS NOT NULL;

v_transType number:=0;
v_transTypePrev varchar(255) ;

BEGIN
FOR GET_REC IN GET_transType LOOP
	select id into 	v_transType from TRANSACTION_TYPE where type=GET_REC.transaction_type;
	update MARKETING_INFORMATION set transaction_type=v_transType where id=GET_REC.id;
END LOOP;
END;
/
COMMIT
/
CREATE TABLE DUMMY_MARKETING_INFORMATION (ID NUMBER(19), TRANSACTION_TYPE VARCHAR2(255))
/
declare
CURSOR GET_transType  IS
select * from MARKETING_INFORMATION ;
BEGIN
FOR GET_REC IN GET_transType LOOP
	INSERT INTO DUMMY_MARKETING_INFORMATION (ID,TRANSACTION_TYPE) 
values (GET_REC.ID ,GET_REC.TRANSACTION_TYPE );
	END LOOP;
END;
/
COMMIT
/
Update MARKETING_INFORMATION set TRANSACTION_TYPE=null
/
COMMIT
/
ALTER TABLE MARKETING_INFORMATION MODIFY TRANSACTION_TYPE NUMBER(19,0)
/
ALTER TABLE MARKETING_INFORMATION ADD CONSTRAINT MKTINGINFO_TRANSACTIONTYPE_FK 
FOREIGN KEY(TRANSACTION_TYPE) REFERENCES TRANSACTION_TYPE(ID)
/
declare

CURSOR GET_transType  IS
select * from DUMMY_MARKETING_INFORMATION WHERE TRANSACTION_TYPE IS NOT NULL;

BEGIN
FOR GET_REC IN GET_transType LOOP
	update MARKETING_INFORMATION set transaction_type=GET_REC.transaction_type where id=GET_REC.id;
	END LOOP;
END;
/
COMMIT
/
drop table DUMMY_MARKETING_INFORMATION
/