-- FOR MISCELLANEOUS PARTS WHICH ARE USED BY TK
-- Author Prashanth Konda
-- Date December 4th 2008

CREATE TABLE MISC_ITEM (ID NUMBER(19) NOT NULL,PART_NUMBER VARCHAR2(50),DESCRIPTION VARCHAR2(50), CONSTRAINT MISCELLANEOUS_ITEM_PK PRIMARY KEY (ID)) 
/
CREATE SEQUENCE  "MISC_ITEM_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 100 NOCACHE  NOORDER  NOCYCLE 
/
CREATE TABLE MISC_ITEM_CRITERIA(ID NUMBER(19) NOT NULL,CONFIG_NAME VARCHAR2(50),DEALER NUMBER(19),DEALER_GROUP NUMBER(19),ACTIVE NUMBER(1) DEFAULT 1 , CONSTRAINT MISC_ITEM_CRITERIA_PK PRIMARY KEY (ID))
/
CREATE SEQUENCE  "MISC_ITEM_CRITERIA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 100 NOCACHE  NOORDER  NOCYCLE 
/
ALTER TABLE MISC_ITEM_CRITERIA ADD CONSTRAINT MISC_ITEM_CRIT_DLR_ID_FK FOREIGN KEY (DEALER) REFERENCES DEALERSHIP(ID) ENABLE VALIDATE
/
ALTER TABLE MISC_ITEM_CRITERIA ADD CONSTRAINT MISC_ITEM_CRIT_DLR_GRP_ID_FK FOREIGN KEY (DEALER_GROUP) REFERENCES DEALER_GROUP(ID) ENABLE VALIDATE
/
CREATE TABLE MISC_ITEM_CONFIG (ID NUMBER(19) NOT NULL,MISC_ITEM NUMBER(19),ACTIVE NUMBER(1),FOR_CRITERIA NUMBER(19),COST_PRICE_AMT NUMBER(19,2),COST_PRICE_CURR VARCHAR2(20),TRESHOLD_QUANTITY NUMBER(19),UOM VARCHAR2(50), CONSTRAINT MISCELLANEOUS_ITEM_CONFIG_PK PRIMARY KEY (ID) )
/
CREATE SEQUENCE "MISC_ITEM_CONFIG_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 100 NOCACHE  NOORDER  NOCYCLE 
/
ALTER TABLE MISC_ITEM_CONFIG ADD CONSTRAINT MISC_ITEM_CFG_MISC_ITEM_ID_FK FOREIGN KEY (MISC_ITEM) REFERENCES MISC_ITEM(ID) ENABLE VALIDATE
/
ALTER TABLE MISC_ITEM_CONFIG ADD CONSTRAINT MISC_ITEM_CFG_MISC_CRIT_ID_FK FOREIGN KEY (FOR_CRITERIA) REFERENCES MISC_ITEM_CRITERIA(ID) ENABLE VALIDATE
/
CREATE TABLE SERVICE_MISC_PARTS_REPLACED ( SERVICE NUMBER(19), MISC_PARTS_REPLACED NUMBER(19) ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING
/
ALTER TABLE SERVICE_MISC_PARTS_REPLACED ADD UNIQUE (SERVICE, MISC_PARTS_REPLACED)
/
ALTER TABLE SERVICE_MISC_PARTS_REPLACED ADD CONSTRAINT SERVICE_MSC_PRT_RPLCD_SER FOREIGN KEY (SERVICE) REFERENCES SERVICE(ID) ENABLE VALIDATE
/
ALTER TABLE SERVICE_MISC_PARTS_REPLACED ADD CONSTRAINT SERVICE_MSC_PRT_RPLCD_PRT FOREIGN KEY (MISC_PARTS_REPLACED) REFERENCES NON_OEM_PART_REPLACED(ID) ENABLE VALIDATE
/
INSERT INTO SECTION (ID, DISPLAY_POSITION, NAME, VERSION) values ((select max(id) + 1 from section),10 ,'MiscellaneousParts' ,1)
/
INSERT INTO COST_CATEGORY (ID, CODE, DESCRIPTION, NAME, VERSION) values ((select max(id)+1 from cost_category), 'MISC_PARTS','Miscellaneous Parts','MiscellaneousParts',1)
/
ALTER TABLE NON_OEM_PART_REPLACED ADD (MISC_ITEM_CONFIG NUMBER(19))
/
ALTER TABLE NON_OEM_PART_REPLACED ADD CONSTRAINT NON_OEM_MISC_ITEM_CFG_ID_FK FOREIGN KEY (MISC_ITEM_CONFIG) REFERENCES MISC_ITEM_CONFIG(ID) ENABLE VALIDATE
/
ALTER TABLE CLAIM ADD (MISC_PARTS_CONFIG NUMBER(1)  DEFAULT 0)
/
ALTER TABLE OEM_PART_REPLACED ADD (UOM_MAPPING NUMBER(19))
/
ALTER TABLE OEM_PART_REPLACED ADD CONSTRAINT OEM_PRT_RPLCD_UOM_MPPING_FK FOREIGN KEY (UOM_MAPPING) REFERENCES UOM_MAPPINGS(ID) ENABLE VALIDATE
/
insert into config_param (ID, DESCRIPTION, DISPLAY_NAME, NAME, TYPE,PARAM_DISPLAY_TYPE) values (config_param_seq.nextval,'Enable UOM in price calculation','Enable UOM in price calculation','isUomEnabled','boolean','radio')
/
insert into config_param_options_mapping values ( CFG_PARAM_OPTNS_MAPPING_SEQ.nextval, (select id from  config_param cp where name='isUomEnabled'),  (select id from  config_param_option cpo where cpo.DISPLAY_VALUE ='Yes')) 
/  
insert into config_param_options_mapping values ( CFG_PARAM_OPTNS_MAPPING_SEQ.nextval, (select id from  config_param cp where name='isUomEnabled'),  (select id from  config_param_option cpo where cpo.DISPLAY_VALUE ='No')) 
/
insert into  config_value (id,value,config_param,business_unit_info,active)  values (CONFIG_VALUE_SEQ.nextval, ( select id from cost_category where name= 'MiscellaneousParts') ,(select id from config_param where name= 'configuredCostCategories'), 'Club Car',1 )
/
insert into i18nsection_text values ((select max(id)+1 from i18nsection_text) , 'en_US','MiscellaneousParts',(select id from section where name='MiscellaneousParts' ) )
/
insert into i18nsection_text values ((select max(id)+1 from i18nsection_text) , 'en_EN','MiscellaneousParts',(select id from section where name='MiscellaneousParts' ) )
/
insert into i18nsection_text values ((select max(id)+1 from i18nsection_text) , 'fr_FR','MiscellaneousParts',(select id from section where name='MiscellaneousParts' ) )
/
insert into i18nsection_text values ((select max(id)+1 from i18nsection_text) , 'de_DE','MiscellaneousParts',(select id from section where name='MiscellaneousParts' ) )
/
COMMIT
/