--Purpose    : Insert Item Condition for each Policy Definition
--Author     : Jitesh Jain
--Created On : 30-Ssep-08

CREATE OR REPLACE PROCEDURE INSERT_ITEM_COND_POLICY_DEF AS

CURSOR C1 IS
SELECT ID, AVAILABILITY_ITEM_CONDITION
FROM POLICY_DEFINITION;

BEGIN

FOR c1_rec IN c1 LOOP 

INSERT INTO POLICY_FOR_ITEMCONDITIONS VALUES (c1_rec.ID, c1_rec.AVAILABILITY_ITEM_CONDITION);

COMMIT;

END LOOP;
END;
/
BEGIN
INSERT_ITEM_COND_POLICY_DEF();
END;
/
