--Purpose    : To populate values in TravelRateValues for existing Travel Rate
--Author     : chandrakant
--Created On : 11-Feb-08


CREATE OR REPLACE PROCEDURE INSERT_TRAVEL_RATE_VALUES AS
CURSOR tr IS
SELECT ID, DISTANCE_RATE_AMT, DISTANCE_RATE_CURR, HOURLY_RATE_AMT, 
HOURLY_RATE_CURR, TRIP_RATE_AMT, TRIP_RATE_CURR,TRAVEL_RATES FROM TRAVEL_RATE; 
CURSOR cer IS 
SELECT FROM_CURRENCY FROM CURRENCY_EXCHANGE_RATE;
BEGIN
	 FOR tr_rec IN tr LOOP 
	 	 FOR cer_rec IN cer LOOP
				IF tr_rec.DISTANCE_RATE_CURR = cer_rec.FROM_CURRENCY THEN
					INSERT INTO TRAVEL_RATE_VALUES VALUES (TRAVEL_RATE_VALUES_SEQ.nextval,
					tr_rec.DISTANCE_RATE_AMT, tr_rec.DISTANCE_RATE_CURR, tr_rec.HOURLY_RATE_AMT, 
					tr_rec.HOURLY_RATE_CURR, tr_rec.TRIP_RATE_AMT, tr_rec.TRIP_RATE_CURR,tr_rec.ID);
				ELSE
					INSERT INTO TRAVEL_RATE_VALUES VALUES (TRAVEL_RATE_VALUES_SEQ.nextval,
					0, cer_rec.FROM_CURRENCY, 0, cer_rec.FROM_CURRENCY,
					0, cer_rec.FROM_CURRENCY,tr_rec.ID);
				END IF;
		END LOOP;
	END LOOP;
	COMMIT;
END;
/
BEGIN
INSERT_TRAVEL_RATE_VALUES();
END;
/
