--Purpose    : To populate values in LaborRateValues for existing Labor Rate
--Author     : chandrakant
--Created On : 11-Feb-08


CREATE OR REPLACE PROCEDURE INSERT_LABOR_RATE_VALUES AS
CURSOR lt IS
SELECT ID, AMT, CURR FROM LABOR_RATE WHERE ID NOT IN (SELECT DISTINCT LABOR_RATE FROM LABOR_RATE_VALUES);
CURSOR cer IS 
SELECT FROM_CURRENCY FROM CURRENCY_EXCHANGE_RATE;
BEGIN
 FOR lt_rec IN lt LOOP 
	 	 FOR cer_rec IN cer LOOP
				IF lt_rec.CURR = cer_rec.FROM_CURRENCY THEN
					INSERT INTO LABOR_RATE_VALUES VALUES (LABOR_RATE_VALUES_SEQ.nextval,
					lt_rec.AMT,cer_rec.FROM_CURRENCY,lt_rec.ID);
				ELSE
					INSERT INTO LABOR_RATE_VALUES VALUES (LABOR_RATE_VALUES_SEQ.nextval,
					0,cer_rec.FROM_CURRENCY,lt_rec.ID);
				END IF;
 		END LOOP;
	END LOOP;
	COMMIT;
END;
/
BEGIN
INSERT_LABOR_RATE_VALUES();
END;
/
