--For bug fix  ESESA-916 - SCRIPT to UPDATE the MODEL ID in ITEMS_IN_GROUP  table with the MODEL ID present in the ITEM table 
--i.e. wherever these 2 are not consistent.

CREATE OR REPLACE PROCEDURE ITEM_SYNC_MODEL_CLEAN_UP
AS

CURSOR C1 IS
SELECT I.ID AS ITEM_ID, I.BUSINESS_UNIT_INFO, I.ITEM_NUMBER, IG1.ID AS VALID_MODEL_ID, IG1.GROUP_CODE AS VALID_MODEL_CODE
, IG2.ID AS INVALID_MODEL_ID, IG2.GROUP_CODE AS INVALID_MODEL_CODE
FROM ITEM I, ITEMS_IN_GROUP IIG, ITEM_GROUP IG1, ITEM_GROUP IG2
WHERE
I.ID = IIG.ITEM
AND I.MODEL <> IIG.ITEM_GROUP
AND I.MODEL = IG1.ID
AND IIG.ITEM_GROUP = IG2.ID ;

V_IS_PRESENT number := 0;

BEGIN

FOR C1_REC IN C1 LOOP

BEGIN
SELECT 1 INTO V_IS_PRESENT FROM
ITEMS_IN_GROUP WHERE ITEM = C1_REC.ITEM_ID
AND ITEM_GROUP = C1_REC.VALID_MODEL_ID ;
EXCEPTION
WHEN NO_DATA_FOUND
THEN

UPDATE ITEMS_IN_GROUP SET ITEM_GROUP = C1_REC.VALID_MODEL_ID
WHERE ITEM = C1_REC.ITEM_ID AND ITEM_GROUP = C1_REC.INVALID_MODEL_ID ;

END ;

IF (V_IS_PRESENT = 1)
THEN

DELETE FROM ITEMS_IN_GROUP WHERE
ITEM = C1_REC.ITEM_ID AND ITEM_GROUP = C1_REC.INVALID_MODEL_ID ;

END IF;
COMMIT;


END LOOP ;
COMMIT;

END;
/ 