--Purpose    : Updated table for User Availability
--Author     : Jhulfikar Ali. A
--Created On : 19-Feb-09

CREATE TABLE USER_BU_AVAILABILITY (
  ID NUMBER NOT NULL,
  ORG_USER NUMBER,
  role NUMBER, 
  BUSINESS_UNIT_INFO VARCHAR2(255),
  AVAILABLE NUMBER(1), 
  default_to_role NUMBER(1),
  CONSTRAINT USER_BU_AVAILABILITY_PK PRIMARY KEY(ID)
)
/
ALTER TABLE USER_BU_AVAILABILITY
ADD CONSTRAINT USER_BU_AVAILABILITY_USER_FK FOREIGN KEY(ORG_USER)
REFERENCES ORG_USER(ID)
/
alter table USER_BU_AVAILABILITY add constraint FK_USER_BU_AVL_ROLE 
foreign key(role) 
references ROLE(ID)
/
drop table USER_BU_AVAILABLITY
/
drop table USER_DEFAULT_ROLES
/
COMMIT
/