--Name :Joseph
--Date : 2 June 2011
--Impact : Disables indexes/constraints in 6.0 to improve performance of inserts

DECLARE

CURSOR cur_det_table
IS
SELECT DISTINCT B.INDEX_NAME,b.status
FROM TAV_GIM_VALID_TABLES A,
  USER_INDEXES B,
  USER_IND_COLUMNS C
WHERE A.TABLE_NAME = B.TABLE_NAME
and B.UNIQUENESS   = 'NONUNIQUE'
and B.INDEX_NAME  = C.INDEX_NAME
and B.INDEX_NAME <> 'WARRANTY_I2'
and a.lookup_function is null
and not exists
(
select  1 from USER_CONS_COLUMNS D , USER_CONSTRAINTS E
where E.CONSTRAINT_NAME = D.CONSTRAINT_NAME
and E.CONSTRAINT_TYPE = 'P'
and D.COLUMN_NAME = C.COLUMN_NAME
and d.table_name = c.table_name
)
;


CURSOR cur_det_table_1
IS
SELECT A.TABLE_NAME FROM TAV_GIM_VALID_TABLES A  ORDER BY a.EXEC_ORDER;


BEGIN 


execute immediate 'alter table LINE_ITEM_GROUPS disable constraint LINEITEMGROUPS_LINEITEMGRPS_FK';
EXECUTE IMMEDIATE 'alter table LINE_ITEM_GROUPS disable constraint LINEITEMGROUPS_FORPAYMENT_FK';


EXECUTE IMMEDIATE 'ALTER TABLE LABOR_SPLIT_DETAILS disable CONSTRAINT SLT_DTL_GRP_AUDIT_FK';
EXECUTE IMMEDIATE 'alter table LABOR_SPLIT_DETAILS disable constraint LABOR_SPLIT_LINE_ITEM_GROUP_FK';

EXECUTE IMMEDIATE 'ALTER TABLE INV_ITEM_ATTR_VALS disable CONSTRAINT INVITEMATTRVALS_INVITEMID_FK';
EXECUTE IMMEDIATE 'alter table INV_ITEM_ATTR_VALS disable constraint INVATTRVAL_INVITEMATTRVALID_FK';

EXECUTE IMMEDIATE 'ALTER TABLE ADD_PAYMENT_INFO disable CONSTRAINT  ADD_PYM_INFO_LINE_ITEM_GRP_FK';
EXECUTE IMMEDIATE 'ALTER TABLE ADD_PAYMENT_INFO disable CONSTRAINT  ADDITIONAL_PAYMENT_INFO_FK';

EXECUTE IMMEDIATE 'ALTER TABLE MODIFIERS  disable CONSTRAINT MODIFIERS_LINE_ITE_FK';
EXECUTE IMMEDIATE 'ALTER TABLE MODIFIERS  disable CONSTRAINT MODIFIERS_LINE_ITEM_GROUP_FK';

EXECUTE IMMEDIATE 'alter table I18NITEM_TEXT disable constraint I18NITEM_TEXT_ITEM_FK';




  FOR cur_det_table_rec_1 IN cur_det_table_1	LOOP
		BEGIN
	  EXECUTE IMMEDIATE 'ALTER TABLE ' || cur_det_table_rec_1.TABLE_NAME || ' NOLOGGING';
    EXCEPTION
		when OTHERS then
		null;
		END;
	END LOOP;

  
	FOR cur_det_table_rec IN cur_det_table	LOOP
		BEGIN		
		EXECUTE IMMEDIATE 'ALTER INDEX ' || CUR_DET_TABLE_REC.INDEX_NAME || ' UNUSABLE';
--		EXECUTE IMMEDIATE 'ALTER INDEX ' || cur_det_table_rec.INDEX_NAME || ' NOLOGGING';
		EXCEPTION
		when OTHERS then
		null;
		end;
	END LOOP;
	
EXCEPTION
when OTHERS then
DBMS_OUTPUT.PUT_LINE('0' || SQLERRM);
END;
/