--Purpose    : Scripts for creating constraints on Staging tables, changes made as a part of 4.3 upgrade
--Created On : 15-Mar-2011
--Created By : Kuldeep Patil
--Impact     : None

ALTER TABLE STG_UPDATE_JOB_CODE ADD CONSTRAINT STG_UPD_JOB_CODE_FK FOREIGN KEY (FILE_UPLOAD_MGT_ID)
REFERENCES FILE_UPLOAD_MGT(ID)
/
ALTER TABLE STG_ALTER_SERIALNUMBER ADD CONSTRAINT STG_ALT_SER_NUM_FK FOREIGN KEY (FILE_UPLOAD_MGT_ID)
REFERENCES FILE_UPLOAD_MGT(ID)
/
ALTER TABLE STG_WNTY_CVG_EXCLUSION ADD CONSTRAINT STG_WNTY_CVG_EXCL_FK FOREIGN KEY (FILE_UPLOAD_MGT_ID)
REFERENCES FILE_UPLOAD_MGT(ID)
/
ALTER TABLE STG_WARRANTY_COVERAGES ADD CONSTRAINT STG_WNTY_COVERAGES_FK FOREIGN KEY (FILE_UPLOAD_MGT_ID)
REFERENCES FILE_UPLOAD_MGT(ID)
/
ALTER TABLE STG_THIRD_PARTY ADD CONSTRAINT STG_THIRD_PARTY_FK FOREIGN KEY (FILE_UPLOAD_MGT_ID)
REFERENCES FILE_UPLOAD_MGT(ID)
/
ALTER TABLE STG_COST_PRICE ADD CONSTRAINT STG_COST_PRICE_FK FOREIGN KEY (FILE_UPLOAD_MGT_ID)
REFERENCES FILE_UPLOAD_MGT(ID)
/
ALTER TABLE STG_DRAFT_CLAIM ADD CONSTRAINT STG_DRAFT_CLAIM_FK FOREIGN KEY (FILE_UPLOAD_MGT_ID)
REFERENCES FILE_UPLOAD_MGT(ID)
/
ALTER TABLE CUSTOMER_STAGING ADD CONSTRAINT CUSTOMER_STAGING_FK FOREIGN KEY (FILE_UPLOAD_MGT_ID)
REFERENCES FILE_UPLOAD_MGT(ID)
/
ALTER TABLE ITEM_STAGING ADD CONSTRAINT ITEM_STAGING_FK FOREIGN KEY (FILE_UPLOAD_MGT_ID)
REFERENCES FILE_UPLOAD_MGT(ID)
/
ALTER TABLE STG_PART_SRC_HIST_UPLD ADD CONSTRAINT STG_PART_SRC_HIST_UPLD_FK FOREIGN KEY (FILE_UPLOAD_MGT_ID)
REFERENCES FILE_UPLOAD_MGT(ID)
/
ALTER TABLE STG_COPY_JOB_CODE_FF ADD CONSTRAINT STG_COPY_JOB_CODE_FF_FK FOREIGN KEY (FILE_UPLOAD_MGT_ID)
REFERENCES FILE_UPLOAD_MGT(ID)
/
delete from STG_JOB_CODE a 
where not exists
(
select 1 from FILE_UPLOAD_MGT b where b.id = a.FILE_UPLOAD_MGT_ID
)
/
commit
/
ALTER TABLE STG_JOB_CODE ADD CONSTRAINT STG_JOB_CODE_FK FOREIGN KEY (FILE_UPLOAD_MGT_ID)
REFERENCES FILE_UPLOAD_MGT(ID)
/
ALTER TABLE STG_INSTALL_BASE ADD CONSTRAINT STG_INSTALL_BASE_FK FOREIGN KEY (FILE_UPLOAD_MGT_ID)
REFERENCES FILE_UPLOAD_MGT(ID)
/
ALTER TABLE STG_REQUESTS_FOR_EXTENSION ADD CONSTRAINT STG_REQUESTS_FOR_EXTENSION_FK FOREIGN KEY (FILE_UPLOAD_MGT_ID)
REFERENCES FILE_UPLOAD_MGT(ID)
/
ALTER TABLE STG_WARRANTY_REGISTRATIONS ADD CONSTRAINT STG_WARRANTY_REGISTRATIONS_FK FOREIGN KEY (FILE_UPLOAD_MGT_ID)
REFERENCES FILE_UPLOAD_MGT(ID)
/
ALTER TABLE STG_SUPPLIER_DECISION ADD CONSTRAINT STG_SUPPLIER_DECISION_FK FOREIGN KEY (FILE_UPLOAD_MGT_ID)
REFERENCES FILE_UPLOAD_MGT(ID)
/
commit
/