--Purpose    : Scripts for creating Staging tables, changes made as a part of 4.3 upgrade, as per mail from Rajakamal 
--Created On : 14-Mar-2011
--Created By : Kuldeep Patil
--Impact     : None

CREATE TABLE STG_WARRANTY_COVERAGES
(
ID                  NUMBER,
FILE_UPLOAD_MGT_ID  NUMBER,
BUSINESS_UNIT_INFO  VARCHAR2(255 BYTE),
SERIAL_NUMBER       VARCHAR2(255 BYTE),
ITEM_NUMBER         VARCHAR2(255 BYTE),
PLAN_CODE           VARCHAR2(255 BYTE),
WARRANTY_START_DATE VARCHAR2(10 BYTE),
WARRANTY_END_DATE   VARCHAR2(10 BYTE),
HOURS_COVERED       NUMBER,
ORDER_DATE          VARCHAR2(10 BYTE),
ORDER_NUMBER        VARCHAR2(255 BYTE),
FORCE_COVERAGE      VARCHAR2(100 BYTE),
COMMENTS            VARCHAR2(255 BYTE),
ERROR_STATUS        VARCHAR2(20 BYTE),
ERROR_CODE          VARCHAR2(4000 BYTE),
UPLOAD_STATUS       VARCHAR2(20 BYTE),
UPLOAD_ERROR        VARCHAR2(4000 BYTE)
)
/
commit
/
CREATE TABLE STG_ALTER_SERIALNUMBER
(
ID                 NUMBER,
FILE_UPLOAD_MGT_ID NUMBER,
SERIAL_NUMBER      VARCHAR2(255 CHAR),
ITEM_NUMBER        VARCHAR2(255 CHAR),
ACTION             VARCHAR2(255 BYTE),
INTERNAL_COMMENTS  VARCHAR2(1000 BYTE),
ERROR_STATUS       VARCHAR2(20 BYTE),
ERROR_CODE         VARCHAR2(4000 BYTE),
UPLOAD_STATUS      VARCHAR2(20 BYTE),
UPLOAD_ERROR       VARCHAR2(4000 BYTE),
UPLOAD_DATE        VARCHAR2(20 BYTE),
SN_ID              NUMBER(*,0) DEFAULT NULL
)
/
commit
/
CREATE TABLE STG_THIRD_PARTY
(
ID                    NUMBER,
FILE_UPLOAD_MGT_ID    NUMBER,
THIRD_PARTY_NUMBER    VARCHAR2(4000 BYTE),
THIRD_PARTY_NAME      VARCHAR2(4000 BYTE),
THIRD_PARTY_SITE_CODE VARCHAR2(4000 BYTE),
PREFERRED_CURRENCY    VARCHAR2(4000 BYTE),
CONTACT_PERSON        VARCHAR2(4000 BYTE),
ADDR1                 VARCHAR2(4000 BYTE),
ADDR2                 VARCHAR2(4000 BYTE),
CITY                  VARCHAR2(4000 BYTE),
STATE                 VARCHAR2(4000 BYTE),
POSTAL_CODE           VARCHAR2(4000 BYTE),
COUNTRY               VARCHAR2(4000 BYTE),
PHONE                 VARCHAR2(4000 BYTE),
EMAIL                 VARCHAR2(4000 BYTE),
STATUS                VARCHAR2(4000 BYTE),
IS_PRIMARY            VARCHAR2(4000 BYTE),
BUSINESS_UNIT_INFO    VARCHAR2(4000 BYTE),
ADDR3                 VARCHAR2(255 BYTE),
ADDR4                 VARCHAR2(255 BYTE),
ERROR_STATUS          VARCHAR2(20 BYTE),
ERROR_CODE            VARCHAR2(4000 BYTE),
UPLOAD_STATUS         VARCHAR2(20 BYTE),
UPLOAD_ERROR          VARCHAR2(4000 BYTE),
UPLOAD_DATE           VARCHAR2(20 BYTE)
)
/
commit
/
CREATE TABLE STG_WNTY_CVG_EXCLUSION
(
ID                  NUMBER,
FILE_UPLOAD_MGT_ID  NUMBER,
POLICY_NAME         VARCHAR2(4000 BYTE),
DEALER_NUMBER       VARCHAR2(4000 BYTE),
BUSINESS_UNIT_INFO  VARCHAR2(4000 BYTE),
IS_REMOVE_EXCLUSION VARCHAR2(20 BYTE),
ERROR_STATUS        VARCHAR2(20 BYTE),
ERROR_CODE          VARCHAR2(4000 BYTE),
UPLOAD_STATUS       VARCHAR2(20 BYTE),
UPLOAD_ERROR        VARCHAR2(4000 BYTE),
UPLOAD_DATE         VARCHAR2(20 BYTE)
)
/
commit
/
CREATE TABLE STG_UPDATE_JOB_CODE
(
ID                      NUMBER,
FILE_UPLOAD_MGT_ID      NUMBER,
BUSINESS_UNIT_NAME      VARCHAR2(255 BYTE),
PRODUCT_CODE            VARCHAR2(255 BYTE),
FIELD_MODEL             VARCHAR2(255 BYTE),
JOB_CODE                VARCHAR2(255 BYTE),
ACTION                  VARCHAR2(255 BYTE),
LABOR_STANDARD_HOURS    VARCHAR2(255 BYTE),
LABOR_STANDARD_MINUTES  VARCHAR2(255 BYTE),
FIELD_MODIFICATION_ONLY VARCHAR2(255 BYTE),
COMPLETE_JOB_CODE       VARCHAR2(255 BYTE),
UPDATE_LEVEL            VARCHAR2(255 BYTE),
ITEM_GROUP_ID           NUMBER,
SP_COUNT                NUMBER,
ERROR_STATUS            VARCHAR2(20 BYTE),
ERROR_CODE              VARCHAR2(4000 BYTE),
UPLOAD_STATUS           VARCHAR2(20 BYTE),
UPLOAD_ERROR            VARCHAR2(4000 BYTE)
)
/
commit
/