create index CLAIM_AUDIT_HISTORICAL_IDX1 on CLAIM_AUDIT_HISTORICAL(AUDIT_ID)
/
create index CLAIM_AUDIT_HIST_LABOR_IDX1 on CLAIM_AUDIT_HIST_LABOR(AUDIT_ID)
/
create index CLAIM_AUDIT_HIST_PARTS_IDX1 on CLAIM_AUDIT_HIST_PARTS(AUDIT_ID)
/
create index CLAIM_AUDIT_HIST_TRAVEL_IDX1 on CLAIM_AUDIT_HIST_TRAVEL(AUDIT_ID)
/
create index CLM_AUDIT_HIST_INCIDENTAL_IDX1 on CLAIM_AUDIT_HIST_INCIDENTALS(AUDIT_ID)
/
create index CLAIM_AUDIT_HIST_NONOEM_IDX1 on CLAIM_AUDIT_HIST_NONOEM_PARTS(AUDIT_ID)
/
