-- Table for Part Recovery audit
-- Created By : deepak patel
-- Created on date 11th July 2013
CREATE SEQUENCE PART_RECOVERY_AUDIT_SEQ MINVALUE 1000 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 1000 NOCACHE NOORDER NOCYCLE
/
CREATE TABLE PART_RECOVERY_AUDIT
   (	
    "ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VERSION" NUMBER(10,0) NOT NULL ENABLE,
	"COMMENTS" VARCHAR2(4000 BYTE), 
	"PR_STATUS" VARCHAR2(255 CHAR), 
	"FOR_PART_REPLACED" NUMBER(19,0) NOT NULL ENABLE, 
	"D_LAST_UPDATED_BY" NUMBER(19,0), 
	"D_UPDATED_ON" DATE, 
	"D_CREATED_ON" DATE, 
	"D_INTERNAL_COMMENTS" VARCHAR2(255 CHAR), 
	"D_CREATED_TIME" TIMESTAMP (6), 
	"D_UPDATED_TIME" TIMESTAMP (6), 
	"D_ACTIVE" NUMBER(1,0) DEFAULT 1, 
	"LIST_INDEX" NUMBER(19,0), 
     CONSTRAINT PRT_REC_AUDIT_PK PRIMARY KEY (ID),
  	 CONSTRAINT PRT_REC_AUDIT_PK_PART FOREIGN KEY (FOR_PART_REPLACED) REFERENCES RECOVERABLE_PART (ID) ENABLE, 
	 CONSTRAINT PRTRECADT_REF_UPDATED_BY FOREIGN KEY (D_LAST_UPDATED_BY) REFERENCES ORG_USER ("ID") ENABLE 
) 
/
CREATE INDEX PRTRECADT_IDX_FORPRTREP ON PART_RECOVERY_AUDIT (FOR_PART_REPLACED)
/
alter table RECOVERABLE_PART add (STATUS VARCHAR2(255 CHAR))
/
  
