--Purpose    : Create table for brand item
--Created On : 12-Nov-2012
--Created By : PRACHER PANCHOLI

CREATE TABLE BRAND_ITEM
(
  BRAND    VARCHAR2(255 CHAR) NOT NULL ENABLE,
  ITEM_NUMBER VARCHAR2(255 CHAR) NOT NULL ENABLE,
  ITEM NUMBER(19,0) NOT NULL ENABLE,
  CONSTRAINT BRD_ITM_FK FOREIGN KEY (ITEM) REFERENCES ITEM (ID) ENABLE
)
/
