--PURPOSE    : PATCH TO ADD COLUMNS NOMS_POLICY_OPTION_CODE AND NOMS_TIER_DESCRIPTION
--AUTHOR     : PARTHASARATHY R
--CREATED ON : 09-OCT-12

ALTER TABLE POLICY_DEFINITION ADD NOMS_POLICY_OPTION_CODE VARCHAR2(255)
/
ALTER TABLE POLICY_DEFINITION ADD NOMS_TIER_DESCRIPTION VARCHAR2(255) 
/
commit
/