--PURPOSE    : PATCH FOR CREATING WPRA Table
--AUTHOR     : Deepak Patel
--CREATED ON : 02-Dec-12

CREATE SEQUENCE WPRA_SEQ MINVALUE 1000 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 1000 NOCACHE NOORDER NOCYCLE
/
CREATE TABLE WPRA
  (
    ID  NUMBER(19,0) NOT NULL ENABLE,
	WPRA_NUMBER   VARCHAR2(255),
    GENERATE_DATE TIMESTAMP (6),
    VERSION     NUMBER(10,0) NOT NULL ENABLE,
    DESTINATION NUMBER(19,0),
    SHIPPED_BY  NUMBER(19,0),
    D_CREATED_ON DATE,
    D_INTERNAL_COMMENTS VARCHAR2(255 CHAR),
    D_UPDATED_ON DATE,
    D_LAST_UPDATED_BY NUMBER(19,0),
    D_CREATED_TIME TIMESTAMP (6),
    D_UPDATED_TIME TIMESTAMP (6),
    D_ACTIVE NUMBER(1,0) DEFAULT 1,
    CONSTRAINT WPRA_PK PRIMARY KEY (ID), 
    CONSTRAINT WPRA_SERVPROVDR_FK FOREIGN KEY (SHIPPED_BY) REFERENCES SERVICE_PROVIDER (ID) DISABLE,
    CONSTRAINT WPRA_LST_UPDT_BY_FK FOREIGN KEY (D_LAST_UPDATED_BY) REFERENCES ORG_USER (ID) ENABLE,
    CONSTRAINT WPRA_DESTINATION_FK FOREIGN KEY (DESTINATION) REFERENCES LOCATION (ID) ENABLE
  )
/
