DROP TABLE INVENTORY_ITEM_WAIVER
/

CREATE TABLE INVENTORY_ITEM_WAIVERS
(
    inventory_item NUMBER(19,0),
    waivers NUMBER(19,0),
    CONSTRAINT INV_DTW_INV_FK FOREIGN KEY (inventory_item) REFERENCES INVENTORY_ITEM (ID) ENABLE,
    CONSTRAINT INV_DTW_WV_FK FOREIGN KEY (waivers) REFERENCES DIESEL_TIER_WAIVER (ID) ENABLE
)
/