--Purpose    : Patch for CREATING TABLE CONTRACT_CODE AND MAINTENANCE_CONTRACT AND --INDUSTRY_CODE.
--Author     : Jyoti Chauhan
--Created On : 30-NOV-2012

CREATE SEQUENCE CONTRACT_CODE_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 1 NOCACHE NOORDER NOCYCLE
/
CREATE TABLE CONTRACT_CODE
  (
    ID                 NUMBER(19,0) NOT NULL,
    CONTRACT_CODE      VARCHAR2(255),   
    VERSION            NUMBER(10,0),
    BUSINESS_UNIT_INFO VARCHAR2(255),
    D_CREATED_BY       NUMBER (19),
    D_LAST_UPDATED_BY  NUMBER(19),
    D_CREATED_ON       DATE,
    D_INTERNAL_COMMENTS VARCHAR2(255 ),
    D_UPDATED_ON        DATE,
    D_CREATED_TIME      TIMESTAMP (6),
    D_UPDATED_TIME      TIMESTAMP (6),
    D_ACTIVE            NUMBER(1,0) DEFAULT 1
  )
/
CREATE SEQUENCE MAINTENANCE_CONTRACT_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 1 NOCACHE NOORDER NOCYCLE
/
CREATE TABLE MAINTENANCE_CONTRACT
  (
    ID                        NUMBER(19,0) NOT NULL,
    MAINTENANCE_CONTRACT      VARCHAR2(255),
    VERSION                   NUMBER(10,0),   
    BUSINESS_UNIT_INFO        VARCHAR2(255),
    D_CREATED_BY              NUMBER (19),
    D_LAST_UPDATED_BY         NUMBER(19),
    D_CREATED_ON              DATE,
    D_INTERNAL_COMMENTS       VARCHAR2(255 ),
    D_UPDATED_ON              DATE,
    D_CREATED_TIME            TIMESTAMP (6),
    D_UPDATED_TIME            TIMESTAMP (6),
    D_ACTIVE                  NUMBER(1,0) DEFAULT 1
  )
/
CREATE SEQUENCE INDUSTRY_CODE_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 1 NOCACHE NOORDER NOCYCLE
/
CREATE TABLE INDUSTRY_CODE
  (
    ID                   NUMBER(19,0) NOT NULL,
    INDUSTRY_CODE        VARCHAR2(255),
    VERSION              NUMBER(10,0),   
    BUSINESS_UNIT_INFO   VARCHAR2(255),
    D_CREATED_BY         NUMBER (19),
    D_LAST_UPDATED_BY    NUMBER(19),
    D_CREATED_ON         DATE,
    D_INTERNAL_COMMENTS  VARCHAR2(255 ),
    D_UPDATED_ON         DATE,
    D_CREATED_TIME       TIMESTAMP (6),
    D_UPDATED_TIME       TIMESTAMP (6),
    D_ACTIVE             NUMBER(1,0) DEFAULT 1
  )
/
ALTER TABLE CONTRACT_CODE ADD CONSTRAINT CONTRACT_CODE_PK PRIMARY KEY (ID)
/
ALTER TABLE MAINTENANCE_CONTRACT ADD CONSTRAINT MAINTENANCE_CONTRACT_PK PRIMARY KEY (ID)
/
ALTER TABLE INDUSTRY_CODE ADD CONSTRAINT INDUSTRY_CODE_PK PRIMARY KEY (ID)
/