-- Purpose    : Patch for adding column REC_CLM_CNT_RECOVER_REASON in recovery claim table
-- Author     : PARTHASARATHY R
-- Created On : 04-Dec-2012

ALTER TABLE RECOVERY_CLAIM ADD ("REC_CLM_CANNOT_RECOVER_REASON" NUMBER(19,0))
/
ALTER TABLE RECOVERY_CLAIM ADD (CONSTRAINT "RECCLAIM_RECCLMCNTRECREASON_FK" FOREIGN KEY ("REC_CLM_CANNOT_RECOVER_REASON") REFERENCES LIST_OF_VALUES("ID"))
/