--Purpose    : Patch for ALTER STG_WARRANTY_REGISTRATIONS
--Author     : Jyoti Chauhan	
--Created On : 14-APR-2013

ALTER TABLE STG_WARRANTY_REGISTRATIONS DROP (TRANSACTION_TYPE,
MARKET_TYPE,
FIRST_TIME_OWNER,
COMPETITION_TYPE,
COMPETITOR_MAKE,
NUMBER_OF_MONTHS,
NUMBER_OF_YEARS)
/
ALTER TABLE STG_WARRANTY_REGISTRATIONS ADD DEALER_REPRESENTATIVE VARCHAR2(255)
/
ALTER TABLE STG_WARRANTY_REGISTRATIONS RENAME COLUMN HOURS_ON_MACHINE  to HOURS_ON_TRUCK
/