CREATE TABLE OPTION_INFO
(
    ID      NUMBER(19,0)  NOT NULL ENABLE,
    CONSTRAINT OPTION_INFO_ID_PK PRIMARY KEY (ID) ENABLE,
    OPTION_CODE    VARCHAR2(255 CHAR),
    OPTION_TYPE    VARCHAR2(30 CHAR) NOT NULL ENABLE,
    ORDER_OPTION_LINE_NUMBER    VARCHAR2(255 CHAR) NOT NULL ENABLE,
    OPTION_DESCRIPTION    VARCHAR2(4000 CHAR) NOT NULL ENABLE,
    OPTION_GROSS_PRICE    NUMBER(19,2)  NOT NULL ENABLE,
    OPTION_NET_PRICE    NUMBER(19,2)  NOT NULL ENABLE,
    OPTION_GROSS_VALUE    NUMBER(19,2)  NOT NULL ENABLE,
    OPTION_DISCOUNT_VALUE    NUMBER(19,2)  NOT NULL ENABLE,
    OPTION_NET_VALUE    NUMBER(19,2)  NOT NULL ENABLE,
    OPTION_DISCOUNT_PERCENT    NUMBER(19,2)  NOT NULL ENABLE,
    ACTIVE_INACTIVE_STATUS    VARCHAR2(30 CHAR) NOT NULL ENABLE,
    SPECIAL_OPTION_STATUS    VARCHAR2(30 CHAR) NOT NULL ENABLE,
    DIESEL_TIER    VARCHAR2(30 CHAR) NOT NULL ENABLE
)
/

CREATE SEQUENCE OPTION_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 110000000000440 CACHE 20 NOORDER NOCYCLE
/

CREATE TABLE INVENTORY_ITEM_OPTIONS
(
    inventory_item NUMBER(19,0),
    options NUMBER(19,0),
    CONSTRAINT INV_OPT_FK FOREIGN KEY (inventory_item) REFERENCES INVENTORY_ITEM (ID) ENABLE,
    CONSTRAINT INV_ITM_OPT_FK FOREIGN KEY (options) REFERENCES OPTION_INFO (ID) ENABLE
)
/