--Purpose    : PATCH FOR RENAMING ADDITIONAL COLS IN STG_WARRANTY_REGISTRATIONS.
--Author     : Jyoti Chauhan
--Created On : 13-MAR-2013

ALTER TABLE STG_WARRANTY_REGISTRATIONS RENAME COLUMN CONTRACT_CODES to CONTRACT_CODE
/
ALTER TABLE STG_WARRANTY_REGISTRATIONS RENAME COLUMN MAINTENANCE_CONTRACTS to MAINTENANCE_CONTRACT
/
ALTER TABLE STG_WARRANTY_REGISTRATIONS RENAME COLUMN INDUSTRY_CODES to INDUSTRY_CODE
/