CREATE SEQUENCE CAMPAIGN_SN_COVERAGE_SEQ
 START WITH     1000
 INCREMENT BY   20
 NOCACHE
 NOCYCLE
/
CREATE SEQUENCE CAMPAIGN_RANGE_COVERAGE_SEQ
 START WITH     1000
 INCREMENT BY   20
 NOCACHE
 NOCYCLE
/
commit
/