--PURPOSE    : CREATE TABLE TO TRACK TECHNICIAN CERTIFICATION
--AUTHOR     : SANTISWAROOP.K
--CREATED ON : 11-SEPT-2012

CREATE TABLE TECHNICIAN_CERTIFICATION
  (
    ID                 NUMBER(19,0) NOT NULL ,
    VERSION            NUMBER(10,0) NOT NULL ,
    CERTIFICATION_NAME VARCHAR2(255),
    CERTIFICATION_FROM_DATE DATE,
    CERTIFICATION_TO_DATE DATE,
    RENEW_DATE DATE,
    SERIES     VARCHAR2(255),
    BRAND      VARCHAR2(255),
    TECHNICIAN NUMBER(19,0) NOT NULL ,
    D_CREATED_ON DATE,
    D_INTERNAL_COMMENTS VARCHAR2(255),
    D_UPDATED_ON DATE,
    D_LAST_UPDATED_BY NUMBER(19,0),
    D_CREATED_TIME TIMESTAMP (6),
    D_UPDATED_TIME TIMESTAMP (6),
    D_ACTIVE NUMBER(1,0) DEFAULT 1
  )
/
alter table TECHNICIAN_CERTIFICATION add constraint TECHNICIAN_CERTIFICATION_PK primary key (ID)
/
alter table TECHNICIAN_CERTIFICATION add constraint TECHNICIAN_CERT_LAST_UPDT_BY_FK foreign key (D_LAST_UPDATED_BY) references ORG_USER (ID)
/
alter table TECHNICIAN_CERTIFICATION add constraint TECHNICIANCERT_TECHNICIAN_FK foreign key (TECHNICIAN) references TECHNICIAN (ID)
/