--PURPOSE    : PATCH FOR ADDING ADDITIONAL DISTANCE AND ADDITIONAL_DISTANCE_REASON COL TO TRAVEL_DETAIL TABLE
--AUTHOR     : ROHIT MEHROTRA
--CREATED ON : 15-NOV-2012

alter table travel_detail add (ADDITIONAL_DISTANCE NUMBER(19,2),ADDITIONAL_DISTANCE_REASON VARCHAR2(255 CHAR))
/
