CREATE TABLE DIESEL_TIER_WAIVER
(
    ID      NUMBER(19,0)  NOT NULL ENABLE,
    CONSTRAINT DIESEL_TIER_WAIVER_ID_PK PRIMARY KEY (ID) ENABLE,
    APPROVED_DATE_TIME    TIMESTAMP (6),
    APPROVED_BY_AGENT_NAME VARCHAR2(255 CHAR) NOT NULL ENABLE,
	AGENT_TITLE VARCHAR2(255 CHAR) NOT NULL ENABLE,
	AGENT_TELEPHONE VARCHAR2(255 CHAR) NOT NULL ENABLE,
	AGENT_EMAIL_ADDRESS VARCHAR2(255 CHAR) NOT NULL ENABLE,
	DESTINATION_COUNTRY VARCHAR2(255 CHAR) NOT NULL ENABLE,
	COUNTRY_EMISSION_RATING VARCHAR2(50 CHAR) NOT NULL ENABLE,
	LANGUAGE_CODE VARCHAR2(50 CHAR) NOT NULL ENABLE,
	DISCLAIMER VARCHAR2(4000 CHAR) NOT NULL ENABLE
)
/

CREATE SEQUENCE DIESEL_TIER_WAIVER_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 110000000000440 CACHE 20 NOORDER NOCYCLE
/

CREATE TABLE INVENTORY_ITEM_WAIVER
(
    inventory_item NUMBER(19,0),
    waivers NUMBER(19,0),
    CONSTRAINT INV_DTW_INV_FK FOREIGN KEY (inventory_item) REFERENCES INVENTORY_ITEM (ID) ENABLE,
    CONSTRAINT INV_DTW_WV_FK FOREIGN KEY (waivers) REFERENCES DIESEL_TIER_WAIVER (ID) ENABLE
)
/