--PURPOSE    : PATCH_TO_ADD_NEW_COLUMN_CONTACT_PERSON_NAME IN SHIPMENT_TABLE
--AUTHOR     : Pracher
--CREATED ON : 12-Feb-14



ALTER TABLE SHIPMENT ADD CONTACT_PERSON_NAME VARCHAR2(255 CHAR)
/
commit
/