--PURPOSE    : PATCH FOR ADDING_COL_STG_WARRANTY_REGISTRATIONS
--AUTHOR     : JYOTI CHAUHAN
--CREATED ON : 11-MAR-13

ALTER TABLE STG_WARRANTY_REGISTRATIONS ADD (CONTRACT_CODES VARCHAR2(255),MAINTENANCE_CONTRACTS VARCHAR2(255),INDUSTRY_CODES VARCHAR2(255))
/