--Purpose    : Patch for adding the column CONTRACT_CODES, MAINTENANCE_CONTRACTS, INDUSTRY_CODES in MARKETING_INFORMATION table.
--Author     : Jyoti Chauhan
--Created On : 03-DEC-2012

ALTER TABLE MARKETING_INFORMATION ADD (CONTRACT_CODE NUMBER(19,0),MAINTENANCE_CONTRACT NUMBER(19,0),INDUSTRY_CODE NUMBER(19,0))
/
ALTER TABLE MARKETING_INFORMATION ADD CONSTRAINT MARKET_INFR_CNTRCT_CDE_FK FOREIGN KEY (CONTRACT_CODE) REFERENCES CONTRACT_CODE(ID)
/
ALTER TABLE MARKETING_INFORMATION ADD CONSTRAINT MARKET_INFR_MTNANCE_CNTRCT_FK FOREIGN KEY (MAINTENANCE_CONTRACT) REFERENCES MAINTENANCE_CONTRACT(ID)
/
ALTER TABLE MARKETING_INFORMATION ADD CONSTRAINT MARKET_INFR_INDSTRY_CDE_FK FOREIGN KEY (INDUSTRY_CODE) REFERENCES INDUSTRY_CODE(ID)
/