--PURPOSE    : PATCH FOR CREATING tables Labor_Rate_Audit_History, LABOR_REPAIR_DATE_HISTORY and sequences Labor_Rate_Audit_History_SEQ,LABOR_REPAIR_DATE_HISTORY_SEQ
--AUTHOR     : JYOTI CHAUHAN
--CREATED ON : 12-SEP-12

CREATE SEQUENCE LABOR_RATE_AUDIT_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 1 NOCACHE NOORDER NOCYCLE
/
CREATE TABLE LABOR_RATE_AUDIT
  (
    ID                 NUMBER(19,0) NOT NULL ,
    LABOR_RATES        NUMBER(19,2),
    DEALER             NUMBER(19,2),
    DEALER_GROUP       NUMBER(19,2),
    PRODUCT_NAME       VARCHAR2(255 ),
    WARRANTY_TYPE      VARCHAR2(255 ),
    CLAIM_TYPE         VARCHAR2(255 ),
    CUSTOMER_TYPE      VARCHAR2(50),
    BUSINESS_UNIT_INFO VARCHAR2(255 ),
    D_CREATED_BY       NUMBER (19),
    D_LAST_UPDATED_BY  NUMBER(19),
    D_CREATED_ON DATE,
    D_INTERNAL_COMMENTS VARCHAR2(255 ),
    D_UPDATED_ON DATE,
    D_CREATED_TIME TIMESTAMP (6),
    D_UPDATED_TIME TIMESTAMP (6),
	LIST_INDEX NUMBER(10),
    D_ACTIVE NUMBER(1,0) DEFAULT 1
  )
/
ALTER TABLE LABOR_RATE_AUDIT ADD CONSTRAINT LABOR_RATE_AUDIT_PK PRIMARY KEY (ID)
/
ALTER TABLE LABOR_RATE_AUDIT ADD CONSTRAINT LABOR_RATE_ADT_LABOR_RATES_FK FOREIGN KEY (LABOR_RATES) REFERENCES LABOR_RATE(LABOR_RATES)
/
CREATE SEQUENCE LABOR_REPAIR_DATE_HISTORY_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 1 NOCACHE NOORDER NOCYCLE
/
CREATE TABLE LABOR_REPAIR_DATE_HISTORY
  (
    ID NUMBER(19,0) NOT NULL ,
    FROM_DATE DATE NOT NULL,
    TILL_DATE DATE NOT NULL,
    AMT                NUMBER(19,0),
    CURR               VARCHAR2(255),
    LABOR_AUDIT        NUMBER(19,0),
    BUSINESS_UNIT_INFO VARCHAR2(255),
    D_CREATED_BY       NUMBER(19),
    D_LAST_UPDATED_BY  NUMBER(19),
    D_CREATED_ON DATE,
    D_UPDATED_ON DATE,
    D_INTERNAL_COMMENTS VARCHAR2(90),
    D_CREATED_TIME TIMESTAMP(6),
    D_UPDATED_TIME TIMESTAMP(6),
    D_ACTIVE NUMBER(1)
  )
/
ALTER TABLE LABOR_RATE_AUDIT ADD CONSTRAINT LABOR_REPAIR_DATE_HISTORY_PK PRIMARY KEY (ID)
/
ALTER TABLE LABOR_RATE_AUDIT ADD CONSTRAINT LBR_REP_DT_HIST_LABOR_AUDIT_FK FOREIGN KEY (LABOR_AUDIT) REFERENCES LABOR_RATE(LABOR_RATES)
/