--PURPOSE    : PATCH TO ADD COLUMN SUPPLIERS
--AUTHOR     : SUSHMA MANTHALE
--CREATED ON : 30-JULY-12

ALTER TABLE CLAIM ADD SUPPLIERS NUMBER(19,0)
/
ALTER TABLE CLAIM ADD SUPPLIER_RECOVERY NUMBER(1,0)
/
ALTER TABLE CLAIM ADD CONSTRAINT "CLM_SUPPLIERS_FK" FOREIGN KEY ("SUPPLIERS") REFERENCES "LIST_OF_VALUES" ("ID") ENABLE
/
