--PURPOSE    : PATCH TO CREATE COMPONENT_AUDIT_HISTORY
--AUTHOR     : KALYANI
--CREATED ON : 08-MAY-13

CREATE TABLE "COMPONENT_AUDIT_HISTORY" 
   ("ID" NUMBER(19,0) NOT NULL ENABLE,
    "SEQUENCE_NUMBER" NUMBER,
    "MANUFACTURER" VARCHAR2(255 BYTE), 
	  "COMPONENT_SERIAL_TYPE" VARCHAR2(255 BYTE),     
	  "COMPONENT_PART_SERIAL_NUMBER" VARCHAR2(255 BYTE),
	  "SERIAL_TYPE_DESCRIPTION" VARCHAR2(255 BYTE),
    "COMPONENT_PART_NUMBER" VARCHAR2(255 BYTE),	
	  "TRANSACTION_TYPE" VARCHAR2(2 BYTE),
	  "D_CREATED_ON" DATE, 
	  "D_UPDATED_ON" DATE,
	  "D_CREATED_TIME" TIMESTAMP (6), 
	  "D_UPDATED_TIME" TIMESTAMP (6), 
	 "D_LAST_UPDATED_BY" NUMBER(19,0),
     "D_ACTIVE" NUMBER(1,0) DEFAULT 1, 
     "D_INTERNAL_COMMENTS" VARCHAR2(255 CHAR),	 
	 "INVENTORY_ITEM" NUMBER(19,0),
	CONSTRAINT "COMPONENT_AUDIT_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 11534336 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "COMP_AUD_LST_UPDT_BY_FK" FOREIGN KEY ("D_LAST_UPDATED_BY")
	  REFERENCES "ORG_USER" ("ID") ENABLE, 
	 CONSTRAINT "INVENTORYITEMCOMP_AUD_FK" FOREIGN KEY ("INVENTORY_ITEM")
	  REFERENCES "INVENTORY_ITEM" ("ID") ENABLE
   )
/
