--PURPOSE    : PATCH TO ADD JOB_STATUS TABLE FOR ITALY CLAIM INTERFACE
--AUTHOR     : KALYANI
--CREATED ON : 30-JAN-13

CREATE TABLE JOB_STATUS
(
ID NUMBER(19,0) NOT NULL ENABLE,
START_DATE TIMESTAMP(6), 
END_DATE TIMESTAMP(6), 
STATUS  varchar(255),
PRIMARY KEY (Id)
)
/
CREATE SEQUENCE job_status_sequence
START WITH 1
INCREMENT BY 1
/
CREATE OR REPLACE TRIGGER job_status_trigger
BEFORE INSERT
ON JOB_STATUS
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
SELECT job_status_sequence.nextval INTO :NEW.ID FROM dual;
END;
/