--PURPOSE    : PATCH TO UPDATE CLAIM_ID 
--AUTHOR     : GHANASHYAM DAS
--CREATED ON : 08-MAY-12

DECLARE
	v_count integer := 0;

  CURSOR VCLAIM_REC
  IS
    SELECT J.ID_   AS TASK_INSTANCE_ID,
      V.LONGVALUE_ AS CLAIM_ID
    FROM JBPM_TASKINSTANCE J,
      JBPM_MODULEINSTANCE M,
      JBPM_VARIABLEINSTANCE V
    WHERE J.TASKMGMTINSTANCE_ = M.ID_
    AND M.PROCESSINSTANCE_    = V.PROCESSINSTANCE_
    AND V.NAME_     in  ('claim','recoveryClaim')
    AND V.LONGVALUE_         IS NOT NULL ;
BEGIN
  FOR EACH_VCLAIM_REC IN VCLAIM_REC
  LOOP
    BEGIN
      UPDATE JBPM_TASKINSTANCE
      SET CLAIM_ID = EACH_VCLAIM_REC.CLAIM_ID
      WHERE ID_    = EACH_VCLAIM_REC.TASK_INSTANCE_ID;
	  IF V_COUNT = 100 THEN
		COMMIT;
		V_COUNT := 0;
	  ELSE
	   V_COUNT :=  V_COUNT + 1;
	  END IF;
    EXCEPTION
    WHEN OTHERS THEN
    NULL;
	--TODO : track erros into separate table.
    END;
	
	 
  END LOOP;
  COMMIT;
END ;
/