--PURPOSE    : PATCH FOR CREATING JOIN table RECOVERY_CLAIM_AUDIT_ATTACHMENTS
--AUTHOR     : SUNEETHA NAGABOYINA
--CREATED ON : 12-oct-12

CREATE TABLE REC_CLAIM_AUDIT_ATTACHMENTS
  (
    RECOVERY_CLAIM_AUDIT NUMBER(19,0) NOT NULL ENABLE,
    ATTACHMENTS NUMBER(19,0) NOT NULL ENABLE
  )
/
ALTER TABLE REC_CLAIM_AUDIT_ATTACHMENTS ADD CONSTRAINT RECCLAIMAUDATTACH_CLAIMAUD_FK FOREIGN KEY (RECOVERY_CLAIM_AUDIT) REFERENCES REC_CLAIM_AUDIT(ID)
/
ALTER TABLE REC_CLAIM_AUDIT_ATTACHMENTS ADD CONSTRAINT RECCLMAUDATTACH_ATTACHMENTS_FK FOREIGN KEY (ATTACHMENTS) REFERENCES DOCUMENT (ID) ENABLE
/