--PURPOSE    : PATCH_FOR_ADDING_COLUMS_ON_CAMPAIGN_NOTIFICATION_TABLE
--AUTHOR     : RAVIKUMAR.Y
--CREATED ON : 17-AUG-12

ALTER TABLE campaign_notification ADD (COMMENTS VARCHAR2(4000 CHAR),STATUS VARCHAR2(32 CHAR),CAMPAIGN_STATUS VARCHAR2(255 CHAR))
/