--PURPOSE    : PATCH TO ADD COLUMN SUPPLIERS
--AUTHOR     : SUSHMA MANTHALE
--CREATED ON : 30-JULY-12

ALTER TABLE POLICY_DEFINITION ADD MONTHS_FROM_BUILD_DATE  NUMBER(19,0)
/
ALTER TABLE POLICY_DEFINITION ADD MONTHS_FRM_ORGNL_DELIVERY  NUMBER(19,0) 
/