--PURPOSE    : PATCH TO ADD SPECIAL_OPTION_STATUS,DIESEL_TIER,MODEL_POWER,MODEL_POWER_DESC,SPECIAL_OPTION_STATUS_DESC
--AUTHOR     : KALYANI
--CREATED ON : 20-JAN-13


ALTER TABLE ITEM ADD (SPECIAL_OPTION_STATUS VARCHAR2(30 CHAR),DIESEL_TIER VARCHAR2(30 CHAR),
MODEL_POWER VARCHAR2(100 BYTE),
MODEL_POWER_DESC VARCHAR2(100 BYTE),
SPECIAL_OPTION_STATUS_DESC  VARCHAR2(100 BYTE))
/
