CREATE TABLE PART_GROUP
(
    ID      NUMBER(19,0)  NOT NULL ENABLE,
    CONSTRAINT PART_GROUP_ID_PK PRIMARY KEY (ID) ENABLE,
    PART_GROUP_CODE    VARCHAR2(100 CHAR),
    PART_GROUP_DESCRIPTION    VARCHAR2(255 CHAR) NOT NULL ENABLE,
    QTY    NUMBER(19,2)  NOT NULL ENABLE,
    STANDARD_COST    NUMBER(19,2)  NOT NULL ENABLE
)
/

CREATE SEQUENCE PART_GROUP_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 110000000000440 CACHE 20 NOORDER NOCYCLE
/

CREATE TABLE INVENTORY_ITEM_PART_GROUP
(
    inventory_item NUMBER(19,0),
    partgroups NUMBER(19,0),
    CONSTRAINT INV_PRT_INV_FK FOREIGN KEY (inventory_item) REFERENCES INVENTORY_ITEM (ID) ENABLE,
    CONSTRAINT INV_PRT_GRP_FK FOREIGN KEY (partgroups) REFERENCES PART_GROUP (ID) ENABLE
)
/