--PURPOSE    : PATCH_FOR_CREATING_TABLE_FIELD_MOD_UPDATE_AUDIT
--AUTHOR     : RAVIKUMAR.Y
--CREATED ON : 17-AUG-12 

CREATE TABLE FIELD_MOD_UPDATE_AUDIT
  (
    ID                    NUMBER(19, 0) NOT NULL ,
    COMMENTS              VARCHAR2(4000 CHAR),
    ACTION_TAKEN          VARCHAR2(50 CHAR) ,
    FOR_FIELD_MOD          NUMBER(19, 0) NOT NULL ,
    LIST_INDEX            NUMBER(3, 0) ,
    D_CREATED_ON          DATE ,
    D_UPDATED_ON          DATE ,
    D_CREATED_TIME        DATE ,
    D_UPDATED_TIME        DATE ,
    D_INTERNAL_COMMENTS VARCHAR2(255 CHAR) ,
    VERSION             NUMBER(10, 0) NOT NULL ,
    D_LAST_UPDATED_BY   NUMBER(19, 0) ,
    D_ACTIVE            NUMBER(1, 0),
	INACTIVE_REASON     VARCHAR2(4000 CHAR)
  )
/
ALTER TABLE FIELD_MOD_UPDATE_AUDIT ADD CONSTRAINT FK_FOR_FIELD_MOD FOREIGN KEY
  (
    FOR_FIELD_MOD
  )
  REFERENCES CAMPAIGN_NOTIFICATION
  (
    ID
  )
  ENABLE
/
CREATE SEQUENCE Field_MOD_AUDIT_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 100000000000000 CACHE 20 NOORDER NOCYCLE
/
  
  