--PURPOSE    : Patch to change claimNumber sequence
--AUTHOR     : Raghu
--CREATED ON : 29-04-2013

DROP SEQUENCE CLAIM_NUMBER_SEQ
/
CREATE SEQUENCE CLAIM_NUMBER_SEQ START WITH 100000 MAXVALUE 999999  INCREMENT BY 1 NOCACHE NOCYCLE
/