--Purpose    : Patch for creating supersession_item
--Author     : Pracher OPancholi
--Created On : 20-Nov-2012

CREATE TABLE SUPERSESSION_ITEM
(
    ID      NUMBER(19,0)  NOT NULL ENABLE,
	CONSTRAINT SUPERSESSION_ITEM_ID_PK PRIMARY KEY (ID) ENABLE,
	OLD_ITEM_ID NUMBER(19,0)  NOT NULL ENABLE,
	NEW_ITEM_ID NUMBER(19,0)  NOT NULL ENABLE,
    START_DATE DATE,
    END_DATE DATE,
    CONSTRAINT SPR_OLD_ITEM_FK FOREIGN KEY (OLD_ITEM_ID) REFERENCES ITEM (ID) ENABLE,
	CONSTRAINT SPR_NEW_ITEM_FK FOREIGN KEY (NEW_ITEM_ID) REFERENCES ITEM (ID) ENABLE
)
/

CREATE SEQUENCE SUPERSESSION_ITEM_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 110000000000440 CACHE 20 NOORDER NOCYCLE
/