--PURPOSE    : PATCH TO ALTER BASE_PART_RETURN TABLE
--AUTHOR     : Deepak Patel
--CREATED ON : 02-Jan-12


ALTER TABLE base_part_return MODIFY DEALER_PICKUP_LOCATION NUMBER(19,0)
/
ALTER TABLE base_part_return ADD CONSTRAINT BPRT_DELERPICKLOC_FK FOREIGN KEY (DEALER_PICKUP_LOCATION) REFERENCES ADDRESS(ID)
/
ALTER TABLE OEM_PART_REPLACED ADD RETURN_DIRECTLY_TO_SUPPLIER NUMBER(1,0)
/
ALTER TABLE OEM_PART_REPLACED ADD APPLIED_CONTRACT NUMBER(19,0)
/
ALTER TABLE OEM_PART_REPLACED ADD CONSTRAINT OEM_PART_REP_CONTRACT_FK FOREIGN KEY (APPLIED_CONTRACT) REFERENCES CONTRACT(ID)
/
update OEM_PART_REPLACED set RETURN_DIRECTLY_TO_SUPPLIER=0
/
COMMIT
/
