--PURPOSE    : PATCH FOR CREATING SHIPMENT_LOAD_DIMENSION Table
--AUTHOR     : Deepak Patel
--CREATED ON : 19-Feb-12

CREATE SEQUENCE SHIP_LOAD_DIMENSION_SEQ MINVALUE 100 MAXVALUE 999999999999999999999999999 INCREMENT BY 10 START WITH 100 NOCACHE NOORDER NOCYCLE
/
CREATE TABLE SHIPMENT_LOAD_DIMENSION
  (
    ID  NUMBER(19,0) NOT NULL ENABLE,
	HEIGHT   NUMBER(19,2),
    WEIGHT   NUMBER(19,2),
    BREADTH  NUMBER(19,2),
    LENGTH   NUMBER(19,2),
    LOAD_TYPE  VARCHAR2(10),
	VERSION     NUMBER(10,0) NOT NULL ENABLE,
	SHIPMENT NUMBER(19,0),
    CONSTRAINT SHIP_LOAD_DIM PRIMARY KEY (ID), 
    CONSTRAINT SHIP_LOAD_DIM_FK FOREIGN KEY (SHIPMENT) REFERENCES SHIPMENT (ID) ENABLE
  )
/