--	PURPOSE		: TO CREATE A ORG_OWNER_ASSOCIATION
--	AUTHOR		: DEEPAK
--	CREATED ON	: 21-June-13

CREATE TABLE ORG_OWNER_ASSOCIATION
(
PARENT_ORG NUMBER(19,0) NOT NULL ENABLE,
CHILD_ORG NUMBER(19,0) NOT NULL ENABLE,
CONSTRAINT ORG_CHID_FK FOREIGN KEY (PARENT_ORG) REFERENCES ORGANIZATION (ID) ENABLE,
CONSTRAINT ORG_CHID_CHID_ORG_FK FOREIGN KEY (CHILD_ORG) REFERENCES ORGANIZATION (ID) ENABLE
)
/
CREATE INDEX ORGOWNERASSO_IDX_PARORG ON ORG_OWNER_ASSOCIATION ("PARENT_ORG")
/
CREATE INDEX ORGOWNERASSO_IDX_CHILD_ORG ON ORG_OWNER_ASSOCIATION ("CHILD_ORG")
/