--PURPOSE    : PATCH TO DROP WAIVER_DESCRIPTION FROM DIESEL_TIER_COUNTRY_MAPPING
--AUTHOR     : PARTHASARATHY R
--CREATED ON : 18-FEB-13

ALTER TABLE DIESEL_TIER_COUNTRY_MAPPING DROP COLUMN WAIVER_DESCRIPTION
/