--PURPOSE    : Patch to delete Pay Labor Charges for SMR Machine and part claim
--AUTHOR     : PRACHER PANCHOLI
--CREATED ON : 10-APR-13

DELETE FROM CONFIG_PARAM_OPTIONS_MAPPING WHERE PARAM_ID IN (SELECT ID FROM CONFIG_PARAM WHERE  NAME='payLaborCharges')
/
DELETE FROM CONFIG_VALUE WHERE CONFIG_PARAM IN (SELECT ID FROM CONFIG_PARAM WHERE  NAME='payLaborCharges')
/
DELETE FROM CONFIG_PARAM WHERE  NAME='payLaborCharges'
/
COMMIT
/

