-- Purpose 		: For Creating table TIER_TIER_MAPPING
-- Author  		: PARTHASARATHY R
-- Created On	: 25-Mar-2013

CREATE TABLE TIER_TIER_MAPPING
   (	
    ID NUMBER(19,0) NOT NULL ENABLE, 
	INVENTORY_TIER varchar(10),
	CUSTOMER_TIER NUMBER(19, 0),
	CONSTRAINT TIER_TIER_MAPPING_PK PRIMARY KEY (ID) ENABLE, 
	CONSTRAINT TIER_DTCM_FK FOREIGN KEY (CUSTOMER_TIER) REFERENCES DIESEL_TIER_COUNTRY_MAPPING (ID) ENABLE
   ) 
/
CREATE SEQUENCE  TIER_TIER_MAPPING_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 1000 CACHE 20 NOORDER  NOCYCLE
/