-- Patch for altering service table to add invoice for incidentals
-- Author: PARTHASARATHY R
-- Created On : 18-OCT-2012

ALTER TABLE service ADD FREIGHT_DUTY_INVOICE NUMBER(19, 0)
/
ALTER TABLE service ADD MEALS_INVOICE NUMBER(19, 0)
/
ALTER TABLE service ADD PER_DIEM_INVOICE NUMBER(19, 0)
/
ALTER TABLE service ADD PARKING_AND_TOLL_INVOICE NUMBER(19, 0)
/
ALTER TABLE service ADD RENTAL_CHARGES_INVOICE NUMBER(19, 0)
/
ALTER TABLE service ADD LOCAL_PURCHASE_INVOICE NUMBER(19, 0)
/
ALTER TABLE service ADD TOLLS_INVOICE NUMBER(19, 0)
/
ALTER TABLE service ADD OTHER_FREIGHT_DUTY_INVOICE NUMBER(19, 0)
/
ALTER TABLE service ADD OTHERS_INVOICE NUMBER(19, 0)
/

ALTER TABLE service ADD CONSTRAINT FREIGHT_DUTY_INVOICE_FK FOREIGN KEY (FREIGHT_DUTY_INVOICE) references DOCUMENT (ID)
/
ALTER TABLE service ADD CONSTRAINT MEALS_INVOICE_FK FOREIGN KEY (MEALS_INVOICE) references DOCUMENT (ID)
/
ALTER TABLE service ADD CONSTRAINT PER_DIEM_INVOICE_FK FOREIGN KEY (PER_DIEM_INVOICE) references DOCUMENT (ID)
/
ALTER TABLE service ADD CONSTRAINT PARKING_AND_TOLL_INVOICE_FK FOREIGN KEY (PARKING_AND_TOLL_INVOICE) references DOCUMENT (ID)
/
ALTER TABLE service ADD CONSTRAINT RENTAL_CHARGES_INVOICE_FK FOREIGN KEY (RENTAL_CHARGES_INVOICE) references DOCUMENT (ID)
/
ALTER TABLE service ADD CONSTRAINT LOCAL_PURCHASE_INVOICE_FK FOREIGN KEY (LOCAL_PURCHASE_INVOICE) references DOCUMENT (ID)
/
ALTER TABLE service ADD CONSTRAINT TOLLS_INVOICE_FK FOREIGN KEY (TOLLS_INVOICE) references DOCUMENT (ID)
/
ALTER TABLE service ADD CONSTRAINT OTHER_FREIGHT_DUTY_INVOICE_FK FOREIGN KEY (OTHER_FREIGHT_DUTY_INVOICE) references DOCUMENT (ID)
/
ALTER TABLE service ADD CONSTRAINT OTHERS_INVOICE_FK FOREIGN KEY (OTHERS_INVOICE) references DOCUMENT (ID)
/
commit
/