--PURPOSE    : PATCH TO RENAME COLUMNS OF STG_DRAFT_CLAIM TABLE
--AUTHOR     : GHANASHYAM DAS
--CREATED ON : 01-JUNE-12

alter table STG_DRAFT_CLAIM rename column REPLACED_IR_PARTS to REPLACED_OEM_PARTS
/
alter table STG_DRAFT_CLAIM rename column REPLACED_IR_PARTS_QUANTITY to REPLACED_OEM_PARTS_QUANTITY
/
alter table STG_DRAFT_CLAIM rename column REPLACED_NON_IR_PARTS to REPLACED_NON_OEM_PARTS
/
alter table STG_DRAFT_CLAIM rename column REPLACED_NON_IR_PARTS_QUANTITY to REPLACED_NON_OEM_PARTS_QTY
/
alter table STG_DRAFT_CLAIM rename column REPLACED_NON_IR_PARTS_PRICE to REPLACED_NON_OEM_PARTS_PRICE
/
alter table STG_DRAFT_CLAIM rename column REPLACED_NON_IR_PARTS_DESC to REPLACED_NON_OEM_PARTS_DESC
/
alter table STG_DRAFT_CLAIM rename column IS_PART_INSTALLED_ON_TKTSA to IS_PART_INSTALLED_ON_OEM
/
alter table STG_DRAFT_CLAIM rename column REPLACED_IR_PARTS_SERIAL_NUM to REPLACED_OEM_PARTS_SERIAL_NUM
/
alter table STG_DRAFT_CLAIM rename column INSTALLED_IR_PARTS to INSTALLED_OEM_PARTS
/
alter table STG_DRAFT_CLAIM rename column INSTALLED_IR_PARTS_QUANTITY to INSTALLED_OEM_PARTS_QUANTITY
/
alter table STG_DRAFT_CLAIM rename column INSTALLED_IR_PARTS_SERIAL_NUM to INSTALLED_OEM_PARTS_SERIAL_NUM
/