--Purpose    : PATCH FOR RENAMING EXTENDED to EXTENDED PROTECTION.
--Author     : Arpitha Nadig
--Created On : 27-NOV-2013

ALTER TABLE POLICY_DEFINITION DROP CONSTRAINT POLICYDEF_WARRANTYTYPE_FK;
update POLICY_DEFINITION set warranty_type='EXTENDED PROTECTION' where warranty_type='EXTENDED';
UPDATE warranty_type set type='EXTENDED PROTECTION' where type='EXTENDED';
ALTER TABLE POLICY_DEFINITION ADD CONSTRAINT "POLICYDEF_WARRANTYTYPE_FK" FOREIGN KEY ("WARRANTY_TYPE")
	  REFERENCES WARRANTY_TYPE ("TYPE") ENABLE;
commit;