--PURPOSE    : PATCH FOR ADDING CONSTRAINTS I18N_INDUSTRY_CODE_FK,I18N_MAINTENANCE_TEXT_FK
--AUTHOR     : Jyoti Chauhan
--CREATED ON : 11-Dec-12

ALTER TABLE I18NINDUSTRY_CODE_TEXT ADD CONSTRAINT I18N_INDUSTRY_CODE_FK FOREIGN KEY (I18N_INDUSTRY_CODE) REFERENCES INDUSTRY_CODE(ID)
/
ALTER TABLE I18NMAINTENANCE_CONTRACT_TEXT ADD CONSTRAINT I18N_MAINTENANCE_TEXT_FK FOREIGN KEY (I18N_MAINTENANCE_CONTRACT) REFERENCES MAINTENANCE_CONTRACT(ID)
/