-- PURPOSE    : PATCH TO ADD COLUMN ALLOWED_NCR_WITH_30_DAYS IN SERVICE_PROVIDER TABLE
-- AUTHOR     : PARTHASARATHY R
-- CREATED ON : 12-Mar-2013

alter table SERVICE_PROVIDER add (ALLOWED_NCR_WITH_30_DAYS NUMBER(1))
/