-- Patch for updating TYPE 'GOODWILL'  to TYPE POLICY in WARRANTY_TYPE
-- Author: PRACHER 
-- Created On : 9-APRIL-2013


INSERT INTO  WARRANTY_TYPE VALUES ('POLICY',1,NULL,NULL,NULL,NULL,NULL,NULL,1)  
/
update ITEM_PRICE_CRITERIA set WARRANTY_TYPE ='POLICY' where WARRANTY_TYPE ='GOODWILL' 
/   
update LABOR_RATES set WARRANTY_TYPE ='POLICY' where WARRANTY_TYPE ='GOODWILL' 
/           
update LABOR_RATE_AUDIT set WARRANTY_TYPE ='POLICY' where WARRANTY_TYPE ='GOODWILL'    
/      
update PART_RETURN_DEFINITION set WARRANTY_TYPE ='POLICY' where WARRANTY_TYPE ='GOODWILL' 
/
update PAYMENT_MODIFIER set WARRANTY_TYPE ='POLICY' where WARRANTY_TYPE ='GOODWILL' 
/      
update POLICY_CRITERIA set WARRANTY_TYPE ='POLICY' where WARRANTY_TYPE ='GOODWILL' 
/       
update POLICY_DEFINITION set WARRANTY_TYPE ='POLICY' where WARRANTY_TYPE ='GOODWILL' 
/     
update POLICY_RATES set WARRANTY_TYPE ='POLICY' where WARRANTY_TYPE ='GOODWILL' 
/          
update TRAVEL_RATES set WARRANTY_TYPE ='POLICY' where WARRANTY_TYPE ='GOODWILL'
/
DELETE FROM WARRANTY_TYPE WHERE TYPE='GOODWILL' 
/
COMMIT
/

