-- Purpose 		: For Creating table Inventory_Comment table
-- Author  		: PARTHASARATHY R
-- Created On	: 08-May-2013

CREATE TABLE INVENTORY_COMMENT
   (
    ID NUMBER(19,0) NOT NULL ENABLE, 
	INVENTORY_ITEM NUMBER(19, 0) NOT NULL ENABLE,
	SEQUENCE_NUMBER NUMBER(10) NOT NULL ENABLE,
	USER_ID VARCHAR2(255) NOT NULL ENABLE,
	DATE_OF_COMMENT DATE NOT NULL ENABLE,
	NEMIS_COMMENT VARCHAR2(4000) NOT NULL ENABLE,
	CONSTRAINT INVENTORY_COMMENT_PK PRIMARY KEY (ID) ENABLE, 
	CONSTRAINT INV_COMMENT_INV_ITEM FOREIGN KEY (INVENTORY_ITEM) REFERENCES INVENTORY_ITEM (ID) ENABLE
   )
/
CREATE SEQUENCE  INVENTORY_COMMENT_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 20 START WITH 1000 CACHE 20 NOORDER  NOCYCLE
/