--PURPOSE    : SLMSPROD_593_PATCH_TO_ADD_CLMNS_CREDIT_AMOUNT_IN_CREDITMEMO
--AUTHOR     : Ravi Sinha
--CREATED ON : 09-Apr-14


ALTER TABLE CREDIT_MEMO ADD ("CREDIT_AMOUNT_AMT" NUMBER(19,2))
/
ALTER TABLE CREDIT_MEMO ADD ("CREDIT_AMOUNT_CURR" VARCHAR2(255 CHAR))
/