--1283 2nd recovery claim patch

ALTER TABLE RECOVERY_CLAIM ADD FLAG_FOR_ANOTHER_RECOVERY NUMBER(1,0)
/
update RECOVERY_CLAIM set FLAG_FOR_ANOTHER_RECOVERY = 0
/
commit
/
ALTER TABLE RECOVERY_CLAIM MODIFY (FLAG_FOR_ANOTHER_RECOVERY NUMBER(1,0) CONSTRAINT C_anoreco_notnull NOT NULL)
/
ALTER TABLE recovery_info DROP CONSTRAINT UC_REC_INFO_CLAIM
/
drop index  UC_REC_INFO_CLAIM
/