--PURPOSE    : patch to create technician tables
--AUTHOR     : Raghu
--CREATED ON : 23-JAN-2014
--Creating  SERIES_REF_CERTIFICATION table
CREATE TABLE SERIES_REF_CERTIFICATION 
(	
ID NUMBER(19,0) NOT NULL ENABLE, 
SERIES NUMBER(19,0),
START_DATE DATE,
END_DATE DATE,
D_CREATED_ON DATE, 
D_INTERNAL_COMMENTS VARCHAR2(255 CHAR), 
D_UPDATED_ON DATE, 
D_LAST_UPDATED_BY NUMBER(19,0), 
D_CREATED_TIME TIMESTAMP (6), 
D_UPDATED_TIME TIMESTAMP (6), 
D_ACTIVE NUMBER(1,0) DEFAULT 1,  
CONSTRAINT "SERIES_REF_CERT_PK" PRIMARY KEY ("ID")
) 
/
alter table SERIES_REF_CERTIFICATION add CONSTRAINT "SERIES_REF_LST_UPDT_BY_FK" FOREIGN KEY ("D_LAST_UPDATED_BY") REFERENCES "ORG_USER" ("ID") ENABLE
/
alter table SERIES_REF_CERTIFICATION add CONSTRAINT "SERIES_CERT_FK" FOREIGN KEY ("SERIES") REFERENCES "ITEM_GROUP" ("ID") ENABLE
/
--Creating SERIES_CERTIFICATION TABLE 
CREATE TABLE SERIES_CERTIFICATION 
(	
ID NUMBER(19,0) NOT NULL ENABLE, 
CERTIFICATE_NAME VARCHAR2(2048),
BRAND VARCHAR2(255 BYTE),
CATEGORY_LEVEL VARCHAR2(255 BYTE), 
CATEGORY_NAME VARCHAR2(2048), 
SERIES_REF_CERT NUMBER(19,0) NOT NULL ENABLE,
D_CREATED_ON DATE, 
D_INTERNAL_COMMENTS VARCHAR2(255 CHAR), 
D_UPDATED_ON DATE, 
D_LAST_UPDATED_BY NUMBER(19,0), 
D_CREATED_TIME TIMESTAMP (6), 
D_UPDATED_TIME TIMESTAMP (6), 
D_ACTIVE NUMBER(1,0) DEFAULT 1,  
CONSTRAINT "CERT_FOR_SERIES_PK" PRIMARY KEY ("ID")
) 
/
alter table SERIES_CERTIFICATION add CONSTRAINT "CERT_FOR_SERIES_FK" FOREIGN KEY ("SERIES_REF_CERT") REFERENCES "SERIES_REF_CERTIFICATION" ("ID") ENABLE
/
alter table SERIES_CERTIFICATION add CONSTRAINT "SERIES_CERT_LST_UPDT_BY_FK" FOREIGN KEY ("D_LAST_UPDATED_BY") REFERENCES "ORG_USER" ("ID") ENABLE
/
--creating CORE_CERTIFICATION table
create table CORE_CERTIFICATION
(
ID NUMBER(19,0) NOT NULL ENABLE, 
CERTIFICATE_NAME VARCHAR2(2000),
CATEGORY_LEVEL VARCHAR2(2000),
CATEGORY_NAME VARCHAR2(2000),
BRAND VARCHAR2(255 CHAR),
D_CREATED_ON DATE, 
D_INTERNAL_COMMENTS VARCHAR2(255 CHAR), 
D_UPDATED_ON DATE, 
D_LAST_UPDATED_BY NUMBER(19,0), 
D_CREATED_TIME TIMESTAMP (6), 
D_UPDATED_TIME TIMESTAMP (6), 
D_ACTIVE NUMBER(1,0) DEFAULT 1,  
CONSTRAINT "CERTIFICATE_PK" PRIMARY KEY ("ID")
)
/
alter table CORE_CERTIFICATION add CONSTRAINT "CERTIFICATES_LST_UPDT_BY_FK" FOREIGN KEY ("D_LAST_UPDATED_BY") REFERENCES "ORG_USER" ("ID") ENABLE
/