--PURPOSE    : patch to add constraints for TECH_PRODUCT_CERTIFICATIONS
--AUTHOR     : Raghu
--CREATED ON : 19-FEB-2014

alter table TECH_PRODUCT_CERTIFICATIONS add CONSTRAINT "TECH_CERTIF_REF_FK" FOREIGN KEY ("TECHNICIAN_CERTIFICATION") REFERENCES "TECHNICIAN_CERTIFICATION" ("ID") ENABLE
/
alter table TECH_PRODUCT_CERTIFICATIONS add CONSTRAINT "PRODUCT_CERTIFI_REF_FK" FOREIGN KEY ("PRODUCT_CERTIFICATION") REFERENCES "SERIES_REF_CERTIFICATION" ("ID") ENABLE
/