ALTER table PART_PRICES add CONSTRAINT "PART_PRICES_BU_FK" FOREIGN KEY ("BUSINESS_UNIT_INFO") REFERENCES "BUSINESS_UNIT" ("NAME") ENABLE
/
ALTER table PART_PRICES add CONSTRAINT "PART_PRICES_LAST_UPTD_BY_FK" FOREIGN KEY ("D_LAST_UPDATED_BY") REFERENCES "ORG_USER" ("ID") ENABLE
/
ALTER table PART_PRICES add CONSTRAINT "PARTNUMBER_PARTNUMBER_FK" FOREIGN KEY ("NMHG_PART_NUMBER") REFERENCES "ITEM" ("ID") ENABLE
/
ALTER table PART_PRICE add CONSTRAINT "PART_PRICE_LST_UPDT_BY_FK" FOREIGN KEY ("D_LAST_UPDATED_BY") REFERENCES "ORG_USER" ("ID") ENABLE
/
ALTER table PART_PRICE add CONSTRAINT "PARTPRICE_PARTPRICES_FK" FOREIGN KEY ("PART_PRICES") REFERENCES "PART_PRICES" ("ID") ENABLE
/
ALTER table PART_PRICE_VALUES add CONSTRAINT "PART_PRICE_VLS_ID_FK"  FOREIGN KEY ("PART_PRICE") REFERENCES "PART_PRICE" ("ID")ENABLE
/
ALTER table PART_PRICE_AUDIT add CONSTRAINT "PART_PRICE_ADT_ID_FK"  FOREIGN KEY ("PART_PRICES") REFERENCES "PART_PRICES" ("ID")ENABLE	
/
ALTER table PART_PRICE_REPAIR_DATE_HISTORY add CONSTRAINT "PRT_RD_PRT_PRICE_AUDIT_ID_FK"  FOREIGN KEY ("PART_PRICE_AUDIT") REFERENCES "PART_PRICE_AUDIT" ("ID")ENABLE
/