--Purpose    : DDL for NMHGSLMS-425 -To create STATE_MNDTE_COST_CTGY_AUDIT
--Author     : Arpitha Nadig AR
--Created On : 14-JAN-2013

CREATE TABLE STATE_MNDTE_COST_CTGY_AUDIT
( 
ID NUMBER(19,0) NOT NULL ENABLE,
STATE_MANDATE_AUDIT NUMBER(19,0) NOT NULL ENABLE,
COST_CATEGORY NUMBER(19,0),
MANDATORY NUMBER(1,0) NOT NULL ENABLE,
OTHERS VARCHAR2(255 BYTE),
CONSTRAINT "STATE_MNDTE_COST_CTGY_AUD_PK" PRIMARY KEY ("ID"), 
CONSTRAINT "STATE_MANDATE_AUD_FK" FOREIGN KEY ("STATE_MANDATE_AUDIT") 
REFERENCES "STATE_MANDATE_AUDIT" ("ID") ENABLE, 
CONSTRAINT "COST_CATEGORY_AUD_FK" FOREIGN KEY ("COST_CATEGORY") 
REFERENCES "COST_CATEGORY" ("ID") ENABLE
)
/