-- PURPOSE    : PATCH TO alter table STATE_MNDTE_COST_CTGY_MAPPING
-- AUTHOR     : Arpitha Nadig AR
-- CREATED ON : 14-JAN-2013
ALTER TABLE STATE_MNDTE_COST_CTGY_MAPPING ADD OTHERS VARCHAR2(255 BYTE)
/
ALTER TABLE STATE_MNDTE_COST_CTGY_MAPPING MODIFY (COST_CATEGORY null)
/