--Purpose    :  patch to create table for inventory Additional components
--Author     : Raghavendra
--Created On : 12-Dec-2013

CREATE TABLE inventory_additional_comp
(	
"ID" NUMBER(19,0) NOT NULL ENABLE, 
"TYPE" VARCHAR2(255 BYTE),
"SUB_TYPE" VARCHAR2(255 BYTE),
"VERSION" NUMBER(10,0) NOT NULL ENABLE,
"PART_NUMBER" VARCHAR2(255 BYTE),
"PART_DESCRIPTION" VARCHAR2(255 BYTE), 
"ITEM" NUMBER(19,0) NOT NULL ENABLE, 
"D_CREATED_ON" DATE,
"D_INTERNAL_COMMENTS" VARCHAR2(255 CHAR),
"D_UPDATED_ON" DATE,
"D_LAST_UPDATED_BY" NUMBER(19,0),
"D_CREATED_TIME" TIMESTAMP (6),
"D_UPDATED_TIME" TIMESTAMP (6),
"D_ACTIVE" NUMBER(1,0) DEFAULT 1,
"MANUFACTURER" VARCHAR2(255 BYTE),
"SERIAL_NUMBER" VARCHAR2(255 CHAR),
"MODEL" VARCHAR2(255 BYTE),
"DATE_CODE" VARCHAR2(255 BYTE),
CONSTRAINT "INV_ITEM_ADD_COMPO_PK" PRIMARY KEY ("ID")
)
/