-- Patch to alter table part recovery audit
-- Created by deepak 04- Feb 14


ALTER TABLE PART_RECOVERY_AUDIT ADD PART_RETURN_ACTION1 NUMBER(19,0)
/
ALTER TABLE PART_RECOVERY_AUDIT ADD PART_RETURN_ACTION2 NUMBER(19,0)
/
ALTER TABLE PART_RECOVERY_AUDIT ADD PART_RETURN_ACTION3 NUMBER(19,0)
/
ALTER TABLE PART_RECOVERY_AUDIT ADD CONSTRAINT PAT_RET_ACTION1 FOREIGN KEY (PART_RETURN_ACTION1) REFERENCES PART_RETURN_ACTION(ID)
/
ALTER TABLE PART_RECOVERY_AUDIT ADD CONSTRAINT PAT_RET_ACTION2 FOREIGN KEY (PART_RETURN_ACTION2) REFERENCES PART_RETURN_ACTION(ID)
/
ALTER TABLE PART_RECOVERY_AUDIT ADD CONSTRAINT PAT_RET_ACTION3 FOREIGN KEY (PART_RETURN_ACTION3) REFERENCES PART_RETURN_ACTION(ID)
/