--Purpose    :  patch to insert values to LOVs
--Author     : Raghavendra
--Created On : 12-Dec-2013


INSERT INTO LIST_OF_VALUES (TYPE, CODE, DESCRIPTION, STATE, VERSION, D_CREATED_ON, D_UPDATED_ON, ID, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE) VALUES ('ADDITIONALCOMPONENTTYPE', 'C', 'Carriage', 'active', '0', Sysdate, Sysdate, LIST_OF_VALUES_SEQ.nextval, 'AMER', Sysdate, Sysdate, '1')
/
INSERT INTO LIST_OF_VALUES (TYPE, CODE, DESCRIPTION, STATE, VERSION, D_CREATED_ON, D_UPDATED_ON, ID, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE) VALUES ('ADDITIONALCOMPONENTTYPE', 'F', 'Fork', 'active', '0', Sysdate, Sysdate, LIST_OF_VALUES_SEQ.nextval, 'AMER', Sysdate, Sysdate, '1')
/
INSERT INTO LIST_OF_VALUES (TYPE, CODE, DESCRIPTION, STATE, VERSION, D_CREATED_ON, D_UPDATED_ON, ID, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE) VALUES ('ADDITIONALCOMPONENTTYPE', 'A', 'Attachment', 'active', '0', Sysdate, Sysdate, LIST_OF_VALUES_SEQ.nextval, 'AMER', Sysdate, Sysdate, '1')
/
INSERT INTO LIST_OF_VALUES (TYPE, CODE, DESCRIPTION, STATE, VERSION, D_CREATED_ON, D_UPDATED_ON, ID, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE) VALUES ('ADDITIONALCOMPONENTSUBTYPE', 'H', 'Hook', 'active', '0', Sysdate, Sysdate, LIST_OF_VALUES_SEQ.nextval, 'AMER', Sysdate, Sysdate, '1')
/
INSERT INTO LIST_OF_VALUES (TYPE, CODE, DESCRIPTION, STATE, VERSION, D_CREATED_ON, D_UPDATED_ON, ID, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE) VALUES ('ADDITIONALCOMPONENTSUBTYPE', 'P', 'Pin', 'active', '0', Sysdate, Sysdate, LIST_OF_VALUES_SEQ.nextval, 'AMER', Sysdate, Sysdate, '1')
/
INSERT INTO LIST_OF_VALUES (TYPE, CODE, DESCRIPTION, STATE, VERSION, D_CREATED_ON, D_UPDATED_ON, ID, BUSINESS_UNIT_INFO, D_CREATED_TIME, D_UPDATED_TIME, D_ACTIVE) VALUES ('ADDITIONALCOMPONENTSUBTYPE', 'N', 'None', 'active', '0', Sysdate, Sysdate, LIST_OF_VALUES_SEQ.nextval, 'AMER', Sysdate, Sysdate, '1')
/