--PURPOSE    : INSERT DATA ROLE PERMISSION MAPPING
--AUTHOR     : Chetan
--CREATED ON : 30-APR-2014
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminWarrantyAdminTab'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminWarrantyAdminTab:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminManageBusinessConfigurations'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminManageBusinessConfigurations:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminManageWarrantyPolicies'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminManageWarrantyPolicies:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminPolicyDefinition'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminPolicyDefinition:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminManageFlatRates'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminManageFlatRates:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminLaborRates'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminLaborRates:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminTravelRates'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminTravelRates:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminItemPriceModifiers'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminItemPriceModifiers:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminManagePartsCost'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminManagePartsCost:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminPartReturnConfiguration'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminPartReturnConfiguration:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminManageStateMandates'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminManageStateMandates:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminManageClaimPayment'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminManageClaimPayment:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminCreateClaimPaymentModifier'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminCreateClaimPaymentModifier:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminConfigureClaimPaymentDefinition'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminConfigureClaimPaymentDefinition:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminManageFailureStructure'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminManageFailureStructure:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminSeriesFailureHierarchy'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminSeriesFailureHierarchy:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminListFaultLocations'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminListFaultLocations:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminListServiceProcedures'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminListServiceProcedures:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminFaultFound/CausedByAssociation'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminFaultFound/CausedByAssociation:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminMaintainFailureDetailofFailureURL'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminMaintainFailureDetailofFailureURL:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminManageGroups'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminManageGroups:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminItemGroups'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminItemGroups:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminDealerGroups'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminDealerGroups:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminUserGroups'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminUserGroups:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminManageBusinessRuleGroups'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminManageBusinessRuleGroups:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminClaimsProcessing'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminClaimsProcessing:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminClaimProcessorRouting'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminClaimProcessorRouting:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminDSMRouting'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminDSMRouting:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminAdvisorRouting'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminAdvisorRouting:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminManageBusinessRules'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminManageBusinessRules:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminEntryValidations'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminEntryValidations:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminProcessorAuthority'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminProcessorAuthority:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminManageBusinessConditions'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminManageBusinessConditions:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminWarrantyBusinessConditions'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminWarrantyBusinessConditions:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminManageUserAvailability'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminManageUserAvailability:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminProcessor'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminProcessor:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminDSM'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminDSM:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminDSMAdvisor'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminDSMAdvisor:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminRecoveryProcessor'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminRecoveryProcessor:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminFieldProductImprovement'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminFieldProductImprovement:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminRelatedFPIsManagement'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminRelatedFPIsManagement:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminManageWarehouses'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminManageWarehouses:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminListOfValues'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminListOfValues:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminManageDisplayedFaultCode'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminManageDisplayedFaultCode:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminAdditionalAttributes'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminAdditionalAttributes:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminCreate/UpdateAttributes'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminCreate/UpdateAttributes:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminAssociate/DissociatePartAttributes'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminAssociate/DissociatePartAttributes:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='Associate/DissociateFlatRatesAttributes'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:Associate/DissociateFlatRatesAttributes:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='Associate/DissociateClaimedInventoryAttributes'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:Associate/DissociateClaimedInventoryAttributes:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminAssociate/DissociateClaimAttributes'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminAssociate/DissociateClaimAttributes:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminManageFreight/Shippers'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminManageFreight/Shippers:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminViewSupplier'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminViewSupplier:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminViewLabels'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminViewLabels:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminManageLaborSplit'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminManageLaborSplit:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminCreateLabelsforinventory'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminCreateLabelsforinventory:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminCreateLabelsforModels'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminCreateLabelsforModels:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminMiscellaneousParts'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminMiscellaneousParts:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminManageMiscellaneousParts'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminManageMiscellaneousParts:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminConfigureMiscellaneousParts'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminConfigureMiscellaneousParts:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminCostCategoryConfiguration'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminCostCategoryConfiguration:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminManageLOASchemes'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminManageLOASchemes:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='warrantyAdminManageAdditionalLaborEligibility'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='warrantyAdmin'),'warrantyAdmin:warrantyAdminManageAdditionalLaborEligibility:update' from role where name in ('admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsClaimTab'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsClaimTab:update' from role where name in ('baserole','processor','dsm','dsmAdvisor','recoveryProcessor','cpAdvisor','dealerWarrantyAdmin','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsMultiClaimMaintenance'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsMultiClaimMaintenance:update' from role where name in ('admin','processor','inventoryAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsClaimAttributes'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsClaimAttributes:update' from role where name in ('admin','processor','inventoryAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsTransfer/Re-process'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsTransfer/Re-process:update' from role where name in ('admin','processor','inventoryAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsAdviceRequest'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsAdviceRequest:update' from role where name in ('baserole','processor','dsm','dsmAdvisor','recoveryProcessor','cpAdvisor','dealerWarrantyAdmin','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsAppeals'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsAppeals:update' from role where name in ('baserole','processor','dsm','dsmAdvisor','recoveryProcessor','cpAdvisor','dealerWarrantyAdmin','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsDraftClaim'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsDraftClaim:update' from role where name in ('baserole','processor','dsm','dsmAdvisor','recoveryProcessor','cpAdvisor','dealerWarrantyAdmin','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsForwardedExternally'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsForwardedExternally:update' from role where name in ('baserole','processor','dsm','dsmAdvisor','recoveryProcessor','cpAdvisor','dealerWarrantyAdmin','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsForwardedInternally'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsForwardedInternally:update' from role where name in ('baserole','processor','dsm','dsmAdvisor','recoveryProcessor','cpAdvisor','dealerWarrantyAdmin','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsInProgress'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsInProgress:update' from role where name in ('baserole','processor','dsm','dsmAdvisor','recoveryProcessor','cpAdvisor','dealerWarrantyAdmin','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsOnHoldForPartReturn'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsOnHoldForPartReturn:update' from role where name in ('baserole','processor','dsm','dsmAdvisor','recoveryProcessor','cpAdvisor','dealerWarrantyAdmin','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsPartShippedNotReceived'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsPartShippedNotReceived:update' from role where name in ('baserole','processor','dsm','dsmAdvisor','recoveryProcessor','cpAdvisor','dealerWarrantyAdmin','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsPendingAuthorization'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsPendingAuthorization:update' from role where name in ('baserole','processor','dsm','dsmAdvisor','recoveryProcessor','cpAdvisor','dealerWarrantyAdmin','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsNew'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsNew:update' from role where name in ('baserole','processor','dsm','dsmAdvisor','recoveryProcessor','cpAdvisor','dealerWarrantyAdmin','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsRejectedPartReturn'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsRejectedPartReturn:update' from role where name in ('baserole','processor','dsm','dsmAdvisor','recoveryProcessor','cpAdvisor','dealerWarrantyAdmin','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsReplies'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsReplies:update' from role where name in ('baserole','processor','dsm','dsmAdvisor','recoveryProcessor','cpAdvisor','dealerWarrantyAdmin','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsServiceManagerReview'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsServiceManagerReview:update' from role where name in ('baserole','processor','dsm','dsmAdvisor','recoveryProcessor','cpAdvisor','dealerWarrantyAdmin','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsTransferred'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsTransferred:update' from role where name in ('baserole','processor','dsm','dsmAdvisor','recoveryProcessor','cpAdvisor','dealerWarrantyAdmin','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsWaitingForLabor'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsWaitingForLabor:update' from role where name in ('baserole','processor','dsm','dsmAdvisor','recoveryProcessor','cpAdvisor','dealerWarrantyAdmin','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsPendingRecoveryInitiation'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsPendingRecoveryInitiation:update' from role where name in ('baserole','processor','dsm','dsmAdvisor','recoveryProcessor','cpAdvisor','dealerWarrantyAdmin','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsDefineSearchQuery'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsDefineSearchQuery:update' from role where name in ('baserole','processor','dsm','dsmAdvisor','recoveryProcessor','admin','cpAdvisor','dealerWarrantyAdmin','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='claimsPredefinedSearch'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='claims'),'claims:claimsPredefinedSearch:update' from role where name in ('baserole','processor','dsm','dsmAdvisor','recoveryProcessor','admin','cpAdvisor','dealerWarrantyAdmin','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='inventoryInventoryTab'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='inventory'),'inventory:inventoryInventoryTab:update' from role where name in ('inventorysearch','inventorylisting','inventoryAdmin','admin','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='inventoryStock'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='inventory'),'inventory:inventoryStock:update' from role where name in ('inventorylisting','admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='inventoryRetailed'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='inventory'),'inventory:inventoryRetailed:update' from role where name in ('inventorylisting','admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='inventoryDefineSearchQuery'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='inventory'),'inventory:inventoryDefineSearchQuery:update' from role where name in ('inventorysearch','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='inventoryPredefinedStockSearch'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='inventory'),'inventory:inventoryPredefinedStockSearch:update' from role where name in ('inventorysearch','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='inventoryPredefinedRetailSearch'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='inventory'),'inventory:inventoryPredefinedRetailSearch:update' from role where name in ('inventorysearch','readOnly')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='fPIFPITab'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='fPI'),'fPI:fPIFPITab:update' from role where name in ('admin','processor','dsmAdvisor','recoveryProcessor','dsm','recoveryProcessor','dealerWarrantyAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='fPIPendingFPIUpdateRequests'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='fPI'),'fPI:fPIPendingFPIUpdateRequests:update' from role where name in ('internalUserAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='fPIPredefinedSearch'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='fPI'),'fPI:fPIPredefinedSearch:update' from role where name in ('admin','processor','dsmAdvisor','recoveryProcessor','dsm','recoveryProcessor','dealerWarrantyAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='partReturnsPartReturnsTab'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='partReturns'),'partReturns:partReturnsPartReturnsTab:update' from role where name in ('processor','admin','receiver','sra','partshipper','dsmAdvisor','recoveryProcessor','inspector','dealerWarrantyAdmin','cevaProcessor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='partReturnsDuePartsReceipt'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='partReturns'),'partReturns:partReturnsDuePartsReceipt:update' from role where name in ('processor','admin','receiver','sra','partshipper','dsmAdvisor','recoveryProcessor','inspector','dealerWarrantyAdmin','cevaProcessor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='partReturnsDuePartsInspection'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='partReturns'),'partReturns:partReturnsDuePartsInspection:update' from role where name in ('processor','admin','receiver','sra','partshipper','dsmAdvisor','recoveryProcessor','inspector','dealerWarrantyAdmin','cevaProcessor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='partReturnsAwaitingShipmentforDealer'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='partReturns'),'partReturns:partReturnsAwaitingShipmentforDealer:update' from role where name in ('processor','admin','receiver','sra','partshipper','dsmAdvisor','recoveryProcessor','inspector','dealerWarrantyAdmin','cevaProcessor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='partReturnsShipmentGeneratedForDealer'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='partReturns'),'partReturns:partReturnsShipmentGeneratedForDealer:update' from role where name in ('processor','admin','receiver','sra','partshipper','dsmAdvisor','recoveryProcessor','inspector','dealerWarrantyAdmin','cevaProcessor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='partReturnsDealerRequestedPartsShipped'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='partReturns'),'partReturns:partReturnsDealerRequestedPartsShipped:update' from role where name in ('processor','admin','receiver','sra','partshipper','dsmAdvisor','recoveryProcessor','inspector','dealerWarrantyAdmin','cevaProcessor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='partReturnsRequiredPartsfromDealer'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='partReturns'),'partReturns:partReturnsRequiredPartsfromDealer:update' from role where name in ('processor','admin','receiver','sra','partshipper','dsmAdvisor','recoveryProcessor','inspector','dealerWarrantyAdmin','cevaProcessor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='partReturnsDealerRequestedPart'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='partReturns'),'partReturns:partReturnsDealerRequestedPart:update' from role where name in ('processor','admin','receiver','sra','partshipper','dsmAdvisor','recoveryProcessor','inspector','dealerWarrantyAdmin','cevaProcessor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='partReturnsDefineSearchQuery'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='partReturns'),'partReturns:partReturnsDefineSearchQuery:update' from role where name in ('receiverLimitedView','inspectorLimitedView')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='partReturnsPredefinedSearch'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='partReturns'),'partReturns:partReturnsPredefinedSearch:update' from role where name in ('receiverLimitedView','inspectorLimitedView')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='partsRecoveryPartsRecoveryTab'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='partsRecovery'),'partsRecovery:partsRecoveryPartsRecoveryTab:update' from role where name in ('partshipper','recoveryProcessor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='partsRecoveryAwaitingShipment'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='partsRecovery'),'partsRecovery:partsRecoveryAwaitingShipment:update' from role where name in ('partshipper','recoveryProcessor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='partsRecoveryAwaitingShipmentToWarehouse'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='partsRecovery'),'partsRecovery:partsRecoveryAwaitingShipmentToWarehouse:update' from role where name in ('partshipper','recoveryProcessor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='partsRecoveryAwaitingShipmenttoSupplier'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='partsRecovery'),'partsRecovery:partsRecoveryAwaitingShipmenttoSupplier:update' from role where name in ('partshipper','recoveryProcessor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='partsRecoverySupplierPartsShipped'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='partsRecovery'),'partsRecovery:partsRecoverySupplierPartsShipped:update' from role where name in ('partshipper','recoveryProcessor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='partsRecoveryShipmentGenerated'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='partsRecovery'),'partsRecovery:partsRecoveryShipmentGenerated:update' from role where name in ('partshipper','recoveryProcessor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='partsRecoveryPredefinedSearch'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='partsRecovery'),'partsRecovery:partsRecoveryPredefinedSearch:update' from role where name in ('partshipper','recoveryProcessor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='processorRecoveryProcessorRecoveryTab'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='processorRecovery'),'processorRecovery:processorRecoveryProcessorRecoveryTab:update' from role where name in ('recoveryProcessor','processor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='processorRecoveryClaimsDueForRecovery'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='processorRecovery'),'processorRecovery:processorRecoveryClaimsDueForRecovery:update' from role where name in ('recoveryProcessor','processor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='processorRecoveryNew'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='processorRecovery'),'processorRecovery:processorRecoveryNew:update' from role where name in ('recoveryProcessor','processor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='processorRecoveryInProgress'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='processorRecovery'),'processorRecovery:processorRecoveryInProgress:update' from role where name in ('recoveryProcessor','processor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='processorRecoveryNotForRecoveryRequest'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='processorRecovery'),'processorRecovery:processorRecoveryNotForRecoveryRequest:update' from role where name in ('recoveryProcessor','processor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='processorRecoveryNotForRecoveryResponse'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='processorRecovery'),'processorRecovery:processorRecoveryNotForRecoveryResponse:update' from role where name in ('recoveryProcessor','processor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='processorRecoveryTransferred'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='processorRecovery'),'processorRecovery:processorRecoveryTransferred:update' from role where name in ('recoveryProcessor','processor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='processorRecoveryReopened'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='processorRecovery'),'processorRecovery:processorRecoveryReopened:update' from role where name in ('recoveryProcessor','processor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='processorRecoveryClaimsUnderRecovery'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='processorRecovery'),'processorRecovery:processorRecoveryClaimsUnderRecovery:update' from role where name in ('recoveryProcessor','processor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='processorRecoveryDisputed'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='processorRecovery'),'processorRecovery:processorRecoveryDisputed:update' from role where name in ('recoveryProcessor','processor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='processorRecoveryAccepted'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='processorRecovery'),'processorRecovery:processorRecoveryAccepted:update' from role where name in ('recoveryProcessor','processor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='processorRecoveryAwaitingSupplierResponse'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='processorRecovery'),'processorRecovery:processorRecoveryAwaitingSupplierResponse:update' from role where name in ('recoveryProcessor','processor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='processorRecoveryNotForRecovery'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='processorRecovery'),'processorRecovery:processorRecoveryNotForRecovery:update' from role where name in ('recoveryProcessor','processor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='processorRecoveryMultiClaimMaintenance'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='processorRecovery'),'processorRecovery:processorRecoveryMultiClaimMaintenance:update' from role where name in ('recoveryProcessor','processor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='processorRecoveryReadyForDebit'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='processorRecovery'),'processorRecovery:processorRecoveryReadyForDebit:update' from role where name in ('recoveryProcessor','processor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='processorRecoveryDefineSearchQuery'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='processorRecovery'),'processorRecovery:processorRecoveryDefineSearchQuery:update' from role where name in ('recoveryProcessor','processor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='processorRecoveryPreDefinedSearch'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='processorRecovery'),'processorRecovery:processorRecoveryPreDefinedSearch:update' from role where name in ('recoveryProcessor','processor')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='contractAdminContractAdminTab'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='contractAdmin'),'contractAdmin:contractAdminContractAdminTab:update' from role where name in ('sra')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='contractAdminMaintainSupplierContracts'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='contractAdmin'),'contractAdmin:contractAdminMaintainSupplierContracts:update' from role where name in ('sra')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='contractAdminManageBusinessConditions'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='contractAdmin'),'contractAdmin:contractAdminManageBusinessConditions:update' from role where name in ('sra')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='contractAdminManageBusinessRules'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='contractAdmin'),'contractAdmin:contractAdminManageBusinessRules:update' from role where name in ('sra')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='contractAdminRecoveryClaimProcessorRouting'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='contractAdmin'),'contractAdmin:contractAdminRecoveryClaimProcessorRouting:update' from role where name in ('sra')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='contractAdminManageSuppliers'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='contractAdmin'),'contractAdmin:contractAdminManageSuppliers:update' from role where name in ('sra')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='contractAdminViewPartSourceHistory'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='contractAdmin'),'contractAdmin:contractAdminViewPartSourceHistory:update' from role where name in ('sra')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='contractAdminViewSupplier'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='contractAdmin'),'contractAdmin:contractAdminViewSupplier:update' from role where name in ('sra')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='contractAdminManageGroups'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='contractAdmin'),'contractAdmin:contractAdminManageGroups:update' from role where name in ('sra')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='contractAdminUserGroups'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='contractAdmin'),'contractAdmin:contractAdminUserGroups:update' from role where name in ('sra')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='itemsItemsTab'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='items'),'items:itemsItemsTab:update' from role where name in ('dealerWarrantyAdmin','dealerSalesAdministration')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='itemsDefinedSearchQuery'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='items'),'items:itemsDefinedSearchQuery:update' from role where name in ('dealerWarrantyAdmin','dealerSalesAdministration')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='reportsReportsTab'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='reports'),'reports:reportsReportsTab:update' from role where name in ('dealerWarrantyAdmin','baserole','processor','dsm','dsmAdvisor','recoveryProcessor','admin','supplier')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='reportsVendorRecoveryReport'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='reports'),'reports:reportsVendorRecoveryReport:update' from role where name in ('recoveryProcessor','admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='reportsManageUploads/Downloads'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='reports'),'reports:reportsManageUploads/Downloads:update' from role where name in ('supplier','masterSupplier')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='reportsUploadManagement'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='reports'),'reports:reportsUploadManagement:update' from role where name in ('supplier','masterSupplier')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='reportsDownloadManagement'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='reports'),'reports:reportsDownloadManagement:update' from role where name in ('supplier','masterSupplier')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='dealerInformationDealerSummary'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='dealerInformation'),'dealerInformation:dealerInformationDealerSummary:update' from role where name in ('admin','SSDataAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='dRApproval/TransferDRApproval/TransferTab'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='dRApproval/Transfer'),'dRApproval/Transfer:dRApproval/TransferDRApproval/TransferTab:update' from role where name in ('inventoryAdmin','warrantyProcessor','dealerSalesAdministration','dealerWarrantyAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='dRApproval/TransferDeliveryReport'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='dRApproval/Transfer'),'dRApproval/Transfer:dRApproval/TransferDeliveryReport:update' from role where name in ('inventoryAdmin','warrantyProcessor','dealerSalesAdministration','dealerWarrantyAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='dRApproval/TransferDraft'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='dRApproval/Transfer'),'dRApproval/Transfer:dRApproval/TransferDraft:update' from role where name in ('inventoryAdmin','warrantyProcessor','dealerSalesAdministration','dealerWarrantyAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='dRApproval/TransferPendingforApproval'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='dRApproval/Transfer'),'dRApproval/Transfer:dRApproval/TransferPendingforApproval:update' from role where name in ('inventoryAdmin','warrantyProcessor','dealerSalesAdministration','dealerWarrantyAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='dRApproval/TransferForwardedToDealer'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='dRApproval/Transfer'),'dRApproval/Transfer:dRApproval/TransferForwardedToDealer:update' from role where name in ('inventoryAdmin','warrantyProcessor','dealerSalesAdministration','dealerWarrantyAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='dRApproval/TransferRejected'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='dRApproval/Transfer'),'dRApproval/Transfer:dRApproval/TransferRejected:update' from role where name in ('inventoryAdmin','warrantyProcessor','dealerSalesAdministration','dealerWarrantyAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='dRApproval/TransferReplies'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='dRApproval/Transfer'),'dRApproval/Transfer:dRApproval/TransferReplies:update' from role where name in ('inventoryAdmin','warrantyProcessor','dealerSalesAdministration','dealerWarrantyAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='dRApproval/TransferResubmitted'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='dRApproval/Transfer'),'dRApproval/Transfer:dRApproval/TransferResubmitted:update' from role where name in ('inventoryAdmin','warrantyProcessor','dealerSalesAdministration','dealerWarrantyAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='dRApproval/TransferUnitTransfer'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='dRApproval/Transfer'),'dRApproval/Transfer:dRApproval/TransferUnitTransfer:update' from role where name in ('inventoryAdmin','warrantyProcessor','dealerSalesAdministration','dealerWarrantyAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='dRApproval/TransferDeleted'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='dRApproval/Transfer'),'dRApproval/Transfer:dRApproval/TransferDeleted:update' from role where name in ('inventoryAdmin','warrantyProcessor','dealerSalesAdministration','dealerWarrantyAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='settingsSettingsTab'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='settings'),'settings:settingsSettingsTab:update' from role where name in ('processor','admin','receiver','sra','partshipper','dsmAdvisor','recoveryProcessor','inspector','inventoryAdmin','warrantyProcessor','dealerSalesAdministration','sra','supplier','dealerWarrantyAdmin','dealerAdministrator','SSDataAdmin','readOnly','cpAdvisor','dsm')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='settingsProfile'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='settings'),'settings:settingsProfile:update' from role where name in ('processor','admin','receiver','sra','partshipper','dsmAdvisor','recoveryProcessor','inspector','inventoryAdmin','warrantyProcessor','dealerSalesAdministration','sra','supplier','dealerWarrantyAdmin','dealerAdministrator','SSDataAdmin','readOnly','cpAdvisor','dsm')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='settingsUserManagement'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='settings'),'settings:settingsUserManagement:update' from role where name in ('dealerAdministrator','SSDataAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='settingsCreateUser'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='settings'),'settings:settingsCreateUser:update' from role where name in ('dealerAdministrator','SSDataAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='settingsUpdateUser'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='settings'),'settings:settingsUpdateUser:update' from role where name in ('dealerAdministrator','SSDataAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='settingsSeriesReftoCertification'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='settings'),'settings:settingsSeriesReftoCertification:update' from role where name in ('dealerAdministrator','SSDataAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='settingsCreateInternalUser'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='settings'),'settings:settingsCreateInternalUser:update' from role where name in ('dealerAdministrator','SSDataAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='settingsUpdateInternalUser'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='settings'),'settings:settingsUpdateInternalUser:update' from role where name in ('dealerAdministrator','SSDataAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='settingsManageUserBusinessUnitMapping'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='settings'),'settings:settingsManageUserBusinessUnitMapping:update' from role where name in ('admin','SSDataAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='settingsEmailSubscription'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='settings'),'settings:settingsEmailSubscription:update' from role where name in ('dealerWarrantyAdmin','baserole','processor','dsm','dsmAdvisor','cpAdvisor','admin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='settingsMapServiceProviderBusinessUnit'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='settings'),'settings:settingsMapServiceProviderBusinessUnit:update' from role where name in ('admin','SSDataAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='settingsMapSupplierBusinessUnit'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='settings'),'settings:settingsMapSupplierBusinessUnit:update' from role where name in ('admin','SSDataAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='settingsManageRoles'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='settings'),'settings:settingsManageRoles:update' from role where name in ('processor','admin','receiver','sra','partshipper','dsmAdvisor','recoveryProcessor','inspector','inventoryAdmin','warrantyProcessor','dealerSalesAdministration','sra','supplier','dealerWarrantyAdmin','dealerAdministrator','SSDataAdmin','readOnly','cpAdvisor','dsm')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='accountsAccountsTab'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='accounts'),'accounts:accountsAccountsTab:update' from role where name in ('admin','SSDataAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='accountsRemoteInteractionsLogs'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='accounts'),'accounts:accountsRemoteInteractionsLogs:update' from role where name in ('admin','SSDataAdmin')
/
INSERT INTO ROLE_PERMISSION_MAPPING select ROLE_PERMISSION_MAPPING_SEQ.nextval,id,(select id from MST_ADMIN_FNC_AREA where name='accountsMonthEndScheduler'),(select id from MST_ADMIN_ACTION where action='update'),(select id from MST_ADMIN_SUBJECT_AREA WHERE name='accounts'),'accounts:accountsMonthEndScheduler:update' from role where name in ('admin')
/