--PURPOSE    : patch to create table TECH_PRODUCT_CERTIFICATIONS
--AUTHOR     : Raghu
--CREATED ON : 19-FEB-2014

create table TECH_PRODUCT_CERTIFICATIONS
(
TECHNICIAN_CERTIFICATION NUMBER(19,0),
PRODUCT_CERTIFICATION NUMBER(19,0)
)
/