--	PURPOSE    : PATCH TO ADD PART RETURN COMMENTS TO DEALER IN RECOVERY CLAIM AUDIT
--	AUTHOR     : ParthaSarathy R
--	CREATED ON : 22-January-2014

ALTER TABLE REC_CLAIM_AUDIT ADD PART_RETURN_COMMENTS_TO_DEALER VARCHAR2(4000)
/