alter table STG_WARRANTY_REGISTRATIONS add TRANSACTION_TYPE VARCHAR2(255)
/
alter table STG_WARRANTY_REGISTRATIONS add COMPETITOR_MAKE VARCHAR2(255)
/
alter table STG_WARRANTY_REGISTRATIONS add MARKET_TYPE VARCHAR2(255)
/
alter table STG_WARRANTY_REGISTRATIONS add COMPETITION_TYPE VARCHAR2(255)
/
alter table STG_WARRANTY_REGISTRATIONS add NUMBER_OF_YEARS VARCHAR2(255)
/
alter table STG_WARRANTY_REGISTRATIONS add NUMBER_OF_MONTHS VARCHAR2(255)
/
alter table STG_WARRANTY_REGISTRATIONS add FIRST_TIME_OWNER VARCHAR2(255)
/