--Purpose    : DDL for NMHGSLMS-425 -To create State_Mandate_Audit
--Author     : Arpitha Nadig AR
--Created On : 14-JAN-2013

CREATE TABLE STATE_MANDATE_AUDIT
( "ID" NUMBER(19,0) NOT NULL ENABLE,
"STATE_MANDATE" NUMBER(19,2),
"D_LAST_UPDATED_BY" NUMBER(19,0),
"D_CREATED_ON" DATE,
"D_INTERNAL_COMMENTS" VARCHAR2(255 BYTE), 
"D_UPDATED_ON" DATE, 
"D_CREATED_TIME" TIMESTAMP (6),
"D_UPDATED_TIME" TIMESTAMP (6),
"D_ACTIVE" NUMBER(1,0) DEFAULT 1, 
"COMMENTS" VARCHAR2(255 BYTE), 
"EFFECTIVE_DATE" DATE, 
"LABOR_RATE_TYPE" NUMBER(19,0), 
"OEM_PARTS_PERCENT" NUMBER(19,2), 
"STATE" VARCHAR2(255 BYTE), 
"CREATED_BY" NUMBER(19,0),
CONSTRAINT "STATE_MANDATE_AUDIT_PK" PRIMARY KEY ("ID"),
CONSTRAINT "STATE_MANDATE_AUDIT_FK" FOREIGN KEY ("STATE_MANDATE") 
REFERENCES "STATE_MANDATES" ("ID") ENABLE,
CONSTRAINT "CREATED_BY_FK" FOREIGN KEY ("CREATED_BY") 
REFERENCES "ORG_USER" ("ID") ENABLE
)
/