--PURPOSE    : patch to create table MARKETING_GROUP_BRAND
--AUTHOR     : Raghu
--CREATED ON : 19-FEB-2014

CREATE TABLE MARKETING_GROUP_BRAND
(
ID NUMBER(19,0), 
MARKETING_GROUP VARCHAR2(255 BYTE), 
BRAND VARCHAR2(255 BYTE)
)
/