-- Patch to create Constraints for Internal_Install_Type
-- Author		: ParthaSarathy R
-- Created On	: 18-Dec-2013

ALTER TABLE INTERNAL_INSTALL_TYPE ADD CONSTRAINT INTERNAL_INSTALL_TYPE_PK PRIMARY KEY (ID)
/
ALTER TABLE INTERNAL_INSTALL_TYPE ADD CONSTRAINT INTERNAL_INSTALL_TYPE_BU_FK FOREIGN KEY (BUSINESS_UNIT_INFO) REFERENCES BUSINESS_UNIT(NAME)
/
ALTER TABLE I18NINTERNAL_INSTALL_TYPE ADD CONSTRAINT I18NINTERNAL_INSTALL_TYPE_PK PRIMARY KEY (ID)
/
ALTER TABLE I18NINTERNAL_INSTALL_TYPE ADD CONSTRAINT I18NINTERNAL_INSTALL_TYPE_FK FOREIGN KEY (I18NINTERNAL_INSTALL_TYPE) REFERENCES INTERNAL_INSTALL_TYPE(ID)
/