-- PURPOSE    : PATCH TO add constraints
-- AUTHOR     : Arpitha Nadig AR.
-- CREATED ON : 05-JAN-2013

ALTER TABLE POLICY_PRODUCT_MAPPING ADD CONSTRAINT "PRODUCT_FK" FOREIGN KEY ("PRODUCT")
REFERENCES ITEM_GROUP ("ID") ENABLE
/
ALTER TABLE POLICY_PRODUCT_MAPPING ADD CONSTRAINT "POLICY_DEFINITION_FK" FOREIGN KEY ("POLICY_DEFN")
REFERENCES POLICY_DEFINITION ("ID") ENABLE
/