--Purpose    : Patch for adding the Customer Contact Title column in address table
--Author     : Priyanka S
--Created On : 27-NOV-2013
CREATE TABLE WAREHOUSE_LABELS
(
WAREHOUSE NUMBER(19,0) NOT NULL ENABLE, 
LABELS VARCHAR2(255 CHAR) NOT NULL ENABLE
)
/
alter table WAREHOUSE_LABELS add CONSTRAINT "WAREHOUSE_FK" FOREIGN KEY ("WAREHOUSE") REFERENCES "WAREHOUSE" ("ID") ENABLE
/
alter table WAREHOUSE_LABELS add CONSTRAINT "LABELS_FK" FOREIGN KEY ("LABELS") REFERENCES "LABEL" ("NAME") ENABLE
/
