ALTER TABLE TECHNICIAN
ADD
(
ORG_USER NUMBER
)
/
ALTER TABLE TECHNICIAN
ADD CONSTRAINT ORG_USER_FK FOREIGN KEY (ORG_USER) REFERENCES ORG_USER (ID)
/
CREATE SEQUENCE TECHNICIAN_SEQ
START WITH     1000
INCREMENT BY   20
NOCACHE
NOCYCLE
/
alter table technician drop constraint TECHNICIAN_ID_FK
/
commit
/