--Purpose    : Patch FOR PERFORMANCE FIXES
--Author     : HARI KRISHNA Y D
--Created On : 23-APR-2014

CREATE INDEX INDIVIDUAL_LINE_ITEM_LIG_IDX ON individual_line_item (line_item_group)
/
CREATE INDEX INVENTORY_ITEM_SHIPMENT_IDX ON INVENTORY_ITEM(SHIPMENT_DATE)
/
CREATE INDEX ADDRESS_BOOK_IDX1 ON address_book (belongs_to)
/
Create Index BU_ITEM_MAPPING_ITEM_IDX on BU_ITEM_MAPPING (Item)
/