--PURPOSE    : Patch to add a new column in TECHNICIAN_CERTIFICATION Table for maintaining foreign key relation with TECHNICIAN table
--AUTHOR     : Sumesh
--CREATED ON : 26-Dec-2013

ALTER TABLE TECHNICIAN_CERTIFICATION ADD TECHNICIAN_DETAILS NUMBER(19)
/
ALTER TABLE TECHNICIAN_CERTIFICATION ADD(CONSTRAINT "TECHNICIAN_DETAILS" FOREIGN KEY ("TECHNICIAN_DETAILS") REFERENCES TECHNICIAN(ID))
/