--Purpose    : DDL for NMHGSLMS-425 -State Mandates
--Author     : Arpitha Nadig AR
--Created On : 13-DEC-2013
--------------------------------------------------------
--  DDL for Table STATE_MANDATES
--------------------------------------------------------
--------------------------------------------------
 --  DDL for Table STATE_MNDTE_COST_CTGY_MAPPING
---------------------------------------------------
CREATE TABLE STATE_MANDATES
(	ID NUMBER(19,0) NOT NULL,
  	STATE VARCHAR2(255 BYTE) NOT NULL,
 	EFFECTIVE_DATE DATE, 
	LABOR_RATE_TYPE NUMBER(19,0),
  	OEM_PARTS NUMBER(19,0),
	STATUS VARCHAR2(255 BYTE) NOT NULL, 
	VERSION NUMBER(10,0) NOT NULL, 
	D_CREATED_ON DATE,
	D_UPDATED_ON DATE, 
	D_INTERNAL_COMMENTS VARCHAR2(255 BYTE),
  	D_ACTIVE NUMBER(1,0) DEFAULT 1, 
	D_LAST_UPDATED_BY NUMBER(19,0), 
	D_CREATED_TIME TIMESTAMP (6),
	D_UPDATED_TIME TIMESTAMP (6),
	BUSINESS_UNIT_INFO VARCHAR2(255 BYTE) NOT NULL,
	PRIMARY KEY (ID)
   )
/
CREATE TABLE STATE_MNDTE_COST_CTGY_MAPPING
( 	ID NUMBER(19,0) NOT NULL,
	STATE_MANDATE NUMBER(19,0) NOT  NULL,
	COST_CATEGORY NUMBER(19,0) NOT NULL,
    MANDATORY NUMBER(1,0) NOT NULL,
	PRIMARY KEY (ID)
   )
/