--Purpose    : DDL SCRIPTS FOR NMHGSLMS-431 : STG_SUPPLIER_DECISION
--Author     : Arpitha Nadig AR
--Created On : 19-MAR-2014
alter table STG_SUPPLIER_DECISION add SUPPLIER_CONTRACT_CODE VARCHAR2(255)
/
alter table STG_SUPPLIER_DECISION add PART_RETURN_REQUEST VARCHAR2(255)
/
alter table STG_SUPPLIER_DECISION add RETURN_LOCATION_CODE VARCHAR2(255)
/
alter table STG_SUPPLIER_DECISION add RMA_NUMBER VARCHAR2(255)
/
alter table STG_SUPPLIER_DECISION add CLAIM_AMOUNT_BEING_ACCEPTED NUMBER(19,2)
/
alter table STG_SUPPLIER_DECISION add CREDIT_MEMO_NUMBER VARCHAR2(255)
/
alter table STG_SUPPLIER_DECISION add CREDIT_MEMO_DATE  VARCHAR2(255)
/
alter table stg_supplier_decision rename column decision_comments to supplier_comments
/