--  REFERENCE   : SLMSPOD-970 
--	AUTHOR		: Ravi K Sinha

INSERT INTO INVENTORY_CLASS VALUES (INV_CLASS_SEQ.nextVal, 'Big Truck', 'Big Truck', 'EMEA')
/

INSERT INTO INVENTORY_CLASS VALUES (INV_CLASS_SEQ.nextVal, 'CLASS I', 'CLASS I', 'EMEA')
/

INSERT INTO INVENTORY_CLASS VALUES (INV_CLASS_SEQ.nextVal, 'CLASS II', 'CLASS II', 'EMEA')
/

INSERT INTO INVENTORY_CLASS VALUES (INV_CLASS_SEQ.nextVal, 'CLASS III', 'CLASS III', 'EMEA')
/

INSERT INTO INVENTORY_CLASS VALUES (INV_CLASS_SEQ.nextVal, 'CLASS IV', 'CLASS IV', 'EMEA')
/

INSERT INTO INVENTORY_CLASS VALUES (INV_CLASS_SEQ.nextVal, 'CLASS V', 'CLASS V', 'EMEA')
/

COMMIT
/