--  REFERENCE   : SLMSPOD-970 
--	AUTHOR		: Ravi K Sinha

CREATE TABLE INVENTORY_CLASS
(
    ID      			NUMBER(19,0)  NOT NULL ENABLE,
    NAME    			VARCHAR2 (255 CHAR) NOT NULL UNIQUE,
    DESCRIPTION 		VARCHAR2(1000 CHAR) NOT NULL ENABLE,
	BUSINESS_UNIT_INFO	VARCHAR2(255 CHAR),
	CONSTRAINT INVENTORY_CLASS_ID_PK PRIMARY KEY (ID) ENABLE
)
/

CREATE TABLE INV_CLASS_DEALER_MAPPING
  (
   ID                       NUMBER(19,0) NOT NULL ENABLE,
   INVENTORY_CLASS_ID       NUMBER(19,0) NOT NULL ENABLE,
   SERVICE_PROVIDER_ID      NUMBER(19,0) NOT NULL ENABLE,
   D_CREATED_ON				DATE,
   D_INTERNAL_COMMENTS		VARCHAR2(255 CHAR),
   D_UPDATED_ON				DATE,
   D_LAST_UPDATED_BY		NUMBER(19,0),
   D_CREATED_TIME			TIMESTAMP(6),
   D_UPDATED_TIME			TIMESTAMP(6),
   D_ACTIVE					NUMBER(1,0),
   CONSTRAINT "INV_CLASS_DEALER_MAPPING_PK" PRIMARY KEY ("ID") ENABLE,
   CONSTRAINT "INV_CLS_DLR_MPNG_INV_CLS_FK" FOREIGN KEY ("INVENTORY_CLASS_ID") REFERENCES "INVENTORY_CLASS" ("ID") ENABLE,
   CONSTRAINT "INV_CLS_DLR_MPNG_SER_PRVDR_FK" FOREIGN KEY ("SERVICE_PROVIDER_ID") REFERENCES "SERVICE_PROVIDER" ("ID") ENABLE
   )
/

COMMIT
/